class MurderMysteryKnifeSkinPrestigeXp {
  '10000Spoons': number;
  apple: number;
  bastedTurkey: number;
  blazeStick: number;
  bloodyBrick: number;
  bone: number;
  campfireLeftovers: number;
  carrotOnStick: number;
  cheapo: number;
  cheese: number;
  chewedBush: number;
  diamondShovel: number;
  doubleDeathScythe: number;
  dragonEgg: number;
  earthenDagger: number;
  easterBasket: number;
  farmingImplement: number;
  feather: number;
  fragilePlant: number;
  frisbee: number;
  glisteningMelon: number;
  goldDigger: number;
  grilledSteak: number;
  grimoire: number;
  iceShard: number;
  mouseTrap: number;
  prickly: number;
  pumpkinPie: number;
  rudolphsNose: number;
  rudolphsSnack: number;
  salmon: number;
  scythe: number;
  shears: number;
  shinySnack: number;
  shovel: number;
  shred: number;
  sprayPaintedShovel: number;
  stake: number;
  stick: number;
  stickWithHat: number;
  sweetTreat: number;
  timber: number;
  woodAxe: number;
  constructor(data: Record<string, any>) {
    this['10000Spoons'] = data?.['10000_spoons'] || 0;
    this.apple = data?.apple || 0;
    this.bastedTurkey = data?.basted_turkey || 0;
    this.blazeStick = data?.blaze_stick || 0;
    this.bloodyBrick = data?.bloody_brick || 0;
    this.bone = data?.bone || 0;
    this.campfireLeftovers = data?.campfire_leftovers || 0;
    this.carrotOnStick = data?.carrot_on_stick || 0;
    this.cheapo = data?.cheapo || 0;
    this.cheese = data?.cheese || 0;
    this.chewedBush = data?.chewed_bush || 0;
    this.diamondShovel = data?.diamond_shovel || 0;
    this.doubleDeathScythe = data?.double_death_scythe || 0;
    this.dragonEgg = data?.dragon_egg || 0;
    this.earthenDagger = data?.earthen_dagger || 0;
    this.easterBasket = data?.easter_basket || 0;
    this.farmingImplement = data?.farming_implement || 0;
    this.feather = data?.feather || 0;
    this.fragilePlant = data?.fragile_plant || 0;
    this.frisbee = data?.frisbee || 0;
    this.glisteningMelon = data?.glistening_melon || 0;
    this.goldDigger = data?.gold_digger || 0;
    this.grilledSteak = data?.grilled_steak || 0;
    this.grimoire = data?.grimoire || 0;
    this.iceShard = data?.ice_shard || 0;
    this.mouseTrap = data?.mouse_trap || 0;
    this.prickly = data?.prickly || 0;
    this.pumpkinPie = data?.pumpkin_pie || 0;
    this.rudolphsNose = data?.rudolphs_nose || 0;
    this.rudolphsSnack = data?.rudolphs_snack || 0;
    this.salmon = data?.salmon || 0;
    this.scythe = data?.scythe || 0;
    this.shears = data?.shears || 0;
    this.shinySnack = data?.shiny_snack || 0;
    this.shovel = data?.shovel || 0;
    this.shred = data?.shred || 0;
    this.sprayPaintedShovel = data?.spray_painted_shovel || 0;
    this.stake = data?.stake || 0;
    this.stick = data?.stick || 0;
    this.stickWithHat = data?.stick_with_hat || 0;
    this.sweetTreat = data?.sweet_treat || 0;
    this.timber = data?.timber || 0;
    this.woodAxe = data?.wood_axe || 0;
  }
}

export default MurderMysteryKnifeSkinPrestigeXp;
