import MurderMysteryDescentItem from './MurderMysteryDescentItem.ts';

class MurderMysteryDescent {
  Armed: MurderMysteryDescentItem;
  bloodLust: MurderMysteryDescentItem;
  bountyHunter: MurderMysteryDescentItem;
  cleanJob: MurderMysteryDescentItem;
  Collateral: MurderMysteryDescentItem;
  contagionContained: MurderMysteryDescentItem;
  Cornucopia: MurderMysteryDescentItem;
  crimsonJoy: MurderMysteryDescentItem;
  crowdControl: MurderMysteryDescentItem;
  cuttingTheroots: MurderMysteryDescentItem;
  deadlyPrecision: MurderMysteryDescentItem;
  deadorAlive: MurderMysteryDescentItem;
  deathDefy: MurderMysteryDescentItem;
  distanttransMission: MurderMysteryDescentItem;
  doubleDosage: MurderMysteryDescentItem;
  dualProficiency: MurderMysteryDescentItem;
  exponentiation: MurderMysteryDescentItem;
  eyeonPrey: MurderMysteryDescentItem;
  firstJob: MurderMysteryDescentItem;
  firstOfMany: MurderMysteryDescentItem;
  firstSteps: MurderMysteryDescentItem;
  grandSlam: MurderMysteryDescentItem;
  hero: MurderMysteryDescentItem;
  highRoller: MurderMysteryDescentItem;
  holdGround: MurderMysteryDescentItem;
  huntsman: MurderMysteryDescentItem;
  jobSearch: MurderMysteryDescentItem;
  lawMaker: MurderMysteryDescentItem;
  Legacy: MurderMysteryDescentItem;
  localSpecialty: MurderMysteryDescentItem;
  lurkingContagion: MurderMysteryDescentItem;
  makeshiftShield: MurderMysteryDescentItem;
  mowingDown: MurderMysteryDescentItem;
  oneOfUs: MurderMysteryDescentItem;
  paneKiller: MurderMysteryDescentItem;
  patientZero: MurderMysteryDescentItem;
  postPandemic: MurderMysteryDescentItem;
  pythagoreanDisposal: MurderMysteryDescentItem;
  quickDraw: MurderMysteryDescentItem;
  reloaded: MurderMysteryDescentItem;
  seasonedHitman: MurderMysteryDescentItem;
  selfDefense: MurderMysteryDescentItem;
  serialTrapper: MurderMysteryDescentItem;
  silverBullet: MurderMysteryDescentItem;
  slaughterHouse: MurderMysteryDescentItem;
  sneaky: MurderMysteryDescentItem;
  survival: MurderMysteryDescentItem;
  totaloutBreak: MurderMysteryDescentItem;
  trapping101: MurderMysteryDescentItem;
  trulyMad: MurderMysteryDescentItem;
  viralKnife: MurderMysteryDescentItem;
  constructor(data: Record<string, any>) {
    this.Armed = new MurderMysteryDescentItem(data?.Armed || {});
    this.bloodLust = new MurderMysteryDescentItem(data?.Bloodlust || {});
    this.bountyHunter = new MurderMysteryDescentItem(data?.Bountyhunter || {});
    this.cleanJob = new MurderMysteryDescentItem(data?.Cleanjob || {});
    this.Collateral = new MurderMysteryDescentItem(data?.Collateral || {});
    this.contagionContained = new MurderMysteryDescentItem(data?.Contagioncontained || {});
    this.Cornucopia = new MurderMysteryDescentItem(data?.Cornucopia || {});
    this.crimsonJoy = new MurderMysteryDescentItem(data?.Crimsonjoy || {});
    this.crowdControl = new MurderMysteryDescentItem(data?.Crowdcontrol || {});
    this.cuttingTheroots = new MurderMysteryDescentItem(data?.Cuttingtheroots || {});
    this.deadlyPrecision = new MurderMysteryDescentItem(data?.Deadlyprecision || {});
    this.deadorAlive = new MurderMysteryDescentItem(data?.Deadoralive || {});
    this.deathDefy = new MurderMysteryDescentItem(data?.Deathdefy || {});
    this.distanttransMission = new MurderMysteryDescentItem(data?.Distanttransmission || {});
    this.doubleDosage = new MurderMysteryDescentItem(data?.Doubledosage || {});
    this.dualProficiency = new MurderMysteryDescentItem(data?.Dualproficiency || {});
    this.exponentiation = new MurderMysteryDescentItem(data?.Exponentiation || {});
    this.eyeonPrey = new MurderMysteryDescentItem(data?.Eyeonprey || {});
    this.firstJob = new MurderMysteryDescentItem(data?.Firstjob || {});
    this.firstOfMany = new MurderMysteryDescentItem(data?.Firstofmany || {});
    this.firstSteps = new MurderMysteryDescentItem(data?.Firststeps || {});
    this.grandSlam = new MurderMysteryDescentItem(data?.Grandslam || {});
    this.hero = new MurderMysteryDescentItem(data?.Hero || {});
    this.highRoller = new MurderMysteryDescentItem(data?.Highroller || {});
    this.holdGround = new MurderMysteryDescentItem(data?.Holdground || {});
    this.huntsman = new MurderMysteryDescentItem(data?.Huntsman || {});
    this.jobSearch = new MurderMysteryDescentItem(data?.Jobsearch || {});
    this.lawMaker = new MurderMysteryDescentItem(data?.Lawmaker || {});
    this.Legacy = new MurderMysteryDescentItem(data?.Legacy || {});
    this.localSpecialty = new MurderMysteryDescentItem(data?.Localspecialty || {});
    this.lurkingContagion = new MurderMysteryDescentItem(data?.Lurkingcontagion || {});
    this.makeshiftShield = new MurderMysteryDescentItem(data?.Makeshiftshield || {});
    this.mowingDown = new MurderMysteryDescentItem(data?.Mowingdown || {});
    this.oneOfUs = new MurderMysteryDescentItem(data?.Oneofus || {});
    this.paneKiller = new MurderMysteryDescentItem(data?.Panekiller || {});
    this.patientZero = new MurderMysteryDescentItem(data?.Patientzero || {});
    this.postPandemic = new MurderMysteryDescentItem(data?.Postpandemic || {});
    this.pythagoreanDisposal = new MurderMysteryDescentItem(data?.Pythagoreandisposal || {});
    this.quickDraw = new MurderMysteryDescentItem(data?.Quickdraw || {});
    this.reloaded = new MurderMysteryDescentItem(data?.Reloaded || {});
    this.seasonedHitman = new MurderMysteryDescentItem(data?.Seasonedhitman || {});
    this.selfDefense = new MurderMysteryDescentItem(data?.Selfdefense || {});
    this.serialTrapper = new MurderMysteryDescentItem(data?.Serialtrapper || {});
    this.silverBullet = new MurderMysteryDescentItem(data?.Silverbullet || {});
    this.slaughterHouse = new MurderMysteryDescentItem(data?.Slaughterhouse || {});
    this.sneaky = new MurderMysteryDescentItem(data?.Sneaky || {});
    this.survival = new MurderMysteryDescentItem(data?.Survival || {});
    this.totaloutBreak = new MurderMysteryDescentItem(data?.Totaloutbreak || {});
    this.trapping101 = new MurderMysteryDescentItem(data?.Trapping101 || {});
    this.trulyMad = new MurderMysteryDescentItem(data?.Trulymad || {});
    this.viralKnife = new MurderMysteryDescentItem(data?.Viralknife || {});
  }
}

export default MurderMysteryDescent;
