import House from './House.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { UUID } from '../Types/Global.js';

test('House', () => {
  const data = new House({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(House);
  expectTypeOf(data).toEqualTypeOf<House>();
  expect(data.name).toBeDefined();
  expectTypeOf(data.name).toEqualTypeOf<string>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<UUID>();
  expect(data.owner).toBeDefined();
  expectTypeOf(data.owner).toEqualTypeOf<string>();
  expect(data.createdAtTimestamp).toBeDefined();
  expectTypeOf(data.createdAtTimestamp).toEqualTypeOf<number | null>();
  expect(data.createdAt).toBeDefined();
  expectTypeOf(data.createdAt).toEqualTypeOf<Date | null>();
  expect(data.players).toBeDefined();
  expect(data.players).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.players).toEqualTypeOf<number>();
  expect(data.cookies).toBeDefined();
  expect(data.cookies).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.cookies).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => string>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.name);
  expectTypeOf(data.toString()).toEqualTypeOf<string>();
});
