import SkyBlockMemberQuestsHarp from './SkyBlockMemberQuestsHarp.js';
import SkyBlockMemberQuestsHarpSong from './SkyBlockMemberQuestsHarpSong.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { HarpSong } from '../../../../Types/SkyBlock.js';

test('SkyBlockMemberQuestsHarp', () => {
  const data = new SkyBlockMemberQuestsHarp({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberQuestsHarp);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberQuestsHarp>();
  expect(data.selectedSong).toBeDefined();
  expectTypeOf(data.selectedSong).toEqualTypeOf<HarpSong | 'UNKNOWN'>();
  expect(data.selectedSongTimestamp).toBeDefined();
  expect(data.selectedSongTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.selectedSongTimestamp).toEqualTypeOf<number>();
  expect(data.selectedSongDate).toBeDefined();
  expect(data.selectedSongDate).toBeInstanceOf(Date);
  expectTypeOf(data.selectedSongDate).toEqualTypeOf<Date>();
  expect(data.claimedTalisman).toBeDefined();
  expectTypeOf(data.claimedTalisman).toEqualTypeOf<boolean>();
  expect(data.hymnJoy).toBeDefined();
  expect(data.hymnJoy).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.hymnJoy).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.frereJacques).toBeDefined();
  expect(data.frereJacques).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.frereJacques).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.amazingGrace).toBeDefined();
  expect(data.amazingGrace).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.amazingGrace).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.brahms).toBeDefined();
  expect(data.brahms).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.brahms).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.happyBirthday).toBeDefined();
  expect(data.happyBirthday).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.happyBirthday).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.greensleeves).toBeDefined();
  expect(data.greensleeves).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.greensleeves).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.jeopardy).toBeDefined();
  expect(data.jeopardy).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.jeopardy).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.minuet).toBeDefined();
  expect(data.minuet).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.minuet).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.joyWorld).toBeDefined();
  expect(data.joyWorld).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.joyWorld).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.pureImagination).toBeDefined();
  expect(data.pureImagination).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.pureImagination).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.vieEnRose).toBeDefined();
  expect(data.vieEnRose).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.vieEnRose).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.fireAndFlames).toBeDefined();
  expect(data.fireAndFlames).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.fireAndFlames).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.pachelbel).toBeDefined();
  expect(data.pachelbel).toBeInstanceOf(SkyBlockMemberQuestsHarpSong);
  expectTypeOf(data.pachelbel).toEqualTypeOf<SkyBlockMemberQuestsHarpSong>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => HarpSong | 'UNKNOWN'>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.selectedSong);
  expectTypeOf(data.toString()).toEqualTypeOf<HarpSong | 'UNKNOWN'>();
});
