import SkyWarsMode from '../../SkyWarsMode/SkyWarsMode.js';
import SkyWarsSoloKitsMini from './SkyWarsSoloKitsMini.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsSoloKitsMini', () => {
  const data = new SkyWarsSoloKitsMini({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsSoloKitsMini);
  expectTypeOf(data).toEqualTypeOf<SkyWarsSoloKitsMini>();
  expect(data.athlete).toBeDefined();
  expect(data.athlete).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.athlete).toEqualTypeOf<SkyWarsMode>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<SkyWarsMode>();
  expect(data.champion).toBeDefined();
  expect(data.champion).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.champion).toEqualTypeOf<SkyWarsMode>();
  expect(data.magician).toBeDefined();
  expect(data.magician).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.magician).toEqualTypeOf<SkyWarsMode>();
  expect(data.bowman).toBeDefined();
  expect(data.bowman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.bowman).toEqualTypeOf<SkyWarsMode>();
  expect(data.healer).toBeDefined();
  expect(data.healer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.healer).toEqualTypeOf<SkyWarsMode>();
  expect(data.pyromancer).toBeDefined();
  expect(data.pyromancer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.pyromancer).toEqualTypeOf<SkyWarsMode>();
  expect(data.armorer).toBeDefined();
  expect(data.armorer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.armorer).toEqualTypeOf<SkyWarsMode>();
  expect(data.blacksmith).toBeDefined();
  expect(data.blacksmith).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.blacksmith).toEqualTypeOf<SkyWarsMode>();
  expect(data.hound).toBeDefined();
  expect(data.hound).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.hound).toEqualTypeOf<SkyWarsMode>();
  expect(data.paladin).toBeDefined();
  expect(data.paladin).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.paladin).toEqualTypeOf<SkyWarsMode>();
});
