import BaseSkyWarsMode from '../../SkyWarsMode/BaseSkyWarsMode.js';
import SkyWarsSoloKitsAdvanced from './SkyWarsSoloKitsAdvanced.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsSoloKitsAdvanced', () => {
  const data = new SkyWarsSoloKitsAdvanced({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsSoloKitsAdvanced);
  expectTypeOf(data).toEqualTypeOf<SkyWarsSoloKitsAdvanced>();
  expect(data.farmer).toBeDefined();
  expect(data.farmer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.farmer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.enchanter).toBeDefined();
  expect(data.enchanter).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.enchanter).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.hunter).toBeDefined();
  expect(data.hunter).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.hunter).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.knight).toBeDefined();
  expect(data.knight).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.knight).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.armorer).toBeDefined();
  expect(data.armorer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.armorer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.cannoneer).toBeDefined();
  expect(data.cannoneer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.cannoneer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.pyro).toBeDefined();
  expect(data.pyro).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.pyro).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.salmon).toBeDefined();
  expect(data.salmon).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.salmon).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.zookeeper).toBeDefined();
  expect(data.zookeeper).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.zookeeper).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.enderman).toBeDefined();
  expect(data.enderman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.enderman).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.slime).toBeDefined();
  expect(data.slime).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.slime).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.pigRider).toBeDefined();
  expect(data.pigRider).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.pigRider).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.sloth).toBeDefined();
  expect(data.sloth).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.sloth).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.jester).toBeDefined();
  expect(data.jester).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.jester).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.guardian).toBeDefined();
  expect(data.guardian).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.guardian).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.engineer).toBeDefined();
  expect(data.engineer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.engineer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.magician).toBeDefined();
  expect(data.magician).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.magician).toEqualTypeOf<BaseSkyWarsMode>();
});
