import SkyWars from './SkyWars.js';
import SkyWarsKitsMythics from './SkyWarsKitsMythics/SkyWarsKitsMythics.js';
import SkyWarsMega from './SkyWarsMega/SkyWarsMega.js';
import SkyWarsMini from './SkyWarsMini.js';
import SkyWarsPrivateGames from './SkyWarsPrivateGames.js';
import SkyWarsSolo from './SkyWarsSolo/SkyWarsSolo.js';
import SkyWarsTeams from './SkyWarsTeams/SkyWarsTeams.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { ShopSort } from '../../../Types/Player.js';

test('SkyWars', () => {
  const data = new SkyWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWars);
  expectTypeOf(data).toEqualTypeOf<SkyWars>();
  expect(data.activeKillEffect).toBeDefined();
  expectTypeOf(data.activeKillEffect).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeVictoryDance).toBeDefined();
  expectTypeOf(data.activeVictoryDance).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeKillMessages).toBeDefined();
  expectTypeOf(data.activeKillMessages).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeDeathCry).toBeDefined();
  expectTypeOf(data.activeDeathCry).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeBalloon).toBeDefined();
  expectTypeOf(data.activeBalloon).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeCage).toBeDefined();
  expectTypeOf(data.activeCage).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeSprays).toBeDefined();
  expectTypeOf(data.activeSprays).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.activeProjectileTrail).toBeDefined();
  expectTypeOf(data.activeProjectileTrail).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.shopSort).toBeDefined();
  expectTypeOf(data.shopSort).toEqualTypeOf<ShopSort | 'UNKNOWN'>();
  expect(data.coins).toBeDefined();
  expect(data.coins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.coins).toEqualTypeOf<number>();
  expect(data.tokens).toBeDefined();
  expect(data.tokens).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.tokens).toEqualTypeOf<number>();
  expect(data.xp).toBeDefined();
  expect(data.xp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.xp).toEqualTypeOf<number>();
  expect(data.mythicalKits).toBeDefined();
  expect(data.mythicalKits).toBeInstanceOf(SkyWarsKitsMythics);
  expectTypeOf(data.mythicalKits).toEqualTypeOf<SkyWarsKitsMythics>();
  expect(data.selectedPrestigeIcon).toBeDefined();
  expectTypeOf(data.selectedPrestigeIcon).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.angelOfDeathLevel).toBeDefined();
  expect(data.angelOfDeathLevel).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.angelOfDeathLevel).toEqualTypeOf<number>();
  expect(data.quits).toBeDefined();
  expect(data.quits).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.quits).toEqualTypeOf<number>();
  expect(data.souls).toBeDefined();
  expect(data.souls).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.souls).toEqualTypeOf<number>();
  expect(data.soulWell).toBeDefined();
  expect(data.soulWell).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soulWell).toEqualTypeOf<number>();
  expect(data.soulsGathered).toBeDefined();
  expect(data.soulsGathered).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soulsGathered).toEqualTypeOf<number>();
  expect(data.paidSouls).toBeDefined();
  expect(data.paidSouls).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.paidSouls).toEqualTypeOf<number>();
  expect(data.soulWellRares).toBeDefined();
  expect(data.soulWellRares).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soulWellRares).toEqualTypeOf<number>();
  expect(data.soulWellLegendaries).toBeDefined();
  expect(data.soulWellLegendaries).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soulWellLegendaries).toEqualTypeOf<number>();
  expect(data.refillChestDestroy).toBeDefined();
  expect(data.refillChestDestroy).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.refillChestDestroy).toEqualTypeOf<number>();
  expect(data.harvestingSeason).toBeDefined();
  expect(data.harvestingSeason).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.harvestingSeason).toEqualTypeOf<number>();
  expect(data.xezbethLuck).toBeDefined();
  expect(data.xezbethLuck).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.xezbethLuck).toEqualTypeOf<number>();
  expect(data.extraWheels).toBeDefined();
  expect(data.extraWheels).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.extraWheels).toEqualTypeOf<number>();
  expect(data.weeklyKills).toBeDefined();
  expect(data.weeklyKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKills).toEqualTypeOf<number>();
  expect(data.weeklyKillsA).toBeDefined();
  expect(data.weeklyKillsA).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKillsA).toEqualTypeOf<number>();
  expect(data.weeklyKillsB).toBeDefined();
  expect(data.weeklyKillsB).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKillsB).toEqualTypeOf<number>();
  expect(data.monthlyKills).toBeDefined();
  expect(data.monthlyKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKills).toEqualTypeOf<number>();
  expect(data.monthlyKillsA).toBeDefined();
  expect(data.monthlyKillsA).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKillsA).toEqualTypeOf<number>();
  expect(data.monthlyKillsB).toBeDefined();
  expect(data.monthlyKillsB).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKillsB).toEqualTypeOf<number>();
  expect(data.quickjoinUsesTotal).toBeDefined();
  expect(data.quickjoinUsesTotal).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.quickjoinUsesTotal).toEqualTypeOf<number>();
  expect(data.quickjoinUsesRandom).toBeDefined();
  expect(data.quickjoinUsesRandom).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.quickjoinUsesRandom).toEqualTypeOf<number>();
  expect(data.chests).toBeDefined();
  expect(data.chests).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.chests).toEqualTypeOf<number>();
  expect(data.chestHistory).toBeDefined();
  expectTypeOf(data.chestHistory).toEqualTypeOf<string[]>();
  expect(data.goldenBoxes).toBeDefined();
  expect(data.goldenBoxes).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.goldenBoxes).toEqualTypeOf<number>();
  expect(data.halloweenBoxes).toBeDefined();
  expect(data.halloweenBoxes).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.halloweenBoxes).toEqualTypeOf<number>();
  expect(data.christmasBoxes).toBeDefined();
  expect(data.christmasBoxes).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.christmasBoxes).toEqualTypeOf<number>();
  expect(data.lunarBoxes).toBeDefined();
  expect(data.lunarBoxes).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.lunarBoxes).toEqualTypeOf<number>();
  expect(data.easterBoxes).toBeDefined();
  expect(data.easterBoxes).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.easterBoxes).toEqualTypeOf<number>();
  expect(data.beastChance).toBeDefined();
  expect(data.beastChance).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.beastChance).toEqualTypeOf<number>();
  expect(data.privateGamesSettings).toBeDefined();
  expect(data.privateGamesSettings).toBeInstanceOf(SkyWarsPrivateGames);
  expectTypeOf(data.privateGamesSettings).toEqualTypeOf<SkyWarsPrivateGames>();
  expect(data.solo).toBeDefined();
  expect(data.solo).toBeInstanceOf(SkyWarsSolo);
  expectTypeOf(data.solo).toEqualTypeOf<SkyWarsSolo>();
  expect(data.teams).toBeDefined();
  expect(data.teams).toBeInstanceOf(SkyWarsTeams);
  expectTypeOf(data.teams).toEqualTypeOf<SkyWarsTeams>();
  expect(data.mega).toBeDefined();
  expect(data.mega).toBeInstanceOf(SkyWarsMega);
  expectTypeOf(data.mega).toEqualTypeOf<SkyWarsMega>();
  expect(data.mini).toBeDefined();
  expect(data.mini).toBeInstanceOf(SkyWarsMini);
  expectTypeOf(data.mini).toEqualTypeOf<SkyWarsMini>();
});
