import SkyWarsHeads from './SkyWarsHeads.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsHeads', () => {
  const data = new SkyWarsHeads({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsHeads);
  expectTypeOf(data).toEqualTypeOf<SkyWarsHeads>();
  expect(data.total).toBeDefined();
  expect(data.total).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.total).toEqualTypeOf<number>();
  expect(data.tasty).toBeDefined();
  expect(data.tasty).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.tasty).toEqualTypeOf<number>();
  expect(data.yucky).toBeDefined();
  expect(data.yucky).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.yucky).toEqualTypeOf<number>();
  expect(data.eww).toBeDefined();
  expect(data.eww).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.eww).toEqualTypeOf<number>();
  expect(data.salty).toBeDefined();
  expect(data.salty).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.salty).toEqualTypeOf<number>();
  expect(data.divine).toBeDefined();
  expect(data.divine).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.divine).toEqualTypeOf<number>();
  expect(data.heavenly).toBeDefined();
  expect(data.heavenly).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.heavenly).toEqualTypeOf<number>();
  expect(data.decent).toBeDefined();
  expect(data.decent).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.decent).toEqualTypeOf<number>();
  expect(data.meh).toBeDefined();
  expect(data.meh).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.meh).toEqualTypeOf<number>();
  expect(data.succulent).toBeDefined();
  expect(data.succulent).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.succulent).toEqualTypeOf<number>();
  expect(data.sweet).toBeDefined();
  expect(data.sweet).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sweet).toEqualTypeOf<number>();
  expect(data.ethereal).toBeDefined();
  expect(data.ethereal).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.ethereal).toEqualTypeOf<number>();
  expect(data.indescribable).toBeDefined();
  expect(data.indescribable).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.indescribable).toEqualTypeOf<number>();
  expect(data.special).toBeDefined();
  expect(data.special).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.special).toEqualTypeOf<number>();
});
