import WoolWars from './WoolWars.js';
import WoolWarsClass from './WoolWarsClass.js';
import WoolWarsSettings from './WoolWarsSettings.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { WoolGamesWoolWarsClassName } from '../../../../Types/Player.js';

test('WoolWars', () => {
  const data = new WoolWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(WoolWars);
  expectTypeOf(data).toEqualTypeOf<WoolWars>();
  expect(data.selectedClass).toBeDefined();
  expectTypeOf(data.selectedClass).toEqualTypeOf<WoolGamesWoolWarsClassName | 'None'>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.assists).toBeDefined();
  expect(data.assists).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.assists).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.killDeathRatio).toBeDefined();
  expect(data.killDeathRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killDeathRatio).toEqualTypeOf<number>();
  expect(data.gamesPlayed).toBeDefined();
  expect(data.gamesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gamesPlayed).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.winLossRatio).toBeDefined();
  expect(data.winLossRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winLossRatio).toEqualTypeOf<number>();
  expect(data.woolPlaced).toBeDefined();
  expect(data.woolPlaced).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.woolPlaced).toEqualTypeOf<number>();
  expect(data.blocksBroken).toBeDefined();
  expect(data.blocksBroken).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.blocksBroken).toEqualTypeOf<number>();
  expect(data.placeBreakRatio).toBeDefined();
  expect(data.placeBreakRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.placeBreakRatio).toEqualTypeOf<number>();
  expect(data.powerupsGotten).toBeDefined();
  expect(data.powerupsGotten).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.powerupsGotten).toEqualTypeOf<number>();
  expect(data.settings).toBeDefined();
  expect(data.settings).toBeInstanceOf(WoolWarsSettings);
  expectTypeOf(data.settings).toEqualTypeOf<WoolWarsSettings>();
  expect(data.assault).toBeDefined();
  expect(data.assault).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.assault).toEqualTypeOf<WoolWarsClass>();
  expect(data.tank).toBeDefined();
  expect(data.tank).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.tank).toEqualTypeOf<WoolWarsClass>();
  expect(data.golem).toBeDefined();
  expect(data.golem).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.golem).toEqualTypeOf<WoolWarsClass>();
  expect(data.swordsman).toBeDefined();
  expect(data.swordsman).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.swordsman).toEqualTypeOf<WoolWarsClass>();
  expect(data.engineer).toBeDefined();
  expect(data.engineer).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.engineer).toEqualTypeOf<WoolWarsClass>();
  expect(data.archer).toBeDefined();
  expect(data.archer).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.archer).toEqualTypeOf<WoolWarsClass>();
});
