import GameCountsSkyWarsModes from './GameCountsSkyWarsModes.js';
import { expect, expectTypeOf, test } from 'vitest';

test('GameCountsSkyWarsModes', () => {
  const data = new GameCountsSkyWarsModes({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(GameCountsSkyWarsModes);
  expectTypeOf(data).toEqualTypeOf<GameCountsSkyWarsModes>();
  expect(data.soloInsaneLucky).toBeDefined();
  expect(data.soloInsaneLucky).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soloInsaneLucky).toEqualTypeOf<number>();
  expect(data.soloInsaneSlime).toBeDefined();
  expect(data.soloInsaneSlime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soloInsaneSlime).toEqualTypeOf<number>();
  expect(data.teamsInsaneSlime).toBeDefined();
  expect(data.teamsInsaneSlime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.teamsInsaneSlime).toEqualTypeOf<number>();
  expect(data.teamsInsaneRush).toBeDefined();
  expect(data.teamsInsaneRush).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.teamsInsaneRush).toEqualTypeOf<number>();
  expect(data.teamsInsaneLucky).toBeDefined();
  expect(data.teamsInsaneLucky).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.teamsInsaneLucky).toEqualTypeOf<number>();
  expect(data.soloInsaneHuntersVsBeasts).toBeDefined();
  expect(data.soloInsaneHuntersVsBeasts).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soloInsaneHuntersVsBeasts).toEqualTypeOf<number>();
  expect(data.soloInsaneTntMadness).toBeDefined();
  expect(data.soloInsaneTntMadness).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soloInsaneTntMadness).toEqualTypeOf<number>();
  expect(data.megaDoubles).toBeDefined();
  expect(data.megaDoubles).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.megaDoubles).toEqualTypeOf<number>();
  expect(data.miniNormal).toBeDefined();
  expect(data.miniNormal).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.miniNormal).toEqualTypeOf<number>();
  expect(data.soloInsaneRush).toBeDefined();
  expect(data.soloInsaneRush).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soloInsaneRush).toEqualTypeOf<number>();
  expect(data.soloInsane).toBeDefined();
  expect(data.soloInsane).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soloInsane).toEqualTypeOf<number>();
  expect(data.teamsInsaneTntMadness).toBeDefined();
  expect(data.teamsInsaneTntMadness).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.teamsInsaneTntMadness).toEqualTypeOf<number>();
});
