import SkyBlockMemberInventories from './SkyBlockMemberInventories.js';
import SkyBlockMemberInventoriesArmor from './Armor/SkyBlockMemberInventoriesArmor.js';
import SkyBlockMemberInventoriesBackpacks from './Backpacks/SkyBlockMemberInventoriesBackpacks.js';
import SkyBlockMemberInventoriesBags from './Bags/SkyBlockMemberInventoriesBags.js';
import SkyBlockMemberInventoriesEquipment from './Equipment/SkyBlockMemberInventoriesEquipment.js';
import SkyBlockMemberInventoriesInventory from './Inventory/SkyBlockMemberInventoriesInventory.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberInventories', () => {
  const data = new SkyBlockMemberInventories({ stats: 'meow' }, { stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberInventories);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberInventories>();
  expect(data.inventory).toBeDefined();
  expect(data.inventory).toBeInstanceOf(SkyBlockMemberInventoriesInventory);
  expectTypeOf(data.inventory).toEqualTypeOf<SkyBlockMemberInventoriesInventory>();
  expect(data.armor).toBeDefined();
  expect(data.armor).toBeInstanceOf(SkyBlockMemberInventoriesArmor);
  expectTypeOf(data.armor).toEqualTypeOf<SkyBlockMemberInventoriesArmor>();
  expect(data.equipment).toBeDefined();
  expect(data.equipment).toBeInstanceOf(SkyBlockMemberInventoriesEquipment);
  expectTypeOf(data.equipment).toEqualTypeOf<SkyBlockMemberInventoriesEquipment>();
  expect(data.backpacks).toBeDefined();
  expect(data.backpacks).toBeInstanceOf(SkyBlockMemberInventoriesBackpacks);
  expectTypeOf(data.backpacks).toEqualTypeOf<SkyBlockMemberInventoriesBackpacks>();
  expect(data.enderChest).toBeDefined();
  expect(data.enderChest).toBeInstanceOf(SkyBlockMemberInventoriesInventory);
  expectTypeOf(data.enderChest).toEqualTypeOf<SkyBlockMemberInventoriesInventory>();
  expect(data.bags).toBeDefined();
  expect(data.bags).toBeInstanceOf(SkyBlockMemberInventoriesBags);
  expectTypeOf(data.bags).toEqualTypeOf<SkyBlockMemberInventoriesBags>();
  expect(data.personalVault).toBeDefined();
  expect(data.personalVault).toBeInstanceOf(SkyBlockMemberInventoriesInventory);
  expectTypeOf(data.personalVault).toEqualTypeOf<SkyBlockMemberInventoriesInventory>();
  expect(data.wardrobe).toBeDefined();
  expect(data.wardrobe).toBeInstanceOf(SkyBlockMemberInventoriesInventory);
  expectTypeOf(data.wardrobe).toEqualTypeOf<SkyBlockMemberInventoriesInventory>();
  expect(data.sacksCounts).toBeDefined();
  expectTypeOf(data.sacksCounts).toEqualTypeOf<Record<string, number>>();
  expect(data.candy).toBeDefined();
  expect(data.candy).toBeInstanceOf(SkyBlockMemberInventoriesInventory);
  expectTypeOf(data.candy).toEqualTypeOf<SkyBlockMemberInventoriesInventory>();
  expect(data.carnivalMask).toBeDefined();
  expect(data.carnivalMask).toBeInstanceOf(SkyBlockMemberInventoriesInventory);
  expectTypeOf(data.carnivalMask).toEqualTypeOf<SkyBlockMemberInventoriesInventory>();
});
