import Booster from './Booster.js';
import Game from '../Game.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { BoosterType } from '../../Types/Booster.js';

test('Booster', () => {
  const data = new Booster({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Booster);
  expectTypeOf(data).toEqualTypeOf<Booster>();
  expect(data.purchaser).toBeDefined();
  expectTypeOf(data.purchaser).toEqualTypeOf<string>();
  expect(data.amount).toBeDefined();
  expect(data.amount).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.amount).toEqualTypeOf<number>();
  expect(data.originalLength).toBeDefined();
  expect(data.originalLength).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.originalLength).toEqualTypeOf<number>();
  expect(data.remaining).toBeDefined();
  expect(data.remaining).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.remaining).toEqualTypeOf<number>();
  expect(data.activatedTimestamp).toBeDefined();
  expect(data.activatedTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.activatedTimestamp).toEqualTypeOf<number>();
  expect(data.activated).toBeDefined();
  expect(data.activated).toBeInstanceOf(Date);
  expectTypeOf(data.activated).toEqualTypeOf<Date>();
  expect(data.game).toBeDefined();
  expect(data.game).toBeInstanceOf(Game);
  expectTypeOf(data.game).toEqualTypeOf<Game>();
  expect(data.isActive).toBeDefined();
  expectTypeOf(data.isActive).toEqualTypeOf<boolean>();
  expect(data.type).toBeDefined();
  expectTypeOf(data.type).toEqualTypeOf<BoosterType>();
  expect(data.stackers).toBeDefined();
  expectTypeOf(data.stackers).toEqualTypeOf<string[]>();
  expect(data.expired).toBeDefined();
  expectTypeOf(data.expired).toEqualTypeOf<boolean>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => string>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(`${data.purchaser}'s booster in ${data.game}`);
  expectTypeOf(data.toString()).toEqualTypeOf<string>();
});
