const i = {
	2: 'Quake Craft',
	3: 'Walls',
	4: 'Paintball',
	5: 'Blitz Survival Games',
	6: 'TNT Games',
	7: 'VampireZ',
	13: 'Walls3',
	14: 'Arcade',
	17: 'Arena', 
	20: 'UHC',
	21: 'Cops and Crims',
	23: 'Warlords', 
	24: 'Smash Heroes',
	25: 'Turbo Kart Racers',
	26: 'Housing',
	51: 'SkyWars',
	52: 'Crazy Walls',
	54: 'Speed UHC',
	55: 'SkyClash',
	56: 'Classic Games',
	57: 'Prototype',
	58: 'BedWars',
	59: 'Murder Mystery',
	60: 'Build Battle',
	61: 'Duels',
	63: 'SkyBlock',
	64: 'The Pit'
};
module.exports = i;