import BedWarsSLumberSandman from './BedWarsSlumberSandman.js';
import BedWarsSlumber from './BedWarsSlumber.js';
import BedWarsSlumberMinion from './BedWarsSlumberMinion.js';
import BedWarsSlumberPhase from './BedWarsSlumberPhase.js';
import BedWarsSlumberPhaseThree from './BedWarsSlumberPhaseThree.js';
import BedWarsSlumberQuest from './BedWarsSlumberQuest/BedWarsSlumberQuest.js';
import BedWarsSlumberRoom from './BedWarsSlumberRoom.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { BedWarsSlumberBag, ShopSort } from '../../../../Types/Player.js';

test('BedWarsSlumber', () => {
  const data = new BedWarsSlumber({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsSlumber);
  expectTypeOf(data).toEqualTypeOf<BedWarsSlumber>();
  expect(data.bagType).toBeDefined();
  expectTypeOf(data.bagType).toEqualTypeOf<BedWarsSlumberBag | 'UNKNOWN'>();
  expect(data.boonMultiplier).toBeDefined();
  expect(data.boonMultiplier).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.boonMultiplier).toEqualTypeOf<number>();
  expect(data.currentCosmeticSorting).toBeDefined();
  expectTypeOf(data.currentCosmeticSorting).toEqualTypeOf<ShopSort | 'UNKNOWN'>();
  expect(data.doublers).toBeDefined();
  expect(data.doublers).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.doublers).toEqualTypeOf<number>();
  expect(data.minion).toBeDefined();
  expect(data.minion).toBeInstanceOf(BedWarsSlumberMinion);
  expectTypeOf(data.minion).toEqualTypeOf<BedWarsSlumberMinion>();
  expect(data.phase).toBeDefined();
  expect(data.phase).toBeInstanceOf(BedWarsSlumberPhase);
  expectTypeOf(data.phase).toEqualTypeOf<BedWarsSlumberPhase>();
  expect(data.phasethree).toBeDefined();
  expect(data.phasethree).toBeInstanceOf(BedWarsSlumberPhaseThree);
  expectTypeOf(data.phasethree).toEqualTypeOf<BedWarsSlumberPhaseThree>();
  expect(data.quest).toBeDefined();
  expect(data.quest).toBeInstanceOf(BedWarsSlumberQuest);
  expectTypeOf(data.quest).toEqualTypeOf<BedWarsSlumberQuest>();
  expect(data.rooms).toBeDefined();
  expect(data.rooms).toBeInstanceOf(BedWarsSlumberRoom);
  expectTypeOf(data.rooms).toEqualTypeOf<BedWarsSlumberRoom>();
  expect(data.sandman).toBeDefined();
  expect(data.sandman).toBeInstanceOf(BedWarsSLumberSandman);
  expectTypeOf(data.sandman).toEqualTypeOf<BedWarsSLumberSandman>();
  expect(data.tickets).toBeDefined();
  expect(data.tickets).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.tickets).toEqualTypeOf<number>();
  expect(data.ticketsGivenToDoorman).toBeDefined();
  expect(data.ticketsGivenToDoorman).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.ticketsGivenToDoorman).toEqualTypeOf<number>();
  expect(data.ticketsRequirementMet).toBeDefined();
  expectTypeOf(data.ticketsRequirementMet).toEqualTypeOf<boolean>();
  expect(data.totalTicketsEarned).toBeDefined();
  expect(data.totalTicketsEarned).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.totalTicketsEarned).toEqualTypeOf<number>();
  expect(data.walletFullWarning).toBeDefined();
  expectTypeOf(data.walletFullWarning).toEqualTypeOf<boolean>();
});
