import SkyBlockInventoryItem from './SkyBlockInventoryItem.js';
import SkyBlockInventoryItemAttribute from './SkyBlockInventoryItemAttribute.js';
import SkyBlockInventoryItemEnchantment from './SkyBlockInventoryItemEnchantment.js';
import SkyBlockInventoryItemRune from './SkyBlockInventoryItemRune.js';
import SkyBlockPotionEffect from '../Potion/SkyBlockPotionEffect.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { Rarity } from '../../../Types/SkyBlock.js';
import type { UUID } from '../../../Types/Global.js';

test('SkyBlockInventoryItem', () => {
  const data = new SkyBlockInventoryItem({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockInventoryItem);
  expectTypeOf(data).toEqualTypeOf<SkyBlockInventoryItem>();
  expect(data.minecraftItemId).toBeDefined();
  expect(data.minecraftItemId).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.minecraftItemId).toEqualTypeOf<number>();
  expect(data.itemCount).toBeDefined();
  expect(data.itemCount).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.itemCount).toEqualTypeOf<number>();
  expect(data.itemDamage).toBeDefined();
  expect(data.itemDamage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.itemDamage).toEqualTypeOf<number>();
  expect(data.unbreakable).toBeDefined();
  expectTypeOf(data.unbreakable).toEqualTypeOf<boolean>();
  expect(data.hideFlags).toBeDefined();
  expectTypeOf(data.hideFlags).toEqualTypeOf<number | null>();
  expect(data.lore).toBeDefined();
  expectTypeOf(data.lore).toEqualTypeOf<string[] | null>();
  expect(data.name).toBeDefined();
  expectTypeOf(data.name).toEqualTypeOf<string | 'UNKNOWN'>();
  expect(data.color).toBeDefined();
  expectTypeOf(data.color).toEqualTypeOf<number | null>();
  expect(data.recombobulated).toBeDefined();
  expectTypeOf(data.recombobulated).toEqualTypeOf<boolean>();
  expect(data.statsBook).toBeDefined();
  expectTypeOf(data.statsBook).toEqualTypeOf<number | null>();
  expect(data.runes).toBeDefined();
  expectTypeOf(data.runes).toEqualTypeOf<SkyBlockInventoryItemRune[] | null>();
  expect(data.reforge).toBeDefined();
  expectTypeOf(data.reforge).toEqualTypeOf<string | 'none'>();
  expect(data.hasArtOfWar).toBeDefined();
  expectTypeOf(data.hasArtOfWar).toEqualTypeOf<boolean>();
  expect(data.starCount).toBeDefined();
  expect(data.starCount).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.starCount).toEqualTypeOf<number>();
  expect(data.enchantments).toBeDefined();
  expectTypeOf(data.enchantments).toEqualTypeOf<SkyBlockInventoryItemEnchantment[] | null>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<UUID | null>();
  expect(data.hotPotatoBookCount).toBeDefined();
  expectTypeOf(data.hotPotatoBookCount).toEqualTypeOf<number | null>();
  expect(data.championCombatXP).toBeDefined();
  expectTypeOf(data.championCombatXP).toEqualTypeOf<number | null>();
  expect(data.id).toBeDefined();
  expectTypeOf(data.id).toEqualTypeOf<string>();
  expect(data.hasDonatedItem).toBeDefined();
  expectTypeOf(data.hasDonatedItem).toEqualTypeOf<boolean>();
  expect(data.transmissionTunerCount).toBeDefined();
  expectTypeOf(data.transmissionTunerCount).toEqualTypeOf<number | null>();
  expect(data.powerAbilityScroll).toBeDefined();
  expectTypeOf(data.powerAbilityScroll).toEqualTypeOf<string | null>();
  expect(data.hasEtherwarp).toBeDefined();
  expectTypeOf(data.hasEtherwarp).toEqualTypeOf<boolean>();
  expect(data.isDungeonItem).toBeDefined();
  expectTypeOf(data.isDungeonItem).toEqualTypeOf<boolean>();
  expect(data.abilityScrolls).toBeDefined();
  expectTypeOf(data.abilityScrolls).toEqualTypeOf<string[] | null>();
  expect(data.dungeonSkillRequirement).toBeDefined();
  expectTypeOf(data.dungeonSkillRequirement).toEqualTypeOf<number | null>();
  expect(data.baseStatBoostPercentage).toBeDefined();
  expectTypeOf(data.baseStatBoostPercentage).toEqualTypeOf<number | null>();
  expect(data.itemTier).toBeDefined();
  expectTypeOf(data.itemTier).toEqualTypeOf<number | null>();
  expect(data.manaDisintergratorCount).toBeDefined();
  expectTypeOf(data.manaDisintergratorCount).toEqualTypeOf<number | null>();
  expect(data.skin).toBeDefined();
  expectTypeOf(data.skin).toEqualTypeOf<string | null>();
  expect(data.blazetekkChannel).toBeDefined();
  expectTypeOf(data.blazetekkChannel).toEqualTypeOf<number | null>();
  expect(data.capturedPlayer).toBeDefined();
  expectTypeOf(data.capturedPlayer).toEqualTypeOf<string | null>();
  expect(data.cakeOwner).toBeDefined();
  expectTypeOf(data.cakeOwner).toEqualTypeOf<string | null>();
  expect(data.soulDurability).toBeDefined();
  expectTypeOf(data.soulDurability).toEqualTypeOf<number | null>();
  expect(data.initiatorPlayer).toBeDefined();
  expectTypeOf(data.initiatorPlayer).toEqualTypeOf<string | null>();
  expect(data.isShiny).toBeDefined();
  expectTypeOf(data.isShiny).toEqualTypeOf<boolean>();
  expect(data.attributes).toBeDefined();
  expectTypeOf(data.attributes).toEqualTypeOf<SkyBlockInventoryItemAttribute[] | null>();
  expect(data.jalapenoCount).toBeDefined();
  expectTypeOf(data.jalapenoCount).toEqualTypeOf<number | null>();
  expect(data.hecatombSRuns).toBeDefined();
  expectTypeOf(data.hecatombSRuns).toEqualTypeOf<number | null>();
  expect(data.dungeonItemLevel).toBeDefined();
  expectTypeOf(data.dungeonItemLevel).toEqualTypeOf<number | null>();
  expect(data.originTag).toBeDefined();
  expectTypeOf(data.originTag).toEqualTypeOf<string | null>();
  expect(data.hasArtOfPeace).toBeDefined();
  expectTypeOf(data.hasArtOfPeace).toEqualTypeOf<boolean>();
  expect(data.secondRandomColor).toBeDefined();
  expectTypeOf(data.secondRandomColor).toEqualTypeOf<number | null>();
  expect(data.dyeItem).toBeDefined();
  expectTypeOf(data.dyeItem).toEqualTypeOf<string | null>();
  expect(data.raffleYear).toBeDefined();
  expectTypeOf(data.raffleYear).toEqualTypeOf<number | null>();
  expect(data.raffleWin).toBeDefined();
  expectTypeOf(data.raffleWin).toEqualTypeOf<string | null>();
  expect(data.edition).toBeDefined();
  expectTypeOf(data.edition).toEqualTypeOf<number | null>();
  expect(data.recipientName).toBeDefined();
  expectTypeOf(data.recipientName).toEqualTypeOf<string | null>();
  expect(data.recipientUUID).toBeDefined();
  expectTypeOf(data.recipientUUID).toEqualTypeOf<string | null>();
  expect(data.bossTier).toBeDefined();
  expectTypeOf(data.bossTier).toEqualTypeOf<number | null>();
  expect(data.divanPowerCoating).toBeDefined();
  expectTypeOf(data.divanPowerCoating).toEqualTypeOf<number | null>();
  expect(data.year).toBeDefined();
  expectTypeOf(data.year).toEqualTypeOf<number | null>();
  expect(data.bossId).toBeDefined();
  expectTypeOf(data.bossId).toEqualTypeOf<number | null>();
  expect(data.spawnedFor).toBeDefined();
  expectTypeOf(data.spawnedFor).toEqualTypeOf<number | null>();
  expect(data.emanKills).toBeDefined();
  expectTypeOf(data.emanKills).toEqualTypeOf<number | null>();
  expect(data.isRiftTransferable).toBeDefined();
  expectTypeOf(data.isRiftTransferable).toEqualTypeOf<boolean>();
  expect(data.coinsGained).toBeDefined();
  expectTypeOf(data.coinsGained).toEqualTypeOf<number | null>();
  expect(data.ranchersSpeed).toBeDefined();
  expectTypeOf(data.ranchersSpeed).toEqualTypeOf<number | null>();
  expect(data.favoriteSentinalWarden).toBeDefined();
  expectTypeOf(data.favoriteSentinalWarden).toEqualTypeOf<number | null>();
  expect(data.potionLevel).toBeDefined();
  expectTypeOf(data.potionLevel).toEqualTypeOf<number | null>();
  expect(data.potion).toBeDefined();
  expectTypeOf(data.potion).toEqualTypeOf<number | null>();
  expect(data.potionEffects).toBeDefined();
  expectTypeOf(data.potionEffects).toEqualTypeOf<SkyBlockPotionEffect[] | null>();
  expect(data.potionType).toBeDefined();
  expectTypeOf(data.potionType).toEqualTypeOf<number | null>();
  expect(data.isSplashPotion).toBeDefined();
  expectTypeOf(data.isSplashPotion).toEqualTypeOf<boolean>();
  expect(data.potionName).toBeDefined();
  expectTypeOf(data.potionName).toEqualTypeOf<string | null>();
  expect(data.isDungeonPotion).toBeDefined();
  expectTypeOf(data.isDungeonPotion).toEqualTypeOf<boolean>();
  expect(data.gearScore).toBeDefined();
  expect(data.gearScore).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gearScore).toEqualTypeOf<number>();
  expect(data.rarity).toBeDefined();
  expectTypeOf(data.rarity).toEqualTypeOf<Rarity>();
  expect(data.raw).toBeDefined();
  expectTypeOf(data.raw).toEqualTypeOf<Record<string, any>>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => string>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.name);
  expectTypeOf(data.toString()).toEqualTypeOf<string>();
});
