import { parseRarity } from '../../Utils/SkyblockUtils.js';

class SkyblockItem {
  name: string;
  material: string;
  id: string;
  durability?: number;
  skin?: Record<string, any>;
  category?: string;
  tier?: string;
  npc_sell_price?: number;
  salvages?: Record<string, any>[];
  rarity_salvageable?: boolean;
  stats?: Record<string, any>;
  unstackable?: boolean;
  museum_data?: Record<string, any>;
  color?: string;
  soulbound?: string;
  has_uuid?: boolean | string;
  gemstone_slots?: Record<string, any>[];
  glowing?: boolean;
  can_auction?: boolean;
  can_trade?: boolean;
  requirements?: Record<string, any>[];
  can_place?: boolean;
  museum?: boolean;
  generator?: string;
  generator_tier?: number;
  furniture?: string;
  item_specific?: Record<string, any>;
  description?: string;
  upgrade_costs?: Array<Array<Record<string, any>>>;
  gear_score?: number;
  dungeon_item?: boolean;
  dungeon_item_conversion_cost?: Record<string, any>;
  catacombs_requirements?: Record<string, any>[];
  can_have_attributes?: boolean;
  salvageable_from_recipe?: boolean;
  can_recombobulate?: boolean;
  enchantments?: Record<string, any>;
  rift_transferrable?: boolean;
  origin?: string;
  double_tap_to_drop?: boolean;
  hide_from_viewrecipe_command?: boolean;
  sword_type?: string;
  ability_damage_scaling?: number;
  tiered_stats?: Record<string, any>;
  motes_sell_price?: number;
  crystal?: string;
  can_burn_in_furnace?: boolean;
  salvage?: Record<string, any>;
  serializable?: boolean;
  can_interact?: boolean;
  can_interact_right_click?: boolean;
  private_island?: string;
  can_have_power_scroll?: boolean;
  can_interact_entity?: boolean;
  MINING_FORTUNE?: number;
  recipes?: Record<string, any>[];
  cannot_reforge?: boolean;
  lose_motes_value_on_transfer?: boolean;
  prestige?: Record<string, any>;
  constructor(data: Record<string, any>) {
    this.name = data.name;
    this.material = data.material;
    this.id = data.id;
    this.durability = data.durability ?? 0;
    this.skin = data.skin ?? {};
    this.category = data.category ?? "";
    this.tier = data.tier ?? "";
    this.npc_sell_price = data.npc_sell_price ?? 0;
    this.salvages = data.salvages ?? [];
    this.rarity_salvageable = data.rarity_salvageable ?? false;
    this.stats = data.stats ?? {};
    this.unstackable = data.unstackable ?? false;
    this.museum_data = data.museum_data ?? {};
    this.color = data.color ?? "";
    this.soulbound = data.soulbound ?? "";
    this.has_uuid = data.has_uuid ?? false;
    this.gemstone_slots = data.gemstone_slots ?? [];
    this.glowing = data.glowing ?? false;
    this.can_auction = data.can_auction ?? false;
    this.can_trade = data.can_trade ?? false;
    this.requirements = data.requirements ?? [];
    this.can_place = data.can_place ?? false;
    this.museum = data.museum ?? false;
    this.generator = data.generator ?? "";
    this.generator_tier = data.generator_tier ?? 0;
    this.furniture = data.furniture ?? "";
    this.item_specific = data.item_specific ?? {};
    this.description = data.description ?? "";
    this.upgrade_costs = data.upgrade_costs ?? [];
    this.gear_score = data.gear_score ?? 0;
    this.dungeon_item = data.dungeon_item ?? false;
    this.dungeon_item_conversion_cost = data.dungeon_item_conversion_cost ?? {};
    this.catacombs_requirements = data.catacombs_requirements ?? [];
    this.can_have_attributes = data.can_have_attributes ?? false;
    this.salvageable_from_recipe = data.salvageable_from_recipe ?? false;
    this.can_recombobulate = data.can_recombobulate ?? false;
    this.enchantments = data.enchantments ?? {};
    this.rift_transferrable = data.rift_transferrable ?? false;
    this.origin = data.origin ?? "";
    this.double_tap_to_drop = data.double_tap_to_drop ?? false;
    this.hide_from_viewrecipe_command = data.hide_from_viewrecipe_command ?? false;
    this.sword_type = data.sword_type ?? "";
    this.ability_damage_scaling = data.ability_damage_scaling ?? 0;
    this.tiered_stats = data.tiered_stats ?? {};
    this.motes_sell_price = data.motes_sell_price ?? 0;
    this.crystal = data.crystal ?? "";
    this.can_burn_in_furnace = data.can_burn_in_furnace ?? false;
    this.salvage = data.salvage ?? {};
    this.serializable = data.serializable ?? false;
    this.can_interact = data.can_interact ?? false;
    this.can_interact_right_click = data.can_interact_right_click ?? false;
    this.private_island = data.private_island ?? "";
    this.can_have_power_scroll = data.can_have_power_scroll ?? false;
    this.can_interact_entity = data.can_interact_entity ?? false;
    this.MINING_FORTUNE = data.MINING_FORTUNE ?? 0;
    this.recipes = data.recipes ?? [];
    this.cannot_reforge = data.cannot_reforge ?? false;
    this.lose_motes_value_on_transfer = data.lose_motes_value_on_transfer ?? false;
    this.prestige = data.prestige ?? {};
  }

  toString(): string {
    return this.name;
  }
}

export default SkyblockItem;
