import SmashHeoresHero from './SmashHeoresHero.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { SmashHeoresHeros } from '../../../Types/Player.js';

test('SmashHeoresHero', () => {
  const data = new SmashHeoresHero({ stats: 'meow' }, 'BOTMUN');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SmashHeoresHero);
  expectTypeOf(data).toEqualTypeOf<SmashHeoresHero>();
  expect(data.name).toBeDefined();
  expectTypeOf(data.name).toEqualTypeOf<SmashHeoresHeros>();
  expect(data.level).toBeDefined();
  expect(data.level).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.level).toEqualTypeOf<number>();
  expect(data.xp).toBeDefined();
  expect(data.xp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.xp).toEqualTypeOf<number>();
  expect(data.prestige).toBeDefined();
  expect(data.prestige).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.prestige).toEqualTypeOf<number>();
  expect(data.playedGames).toBeDefined();
  expect(data.playedGames).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.playedGames).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.WLR).toBeDefined();
  expect(data.WLR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.WLR).toEqualTypeOf<number>();
});
