import SmashHeroesMode from './SmashHeroesMode.js';
import SmashHerosHero from './SmashHerosHero.js';
import { Divide } from '../../../Utils/index.js';
import type { SmashHerosHeroId } from '../../../Types/index.js';

class SmashHeroes {
  coins: number;
  level: number;
  winStreak: number;
  playedGames: number;
  kills: number;
  deaths: number;
  killDeathRatio: number;
  wins: number;
  losses: number;
  winLossRatio: number;
  smashed: number;
  '1v1v1v1': SmashHeroesMode;
  '2v2': SmashHeroesMode;
  '2v2v2': SmashHeroesMode;
  activeHero: SmashHerosHeroId | 'None';
  theBulk: SmashHerosHero;
  cakeMonster: SmashHerosHero;
  generalCluck: SmashHerosHero;
  botmun: SmashHerosHero;
  marauder: SmashHerosHero;
  pug: SmashHerosHero;
  tinman: SmashHerosHero;
  spoderman: SmashHerosHero;
  frosty: SmashHerosHero;
  sergeantShield: SmashHerosHero;
  skullfire: SmashHerosHero;
  goku: SmashHerosHero;
  sanic: SmashHerosHero;
  duskCrawler: SmashHerosHero;
  shoopDaWhoop: SmashHerosHero;
  greenHood: SmashHerosHero;
  constructor(data: Record<string, any>) {
    this.coins = data?.coins ?? data?.tokens ?? 0;
    this.level = data?.smash_level_total ?? 0;
    this.winStreak = data?.win_streak ?? 0;
    this.playedGames = data?.games ?? 0;
    this.kills = data?.kills ?? 0;
    this.deaths = data?.deaths ?? 0;
    this.killDeathRatio = Divide(this.kills, this.deaths);
    this.wins = data?.wins ?? 0;
    this.losses = data?.losses ?? 0;
    this.winLossRatio = Divide(this.wins, this.losses);
    this.smashed = data?.smashed ?? 0;
    this['1v1v1v1'] = new SmashHeroesMode(data, 'normal');
    this['2v2'] = new SmashHeroesMode(data, '2v2');
    this['2v2v2'] = new SmashHeroesMode(data, 'teams');
    this.activeHero = data?.active_class ?? 'None';
    this.theBulk = new SmashHerosHero(data, 'THE_BULK');
    this.cakeMonster = new SmashHerosHero(data, 'CAKE_MONSTER');
    this.generalCluck = new SmashHerosHero(data, 'GENERAL_CLUCK');
    this.botmun = new SmashHerosHero(data, 'BOTMUN');
    this.marauder = new SmashHerosHero(data, 'MARAUDER');
    this.pug = new SmashHerosHero(data, 'PUG');
    this.tinman = new SmashHerosHero(data, 'TINMAN');
    this.spoderman = new SmashHerosHero(data, 'SPODERMAN');
    this.frosty = new SmashHerosHero(data, 'FROSTY');
    this.sergeantShield = new SmashHerosHero(data, 'SERGEANT_SHIELD');
    this.skullfire = new SmashHerosHero(data, 'SKULLFIRE');
    this.goku = new SmashHerosHero(data, 'GOKU');
    this.sanic = new SmashHerosHero(data, 'SANIC');
    this.duskCrawler = new SmashHerosHero(data, 'DUSK_CRAWLER');
    this.shoopDaWhoop = new SmashHerosHero(data, 'SHOOP_DA_WHOOP');
    this.greenHood = new SmashHerosHero(data, 'GREEN_HOOD');
  }
}

export default SmashHeroes;
