/* eslint-disable */
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';
import prettier from 'eslint-config-prettier';
import sortImports from '@j4cobi/eslint-plugin-sort-imports';
import ts from 'typescript-eslint';
import stylistic from '@stylistic/eslint-plugin';
import { globalIgnores } from 'eslint/config';

export default [
  ...ts.configs.recommended,
  importPlugin.flatConfigs.recommended,
  importPlugin.flatConfigs.typescript,
  prettier,
  globalIgnores(['./dist/', './coverage/', './documentation/', 'vitest.setup.ts']),
  {
    files: ['**/*.ts', '**/*.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'module', globals: { ...globals.es2022, ...globals.node } },
    plugins: { '@stylistic': stylistic, 'sort-imports': sortImports },
    settings: { 'import/resolver': { typescript: true, node: true } },
    rules: {
      'sort-imports/sort-imports': [
        'error',
        { ignoreCase: false, ignoreMemberSort: false, memberSyntaxSortOrder: ['all', 'single', 'multiple', 'none'] }
      ],
      '@stylistic/max-len': [
        'warn',
        { code: 120, tabWidth: 2, ignoreComments: true, ignoreUrls: true, ignoreRegExpLiterals: true }
      ],
      '@stylistic/space-before-function-paren': ['error', { anonymous: 'never', named: 'never', catch: 'always' }],
      '@stylistic/function-call-argument-newline': ['error', 'consistent'],
      '@typescript-eslint/no-unused-vars': ['error', { args: 'none' }],
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@stylistic/array-bracket-newline': ['error', 'consistent'],
      'no-constant-condition': ['error', { checkLoops: false }],
      'import/enforce-node-protocol-usage': ['error', 'always'],
      'no-extend-native': ['warn', { exceptions: ['Object'] }],
      '@stylistic/nonblock-statement-body-position': 'error',
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/no-whitespace-before-property': 'error',
      '@stylistic/one-var-declaration-per-line': 'error',
      'prefer-const': ['warn', { destructuring: 'all' }],
      '@stylistic/dot-location': ['error', 'property'],
      '@stylistic/computed-property-spacing': 'error',
      '@stylistic/no-mixed-spaces-and-tabs': 'error',
      '@stylistic/type-named-tuple-spacing': 'error',
      'import/no-cycle': ['error', { maxDepth: 1 }],
      curly: ['warn', 'multi-line', 'consistent'],
      '@stylistic/no-multiple-empty-lines': 'error',
      '@stylistic/max-statements-per-line': 'error',
      '@stylistic/type-annotation-spacing': 'error',
      'import/no-anonymous-default-export': 'error',
      '@stylistic/member-delimiter-style': 'error',
      '@stylistic/template-curly-spacing': 'error',
      'import/no-extraneous-dependencies': 'error',
      '@typescript-eslint/no-explicit-any': 'off',
      '@stylistic/line-comment-position': 'error',
      '@stylistic/object-curly-newline': 'error',
      '@stylistic/array-bracket-spacing': 'warn',
      'import/no-useless-path-segments': 'error',
      '@stylistic/switch-colon-spacing': 'error',
      '@stylistic/type-generic-spacing': 'error',
      '@stylistic/rest-spread-spacing': 'error',
      '@stylistic/no-floating-decimal': 'error',
      '@stylistic/space-before-blocks': 'error',
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/no-confusing-arrow': 'error',
      'import/prefer-default-export': 'error',
      'logical-assignment-operators': 'warn',
      'no-template-curly-in-string': 'error',
      'quote-props': ['error', 'consistent'],
      '@stylistic/space-in-parens': 'error',
      '@stylistic/space-infix-ops': 'error',
      '@stylistic/no-multi-spaces': 'error',
      '@stylistic/keyword-spacing': 'error',
      '@stylistic/linebreak-style': 'error',
      'import/newline-after-import': 'warn',
      '@stylistic/spaced-comment': 'error',
      '@stylistic/no-extra-semi': 'error',
      '@stylistic/arrow-spacing': 'error',
      '@stylistic/block-spacing': 'error',
      '@stylistic/comma-spacing': 'error',
      '@stylistic/curly-newline': 'error',
      'import/no-dynamic-require': 'warn',
      '@stylistic/semi-spacing': 'error',
      '@stylistic/arrow-parens': 'error',
      'import/no-absolute-path': 'error',
      'import/no-named-default': 'error',
      '@stylistic/comma-dangle': 'error',
      '@stylistic/brace-style': 'error',
      '@stylistic/key-spacing': 'error',
      '@stylistic/comma-style': 'error',
      'no-useless-constructor': 'error',
      '@stylistic/semi-style': 'error',
      '@stylistic/new-parens': 'error',
      'no-useless-assignment': 'error',
      'no-inner-declarations': 'error',
      'import/no-self-import': 'error',
      'no-implicit-coercion': 'error',
      'import/no-deprecated': 'error',
      '@stylistic/eol-last': 'error',
      'import/no-namespace': 'error',
      'no-use-before-define': 'warn',
      'no-underscore-dangle': 'warn',
      'no-unneeded-ternary': 'error',
      'import/exports-last': 'error',
      '@stylistic/no-tabs': 'error',
      'default-param-last': 'error',
      'import/no-commonjs': 'error',
      'one-var': ['warn', 'never'],
      'no-inline-comments': 'warn',
      'no-empty-function': 'error',
      'no-useless-return': 'error',
      'no-useless-rename': 'warn',
      'no-useless-concat': 'warn',
      'no-throw-literal': 'error',
      'default-case-last': 'warn',
      '@stylistic/semi': 'error',
      'no-self-compare': 'error',
      'no-new-wrappers': 'error',
      '@stylistic/semi': 'error',
      'no-lone-blocks': 'error',
      'no-undef-init': 'error',
      'no-else-return': 'warn',
      'import/first': 'error',
      'require-await': 'warn',
      'default-case': 'error',
      'dot-notation': 'error',
      'no-sequences': 'warn',
      'no-multi-str': 'warn',
      'no-lonely-if': 'warn',
      'no-new-func': 'error',
      camelcase: 'warn',
      'no-var': 'warn',
      eqeqeq: 'warn'
    }
  }
];
