import SkyBlockMemberInventoriesBackpack from './SkyBlockMemberInventoriesBackpack.js';
import SkyBlockMemberInventoriesBackpacks from './SkyBlockMemberInventoriesBackpacks.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberInventoriesBackpacks', () => {
  const data = new SkyBlockMemberInventoriesBackpacks({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberInventoriesBackpacks);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberInventoriesBackpacks>();
  expect(data.backpack1).toBeDefined();
  expectTypeOf(data.backpack1).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack2).toBeDefined();
  expectTypeOf(data.backpack2).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack3).toBeDefined();
  expectTypeOf(data.backpack3).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack4).toBeDefined();
  expectTypeOf(data.backpack4).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack5).toBeDefined();
  expectTypeOf(data.backpack5).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack6).toBeDefined();
  expectTypeOf(data.backpack6).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack7).toBeDefined();
  expectTypeOf(data.backpack7).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack8).toBeDefined();
  expectTypeOf(data.backpack8).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack9).toBeDefined();
  expectTypeOf(data.backpack9).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack10).toBeDefined();
  expectTypeOf(data.backpack10).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack11).toBeDefined();
  expectTypeOf(data.backpack11).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack12).toBeDefined();
  expectTypeOf(data.backpack12).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack13).toBeDefined();
  expectTypeOf(data.backpack13).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack14).toBeDefined();
  expectTypeOf(data.backpack14).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack15).toBeDefined();
  expectTypeOf(data.backpack15).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack16).toBeDefined();
  expectTypeOf(data.backpack16).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack17).toBeDefined();
  expectTypeOf(data.backpack17).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
  expect(data.backpack18).toBeDefined();
  expectTypeOf(data.backpack18).toEqualTypeOf<SkyBlockMemberInventoriesBackpack | null>();
});
