import SkyBlockMemberBestiary from './SkyBlockMemberBestiary.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { BestiaryCategory } from '../../../../Types/SkyBlock.js';

test('SkyBlockMemberBestiary', () => {
  const data = new SkyBlockMemberBestiary({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberBestiary);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberBestiary>();
  expect(data.kills).toBeDefined();
  expectTypeOf(data.kills).toEqualTypeOf<Record<string, number>>();
  expect(data.deaths).toBeDefined();
  expectTypeOf(data.deaths).toEqualTypeOf<Record<string, number>>();
  expect(data.lastClaimedMilestone).toBeDefined();
  expect(data.lastClaimedMilestone).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.lastClaimedMilestone).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expect(data.level).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.level).toEqualTypeOf<number>();
  expect(data.maxLevel).toBeDefined();
  expect(data.maxLevel).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.maxLevel).toEqualTypeOf<number>();
  expect(data.familiesUnlocked).toBeDefined();
  expect(data.familiesUnlocked).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.familiesUnlocked).toEqualTypeOf<number>();
  expect(data.familiesCompleted).toBeDefined();
  expect(data.familiesCompleted).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.familiesCompleted).toEqualTypeOf<number>();
  expect(data.totalFamilies).toBeDefined();
  expect(data.totalFamilies).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.totalFamilies).toEqualTypeOf<number>();
  expect(data.familyTiers).toBeDefined();
  expect(data.familyTiers).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.familyTiers).toEqualTypeOf<number>();
  expect(data.maxFamilyTiers).toBeDefined();
  expect(data.maxFamilyTiers).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.maxFamilyTiers).toEqualTypeOf<number>();
  expect(data.categories).toBeDefined();
  expectTypeOf(data.categories).toEqualTypeOf<Record<string, BestiaryCategory>>();
});
