import SkyWarsMode from '../../SkyWarsMode/SkyWarsMode.js';
import SkyWarsTeamsKitsAttacking from './SkyWarsTeamsKitsAttacking.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsTeamsKitsAttacking', () => {
  const data = new SkyWarsTeamsKitsAttacking({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsTeamsKitsAttacking);
  expectTypeOf(data).toEqualTypeOf<SkyWarsTeamsKitsAttacking>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<SkyWarsMode>();
  expect(data.knight).toBeDefined();
  expect(data.knight).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.knight).toEqualTypeOf<SkyWarsMode>();
  expect(data.snowman).toBeDefined();
  expect(data.snowman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.snowman).toEqualTypeOf<SkyWarsMode>();
  expect(data.hunter).toBeDefined();
  expect(data.hunter).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.hunter).toEqualTypeOf<SkyWarsMode>();
  expect(data.enderman).toBeDefined();
  expect(data.enderman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.enderman).toEqualTypeOf<SkyWarsMode>();
  expect(data.energix).toBeDefined();
  expect(data.energix).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.energix).toEqualTypeOf<SkyWarsMode>();
  expect(data.slime).toBeDefined();
  expect(data.slime).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.slime).toEqualTypeOf<SkyWarsMode>();
  expect(data.salmon).toBeDefined();
  expect(data.salmon).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.salmon).toEqualTypeOf<SkyWarsMode>();
  expect(data.sloth).toBeDefined();
  expect(data.sloth).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.sloth).toEqualTypeOf<SkyWarsMode>();
  expect(data.pigRider).toBeDefined();
  expect(data.pigRider).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.pigRider).toEqualTypeOf<SkyWarsMode>();
  expect(data.grenade).toBeDefined();
  expect(data.grenade).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.grenade).toEqualTypeOf<SkyWarsMode>();
  expect(data.engineer).toBeDefined();
  expect(data.engineer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.engineer).toEqualTypeOf<SkyWarsMode>();
  expect(data.magician).toBeDefined();
  expect(data.magician).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.magician).toEqualTypeOf<SkyWarsMode>();
  expect(data.default).toBeDefined();
  expect(data.default).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.default).toEqualTypeOf<SkyWarsMode>();
  expect(data.jester).toBeDefined();
  expect(data.jester).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.jester).toEqualTypeOf<SkyWarsMode>();
  expect(data.fisherman).toBeDefined();
  expect(data.fisherman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.fisherman).toEqualTypeOf<SkyWarsMode>();
  expect(data.archeologist).toBeDefined();
  expect(data.archeologist).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.archeologist).toEqualTypeOf<SkyWarsMode>();
  expect(data.defaultTeams).toBeDefined();
  expect(data.defaultTeams).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.defaultTeams).toEqualTypeOf<SkyWarsMode>();
  expect(data.fallenAngel).toBeDefined();
  expect(data.fallenAngel).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.fallenAngel).toEqualTypeOf<SkyWarsMode>();
});
