import SkyWarsMode from '../../SkyWarsMode/SkyWarsMode.js';
import SkyWarsTeamsKitsSupporting from './SkyWarsTeamsKitsSupporting.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsTeamsKitsSupporting', () => {
  const data = new SkyWarsTeamsKitsSupporting({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsTeamsKitsSupporting);
  expectTypeOf(data).toEqualTypeOf<SkyWarsTeamsKitsSupporting>();
  expect(data.healer).toBeDefined();
  expect(data.healer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.healer).toEqualTypeOf<SkyWarsMode>();
  expect(data.ecologist).toBeDefined();
  expect(data.ecologist).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.ecologist).toEqualTypeOf<SkyWarsMode>();
  expect(data.armorsmith).toBeDefined();
  expect(data.armorsmith).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.armorsmith).toEqualTypeOf<SkyWarsMode>();
  expect(data.rookie).toBeDefined();
  expect(data.rookie).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.rookie).toEqualTypeOf<SkyWarsMode>();
  expect(data.enchanter).toBeDefined();
  expect(data.enchanter).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.enchanter).toEqualTypeOf<SkyWarsMode>();
  expect(data.pyro).toBeDefined();
  expect(data.pyro).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.pyro).toEqualTypeOf<SkyWarsMode>();
  expect(data.pharaoh).toBeDefined();
  expect(data.pharaoh).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.pharaoh).toEqualTypeOf<SkyWarsMode>();
  expect(data.warlock).toBeDefined();
  expect(data.warlock).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.warlock).toEqualTypeOf<SkyWarsMode>();
  expect(data.zookeeper).toBeDefined();
  expect(data.zookeeper).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.zookeeper).toEqualTypeOf<SkyWarsMode>();
  expect(data.princess).toBeDefined();
  expect(data.princess).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.princess).toEqualTypeOf<SkyWarsMode>();
  expect(data.troll).toBeDefined();
  expect(data.troll).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.troll).toEqualTypeOf<SkyWarsMode>();
});
