import BaseSkyWarsMode from '../../SkyWarsMode/BaseSkyWarsMode.js';
import SkyWarsTeamsKitsAttacking from './SkyWarsTeamsKitsAttacking.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsTeamsKitsAttacking', () => {
  const data = new SkyWarsTeamsKitsAttacking({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsTeamsKitsAttacking);
  expectTypeOf(data).toEqualTypeOf<SkyWarsTeamsKitsAttacking>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.knight).toBeDefined();
  expect(data.knight).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.knight).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.snowman).toBeDefined();
  expect(data.snowman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.snowman).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.hunter).toBeDefined();
  expect(data.hunter).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.hunter).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.enderman).toBeDefined();
  expect(data.enderman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.enderman).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.energix).toBeDefined();
  expect(data.energix).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.energix).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.slime).toBeDefined();
  expect(data.slime).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.slime).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.salmon).toBeDefined();
  expect(data.salmon).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.salmon).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.sloth).toBeDefined();
  expect(data.sloth).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.sloth).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.pigRider).toBeDefined();
  expect(data.pigRider).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.pigRider).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.grenade).toBeDefined();
  expect(data.grenade).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.grenade).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.engineer).toBeDefined();
  expect(data.engineer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.engineer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.magician).toBeDefined();
  expect(data.magician).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.magician).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.default).toBeDefined();
  expect(data.default).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.default).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.jester).toBeDefined();
  expect(data.jester).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.jester).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.fisherman).toBeDefined();
  expect(data.fisherman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.fisherman).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.archeologist).toBeDefined();
  expect(data.archeologist).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.archeologist).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.defaultTeams).toBeDefined();
  expect(data.defaultTeams).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.defaultTeams).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.fallenAngel).toBeDefined();
  expect(data.fallenAngel).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.fallenAngel).toEqualTypeOf<BaseSkyWarsMode>();
});
