import Duels from './Duels.js';
import DuelsBridge from './DuelsBridge.js';
import DuelsGamemode from './DuelsGamemode.js';
import DuelsMegaWalls from './DuelsMegaWalls.js';
import DuelsOP from './DuelsOP.js';
import DuelsSkyWars from './DuelsSkyWars.js';
import DuelsUHC from './DuelsUHC.js';
import { expect, expectTypeOf, test } from 'vitest';

test('Duels', () => {
  const data = new Duels({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Duels);
  expectTypeOf(data).toEqualTypeOf<Duels>();
  expect(data.tokens).toBeDefined();
  expect(data.tokens).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.tokens).toEqualTypeOf<number>();
  expect(data.title).toBeDefined();
  expectTypeOf(data.title).toEqualTypeOf<string | null>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.WLR).toBeDefined();
  expect(data.WLR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.WLR).toEqualTypeOf<number>();
  expect(data.playedGames).toBeDefined();
  expect(data.playedGames).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.playedGames).toEqualTypeOf<number>();
  expect(data.winStreak).toBeDefined();
  expect(data.winStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winStreak).toEqualTypeOf<number>();
  expect(data.bestWinStreak).toBeDefined();
  expect(data.bestWinStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bestWinStreak).toEqualTypeOf<number>();
  expect(data.ping).toBeDefined();
  expect(data.ping).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.ping).toEqualTypeOf<number>();
  expect(data.blocksPlaced).toBeDefined();
  expect(data.blocksPlaced).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.blocksPlaced).toEqualTypeOf<number>();
  expect(data.swings).toBeDefined();
  expect(data.swings).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.swings).toEqualTypeOf<number>();
  expect(data.hits).toBeDefined();
  expect(data.hits).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.hits).toEqualTypeOf<number>();
  expect(data.meleeAccuracy).toBeDefined();
  expect(data.meleeAccuracy).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.meleeAccuracy).toEqualTypeOf<number>();
  expect(data.bowShots).toBeDefined();
  expect(data.bowShots).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowShots).toEqualTypeOf<number>();
  expect(data.bowHits).toBeDefined();
  expect(data.bowHits).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowHits).toEqualTypeOf<number>();
  expect(data.bowAccuracy).toBeDefined();
  expect(data.bowAccuracy).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowAccuracy).toEqualTypeOf<number>();
  expect(data.healthRegenerated).toBeDefined();
  expect(data.healthRegenerated).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.healthRegenerated).toEqualTypeOf<number>();
  expect(data.goldenApplesEaten).toBeDefined();
  expect(data.goldenApplesEaten).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.goldenApplesEaten).toEqualTypeOf<number>();
  expect(data.uhc).toBeDefined();
  expect(data.uhc).toBeInstanceOf(DuelsUHC);
  expectTypeOf(data.uhc).toEqualTypeOf<DuelsUHC>();
  expect(data.skywars).toBeDefined();
  expect(data.skywars).toBeInstanceOf(DuelsSkyWars);
  expectTypeOf(data.skywars).toEqualTypeOf<DuelsSkyWars>();
  expect(data.megawalls).toBeDefined();
  expect(data.megawalls).toBeInstanceOf(DuelsMegaWalls);
  expectTypeOf(data.megawalls).toEqualTypeOf<DuelsMegaWalls>();
  expect(data.blitz).toBeDefined();
  expect(data.blitz).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.blitz).toEqualTypeOf<DuelsGamemode>();
  expect(data.op).toBeDefined();
  expect(data.op).toBeInstanceOf(DuelsOP);
  expectTypeOf(data.op).toEqualTypeOf<DuelsOP>();
  expect(data.classic).toBeDefined();
  expect(data.classic).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.classic).toEqualTypeOf<DuelsGamemode>();
  expect(data.bow).toBeDefined();
  expect(data.bow).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.bow).toEqualTypeOf<DuelsGamemode>();
  expect(data.noDebuff).toBeDefined();
  expect(data.noDebuff).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.noDebuff).toEqualTypeOf<DuelsGamemode>();
  expect(data.combo).toBeDefined();
  expect(data.combo).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.combo).toEqualTypeOf<DuelsGamemode>();
  expect(data.bowSpleef).toBeDefined();
  expect(data.bowSpleef).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.bowSpleef).toEqualTypeOf<DuelsGamemode>();
  expect(data.sumo).toBeDefined();
  expect(data.sumo).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.sumo).toEqualTypeOf<DuelsGamemode>();
  expect(data.bridge).toBeDefined();
  expect(data.bridge).toBeInstanceOf(DuelsBridge);
  expectTypeOf(data.bridge).toEqualTypeOf<DuelsBridge>();
  expect(data.parkour).toBeDefined();
  expect(data.parkour).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.parkour).toEqualTypeOf<DuelsGamemode>();
  expect(data.arena).toBeDefined();
  expect(data.arena).toBeInstanceOf(DuelsGamemode);
  expectTypeOf(data.arena).toEqualTypeOf<DuelsGamemode>();
});
