import SkyWarsMode from '../../../SkyWarsMode/SkyWarsMode.js';
import SkyWarsSoloKitsLabBasic from './SkyWarsSoloKitsLabBasic.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsSoloKitsLabBasic', () => {
  const data = new SkyWarsSoloKitsLabBasic({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsSoloKitsLabBasic);
  expectTypeOf(data).toEqualTypeOf<SkyWarsSoloKitsLabBasic>();
  expect(data.default).toBeDefined();
  expect(data.default).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.default).toEqualTypeOf<SkyWarsMode>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<SkyWarsMode>();
  expect(data.ecologist).toBeDefined();
  expect(data.ecologist).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.ecologist).toEqualTypeOf<SkyWarsMode>();
  expect(data.speleologist).toBeDefined();
  expect(data.speleologist).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.speleologist).toEqualTypeOf<SkyWarsMode>();
  expect(data.armorsmith).toBeDefined();
  expect(data.armorsmith).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.armorsmith).toEqualTypeOf<SkyWarsMode>();
  expect(data.energix).toBeDefined();
  expect(data.energix).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.energix).toEqualTypeOf<SkyWarsMode>();
  expect(data.baseballPlayer).toBeDefined();
  expect(data.baseballPlayer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.baseballPlayer).toEqualTypeOf<SkyWarsMode>();
  expect(data.disco).toBeDefined();
  expect(data.disco).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.disco).toEqualTypeOf<SkyWarsMode>();
  expect(data.pharaoh).toBeDefined();
  expect(data.pharaoh).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.pharaoh).toEqualTypeOf<SkyWarsMode>();
  expect(data.frog).toBeDefined();
  expect(data.frog).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.frog).toEqualTypeOf<SkyWarsMode>();
  expect(data.grenade).toBeDefined();
  expect(data.grenade).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.grenade).toEqualTypeOf<SkyWarsMode>();
  expect(data.fisherman).toBeDefined();
  expect(data.fisherman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.fisherman).toEqualTypeOf<SkyWarsMode>();
  expect(data.rookie).toBeDefined();
  expect(data.rookie).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.rookie).toEqualTypeOf<SkyWarsMode>();
  expect(data.troll).toBeDefined();
  expect(data.troll).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.troll).toEqualTypeOf<SkyWarsMode>();
  expect(data.snowman).toBeDefined();
  expect(data.snowman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.snowman).toEqualTypeOf<SkyWarsMode>();
  expect(data.princess).toBeDefined();
  expect(data.princess).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.princess).toEqualTypeOf<SkyWarsMode>();
  expect(data.batguy).toBeDefined();
  expect(data.batguy).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.batguy).toEqualTypeOf<SkyWarsMode>();
});
