import SkyBlockMemberPlayerStatsFishing from './SkyBlockMemberPlayerStatsFishing.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberPlayerStatsFishing', () => {
  const data = new SkyBlockMemberPlayerStatsFishing({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberPlayerStatsFishing);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberPlayerStatsFishing>();
  expect(data.seaCreaturesKills).toBeDefined();
  expect(data.seaCreaturesKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.seaCreaturesKills).toEqualTypeOf<number>();
  expect(data.normal).toBeDefined();
  expect(data.normal).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.normal).toEqualTypeOf<number>();
  expect(data.treasure).toBeDefined();
  expect(data.treasure).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.treasure).toEqualTypeOf<number>();
  expect(data.largeTreasure).toBeDefined();
  expect(data.largeTreasure).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.largeTreasure).toEqualTypeOf<number>();
  expect(data.trophyFish).toBeDefined();
  expect(data.trophyFish).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.trophyFish).toEqualTypeOf<number>();
  expect(data.total).toBeDefined();
  expect(data.total).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.total).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.total);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
