import SkyBlockMemberPlayerStats from './SkyBlockMemberPlayerStats.js';
import SkyBlockMemberPlayerStatsAuctions from './SkyBlockMemberPlayerStatsAuctions.js';
import SkyBlockMemberPlayerStatsCandy from './SkyBlockMemberPlayerStatsCandy.js';
import SkyBlockMemberPlayerStatsEndIsland from './SkyBlockMemberPlayerStatsEndIsland.js';
import SkyBlockMemberPlayerStatsFishing from './SkyBlockMemberPlayerStatsFishing.js';
import SkyBlockMemberPlayerStatsGifts from './SkyBlockMemberPlayerStatsGifts.js';
import SkyBlockMemberPlayerStatsMythos from './SkyBlockMemberPlayerStatsMythos.js';
import SkyBlockMemberPlayerStatsWinter from './SkyBlockMemberPlayerStatsWinter.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberPlayerStats', () => {
  const data = new SkyBlockMemberPlayerStats({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberPlayerStats);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberPlayerStats>();
  expect(data.fishing).toBeDefined();
  expect(data.fishing).toBeInstanceOf(SkyBlockMemberPlayerStatsFishing);
  expectTypeOf(data.fishing).toEqualTypeOf<SkyBlockMemberPlayerStatsFishing>();
  expect(data.glowingMushroomsBroken).toBeDefined();
  expect(data.glowingMushroomsBroken).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.glowingMushroomsBroken).toEqualTypeOf<number>();
  expect(data.highestDamage).toBeDefined();
  expect(data.highestDamage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestDamage).toEqualTypeOf<number>();
  expect(data.highestCriticalDamage).toBeDefined();
  expect(data.highestCriticalDamage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestCriticalDamage).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expectTypeOf(data.kills).toEqualTypeOf<Record<string, number>>();
  expect(data.deaths).toBeDefined();
  expectTypeOf(data.deaths).toEqualTypeOf<Record<string, number>>();
  expect(data.auctions).toBeDefined();
  expect(data.auctions).toBeInstanceOf(SkyBlockMemberPlayerStatsAuctions);
  expectTypeOf(data.auctions).toEqualTypeOf<SkyBlockMemberPlayerStatsAuctions>();
  expect(data.candy).toBeDefined();
  expect(data.candy).toBeInstanceOf(SkyBlockMemberPlayerStatsCandy);
  expectTypeOf(data.candy).toEqualTypeOf<SkyBlockMemberPlayerStatsCandy>();
  expect(data.gifts).toBeDefined();
  expect(data.gifts).toBeInstanceOf(SkyBlockMemberPlayerStatsGifts);
  expectTypeOf(data.gifts).toEqualTypeOf<SkyBlockMemberPlayerStatsGifts>();
  expect(data.mythos).toBeDefined();
  expect(data.mythos).toBeInstanceOf(SkyBlockMemberPlayerStatsMythos);
  expectTypeOf(data.mythos).toEqualTypeOf<SkyBlockMemberPlayerStatsMythos>();
  expect(data.winter).toBeDefined();
  expect(data.winter).toBeInstanceOf(SkyBlockMemberPlayerStatsWinter);
  expectTypeOf(data.winter).toEqualTypeOf<SkyBlockMemberPlayerStatsWinter>();
  expect(data.endIsland).toBeDefined();
  expect(data.endIsland).toBeInstanceOf(SkyBlockMemberPlayerStatsEndIsland);
  expectTypeOf(data.endIsland).toEqualTypeOf<SkyBlockMemberPlayerStatsEndIsland>();
  expect(data.races).toBeDefined();
  expectTypeOf(data.races).toEqualTypeOf<Record<string, number | Record<string, number>>>();
});
