import SkyBlockMemberPlayerStatsAuctionsStats from './SkyBlockMemberPlayerStatsAuctionsStats.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberPlayerStatsAuctionsStats', () => {
  const data = new SkyBlockMemberPlayerStatsAuctionsStats({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberPlayerStatsAuctionsStats);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberPlayerStatsAuctionsStats>();
  expect(data.common).toBeDefined();
  expect(data.common).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.common).toEqualTypeOf<number>();
  expect(data.uncommon).toBeDefined();
  expect(data.uncommon).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.uncommon).toEqualTypeOf<number>();
  expect(data.rare).toBeDefined();
  expect(data.rare).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.rare).toEqualTypeOf<number>();
  expect(data.epic).toBeDefined();
  expect(data.epic).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.epic).toEqualTypeOf<number>();
  expect(data.legendary).toBeDefined();
  expect(data.legendary).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.legendary).toEqualTypeOf<number>();
  expect(data.special).toBeDefined();
  expect(data.special).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.special).toEqualTypeOf<number>();
  expect(data.mythic).toBeDefined();
  expect(data.mythic).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mythic).toEqualTypeOf<number>();
  expect(data.total).toBeDefined();
  expect(data.total).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.total).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.total);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
