class SkyBlockMemberPlayerStatsRift {
  lifetimeMotesEarned: number;
  motesOrbPickup: number;
  passConsumed: number;
  visits: number;
  lagoonMushroomPoppedOut: number;
  lagoonRocksGameComplete: number;
  lagoonLilPadsSold: number;
  lagoonLeechSupremeKilled: number;
  woodsLarvaKilled: number;
  woodsOdonataBottled: number;
  woodsOdonataRepeatableCompleted: number;
  dreadfarmWiltedHarvested: number;
  dreadfarmCaducousHarvested: number;
  dreadfarmAgaricusHarvested: number;
  dreadfarmRiftwartsHarvested: number;
  dreadfarmChickenKilled: number;
  dreadfarmBeanBulbCollected: number;
  plazaPillarDeaths: number;
  plazaRedLightDeaths: number;
  plazaHayDeaths: number;
  plazaHorsezookaShot: number;
  westCakePartEaten: number;
  westHotDogsGiven: number;
  westVerminVacuumedTotal: number;
  westVerminVacuumedSilverfish: number;
  westVerminVacuumedSpider: number;
  westVerminVacuumedMosquito: number;
  poppedBalloons: number;
  livingMetalSpawneggUsed: number;
  livingMetalPieceMaxed: number;
  livingCaveSnakeCollected: number;
  colosseumGlobowlsAtTentacle: number;
  colosseumBlasterShots: number;
  colosseumBacteDefeated: number;
  castleSentToPrison: number;
  castleEffigyBroken: number;
  shenItemBought: number;
  constructor(data: Record<string, any>) {
    this.lifetimeMotesEarned = data?.lifetime_motes_earned ?? 0;
    this.motesOrbPickup = data?.motes_orb_pickup ?? 0;
    this.passConsumed = data?.pass_consumed ?? 0;
    this.visits = data?.visits ?? 0;
    this.lagoonMushroomPoppedOut = data?.lagoon_mushroom_popped_out ?? 0;
    this.lagoonRocksGameComplete = data?.lagoon_rocks_game_complete ?? 0;
    this.lagoonLilPadsSold = data?.lagoon_lil_pads_sold ?? 0;
    this.lagoonLeechSupremeKilled = data?.lagoon_leech_supreme_killed ?? 0;
    this.woodsLarvaKilled = data?.woods_larva_killed ?? 0;
    this.woodsOdonataBottled = data?.woods_odonata_bottled ?? 0;
    this.woodsOdonataRepeatableCompleted = data?.odonata_repeatable_completed ?? 0;
    this.dreadfarmWiltedHarvested = data?.dreadfarm_wilted_harvested ?? 0;
    this.dreadfarmCaducousHarvested = data?.dreadfarm_caducous_harvested ?? 0;
    this.dreadfarmAgaricusHarvested = data?.dreadfarm_agaricus_harvested ?? 0;
    this.dreadfarmRiftwartsHarvested = data?.dreadfarm_riftwarts_harvested ?? 0;
    this.dreadfarmChickenKilled = data?.dreadfarm_chicken_killed ?? 0;
    this.dreadfarmBeanBulbCollected = data?.dreadfarm_bean_bulb_collected ?? 0;
    this.plazaPillarDeaths = data?.plaza_pillar_deaths ?? 0;
    this.plazaRedLightDeaths = data?.plaza_red_light_deaths ?? 0;
    this.plazaHayDeaths = data?.plaza_hay_deaths ?? 0;
    this.plazaHorsezookaShot = data?.plaza_horsezooka_shot ?? 0;
    this.westCakePartEaten = data?.west_cake_part_eaten ?? 0;
    this.westHotDogsGiven = data?.west_hot_dogs_given ?? 0;
    this.westVerminVacuumedTotal = data?.west_vermin_vacuumed?.total ?? 0;
    this.westVerminVacuumedSilverfish = data?.west_vermin_vacuumed?.silverfish ?? 0;
    this.westVerminVacuumedSpider = data?.west_vermin_vacuumed?.spider ?? 0;
    this.westVerminVacuumedMosquito = data?.west_vermin_vacuumed?.mosquito ?? 0;
    this.poppedBalloons = data?.popped_balloons ?? 0;
    this.livingMetalSpawneggUsed = data?.living_metal_spawnegg_used ?? 0;
    this.livingMetalPieceMaxed = data?.living_metal_piece_maxed ?? 0;
    this.livingCaveSnakeCollected = data?.living_cave_snake_collected ?? 0;
    this.colosseumGlobowlsAtTentacle = data?.colosseum_globowls_at_tentacle ?? 0;
    this.colosseumBlasterShots = data?.colosseum_blaster_shots ?? 0;
    this.colosseumBacteDefeated = data?.colosseum_bacte_defeated ?? 0;
    this.castleSentToPrison = data?.castle_sent_to_prison ?? 0;
    this.castleEffigyBroken = data?.castle_effigy_broken ?? 0;
    this.shenItemBought = data?.shen_item_bought ?? 0;
  }
}

export default SkyBlockMemberPlayerStatsRift;
