import SkyBlockSkill from './SkyBlockSkill.js';
import SkyBlockSkills from './SkyBlockSkills.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockSkills', () => {
  const data = new SkyBlockSkills({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockSkills);
  expectTypeOf(data).toEqualTypeOf<SkyBlockSkills>();
  expect(data.lastUpdated).toBeDefined();
  expect(data.lastUpdated).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.lastUpdated).toEqualTypeOf<number>();
  expect(data.lastUpdatedAt).toBeDefined();
  expect(data.lastUpdatedAt).toBeInstanceOf(Date);
  expectTypeOf(data.lastUpdatedAt).toEqualTypeOf<Date>();
  expect(data.version).toBeDefined();
  expectTypeOf(data.version).toEqualTypeOf<string>();
  expect(data.farming).toBeDefined();
  expect(data.farming).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.farming).toEqualTypeOf<SkyBlockSkill>();
  expect(data.mining).toBeDefined();
  expect(data.mining).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.mining).toEqualTypeOf<SkyBlockSkill>();
  expect(data.combat).toBeDefined();
  expect(data.combat).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.combat).toEqualTypeOf<SkyBlockSkill>();
  expect(data.foraging).toBeDefined();
  expect(data.foraging).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.foraging).toEqualTypeOf<SkyBlockSkill>();
  expect(data.fishing).toBeDefined();
  expect(data.fishing).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.fishing).toEqualTypeOf<SkyBlockSkill>();
  expect(data.enchanting).toBeDefined();
  expect(data.enchanting).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.enchanting).toEqualTypeOf<SkyBlockSkill>();
  expect(data.alchemy).toBeDefined();
  expect(data.alchemy).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.alchemy).toEqualTypeOf<SkyBlockSkill>();
  expect(data.carpentry).toBeDefined();
  expect(data.carpentry).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.carpentry).toEqualTypeOf<SkyBlockSkill>();
  expect(data.runecrafting).toBeDefined();
  expect(data.runecrafting).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.runecrafting).toEqualTypeOf<SkyBlockSkill>();
  expect(data.social).toBeDefined();
  expect(data.social).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.social).toEqualTypeOf<SkyBlockSkill>();
  expect(data.taming).toBeDefined();
  expect(data.taming).toBeInstanceOf(SkyBlockSkill);
  expectTypeOf(data.taming).toEqualTypeOf<SkyBlockSkill>();
});
