import SkyBlockMemberChocolateFactoryEmployees from './SkyBlockMemberChocolateFactoryEmployees.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberChocolateFactoryEmployees', () => {
  const data = new SkyBlockMemberChocolateFactoryEmployees({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberChocolateFactoryEmployees);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberChocolateFactoryEmployees>();
  expect(data.bro).toBeDefined();
  expect(data.bro).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bro).toEqualTypeOf<number>();
  expect(data.cousin).toBeDefined();
  expect(data.cousin).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.cousin).toEqualTypeOf<number>();
  expect(data.sis).toBeDefined();
  expect(data.sis).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sis).toEqualTypeOf<number>();
  expect(data.father).toBeDefined();
  expect(data.father).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.father).toEqualTypeOf<number>();
  expect(data.grandma).toBeDefined();
  expect(data.grandma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.grandma).toEqualTypeOf<number>();
  expect(data.dog).toBeDefined();
  expect(data.dog).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.dog).toEqualTypeOf<number>();
  expect(data.uncle).toBeDefined();
  expect(data.uncle).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.uncle).toEqualTypeOf<number>();
});
