import SkyBlockMemberChocolateFactory from './SkyBlockMemberChocolateFactory.js';
import SkyBlockMemberChocolateFactoryEggs from './SkyBlockMemberChocolateFactoryEggs.js';
import SkyBlockMemberChocolateFactoryEmployees from './SkyBlockMemberChocolateFactoryEmployees.js';
import SkyBlockMemberChocolateFactoryHitmen from './SkyBlockMemberChocolateFactoryHitmen.js';
import SkyBlockMemberChocolateFactoryTimeTower from './SkyBlockMemberChocolateFactoryTimeTower.js';
import SkyBlockMemberChocolateFactoryUpgrades from './SkyBlockMemberChocolateFactoryUpgrades.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { SkyBlockArea } from '../../../../Types/SkyBlock.js';

test('SkyBlockMemberChocolateFactory', () => {
  const data = new SkyBlockMemberChocolateFactory({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberChocolateFactory);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberChocolateFactory>();
  expect(data.employees).toBeDefined();
  expectTypeOf(data.employees).toEqualTypeOf<SkyBlockMemberChocolateFactoryEmployees>();
  expect(data.timeTower).toBeDefined();
  expectTypeOf(data.timeTower).toEqualTypeOf<SkyBlockMemberChocolateFactoryTimeTower>();
  expect(data.upgrades).toBeDefined();
  expectTypeOf(data.upgrades).toEqualTypeOf<SkyBlockMemberChocolateFactoryUpgrades>();
  expect(data.hitman).toBeDefined();
  expectTypeOf(data.hitman).toEqualTypeOf<SkyBlockMemberChocolateFactoryHitmen>();
  expect(data.currentChocolate).toBeDefined();
  expectTypeOf(data.currentChocolate).toEqualTypeOf<number>();
  expect(data.chocolateSincePrestige).toBeDefined();
  expectTypeOf(data.chocolateSincePrestige).toEqualTypeOf<number>();
  expect(data.totalChocolate).toBeDefined();
  expectTypeOf(data.totalChocolate).toEqualTypeOf<number>();
  expect(data.barnCapacity).toBeDefined();
  expectTypeOf(data.barnCapacity).toEqualTypeOf<number>();
  expect(data.prestige).toBeDefined();
  expectTypeOf(data.prestige).toEqualTypeOf<number>();
  expect(data.lastViewedChocolateFactory).toBeDefined();
  expectTypeOf(data.lastViewedChocolateFactory).toEqualTypeOf<number>();
  expect(data.lastViewedChocolateFactoryDate).toBeDefined();
  expectTypeOf(data.lastViewedChocolateFactoryDate).toEqualTypeOf<Date>();
  expect(data.supremeChocolateBars).toBeDefined();
  expectTypeOf(data.supremeChocolateBars).toEqualTypeOf<number>();
  expect(data.eggs).toBeDefined();
  expectTypeOf(data.eggs).toEqualTypeOf<SkyBlockMemberChocolateFactoryEggs>();
  expect(data.foundRabbits).toBeDefined();
  expectTypeOf(data.foundRabbits).toEqualTypeOf<Record<string, number>>();
  expect(data.foundEggLocations).toBeDefined();
  expectTypeOf(data.foundEggLocations).toEqualTypeOf<Record<keyof SkyBlockArea, string[]>>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toEqual(data.currentChocolate);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
