import SkyBlockMemberChocolateFactoryTimeTower from './SkyBlockMemberChocolateFactoryTimeTower.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberChocolateFactoryTimeTower', () => {
  const data = new SkyBlockMemberChocolateFactoryTimeTower({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberChocolateFactoryTimeTower);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberChocolateFactoryTimeTower>();
  expect(data.charges).toBeDefined();
  expect(data.charges).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.charges).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expect(data.level).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.level).toEqualTypeOf<number>();
  expect(data.activationTime).toBeDefined();
  expect(data.activationTime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.activationTime).toEqualTypeOf<number>();
  expect(data.activationTimeDate).toBeDefined();
  expect(data.activationTimeDate).toBeInstanceOf(Date);
  expectTypeOf(data.activationTimeDate).toEqualTypeOf<Date>();
  expect(data.lastChargeTime).toBeDefined();
  expect(data.lastChargeTime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.lastChargeTime).toEqualTypeOf<number>();
  expect(data.lastChargeTimeDate).toBeDefined();
  expect(data.lastChargeTimeDate).toBeInstanceOf(Date);
  expectTypeOf(data.lastChargeTimeDate).toEqualTypeOf<Date>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.level);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
