import SkyBlockMemberChocolateFactoryHitmen from './SkyBlockMemberChocolateFactoryHitmen.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberChocolateFactoryHitmen', () => {
  const data = new SkyBlockMemberChocolateFactoryHitmen({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberChocolateFactoryHitmen);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberChocolateFactoryHitmen>();
  expect(data.rabbitHitmenSlots).toBeDefined();
  expect(data.rabbitHitmenSlots).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.rabbitHitmenSlots).toEqualTypeOf<number>();
  expect(data.missedUncollectedEggs).toBeDefined();
  expect(data.missedUncollectedEggs).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.missedUncollectedEggs).toEqualTypeOf<number>();
  expect(data.eggSlotCooldownMark).toBeDefined();
  expect(data.eggSlotCooldownMark).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.eggSlotCooldownMark).toEqualTypeOf<number>();
  expect(data.eggSlotCooldownMarkDate).toBeDefined();
  expect(data.eggSlotCooldownMarkDate).toBeInstanceOf(Date);
  expectTypeOf(data.eggSlotCooldownMarkDate).toEqualTypeOf<Date>();
  expect(data.eggSlotCooldownExpire).toBeDefined();
  expect(data.eggSlotCooldownExpire).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.eggSlotCooldownExpire).toEqualTypeOf<number>();
  expect(data.eggSlotCooldownExpireDate).toBeDefined();
  expect(data.eggSlotCooldownExpireDate).toBeInstanceOf(Date);
  expectTypeOf(data.eggSlotCooldownExpireDate).toEqualTypeOf<Date>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.rabbitHitmenSlots);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
