class BedWarsSlumberQuestNPCSNumber {
  arcadePlayer: number;
  billStarr: number;
  blacksmith: number;
  blacksmithApprentice: number;
  bucky: number;
  combatArtistSally: number;
  donEspresso: number;
  electricianRussel: number;
  executives: number;
  gamblerGeorge: number;
  generalDaku: number;
  gizzyMoonpowder: number;
  hammer: number;
  hammerPartTwo: number;
  hermes: number;
  inspector: number;
  jeremyJagger: number;
  jetsMcturbo: number;
  jimmyBimmy: number;
  johnIndigosHammer: number;
  johnPireso: number;
  kingFlut: number;
  ladySaichi: number;
  laundry: number;
  laundryGal: number;
  lesterBrody: number;
  masterMeyer: number;
  meetTheSandman: number;
  oasis: number;
  peter: number;
  quizShowHost: number;
  receptionStart: number;
  skyblockPlayer: number;
  spaceman: number;
  theRatman: number;
  wally: number;
  phaseFourAscensionQ1: number;
  phaseFourAscensionQ2: number;
  phaseFourAscensionQ3: number;
  phaseFourAscensionQ4: number;
  phaseFourAscensionQ5: number;
  phaseFourAscensionWalletQ: number;
  phaseThreeAsc: number;
  phaseTwoAsc: number;
  staffWalletUpgrade: number;
  constructor(data: Record<string, any>) {
    this.arcadePlayer = data?.npc_arcade_player || 0;
    this.billStarr = data?.npc_bill_starr || 0;
    this.blacksmith = data?.npc_blacksmith || 0;
    this.blacksmithApprentice = data?.npc_blacksmith_apprentice || 0;
    this.bucky = data?.npc_bucky || 0;
    this.combatArtistSally = data?.npc_combat_artist_sally || 0;
    this.donEspresso = data?.npc_don_espresso || 0;
    this.electricianRussel = data?.npc_electrician_russel || 0;
    this.executives = data?.npc_executives || 0;
    this.gamblerGeorge = data?.npc_gambler_george || 0;
    this.generalDaku = data?.npc_general_daku || 0;
    this.gizzyMoonpowder = data?.npc_gizzy_moonpowder || 0;
    this.hammer = data?.npc_hammer || 0;
    this.hammerPartTwo = data?.npc_hammer_part_two || 0;
    this.hermes = data?.npc_hermes || 0;
    this.inspector = data?.npc_inspector || 0;
    this.jeremyJagger = data?.npc_jeremy_jagger || 0;
    this.jetsMcturbo = data?.npc_jets_mcturbo || 0;
    this.jimmyBimmy = data?.npc_jimmy_bimmy || 0;
    this.johnIndigosHammer = data?.npc_john_indigos_hammer || 0;
    this.johnPireso = data?.npc_john_pireso || 0;
    this.kingFlut = data?.npc_king_flut || 0;
    this.ladySaichi = data?.npc_lady_saichi || 0;
    this.laundry = data?.npc_laundry || 0;
    this.laundryGal = data?.npc_laundry_gal || 0;
    this.lesterBrody = data?.npc_lester_brody || 0;
    this.masterMeyer = data?.npc_master_meyer || 0;
    this.meetTheSandman = data?.npc_meet_the_sandman || 0;
    this.oasis = data?.npc_oasis || 0;
    this.peter = data?.npc_peter || 0;
    this.quizShowHost = data?.npc_quiz_show_host || 0;
    this.receptionStart = data?.npc_reception_start || 0;
    this.skyblockPlayer = data?.npc_skyblock_player || 0;
    this.spaceman = data?.npc_spaceman || 0;
    this.theRatman = data?.npc_the_ratman || 0;
    this.wally = data?.npc_wally || 0;
    this.phaseFourAscensionQ1 = data?.phase_four_ascension_q1 || 0;
    this.phaseFourAscensionQ2 = data?.phase_four_ascension_q2 || 0;
    this.phaseFourAscensionQ3 = data?.phase_four_ascension_q3 || 0;
    this.phaseFourAscensionQ4 = data?.phase_four_ascension_q4 || 0;
    this.phaseFourAscensionQ5 = data?.phase_four_ascension_q5 || 0;
    this.phaseFourAscensionWalletQ = data?.phase_four_ascension_wallet_q || 0;
    this.phaseThreeAsc = data?.phase_three_asc || 0;
    this.phaseTwoAsc = data?.phase_two_asc || 0;
    this.staffWalletUpgrade = data?.staff_wallet_upgrade || 0;
  }
}

export default BedWarsSlumberQuestNPCSNumber;
