import BedWarsSlumberQuest from './BedWarsSlumberQuest.js';
import BedWarsSlumberQuestGamblerGeorge from './BedWarsSlumberQuestGamblerGeorge.js';
import BedWarsSlumberQuestItem from './BedWarsSlumberQuestItem.js';
import BedWarsSlumberQuestNPC from './BedWarsSlumberQuestNPC.js';
import BedWarsSlumberQuestNPCSBoolean from './BedWarsSlumberQuestNPCSBoolean.js';
import BedWarsSlumberQuestNPCSNumber from './BedWarsSlumberQuestNPCSNumber.js';
import BedWarsSlumberQuestObjective from './BedWarsSlumberQuestObjective.js';
import { expect, expectTypeOf, test } from 'vitest';

test('BedWarsSlumberQuest', () => {
  const data = new BedWarsSlumberQuest({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsSlumberQuest);
  expectTypeOf(data).toEqualTypeOf<BedWarsSlumberQuest>();
  expect(data.completed).toBeDefined();
  expect(data.completed).toBeInstanceOf(BedWarsSlumberQuestNPCSBoolean);
  expectTypeOf(data.completed).toEqualTypeOf<BedWarsSlumberQuestNPCSBoolean>();
  expect(data.gamblerGeorge).toBeDefined();
  expect(data.gamblerGeorge).toBeInstanceOf(BedWarsSlumberQuestGamblerGeorge);
  expectTypeOf(data.gamblerGeorge).toEqualTypeOf<BedWarsSlumberQuestGamblerGeorge>();
  expect(data.item).toBeDefined();
  expect(data.item).toBeInstanceOf(BedWarsSlumberQuestItem);
  expectTypeOf(data.item).toEqualTypeOf<BedWarsSlumberQuestItem>();
  expect(data.lastCompleted).toBeDefined();
  expect(data.lastCompleted).toBeInstanceOf(BedWarsSlumberQuestNPCSNumber);
  expectTypeOf(data.lastCompleted).toEqualTypeOf<BedWarsSlumberQuestNPCSNumber>();
  expect(data.lastStarted).toBeDefined();
  expect(data.lastStarted).toBeInstanceOf(BedWarsSlumberQuestNPCSNumber);
  expectTypeOf(data.lastStarted).toEqualTypeOf<BedWarsSlumberQuestNPCSNumber>();
  expect(data.npc).toBeDefined();
  expect(data.npc).toBeInstanceOf(BedWarsSlumberQuestNPC);
  expectTypeOf(data.npc).toEqualTypeOf<BedWarsSlumberQuestNPC>();
  expect(data.objective).toBeDefined();
  expect(data.objective).toBeInstanceOf(BedWarsSlumberQuestObjective);
  expectTypeOf(data.objective).toEqualTypeOf<BedWarsSlumberQuestObjective>();
  expect(data.started).toBeDefined();
  expect(data.started).toBeInstanceOf(BedWarsSlumberQuestNPCSBoolean);
  expectTypeOf(data.started).toEqualTypeOf<BedWarsSlumberQuestNPCSBoolean>();
});
