class BedWarsSlumberQuestItem {
  airFreshener: number;
  amulet: number;
  bedSheets: number;
  blitzStar: number;
  blockOfMegaWallsObsidian: number;
  boots: number;
  cable: number;
  cleanedUpMurderKnife: number;
  comfyPillow: number;
  diamondFragment: number;
  discardedKartWheel: number;
  dwarvenMithril: number;
  emeraldShard: number;
  enchantedHammer: number;
  enderDust: number;
  fadedBlitzStar: number;
  gloves: number;
  glowingSandPaper: number;
  goldBar: number;
  goldenTicket: number;
  imperialLeather: number;
  indigosMap: number;
  ironNugget: number;
  limboDust: number;
  missingAmulet: number;
  moonStoneNugget: number;
  murderWeapon: number;
  netherStar: number;
  oasisWater: number;
  perfume: number;
  proofOfSuccess: number;
  ratmanMask: number;
  silverBladeReplay: number;
  silverCoins: number;
  soul: number;
  sparkPlug: number;
  timewornMysteryBox: number;
  tokenOfFerocity: number;
  trustyRope: number;
  unusedBombMaterials: number;
  victimPhoto: number;
  weaponMold: number;
  constructor(data: Record<string, any>) {
    this.airFreshener = data?.slumber_item_air_freshener || 0;
    this.amulet = data?.slumber_item_amulet || 0;
    this.bedSheets = data?.slumber_item_bed_sheets || 0;
    this.blitzStar = data?.slumber_item_blitz_star || 0;
    this.blockOfMegaWallsObsidian = data?.slumber_item_block_of_mega_walls_obsidian || 0;
    this.boots = data?.slumber_item_boots || 0;
    this.cable = data?.slumber_item_cable || 0;
    this.cleanedUpMurderKnife = data?.slumber_item_cleaned_up_murder_knife || 0;
    this.comfyPillow = data?.slumber_item_comfy_pillow || 0;
    this.diamondFragment = data?.slumber_item_diamond_fragment || 0;
    this.discardedKartWheel = data?.slumber_item_discarded_kart_wheel || 0;
    this.dwarvenMithril = data?.slumber_item_dwarven_mithril || 0;
    this.emeraldShard = data?.slumber_item_emerald_shard || 0;
    this.enchantedHammer = data?.slumber_item_enchanted_hammer || 0;
    this.enderDust = data?.slumber_item_ender_dust || 0;
    this.fadedBlitzStar = data?.slumber_item_faded_blitz_star || 0;
    this.gloves = data?.slumber_item_gloves || 0;
    this.glowingSandPaper = data?.slumber_item_glowing_sand_paper || 0;
    this.goldBar = data?.slumber_item_gold_bar || 0;
    this.goldenTicket = data?.slumber_item_golden_ticket || 0;
    this.imperialLeather = data?.slumber_item_imperial_leather || 0;
    this.indigosMap = data?.slumber_item_indigos_map || 0;
    this.ironNugget = data?.slumber_item_iron_nugget || 0;
    this.limboDust = data?.slumber_item_limbo_dust || 0;
    this.missingAmulet = data?.slumber_item_missing_amulet || 0;
    this.moonStoneNugget = data?.slumber_item_moon_stone_nugget || 0;
    this.murderWeapon = data?.slumber_item_murder_weapon || 0;
    this.netherStar = data?.slumber_item_nether_star || 0;
    this.oasisWater = data?.slumber_item_oasis_water || 0;
    this.perfume = data?.slumber_item_perfume || 0;
    this.proofOfSuccess = data?.slumber_item_proof_of_success || 0;
    this.ratmanMask = data?.slumber_item_ratman_mask || 0;
    this.silverBladeReplay = data?.slumber_item_silver_blade_replay || 0;
    this.silverCoins = data?.slumber_item_silver_coins || 0;
    this.soul = data?.slumber_item_soul || 0;
    this.sparkPlug = data?.slumber_item_spark_plug || 0;
    this.timewornMysteryBox = data?.slumber_item_timeworn_mystery_box || 0;
    this.tokenOfFerocity = data?.slumber_item_token_of_ferocity || 0;
    this.trustyRope = data?.slumber_item_trusty_rope || 0;
    this.unusedBombMaterials = data?.slumber_item_unused_bomb_materials || 0;
    this.victimPhoto = data?.slumber_item_victim_photo || 0;
    this.weaponMold = data?.slumber_item_weapon_mold || 0;
  }
}

export default BedWarsSlumberQuestItem;
