import ZombiesMap from './ZombiesMap.js';

class Zombies {
  basicZombieKills: number;
  basketballZombieKills: number;
  bestRound: number;
  blazeZombieKills: number;
  blobZombieKills: number;
  bombZombieKills: number;
  broodmotherZombieKills: number;
  bulletsHit: number;
  bulletsShot: number;
  caveSpiderZombieKills: number;
  chargedCreeperZombieKills: number;
  chglugluZombieKills: number;
  clownZombieKills: number;
  corruptedPigmanZombieKills: number;
  creeperZombieKills: number;
  daBombZombieKills: number;
  deaths: number;
  doorsOpened: number;
  drownedZombieKills: number;
  empoweredZombieKills: number;
  enderZombieKills: number;
  endermiteZombieKills: number;
  familyDaughterZombieKills: number;
  familyFatherZombieKills: number;
  familyMotherZombieKills: number;
  familyTwinBlueZombieKills: number;
  familyTwinRedZombieKills: number;
  fastestTime10: number;
  fastestTime20: number;
  fastestTime30: number;
  fireLordZombieKills: number;
  fireZombieKills: number;
  frostZombieZombieKills: number;
  ghastZombieKills: number;
  giantRainbowZombieKills: number;
  giantZombieKills: number;
  guardZombieZombieKills: number;
  guardianZombieKills: number;
  headlessPigmanZombieKills: number;
  headshots: number;
  herobrineMinionZombieKills: number;
  herobrineZombieKills: number;
  humanZombieKills: number;
  infernoPigmanZombieKills: number;
  infernoZombieKills: number;
  invisibleZombieKills: number;
  ironGolemZombieKills: number;
  kingDrownedZombieKills: number;
  kingSlimeZombieKills: number;
  knightDrownedZombieKills: number;
  magmaCubeZombieKills: number;
  magmaZombieKills: number;
  mcdonaldsPigmanZombieKills: number;
  mcdonaldsZombieZombieKills: number;
  megaBlobZombieKills: number;
  megaMagmaZombieKills: number;
  moltenZombieKills: number;
  murderPigmanZombieKills: number;
  murderZombieZombieKills: number;
  nurseZombieZombieKills: number;
  pigZombieZombieKills: number;
  playersRevived: number;
  prisonerPigman2CellZombieKills: number;
  prisonerPigman2ZombieKills: number;
  prisonerPigmanCellZombieKills: number;
  prisonerPigmanZombieKills: number;
  prisonerSkeletonZombieKills: number;
  prisonerZombieAngry2ZombieKills: number;
  prisonerZombieAngry3ZombieKills: number;
  prisonerZombieAngryZombieKills: number;
  prisonerZombieCellZombieKills: number;
  prisonerZombieKills: number;
  rainbowZombieKills: number;
  scubaZombieKills: number;
  sentinelZombieKills: number;
  shadySkeletonZombieKills: number;
  silverfishZombieKills: number;
  skelefishZombieKills: number;
  skeletonZombieKills: number;
  slimeZombieKills: number;
  slimeZombieZombieKills: number;
  spaceBlasterZombieKills: number;
  spaceGruntZombieKills: number;
  tankDrownedZombieKills: number;
  tankZombieZombieKills: number;
  theOldOneZombieKills: number;
  theWardenZombieKills: number;
  timesKnockedDown: number;
  tntBabyZombieKills: number;
  tntZombieKills: number;
  totalRoundsSurvived: number;
  werewolfZombieKills: number;
  windowsRepaired: number;
  wins: number;
  witchZombieKills: number;
  witherSkeletonZombieKills: number;
  witherZombieKills: number;
  witherZombieZombieKills: number;
  wolfDrownedZombieKills: number;
  wolfPetZombieKills: number;
  wolfZombieKills: number;
  worldEnderZombieKills: number;
  wormSmallZombieKills: number;
  wormZombieKills: number;
  zombieKills: number;
  hideTutorials: boolean;
  alienArcadium: ZombiesMap;
  badBlood: ZombiesMap;
  deadEnd: ZombiesMap;
  prison: ZombiesMap;
  constructor(data: Record<string, any>) {
    this.basicZombieKills = data?.basic_zombie_kills_zombies || 0;
    this.basketballZombieKills = data?.basketball_zombie_zombie_kills_zombies || 0;
    this.bestRound = data?.best_round_zombies || 0;
    this.blazeZombieKills = data?.blaze_zombie_kills_zombies || 0;
    this.blobZombieKills = data?.blob_zombie_kills_zombies || 0;
    this.bombZombieKills = data?.bomb_zombie_kills_zombies || 0;
    this.broodmotherZombieKills = data?.broodmother_zombie_kills_zombies || 0;
    this.bulletsHit = data?.bullets_hit_zombies || 0;
    this.bulletsShot = data?.bullets_shot_zombies || 0;
    this.caveSpiderZombieKills = data?.cave_spider_zombie_kills_zombies || 0;
    this.chargedCreeperZombieKills = data?.charged_creeper_zombie_kills_zombies || 0;
    this.chglugluZombieKills = data?.chgluglu_zombie_kills_zombies || 0;
    this.clownZombieKills = data?.clown_zombie_kills_zombies || 0;
    this.corruptedPigmanZombieKills = data?.corrupted_pigman_zombie_kills_zombies || 0;
    this.creeperZombieKills = data?.creeper_zombie_kills_zombies || 0;
    this.daBombZombieKills = data?.da_bomb_zombie_kills_zombies || 0;
    this.deaths = data?.deaths_zombies || 0;
    this.doorsOpened = data?.doors_opened_zombies || 0;
    this.drownedZombieKills = data?.drowned_zombie_kills_zombies || 0;
    this.empoweredZombieKills = data?.empowered_zombie_kills_zombies || 0;
    this.enderZombieKills = data?.ender_zombie_kills_zombies || 0;
    this.endermiteZombieKills = data?.endermite_zombie_kills_zombies || 0;
    this.familyDaughterZombieKills = data?.family_daughter_zombie_kills_zombies || 0;
    this.familyFatherZombieKills = data?.family_father_zombie_kills_zombies || 0;
    this.familyMotherZombieKills = data?.family_mother_zombie_kills_zombies || 0;
    this.familyTwinBlueZombieKills = data?.family_twin_blue_zombie_kills_zombies || 0;
    this.familyTwinRedZombieKills = data?.family_twin_red_zombie_kills_zombies || 0;
    this.fastestTime10 = data?.fastest_time_10_zombies || 0;
    this.fastestTime20 = data?.fastest_time_20_zombies || 0;
    this.fastestTime30 = data?.fastest_time_30_zombies || 0;
    this.fireLordZombieKills = data?.fire_lord_zombie_kills_zombies || 0;
    this.fireZombieKills = data?.fire_zombie_kills_zombies || 0;
    this.frostZombieZombieKills = data?.frost_zombie_zombie_kills_zombies || 0;
    this.ghastZombieKills = data?.ghast_zombie_kills_zombies || 0;
    this.giantRainbowZombieKills = data?.giant_rainbow_zombie_kills_zombies || 0;
    this.giantZombieKills = data?.giant_zombie_kills_zombies || 0;
    this.guardZombieZombieKills = data?.guard_zombie_zombie_kills_zombies || 0;
    this.guardianZombieKills = data?.guardian_zombie_kills_zombies || 0;
    this.headlessPigmanZombieKills = data?.headless_pigman_zombie_kills_zombies || 0;
    this.headshots = data?.headshots_zombies || 0;
    this.herobrineMinionZombieKills = data?.herobrine_minion_zombie_kills_zombies || 0;
    this.herobrineZombieKills = data?.herobrine_zombie_kills_zombies || 0;
    this.humanZombieKills = data?.human_zombie_zombie_kills_zombies || 0;
    this.infernoPigmanZombieKills = data?.inferno_pigman_zombie_kills_zombies || 0;
    this.infernoZombieKills = data?.inferno_zombie_kills_zombies || 0;
    this.invisibleZombieKills = data?.invisible_zombie_kills_zombies || 0;
    this.ironGolemZombieKills = data?.iron_golem_zombie_kills_zombies || 0;
    this.kingDrownedZombieKills = data?.king_drowned_zombie_kills_zombies || 0;
    this.kingSlimeZombieKills = data?.king_slime_zombie_kills_zombies || 0;
    this.knightDrownedZombieKills = data?.knight_drowned_zombie_kills_zombies || 0;
    this.magmaCubeZombieKills = data?.magma_cube_zombie_kills_zombies || 0;
    this.magmaZombieKills = data?.magma_zombie_kills_zombies || 0;
    this.mcdonaldsPigmanZombieKills = data?.mcdonalds_pigman_zombie_kills_zombies || 0;
    this.mcdonaldsZombieZombieKills = data?.mcdonalds_zombie_zombie_kills_zombies || 0;
    this.megaBlobZombieKills = data?.mega_blob_zombie_kills_zombies || 0;
    this.megaMagmaZombieKills = data?.mega_magma_zombie_kills_zombies || 0;
    this.moltenZombieKills = data?.molten_zombie_kills_zombies || 0;
    this.murderPigmanZombieKills = data?.murder_pigman_zombie_kills_zombies || 0;
    this.murderZombieZombieKills = data?.murder_zombie_zombie_kills_zombies || 0;
    this.nurseZombieZombieKills = data?.nurse_zombie_zombie_kills_zombies || 0;
    this.pigZombieZombieKills = data?.pig_zombie_zombie_kills_zombies || 0;
    this.playersRevived = data?.players_revived_zombies || 0;
    this.prisonerPigman2CellZombieKills = data?.prisoner_pigman_2_cell_zombie_kills_zombies || 0;
    this.prisonerPigman2ZombieKills = data?.prisoner_pigman_2_zombie_kills_zombies || 0;
    this.prisonerPigmanCellZombieKills = data?.prisoner_pigman_cell_zombie_kills_zombies || 0;
    this.prisonerPigmanZombieKills = data?.prisoner_pigman_zombie_kills_zombies || 0;
    this.prisonerSkeletonZombieKills = data?.prisoner_skeleton_zombie_kills_zombies || 0;
    this.prisonerZombieAngry2ZombieKills = data?.prisoner_zombie_angry_2_zombie_kills_zombies || 0;
    this.prisonerZombieAngry3ZombieKills = data?.prisoner_zombie_angry_3_zombie_kills_zombies || 0;
    this.prisonerZombieAngryZombieKills = data?.prisoner_zombie_angry_zombie_kills_zombies || 0;
    this.prisonerZombieCellZombieKills = data?.prisoner_zombie_cell_zombie_kills_zombies || 0;
    this.prisonerZombieKills = data?.prisoner_zombie_zombie_kills_zombies || 0;
    this.rainbowZombieKills = data?.rainbow_zombie_kills_zombies || 0;
    this.scubaZombieKills = data?.scuba_zombie_zombie_kills_zombies || 0;
    this.sentinelZombieKills = data?.sentinel_zombie_kills_zombies || 0;
    this.shadySkeletonZombieKills = data?.shady_skeleton_zombie_kills_zombies || 0;
    this.silverfishZombieKills = data?.silverfish_zombie_kills_zombies || 0;
    this.skelefishZombieKills = data?.skelefish_zombie_kills_zombies || 0;
    this.skeletonZombieKills = data?.skeleton_zombie_kills_zombies || 0;
    this.slimeZombieKills = data?.slime_zombie_kills_zombies || 0;
    this.slimeZombieZombieKills = data?.slime_zombie_zombie_kills_zombies || 0;
    this.spaceBlasterZombieKills = data?.space_blaster_zombie_kills_zombies || 0;
    this.spaceGruntZombieKills = data?.space_grunt_zombie_kills_zombies || 0;
    this.tankDrownedZombieKills = data?.tank_drowned_zombie_kills_zombies || 0;
    this.tankZombieZombieKills = data?.tank_zombie_zombie_kills_zombies || 0;
    this.theOldOneZombieKills = data?.the_old_one_zombie_kills_zombies || 0;
    this.theWardenZombieKills = data?.the_warden_zombie_kills_zombies || 0;
    this.timesKnockedDown = data?.times_knocked_down_zombies || 0;
    this.tntBabyZombieKills = data?.tnt_baby_zombie_kills_zombies || 0;
    this.tntZombieKills = data?.tnt_zombie_kills_zombies || 0;
    this.totalRoundsSurvived = data?.total_rounds_survived_zombies || 0;
    this.werewolfZombieKills = data?.werewolf_zombie_kills_zombies || 0;
    this.windowsRepaired = data?.windows_repaired_zombies || 0;
    this.wins = data?.wins_zombies || 0;
    this.witchZombieKills = data?.witch_zombie_kills_zombies || 0;
    this.witherSkeletonZombieKills = data?.wither_skeleton_zombie_kills_zombies || 0;
    this.witherZombieKills = data?.wither_zombie_kills_zombies || 0;
    this.witherZombieZombieKills = data?.wither_zombie_zombie_kills_zombies || 0;
    this.wolfDrownedZombieKills = data?.wolf_drowned_zombie_kills_zombies || 0;
    this.wolfPetZombieKills = data?.wolf_pet_zombie_kills_zombies || 0;
    this.wolfZombieKills = data?.wolf_zombie_kills_zombies || 0;
    this.worldEnderZombieKills = data?.world_ender_zombie_kills_zombies || 0;
    this.wormSmallZombieKills = data?.worm_small_zombie_kills_zombies || 0;
    this.wormZombieKills = data?.worm_zombie_kills_zombies || 0;
    this.zombieKills = data?.zombie_kills_zombies || 0;
    this.hideTutorials = data?.zombies_hideTutorials || false;
    this.alienArcadium = new ZombiesMap(data, 'alienarcadium', false);
    this.badBlood = new ZombiesMap(data, 'badblood', true);
    this.deadEnd = new ZombiesMap(data, 'deadend', true);
    this.prison = new ZombiesMap(data, 'prison', true);
  }
}

export default Zombies;
