import ZombiesMap from './ZombiesMap.js';
import { expect, expectTypeOf, test } from 'vitest';

test('ZombiesMap', () => {
  const data = new ZombiesMap({ stats: 'meow' }, 'alienarcadium');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(ZombiesMap);
  expectTypeOf(data).toEqualTypeOf<ZombiesMap>();
  expect(data.bestRoundZombies).toBeDefined();
  expect(data.bestRoundZombies).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bestRoundZombies).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.fastestTime10).toBeDefined();
  expect(data.fastestTime10).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fastestTime10).toEqualTypeOf<number>();
  expect(data.fastestTime20).toBeDefined();
  expect(data.fastestTime20).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fastestTime20).toEqualTypeOf<number>();
  expect(data.fastestTime30).toBeDefined();
  expect(data.fastestTime30).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fastestTime30).toEqualTypeOf<number>();
  expect(data.playersRevived).toBeDefined();
  expect(data.playersRevived).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.playersRevived).toEqualTypeOf<number>();
  expect(data.timesKnockedDown).toBeDefined();
  expect(data.timesKnockedDown).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.timesKnockedDown).toEqualTypeOf<number>();
  expect(data.totalRoundsSurvived).toBeDefined();
  expect(data.totalRoundsSurvived).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.totalRoundsSurvived).toEqualTypeOf<number>();
  expect(data.windowsRepaired).toBeDefined();
  expect(data.windowsRepaired).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.windowsRepaired).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.zombieKills).toBeDefined();
  expect(data.zombieKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.zombieKills).toEqualTypeOf<number>();
});
