import SkyBlockMemberAccessoryBagTuningSlot from './SkyBlockMemberAccessoryBagTuningSlot.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberAccessoryBagTuningSlot', () => {
  const data = new SkyBlockMemberAccessoryBagTuningSlot({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberAccessoryBagTuningSlot);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberAccessoryBagTuningSlot>();
  expect(data.unlocked).toBeDefined();
  expectTypeOf(data.unlocked).toEqualTypeOf<boolean>();
  expect(data.purchasedTimestamp).toBeDefined();
  expectTypeOf(data.purchasedTimestamp).toEqualTypeOf<number | null>();
  expect(data.purchasedDate).toBeDefined();
  expectTypeOf(data.purchasedDate).toEqualTypeOf<Date | null>();
  expect(data.health).toBeDefined();
  expect(data.health).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.health).toEqualTypeOf<number>();
  expect(data.defense).toBeDefined();
  expect(data.defense).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.defense).toEqualTypeOf<number>();
  expect(data.walkSpeed).toBeDefined();
  expect(data.walkSpeed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.walkSpeed).toEqualTypeOf<number>();
  expect(data.strength).toBeDefined();
  expect(data.strength).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.strength).toEqualTypeOf<number>();
  expect(data.criticalDamage).toBeDefined();
  expect(data.criticalDamage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.criticalDamage).toEqualTypeOf<number>();
  expect(data.criticalChance).toBeDefined();
  expect(data.criticalChance).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.criticalChance).toEqualTypeOf<number>();
  expect(data.attackSpeed).toBeDefined();
  expect(data.attackSpeed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.attackSpeed).toEqualTypeOf<number>();
  expect(data.intelligence).toBeDefined();
  expect(data.intelligence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.intelligence).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => boolean>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.unlocked);
  expectTypeOf(data.toString()).toEqualTypeOf<boolean>();
});
