import SkyBlockMemberCrimsonIsleDojo from './SkyBlockMemberCrimsonIsleDojo.js';
import SkyBlockMemberCrimsonIsleDojoMinigame from './SkyBlockMemberCrimsonIsleDojoMinigame.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { CrimsonIsleBelt } from '../../../../Types/SkyBlock.js';

test('SkyBlockMemberCrimsonIsleDojo', () => {
  const data = new SkyBlockMemberCrimsonIsleDojo({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojo);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojo>();
  expect(data.force).toBeDefined();
  expect(data.force).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.force).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.stamina).toBeDefined();
  expect(data.stamina).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.stamina).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.mastery).toBeDefined();
  expect(data.mastery).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.mastery).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.discipline).toBeDefined();
  expect(data.discipline).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.discipline).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.swiftness).toBeDefined();
  expect(data.swiftness).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.swiftness).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.tenacity).toBeDefined();
  expect(data.tenacity).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.tenacity).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.control).toBeDefined();
  expect(data.control).toBeInstanceOf(SkyBlockMemberCrimsonIsleDojoMinigame);
  expectTypeOf(data.control).toEqualTypeOf<SkyBlockMemberCrimsonIsleDojoMinigame>();
  expect(data.belt).toBeDefined();
  expectTypeOf(data.belt).toEqualTypeOf<CrimsonIsleBelt>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => CrimsonIsleBelt>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.belt);
  expectTypeOf(data.toString()).toEqualTypeOf<CrimsonIsleBelt>();
});
