import SkyBlockMemberCrimsonIsleKuudra from './SkyBlockMemberCrimsonIsleKuudra.js';
import SkyBlockMemberCrimsonIsleKuudraPartyFinder from './SkyBlockMemberCrimsonIsleKuudraPartyFinder.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberCrimsonIsleKuudra', () => {
  const data = new SkyBlockMemberCrimsonIsleKuudra({ stats: 'meow' }, { stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberCrimsonIsleKuudra);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberCrimsonIsleKuudra>();
  expect(data.basicCompletions).toBeDefined();
  expect(data.basicCompletions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.basicCompletions).toEqualTypeOf<number>();
  expect(data.highestWaveBasic).toBeDefined();
  expect(data.highestWaveBasic).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestWaveBasic).toEqualTypeOf<number>();
  expect(data.hotCompletions).toBeDefined();
  expect(data.hotCompletions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.hotCompletions).toEqualTypeOf<number>();
  expect(data.highestWaveHot).toBeDefined();
  expect(data.highestWaveHot).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestWaveHot).toEqualTypeOf<number>();
  expect(data.burningCompletions).toBeDefined();
  expect(data.burningCompletions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.burningCompletions).toEqualTypeOf<number>();
  expect(data.highestWaveBurning).toBeDefined();
  expect(data.highestWaveBurning).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestWaveBurning).toEqualTypeOf<number>();
  expect(data.fieryCompletions).toBeDefined();
  expect(data.fieryCompletions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fieryCompletions).toEqualTypeOf<number>();
  expect(data.highestWaveFiery).toBeDefined();
  expect(data.highestWaveFiery).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestWaveFiery).toEqualTypeOf<number>();
  expect(data.infernalCompletions).toBeDefined();
  expect(data.infernalCompletions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.infernalCompletions).toEqualTypeOf<number>();
  expect(data.highestWaveInfernal).toBeDefined();
  expect(data.highestWaveInfernal).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestWaveInfernal).toEqualTypeOf<number>();
  expect(data.partyFinderOptions).toBeDefined();
  expect(data.partyFinderOptions).toBeInstanceOf(SkyBlockMemberCrimsonIsleKuudraPartyFinder);
  expectTypeOf(data.partyFinderOptions).toEqualTypeOf<SkyBlockMemberCrimsonIsleKuudraPartyFinder>();
  expect(data.totalCompletions).toBeDefined();
  expect(data.totalCompletions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.totalCompletions).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.totalCompletions);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
