import SheepWars from './SheepWars.js';
import SheepWarsLayout from './SheepWarsLayout.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { WoolGamesSheepWarsClassName } from '../../../../Types/Player.js';

test('SheepWars', () => {
  const data = new SheepWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SheepWars);
  expectTypeOf(data).toEqualTypeOf<SheepWars>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.winLossRatio).toBeDefined();
  expect(data.winLossRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winLossRatio).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.killDeathRatio).toBeDefined();
  expect(data.killDeathRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killDeathRatio).toEqualTypeOf<number>();
  expect(data.killsVoid).toBeDefined();
  expect(data.killsVoid).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsVoid).toEqualTypeOf<number>();
  expect(data.deathsVoid).toBeDefined();
  expect(data.deathsVoid).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsVoid).toEqualTypeOf<number>();
  expect(data.killDeathRatioVoid).toBeDefined();
  expect(data.killDeathRatioVoid).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killDeathRatioVoid).toEqualTypeOf<number>();
  expect(data.killsBow).toBeDefined();
  expect(data.killsBow).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsBow).toEqualTypeOf<number>();
  expect(data.deathsBow).toBeDefined();
  expect(data.deathsBow).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsBow).toEqualTypeOf<number>();
  expect(data.killDeathRatioBow).toBeDefined();
  expect(data.killDeathRatioBow).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killDeathRatioBow).toEqualTypeOf<number>();
  expect(data.killsExplosive).toBeDefined();
  expect(data.killsExplosive).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsExplosive).toEqualTypeOf<number>();
  expect(data.deathsExplosive).toBeDefined();
  expect(data.deathsExplosive).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsExplosive).toEqualTypeOf<number>();
  expect(data.killDeathRatioExplosive).toBeDefined();
  expect(data.killDeathRatioExplosive).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killDeathRatioExplosive).toEqualTypeOf<number>();
  expect(data.killsMelee).toBeDefined();
  expect(data.killsMelee).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsMelee).toEqualTypeOf<number>();
  expect(data.deathsMelee).toBeDefined();
  expect(data.deathsMelee).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsMelee).toEqualTypeOf<number>();
  expect(data.killDeathRatioMelee).toBeDefined();
  expect(data.killDeathRatioMelee).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killDeathRatioMelee).toEqualTypeOf<number>();
  expect(data.magicWoolHit).toBeDefined();
  expect(data.magicWoolHit).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.magicWoolHit).toEqualTypeOf<number>();
  expect(data.damageDealt).toBeDefined();
  expect(data.damageDealt).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageDealt).toEqualTypeOf<number>();
  expect(data.sheepThrown).toBeDefined();
  expect(data.sheepThrown).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sheepThrown).toEqualTypeOf<number>();
  expect(data.gamesPlayed).toBeDefined();
  expect(data.gamesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gamesPlayed).toEqualTypeOf<number>();
  expect(data.kit).toBeDefined();
  expectTypeOf(data.kit).toEqualTypeOf<WoolGamesSheepWarsClassName | 'None'>();
  expect(data.layout).toBeDefined();
  expect(data.layout).toBeInstanceOf(SheepWarsLayout);
  expectTypeOf(data.layout).toEqualTypeOf<SheepWarsLayout>();
});
