import BaseSkyWarsMode from '../SkyWarsMode/BaseSkyWarsMode.js';
import SkyWarsRankedKits from './SkyWarsRankedKits.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsRankedKits', () => {
  const data = new SkyWarsRankedKits({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsRankedKits);
  expectTypeOf(data).toEqualTypeOf<SkyWarsRankedKits>();
  expect(data.default).toBeDefined();
  expect(data.default).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.default).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.armorer).toBeDefined();
  expect(data.armorer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.armorer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.bowman).toBeDefined();
  expect(data.bowman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.bowman).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.champion).toBeDefined();
  expect(data.champion).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.champion).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.pyromancer).toBeDefined();
  expect(data.pyromancer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.pyromancer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.hound).toBeDefined();
  expect(data.hound).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.hound).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.athlete).toBeDefined();
  expect(data.athlete).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.athlete).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.magician).toBeDefined();
  expect(data.magician).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.magician).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.healer).toBeDefined();
  expect(data.healer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.healer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.paladin).toBeDefined();
  expect(data.paladin).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.paladin).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.blacksmith).toBeDefined();
  expect(data.blacksmith).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.blacksmith).toEqualTypeOf<BaseSkyWarsMode>();
});
