import SkyBlockMember from './SkyBlockMember.ts';
import SkyBlockMemberAccessoryBag from './AccessoryBag/SkyBlockMemberAccessoryBag.ts';
import SkyBlockMemberBestiary from './Bestiary/SkyBlockMemberBestiary.ts';
import SkyBlockMemberChocolateFactory from './ChocolateFactory/SkyBlockMemberChocolateFactory.ts';
import SkyBlockMemberCrimsonIsle from './CrimsonIsle/SkyBlockMemberCrimsonIsle.ts';
import SkyBlockMemberCurrencies from './SkyBlockMemberCurrencies.ts';
import SkyBlockMemberDungeons from './Dungeons/SkyBlockMemberDungeons.ts';
import SkyBlockMemberFairySouls from './SkyBlockMemberFairySouls.ts';
import SkyBlockMemberGarden from './Garden/SkyBlockMemberGarden.ts';
import SkyBlockMemberInventories from './Inventories/SkyBlockMemberInventories.ts';
import SkyBlockMemberJacobContests from './JacobContests/SkyBlockMemberJacobContests.ts';
import SkyBlockMemberLeveling from './SkyBlockMemberLeveling.ts';
import SkyBlockMemberMining from './Mining/SkyBlockMemberMining.ts';
import SkyBlockMemberObjectives from './SkyBlockMemberObjectives.ts';
import SkyBlockMemberPets from './Pets/SkyBlockMemberPets.ts';
import SkyBlockMemberPlayerData from './PlayerData/SkyBlockMemberPlayerData.ts';
import SkyBlockMemberPlayerStats from './PlayerStats/SkyBlockMemberPlayerStats.ts';
import SkyBlockMemberProfile from './SkyBlockMemberProfile.ts';
import SkyBlockMemberQuests from './Quests/SkyBlockMemberQuests.ts';
import SkyBlockMemberRift from './Rift/SkyBlockMemberRift.ts';
import SkyBlockMemberSkillTrees from './SkillTree/SkyBlockMemberSkillTrees.ts';
import SkyBlockMemberSlayers from './Slayers/SkyBlockMemberSlayers.ts';
import { expect, expectTypeOf, test } from 'vitest';
import type { SkyBlockArrow, UUID } from '../../../Types/index.ts';

test('SkyBlockMember', () => {
  const data = new SkyBlockMember('mrrp', { stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMember);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMember>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<UUID>();
  expect(data.accessoryBag).toBeDefined();
  expect(data.accessoryBag).toBeInstanceOf(SkyBlockMemberAccessoryBag);
  expectTypeOf(data.accessoryBag).toEqualTypeOf<SkyBlockMemberAccessoryBag>();
  expect(data.bestiary).toBeDefined();
  expect(data.bestiary).toBeInstanceOf(SkyBlockMemberBestiary);
  expectTypeOf(data.bestiary).toEqualTypeOf<SkyBlockMemberBestiary>();
  expect(data.collections).toBeDefined();
  expectTypeOf(data.collections).toEqualTypeOf<Record<string, number>>();
  expect(data.currencies).toBeDefined();
  expect(data.currencies).toBeInstanceOf(SkyBlockMemberCurrencies);
  expectTypeOf(data.currencies).toEqualTypeOf<SkyBlockMemberCurrencies>();
  expect(data.dungeons).toBeDefined();
  expect(data.dungeons).toBeInstanceOf(SkyBlockMemberDungeons);
  expectTypeOf(data.dungeons).toEqualTypeOf<SkyBlockMemberDungeons>();
  expect(data.chocolateFactory).toBeDefined();
  expect(data.chocolateFactory).toBeInstanceOf(SkyBlockMemberChocolateFactory);
  expectTypeOf(data.chocolateFactory).toEqualTypeOf<SkyBlockMemberChocolateFactory>();
  expect(data.garden).toBeDefined();
  expect(data.garden).toBeInstanceOf(SkyBlockMemberGarden);
  expectTypeOf(data.garden).toEqualTypeOf<SkyBlockMemberGarden>();
  expect(data.skillTrees).toBeDefined();
  expect(data.skillTrees).toBeInstanceOf(SkyBlockMemberSkillTrees);
  expectTypeOf(data.skillTrees).toEqualTypeOf<SkyBlockMemberSkillTrees>();
  expect(data.fairySouls).toBeDefined();
  expect(data.fairySouls).toBeInstanceOf(SkyBlockMemberFairySouls);
  expectTypeOf(data.fairySouls).toEqualTypeOf<SkyBlockMemberFairySouls>();
  expect(data.soulflow).toBeDefined();
  expect(data.soulflow).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.soulflow).toEqualTypeOf<number>();
  expect(data.favoriteArrow).toBeDefined();
  expectTypeOf(data.favoriteArrow).toEqualTypeOf<SkyBlockArrow>();
  expect(data.jacobContests).toBeDefined();
  expect(data.jacobContests).toBeInstanceOf(SkyBlockMemberJacobContests);
  expectTypeOf(data.jacobContests).toEqualTypeOf<SkyBlockMemberJacobContests>();
  expect(data.leveling).toBeDefined();
  expect(data.leveling).toBeInstanceOf(SkyBlockMemberLeveling);
  expectTypeOf(data.leveling).toEqualTypeOf<SkyBlockMemberLeveling>();
  expect(data.mining).toBeDefined();
  expect(data.mining).toBeInstanceOf(SkyBlockMemberMining);
  expectTypeOf(data.mining).toEqualTypeOf<SkyBlockMemberMining>();
  expect(data.crimsonIsle).toBeDefined();
  expect(data.crimsonIsle).toBeInstanceOf(SkyBlockMemberCrimsonIsle);
  expectTypeOf(data.crimsonIsle).toEqualTypeOf<SkyBlockMemberCrimsonIsle>();
  expect(data.objectives).toBeDefined();
  expect(data.objectives).toBeInstanceOf(SkyBlockMemberObjectives);
  expectTypeOf(data.objectives).toEqualTypeOf<SkyBlockMemberObjectives>();
  expect(data.pets).toBeDefined();
  expect(data.pets).toBeInstanceOf(SkyBlockMemberPets);
  expectTypeOf(data.pets).toEqualTypeOf<SkyBlockMemberPets>();
  expect(data.playerData).toBeDefined();
  expect(data.playerData).toBeInstanceOf(SkyBlockMemberPlayerData);
  expectTypeOf(data.playerData).toEqualTypeOf<SkyBlockMemberPlayerData>();
  expect(data.playerStats).toBeDefined();
  expect(data.playerStats).toBeInstanceOf(SkyBlockMemberPlayerStats);
  expectTypeOf(data.playerStats).toEqualTypeOf<SkyBlockMemberPlayerStats>();
  expect(data.profileStats).toBeDefined();
  expect(data.profileStats).toBeInstanceOf(SkyBlockMemberProfile);
  expectTypeOf(data.profileStats).toEqualTypeOf<SkyBlockMemberProfile>();
  expect(data.quests).toBeDefined();
  expect(data.quests).toBeInstanceOf(SkyBlockMemberQuests);
  expectTypeOf(data.quests).toEqualTypeOf<SkyBlockMemberQuests>();
  expect(data.slayers).toBeDefined();
  expect(data.slayers).toBeInstanceOf(SkyBlockMemberSlayers);
  expectTypeOf(data.slayers).toEqualTypeOf<SkyBlockMemberSlayers>();
  expect(data.rift).toBeDefined();
  expect(data.rift).toBeInstanceOf(SkyBlockMemberRift);
  expectTypeOf(data.rift).toEqualTypeOf<SkyBlockMemberRift>();
  expect(data.inventory).toBeDefined();
  expect(data.inventory).toBeInstanceOf(SkyBlockMemberInventories);
  expectTypeOf(data.inventory).toEqualTypeOf<SkyBlockMemberInventories>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => UUID>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.uuid);
  expectTypeOf(data.toString()).toEqualTypeOf<UUID>();
});
