import SkyBlockMemberCurrencies from './SkyBlockMemberCurrencies.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberCurrencies', () => {
  const data = new SkyBlockMemberCurrencies({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberCurrencies);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberCurrencies>();
  expect(data.purse).toBeDefined();
  expect(data.purse).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.purse).toEqualTypeOf<number>();
  expect(data.motesPurse).toBeDefined();
  expect(data.motesPurse).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.motesPurse).toEqualTypeOf<number>();
  expect(data.witherEssence).toBeDefined();
  expect(data.witherEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherEssence).toEqualTypeOf<number>();
  expect(data.dragonEssence).toBeDefined();
  expect(data.dragonEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.dragonEssence).toEqualTypeOf<number>();
  expect(data.spiderEssence).toBeDefined();
  expect(data.spiderEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.spiderEssence).toEqualTypeOf<number>();
  expect(data.undeadEssence).toBeDefined();
  expect(data.undeadEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.undeadEssence).toEqualTypeOf<number>();
  expect(data.diamondEssence).toBeDefined();
  expect(data.diamondEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.diamondEssence).toEqualTypeOf<number>();
  expect(data.goldEssence).toBeDefined();
  expect(data.goldEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.goldEssence).toEqualTypeOf<number>();
  expect(data.iceEssence).toBeDefined();
  expect(data.iceEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.iceEssence).toEqualTypeOf<number>();
  expect(data.crimsonEssence).toBeDefined();
  expect(data.crimsonEssence).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.crimsonEssence).toEqualTypeOf<number>();
});
