import PlayerSeasonalChristmasYearAdventRewards from './PlayerSeasonalChristmasYearAdventRewards.js';
import { expect, expectTypeOf, test } from 'vitest';

test('PlayerSeasonalChristmasYearAdventRewards', () => {
  const data = new PlayerSeasonalChristmasYearAdventRewards({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(PlayerSeasonalChristmasYearAdventRewards);
  expectTypeOf(data).toEqualTypeOf<PlayerSeasonalChristmasYearAdventRewards>();
  expect(data.day1).toBeDefined();
  expect(data.day1).toBeNull();
  expectTypeOf(data.day1).toEqualTypeOf<Date | null>();
  expect(data.day2).toBeDefined();
  expect(data.day2).toBeNull();
  expectTypeOf(data.day2).toEqualTypeOf<Date | null>();
  expect(data.day3).toBeDefined();
  expect(data.day3).toBeNull();
  expectTypeOf(data.day3).toEqualTypeOf<Date | null>();
  expect(data.day4).toBeDefined();
  expect(data.day4).toBeNull();
  expectTypeOf(data.day4).toEqualTypeOf<Date | null>();
  expect(data.day5).toBeDefined();
  expect(data.day5).toBeNull();
  expectTypeOf(data.day5).toEqualTypeOf<Date | null>();
  expect(data.day6).toBeDefined();
  expect(data.day6).toBeNull();
  expectTypeOf(data.day6).toEqualTypeOf<Date | null>();
  expect(data.day7).toBeDefined();
  expect(data.day7).toBeNull();
  expectTypeOf(data.day7).toEqualTypeOf<Date | null>();
  expect(data.day8).toBeDefined();
  expect(data.day8).toBeNull();
  expectTypeOf(data.day8).toEqualTypeOf<Date | null>();
  expect(data.day9).toBeDefined();
  expect(data.day9).toBeNull();
  expectTypeOf(data.day9).toEqualTypeOf<Date | null>();
  expect(data.day10).toBeDefined();
  expect(data.day10).toBeNull();
  expectTypeOf(data.day10).toEqualTypeOf<Date | null>();
  expect(data.day11).toBeDefined();
  expect(data.day11).toBeNull();
  expectTypeOf(data.day11).toEqualTypeOf<Date | null>();
  expect(data.day12).toBeDefined();
  expect(data.day12).toBeNull();
  expectTypeOf(data.day12).toEqualTypeOf<Date | null>();
  expect(data.day13).toBeDefined();
  expect(data.day13).toBeNull();
  expectTypeOf(data.day13).toEqualTypeOf<Date | null>();
  expect(data.day14).toBeDefined();
  expect(data.day14).toBeNull();
  expectTypeOf(data.day14).toEqualTypeOf<Date | null>();
  expect(data.day15).toBeDefined();
  expect(data.day15).toBeNull();
  expectTypeOf(data.day15).toEqualTypeOf<Date | null>();
  expect(data.day16).toBeDefined();
  expect(data.day16).toBeNull();
  expectTypeOf(data.day16).toEqualTypeOf<Date | null>();
  expect(data.day17).toBeDefined();
  expect(data.day17).toBeNull();
  expectTypeOf(data.day17).toEqualTypeOf<Date | null>();
  expect(data.day18).toBeDefined();
  expect(data.day18).toBeNull();
  expectTypeOf(data.day18).toEqualTypeOf<Date | null>();
  expect(data.day19).toBeDefined();
  expect(data.day19).toBeNull();
  expectTypeOf(data.day19).toEqualTypeOf<Date | null>();
  expect(data.day20).toBeDefined();
  expect(data.day20).toBeNull();
  expectTypeOf(data.day20).toEqualTypeOf<Date | null>();
  expect(data.day21).toBeDefined();
  expect(data.day21).toBeNull();
  expectTypeOf(data.day21).toEqualTypeOf<Date | null>();
  expect(data.day22).toBeDefined();
  expect(data.day22).toBeNull();
  expectTypeOf(data.day22).toEqualTypeOf<Date | null>();
  expect(data.day23).toBeDefined();
  expect(data.day23).toBeNull();
  expectTypeOf(data.day23).toEqualTypeOf<Date | null>();
  expect(data.day24).toBeDefined();
  expect(data.day24).toBeNull();
  expectTypeOf(data.day24).toEqualTypeOf<Date | null>();
  expect(data.day25).toBeDefined();
  expect(data.day25).toBeNull();
  expectTypeOf(data.day25).toEqualTypeOf<Date | null>();
});
