/* v8 ignore next 10000 */
// Credits: Pixelic: https://github.com/pixelicc - Most types in player

import PitInventoryItem from '../Structures/MiniGames/Pit/PitInventoryItem.js';
import type { SortName } from './Global.js';

export type PlayerHousingSettingsTextInputType = 'CHAT';
export type PlayerHousingPlotSize = 'SMALL' | 'MEDIUM' | 'LARGE' | 'MASSIVE' | 'EXTREME';
export type PlayerHousingTutorialStage = 'WAITING_FOR_INTERACTION' | 'GIVING_KIT' | 'FINISHED' | 'FINISH_FINISHED';
export type PlayerTourneyShopSort = 'highest_cost' | SortName;
export type PlayerAchievementsOneTimeSort = 'highest_points' | SortName;
export type SeasonName = 'christmas' | 'easter' | 'summer' | 'halloween' | 'anniversary';
export type SocialMediaId = 'DISCORD' | 'TWITTER' | 'YOUTUBE' | 'INSTAGRAM' | 'TIKTOK' | 'TWITCH' | 'HYPIXEL';
export type ZombiesMaps = 'deadend' | 'badblood' | 'alienarcadium' | 'prison';
export type EnderSpleefTrails = 'RAINBOW' | 'GREEN' | 'DEFAULT' | 'RED' | 'BLUE';
export type TurboKartRacersMaps = 'retro' | 'hypixelgp' | 'olympus' | 'junglerush' | 'canyon';
export type VampireZRoles = 'human' | 'vampire';
export type PixelPartyGameModes = 'normal' | 'hyper';
export type QuakecraftBarrels = 'SMALL_BALL' | 'LARGE_BALL' | 'BURST' | 'STAR' | 'CREEPER';
export type QuakecraftTriggers = 'ZERO_POINT_EIGHT_FIVE' | 'ZERO_POINT_NINE' | 'ONE_POINT_ONE' | 'ONE_POINT_THREE';
export type ArenaBrawlModes = '1v1' | '2v2' | '4v4';
export type ArenaBrawlRunes = 'slowing' | 'energy' | 'damage' | 'tank' | 'speed';
export type MiniWallsKits = 'soldier' | 'archer' | 'builder';
export type WoolWarsClassNames = 'ASSAULT' | 'TANK' | 'GOLEM' | 'SWORDSMAN' | 'ENGINEER' | 'ARCHER';
export type MurderMysteryModes = 'MURDER_CLASSIC' | 'MURDER_ASSASSINS' | 'MURDER_DOUBLE_UP' | 'MURDER_INFECTION';
export type SmashHeoresModes = 'normal' | '2v2' | 'teams';
export type SkyWarsBaseModes = 'solo' | 'team';
export type MegaWallsModes = 'face_off' | 'gvg';
export type SpeedUHCModes = 'solo' | 'solo_normal' | 'solo_insane' | 'team' | 'team_normal' | 'team_insane';
export type UHCModes = 'solo' | 'red_vs_blue' | 'no_diamonds' | 'brawl' | 'solo_brawl' | 'duo_brawl';
export type CopsAndCrimsGamemodes = 'deathmatch' | 'gungame';
export type BedWarsPracticeRecordDistances = 30 | 50 | 100;
export type BedWarsPracticeRecordElevations = 'NONE' | 'SLIGHT' | 'STAIRCASE';
export type BedWarsPracticeModes = 'BRIDGING' | 'FIREBALL_JUMPING' | 'BOW' | 'MLG' | 'PEARL_CLUTCHING';
export type BedWarsDreamGamemodeName = 'ultimate' | 'rush' | 'armed' | 'lucky' | 'voidless';
export type BedWarsGamemodeName =
  | 'eight_one'
  | 'eight_two'
  | 'four_three'
  | 'four_four'
  | 'two_four'
  | 'castle'
  | 'eight_two_ultimate'
  | 'four_four_ultimate'
  | 'eight_two_rush'
  | 'four_four_rush'
  | 'eight_two_armed'
  | 'four_four_armed'
  | 'eight_two_lucky'
  | 'four_four_lucky'
  | 'eight_two_voidless'
  | 'four_four_voidless';

export type BlitzSurvivalGamesKits =
  | 'archer'
  | 'meatmaster'
  | 'speleologist'
  | 'baker'
  | 'knight'
  | 'guardian'
  | 'scout'
  | 'hunter'
  | 'hype train'
  | 'fisherman'
  | 'armorer'
  | 'horsetamer'
  | 'astronaut'
  | 'troll'
  | 'reaper'
  | 'shark'
  | 'reddragon'
  | 'toxicologist'
  | 'rogue'
  | 'warlock'
  | 'slimeyslime'
  | 'jockey'
  | 'golem'
  | 'viking'
  | 'shadow knight'
  | 'pigman'
  | 'paladin'
  | 'necromancer'
  | 'florist'
  | 'diver'
  | 'arachnologist'
  | 'blaze'
  | 'wolftamer'
  | 'tim'
  | 'farmer'
  | 'creepertamer'
  | 'snowman';

export type MegaWallsKits =
  | 'cow'
  | 'hunter'
  | 'shark'
  | 'arcanist'
  | 'deadlord'
  | 'golem'
  | 'herobrine'
  | 'pigman'
  | 'zombie'
  | 'blaze'
  | 'enderman'
  | 'shaman'
  | 'squid'
  | 'creeper'
  | 'pirate'
  | 'sheep'
  | 'skeleton'
  | 'spider'
  | 'werewolf'
  | 'angel'
  | 'assassin'
  | 'automaton'
  | 'moleman'
  | 'phoenix'
  | 'renegade'
  | 'snowman';

export type SkyWarsModes =
  | 'mega'
  | 'mega_doubles'
  | 'lab'
  | 'solo_normal'
  | 'solo_insane'
  | 'team_normal'
  | 'team_insane';

export type SmashHeoresHeros =
  | 'THE_BULK'
  | 'CAKE_MONSTER'
  | 'GENERAL_CLUCK'
  | 'BOTMUN'
  | 'MARAUDER'
  | 'PUG'
  | 'TINMAN'
  | 'SPODERMAN'
  | 'FROSTY'
  | 'SERGEANT_SHIELD'
  | 'SKULLFIRE'
  | 'GOKU'
  | 'SANIC'
  | 'DUSK_CRAWLER'
  | 'SHOOP_DA_WHOOP'
  | 'GREEN_HOOD';

export type WarlordsClasses =
  | 'pyromancer'
  | 'mage'
  | 'thunderlord'
  | 'shaman'
  | 'earthwarden'
  | 'aquamancer'
  | 'paladin'
  | 'avenger'
  | 'warrior'
  | 'defender'
  | 'cryomancer'
  | 'crusader'
  | 'berserker'
  | 'protector'
  | 'revenant'
  | 'spiritguard';

export type DuelsModes =
  | 'blitz'
  | 'classic'
  | 'bow'
  | 'no_debuff'
  | 'combo'
  | 'tnt_games'
  | 'sumo'
  | 'parkour'
  | 'bridge'
  | 'bridge_duel'
  | 'bridge_doubles'
  | 'bridge_threes'
  | 'bridge_fours'
  | '2v2v2v2'
  | '3v3v3v3'
  | 'capture_threes'
  | 'op'
  | 'mega_walls'
  | 'mw_duel'
  | 'mw_doubles'
  | 'sw'
  | 'sw_duel'
  | 'sw_doubles'
  | 'uhc'
  | 'uhc_duel'
  | 'uhc_doubles'
  | 'uhc_four'
  | 'uhc_meetup'
  | 'blitz_duel'
  | 'classic_duel'
  | 'bow_duel'
  | 'potion_duel'
  | 'combo_duel'
  | 'bowspleef_duel'
  | 'sumo_duel'
  | 'parkour_eight'
  | 'duel_arena'
  | 'op_duel'
  | 'op_doubles';

export type PaintballHats =
  | 'speed_hat'
  | 'vip_kevinkool_hat'
  | 'vip_rezzus_hat'
  | 'vip_agentk_hat'
  | 'normal_hat'
  | 'tnt_hat'
  | 'vip_paintballkitty_hat'
  | 'vip_ghost_hat'
  | 'hard_hat'
  | 'ender_hat'
  | 'vip_codename_b_hat'
  | 'snow_hat'
  | 'vip_hypixel_hat'
  | 'vip_noxyd_hat'
  | 'squid_hat'
  | 'shaky_hat'
  | 'spider_hat'
  | 'drunk_hat';

export type QuakecraftKillSounds =
  | 'anvil_land'
  | 'pig_death'
  | 'bat_death'
  | 'level_up'
  | 'cow_hurt'
  | 'ghast_death'
  | 'creeper_death'
  | 'blaze_death'
  | 'zombie_woodbreak'
  | 'enderman_death'
  | 'wither_idle'
  | 'dragon_growl'
  | 'villager_mhm'
  | 'horse_death'
  | 'golem_death'
  | 'thunder';

export type QuakecraftCase =
  | 'SHINY_DIAMOND_HOE'
  | 'STONE_HOE'
  | 'SHINY_IRON_HOE'
  | 'SHINY_STONE_HOE'
  | 'SHINY_WOOD_HOE'
  | 'WOOD_HOE'
  | 'DIAMOND_HOE'
  | 'SHINY_GOLD_HOE'
  | 'IRON_HOE';

export type QuakecraftMuzzle =
  | 'SOUL_SAND'
  | 'QUARTZ'
  | 'REDSTONE'
  | 'NONE'
  | 'IRON'
  | 'DIAMOND'
  | 'LAPIS'
  | 'OBSIDIAN'
  | 'PRISMARINE'
  | 'EMERALD'
  | 'PUMPKIN'
  | 'COMMAND_BLOCK'
  | 'SEA_LANTERN';

export type QuakecraftSights =
  | 'BLACK'
  | 'RED'
  | 'YELLOW'
  | 'SILVER'
  | 'BLUE'
  | 'DIAMOND'
  | 'WHITE'
  | 'PURPLE'
  | 'EMERALD'
  | 'GRAY'
  | 'GOLD'
  | 'ORANGE'
  | 'PINK'
  | 'GREEN';

export type SkyWarsKitNames =
  | 'kit_mythical_end-lord'
  | 'kit_supporting_team_armorsmith'
  | 'ecologist'
  | 'rookie'
  | 'enchanter'
  | 'snowman'
  | 'armorsmith'
  | 'scout'
  | 'knight'
  | 'armorer'
  | 'energix'
  | 'enderchest'
  | 'healer'
  | 'frog'
  | 'grenade'
  | 'batguy'
  | 'pharaoh'
  | 'disco'
  | 'princess'
  | 'enderman'
  | 'pyro'
  | 'speleologist'
  | 'farmer'
  | 'cannoneer'
  | 'fisherman'
  | 'troll'
  | 'hunter'
  | 'guardian'
  | 'engineer'
  | 'salmon'
  | 'slime'
  | 'magician'
  | 'sloth'
  | 'zookeeper'
  | 'jester'
  | 'golem'
  | 'cactus'
  | 'warlock'
  | 'archeologist'
  | 'kit_advanced_solo_pig-rider'
  | 'kit_attacking_team_scout'
  | 'kit_basic_solo_archeologist'
  | 'kit_basic_solo_frog'
  | 'kit_defending_team_armorer'
  | 'kit_advanced_solo_armorer'
  | 'kit_defending_team_batguy'
  | 'kit_supporting_team_ecologist'
  | 'kit_basic_solo_disco'
  | 'kit_attacking_team_knight'
  | 'kit_advanced_solo_farmer'
  | 'kit_advanced_solo_hunter'
  | 'kit_basic_solo_ecologist'
  | 'kit_supporting_team_rookie'
  | 'kit_supporting_team_healer'
  | 'kit_mining_team_cannoneer'
  | 'kit_defending_team_disco'
  | 'kit_mining_team_default'
  | 'kit_advanced_solo_pyro'
  | 'kit_defending_team_baseball-player'
  | 'kit_basic_solo_speleologist'
  | 'kit_attacking_team_energix'
  | 'kit_defending_team_frog'
  | 'kit_advanced_solo_enderman'
  | 'kit_basic_solo_baseball-player';

export type UHCKits =
  | 'ARCHERY_TOOLS'
  | 'WORKING_TOOLS'
  | 'HORSEMAN'
  | 'ECOLOGIST'
  | 'LOOTER'
  | 'MAGIC_TOOLS'
  | 'TRAPPER';

export type CopsAndCrimsGuns =
  | 'smg'
  | 'rifle'
  | 'carbine'
  | 'magnum'
  | 'shotgun'
  | 'sniper'
  | 'scoped_rifle'
  | 'handgun'
  | 'auto_shotgun'
  | 'bullpup'
  | 'knife';

export interface RanksPurchaseTime {
  VIP: Date | null;
  VIP_PLUS: Date | null;
  MVP: Date | null;
  MVP_PLUS: Date | null;
}

export interface ScorpiusBribe {
  year: number;
  timestamp: number;
}

export type BedWarsPrestige =
  | 'Stone'
  | 'Iron'
  | 'Gold'
  | 'Diamond'
  | 'Emerald'
  | 'Sapphire'
  | 'Ruby'
  | 'Crystal'
  | 'Opal'
  | 'Amethyst'
  | 'Rainbow'
  | 'Iron Prime'
  | 'Gold Prime'
  | 'Diamond Prime'
  | 'Emerald Prime'
  | 'Sapphire Prime'
  | 'Ruby Prime'
  | 'Crystal Prime'
  | 'Opal Prime'
  | 'Amethyst Prime'
  | 'Mirror'
  | 'Light'
  | 'Dawn'
  | 'Dusk'
  | 'Air'
  | 'Wind'
  | 'Nebula'
  | 'Thunder'
  | 'Earth'
  | 'Water'
  | 'Fire'
  | 'Sunrise'
  | 'Eclipse'
  | 'Gamma'
  | 'Majestic'
  | 'Andesine'
  | 'Marine'
  | 'Element'
  | 'Galaxy'
  | 'Atomic'
  | 'Sunset'
  | 'Time'
  | 'Winter'
  | 'Obsidian'
  | 'Spring'
  | 'Ice'
  | 'Summer'
  | 'Spinel'
  | 'Autumn'
  | 'Mystic'
  | 'Eternal';

export type SkyWarsPrestige =
  | 'Iron'
  | 'Gold'
  | 'Diamond'
  | 'Emerald'
  | 'Sapphire'
  | 'Ruby'
  | 'Crystal'
  | 'Opal'
  | 'Amethyst'
  | 'Rainbow'
  | 'Mythic';

export type TurboKartRacersHorn =
  | 'DEFAULT'
  | 'SHY'
  | 'ALIEN'
  | 'TAXI'
  | 'KLAXON'
  | 'TRICYCLE'
  | 'ALARM'
  | 'KLOON'
  | 'TEDDY'
  | 'TRUCK'
  | 'JERRY';

export type DuelsBaseDivision =
  | 'Rookie'
  | 'Iron'
  | 'Gold'
  | 'Diamond'
  | 'Master'
  | 'Legend'
  | 'Grandmaster'
  | 'Godlike'
  | 'Celestial'
  | 'Divine'
  | 'Ascended';

export interface BuildBattleWins {
  solo: number;
  teams: number;
  pro: number;
  gtb: number;
}

export interface WoolGamesPrivateGameConfig {
  one_hit_one_kill: boolean;
  rainbow_wool: 'Enabled' | 'Disabled';
  health_buff: string;
  game_speed: string;
  speed: string;
  no_class: 'Enabled' | 'Disabled';
  respawn_enable: boolean;
}

export interface PitArmor {
  helmet: PitInventoryItem | null;
  chestplate: PitInventoryItem | null;
  leggings: PitInventoryItem | null;
  boots: PitInventoryItem | null;
}

export type PlayerAchievementsTotemColors = 'blue' | 'purple' | 'overgrown' | 'yellow' | 'green' | 'steampunk' | 'red';
export type PlayerAchievementsTotemParts =
  | 'birdy'
  | 'happy'
  | 'arrow'
  | 'snake'
  | 'pong'
  | 'corner'
  | 'weird'
  | 'window'
  | 'grumpy'
  | 'grizzly'
  | 'sad'
  | 'connection'
  | 'cube'
  | 'cat';

export type PlayerRank =
  | null
  | 'VIP'
  | 'VIP+'
  | 'MVP'
  | 'MVP+'
  | 'MVP++'
  | 'Game Master'
  | 'Admin'
  | 'YouTube'
  | 'Events'
  | 'Mojang'
  | 'Owner'
  | 'PIG+++'
  | 'Innit';

export interface LevelProgress {
  level: number;
  totalXp: number;
  xpToNext: number;
  remainingXP: number;
  currentXP: number;
  percent: number;
  percentRemaining: number;
}

export type Language =
  | 'CHINESE_SIMPLIFIED'
  | 'CHINESE_TRADITIONAL'
  | 'CZECH'
  | 'DANISH'
  | 'DUTCH'
  | 'ENGLISH'
  | 'FINNISH'
  | 'FRENCH'
  | 'GERMAN'
  | 'GREEK'
  | 'HUNGARIAN'
  | 'ITALIAN'
  | 'JAPANESE'
  | 'KOREAN'
  | 'NORWEGIAN'
  | 'POLISH'
  | 'PORTUGUESE_BR'
  | 'PORTUGUESE_PT'
  | 'PIRATE'
  | 'ROMANIAN'
  | 'RUSSIAN'
  | 'SERBIAN_CYRILLIC'
  | 'SPANISH'
  | 'SWEDISH'
  | 'TURKISH'
  | 'UKRAINIAN';

export type PlayerCosmeticsPetName =
  | 'sheep_white'
  | 'pig'
  | 'mule'
  | 'black_rabbit'
  | 'sheep_blue_baby'
  | 'cat_black'
  | 'frozen_skeleton'
  | 'brown_horse_baby'
  | 'silverfish'
  | 'wolf'
  | 'sheep_magenta'
  | 'sheep_silver'
  | 'sheep_gray'
  | 'zombie_baby'
  | 'horse_grey'
  | 'sheep_brown'
  | 'cat_red_baby'
  | 'zombie'
  | 'chicken'
  | 'sheep_light_blue'
  | 'magma_cube_small'
  | 'cow'
  | 'chicken_baby'
  | 'magma_cube_big'
  | 'zombie_villager'
  | 'horse_black'
  | 'horse_dark_brown_baby'
  | 'cat_siamese'
  | 'horse_creamy'
  | 'horse_chestnut_baby'
  | 'horse_white'
  | 'cat_black_baby'
  | 'slime_big'
  | 'horse_brown'
  | 'pig_baby'
  | 'brown_rabbit'
  | 'horse_chestnut'
  | 'sheep_blue'
  | 'pig_zombie'
  | 'sheep_white_baby'
  | 'sheep_red_baby'
  | 'slime_small'
  | 'slime_tiny'
  | 'magma_cube_tiny'
  | 'totem'
  | 'sheep_red'
  | 'cat_siamese_baby'
  | 'cat_red'
  | 'wolf_baby'
  | 'pig_zombie_baby'
  | 'sheep_green'
  | 'sheep_black_baby'
  | 'sheep_yellow'
  | 'donkey'
  | 'mooshroom_baby'
  | 'mooshroom'
  | 'cow_baby'
  | 'spider_jockey'
  | 'villager_butcher'
  | 'villager_priest'
  | 'spider'
  | 'white_rabbit'
  | 'skeleton'
  | 'sheep_black'
  | 'sheep_yellow_baby'
  | 'villager_farmer'
  | 'enderman'
  | 'horse_undead'
  | 'gold_rabbit'
  | 'salt_pepper_rabbit'
  | 'black_white_rabbit'
  | 'villager_butcher_baby'
  | 'villager_priest_baby'
  | 'creeper'
  | 'villager_blacksmith_baby'
  | 'villager_blacksmith'
  | 'villager_farmer_baby'
  | 'villager_librarian'
  | 'villager_librarian_baby'
  | 'cave_spider'
  | 'horse_dark_brown'
  | 'bat'
  | 'horse_creamy_baby'
  | 'iron_golem'
  | 'creeper_powered'
  | 'fish'
  | 'frozen_zombie'
  | 'sheep_lime'
  | 'sheep_rainbow'
  | 'enderman_snow_block'
  | 'sheep_cyan'
  | 'sheep_purple'
  | 'herobrine'
  | 'sheep_pink_baby'
  | 'sheep_orange'
  | 'witch'
  | 'merry_sheep'
  | 'sheep_orange_baby'
  | 'clownfish'
  | 'sheep_silver_baby'
  | 'sheep_gray_baby'
  | 'rabbit_jockey'
  | 'endermite'
  | 'black_pug'
  | 'sheep_pink'
  | 'specter'
  | 'enderman_pumpkin'
  | 'snowman'
  | 'red_helper'
  | 'green_helper'
  | 'horse_gray_baby'
  | 'sheep_lime_baby'
  | 'white_pug'
  | 'sheep_magenta_baby'
  | 'sheep_cyan_baby'
  | 'growing_zombie'
  | 'bee'
  | 'smoldering_skeleton'
  | 'mini_wither'
  | 'zombie_villager_baby'
  | 'sheep_brown_baby'
  | 'sheep_purple_baby'
  | 'snowman_jockey'
  | 'sheep_light_blue_baby'
  | 'sheep_green_baby'
  | 'flying_squid'
  | 'bouncy_sheep'
  | 'little_you'
  | 'duck'
  | 'frog'
  | 'elephant'
  | 'panda'
  | 'gorrila'
  | 'chimp'
  | 'sloth'
  | 'horse_skeleton'
  | 'killer_rabbit'
  | 'enderman_hay_bale'
  | 'chicken_jockey'
  | 'burning_zombie'
  | 'bouncy_spider'
  | 'colorbox'
  | 'guardian'
  | 'hp8';

export type PlayerCosmeticsSuit =
  | 'mermaid_leggings'
  | 'bumblebee_boots'
  | 'spiderman_boots'
  | 'frog_chestplate'
  | 'baker_chestplate'
  | 'elf_leggings'
  | 'grinch_leggings'
  | 'elf_boots'
  | 'grinch_helmet'
  | 'plumber_boots'
  | 'chicken_chestplate'
  | 'chicken_helmet'
  | 'chicken_boots'
  | 'ghost_boots'
  | 'flash_boots'
  | 'warrior_boots'
  | 'ghost_leggings'
  | 'death_angel_boots'
  | 'arctic_leggings'
  | 'frog_leggings'
  | 'necromancer_leggings'
  | 'mermaid_boots'
  | 'baker_leggings'
  | 'baker_boots'
  | 'thor_boots'
  | 'necromancer_boots'
  | 'mermaid_chestplate'
  | 'warrior_leggings'
  | 'death_angel_leggings'
  | 'fireman_helmet'
  | 'arctic_boots'
  | 'ninja_boots'
  | 'dragon_breath_helmet'
  | 'pirate_boots'
  | 'necromancer_helmet'
  | 'solar_chestplate'
  | 'arctic_chestplate'
  | 'soccer_boots'
  | 'pirate_helmet'
  | 'wolf_leggings'
  | 'warrior_chestplate'
  | 'bumblebee_helmet'
  | 'frog_boots'
  | 'costume_helmet'
  | 'disco_leggings'
  | 'flash_helmet'
  | 'costume_boots'
  | 'vampire_boots'
  | 'costume_leggings'
  | 'costume_chestplate'
  | 'magma_boss_leggings'
  | 'headless_horseman_chestplate'
  | 'vampire_leggings'
  | 'skeleton_samurai_chestplate'
  | 'disco_boots'
  | 'flash_leggings'
  | 'plumber_leggings'
  | 'fireman_boots'
  | 'new_years_boots'
  | 'santa_boots'
  | 'disco_helmet'
  | 'new_years_leggings'
  | 'santa_chestplate'
  | 'thor_leggings'
  | 'mermaid_helmet'
  | 'ninja_helmet'
  | 'flash_chestplate'
  | 'baker_helmet'
  | 'spiderman_leggings'
  | 'plumber_chestplate'
  | 'ghost_chestplate'
  | 'thor_chestplate'
  | 'easter_egg_chestplate'
  | 'warrior_helmet'
  | 'bumblebee_leggings'
  | 'ninja_leggings'
  | 'yeti_leggings'
  | 'new_years_chestplate'
  | 'frog_helmet'
  | 'death_angel_helmet'
  | 'tnt_boots'
  | 'tnt_chestplate'
  | 'tnt_helmet'
  | 'tnt_leggings'
  | 'dragon_breath_chestplate'
  | 'dragon_breath_leggings'
  | 'dragon_breath_boots'
  | 'solar_boots'
  | 'solar_leggings'
  | 'solar_helmet'
  | 'elf_helmet'
  | 'elf_chestplate'
  | 'thor_helmet'
  | 'bumblebee_chestplate'
  | 'pumpkin_helmet'
  | 'skeleton_samurai_boots'
  | 'skeleton_samurai_helmet'
  | 'yeti_chestplate'
  | 'yeti_boots'
  | 'arctic_helmet'
  | 'grinch_boots'
  | 'disco_chestplate'
  | 'fireman_leggings'
  | 'easter_egg_boots'
  | 'easter_egg_leggings'
  | 'chicken_leggings'
  | 'headless_horseman_boots'
  | 'magma_boss_boots'
  | 'ghost_helmet'
  | 'necromancer_chestplate'
  | 'death_angel_chestplate'
  | 'plumber_helmet'
  | 'pirate_leggings'
  | 'ninja_chestplate'
  | 'spiderman_chestplate'
  | 'spiderman_helmet'
  | 'fireman_chestplate'
  | 'toy_chestplate'
  | 'toy_leggings'
  | 'santa_leggings'
  | 'grinch_chestplate'
  | 'soccer_helmet'
  | 'vampire_chestplate'
  | 'soccer_leggings'
  | 'wolf_helmet'
  | 'wolf_chestplate'
  | 'pumpkin_boots'
  | 'vampire_helmet'
  | 'toy_boots'
  | 'pirate_chestplate'
  | 'new_years_helmet'
  | 'easter_egg_helmet'
  | 'treasure_boots'
  | 'toy_helmet'
  | 'wolf_boots'
  | 'headless_horseman_helmet'
  | 'headless_horseman_leggings'
  | 'yeti_helmet'
  | 'soccer_chestplate'
  | 'pumpkin_chestplate'
  | 'treasure_helmet'
  | 'magma_boss_chestplate'
  | 'pumpkin_leggings'
  | 'santa_helmet'
  | 'magma_boss_helmet'
  | 'skeleton_samurai_leggings'
  | 'treasure_chestplate'
  | 'treasure_leggings'
  | 'phoenix_helmet';

export type PlayerCosmeticsHat =
  | 'bee'
  | 'number_5'
  | 'letter_r'
  | 'letter_g'
  | 'letter_plus'
  | 'clownfish'
  | 'earth'
  | 'letter_v'
  | 'festive_zombie'
  | 'festive_skeleton'
  | 'festive_villager'
  | 'festive_squid'
  | 'festive_herobrine'
  | 'rainbow_present'
  | 'wood_elf'
  | 'lady_bug'
  | 'number_1'
  | 'chick'
  | 'toaster'
  | 'letter_a'
  | 'koala'
  | 'beach_ball'
  | 'chocolate_egg'
  | 'golden_knight'
  | 'orc'
  | 'letter_x'
  | 'duckling'
  | 'bird'
  | 'burger'
  | 'cactus'
  | 'polar_bear'
  | 'ferret'
  | 'demon_knight'
  | 'mars'
  | 'letter_u'
  | 'letter_h'
  | 'letter_q'
  | 'letter_z'
  | 'letter_k'
  | 'letter_d'
  | 'letter_y'
  | 'letter_p'
  | 'letter_n'
  | 'groopo'
  | 'evil_eye'
  | 'aqua_orb'
  | 'letter_question'
  | 'fire_demon'
  | 'forester'
  | 'number_2'
  | 'vintage'
  | 'number_9'
  | 'letter_w'
  | 'panda'
  | 'broken_tv'
  | 'number_4'
  | 'squid'
  | 'elephant'
  | 'letter_o'
  | 'elf_princess'
  | 'letter_l'
  | 'letter_j'
  | 'cheese'
  | 'number_8'
  | 'owl'
  | 'assassin'
  | 'egyptian_queen'
  | 'halloween_pig_zombie'
  | 'halloween_skull'
  | 'mummy'
  | 'jason'
  | 'sloth'
  | 'letter_b'
  | 'duck'
  | 'rainbow_glitch'
  | 'number_3'
  | 'football_star'
  | 'letter_exclaimation'
  | 'miner'
  | 'letter_e'
  | 'dead_pirate'
  | 'frog'
  | 'egg_head'
  | 'ginger_bread'
  | 'elfgirl'
  | 'bell'
  | 'pug_black'
  | 'horse'
  | 'otter'
  | 'letter_s'
  | 'letter_hashtag'
  | 'number_7'
  | 'alien_slug'
  | 'skull_king_banner'
  | 'fox'
  | 'monkey'
  | 'number_6'
  | 'letter_t'
  | 'easter_egg'
  | 'snowglobe'
  | 'penguin'
  | 'snow_globe'
  | 'candy_cane'
  | 'present_hat'
  | 'grinch'
  | 'decoration_ball'
  | 'lucky_dragon'
  | 'monk'
  | 'sandwich'
  | 'monitor'
  | 'unlock_machine'
  | 'parrot'
  | 'golem'
  | 'snowball'
  | 'rabbit'
  | 'letter_i'
  | 'odin'
  | 'scavenger'
  | 'space'
  | 'mage'
  | 'astronaut'
  | 'wood_steve'
  | 'ender_dragon'
  | 'clown'
  | 'scarecrow2'
  | 'halloween_ghast'
  | 'walrus'
  | 'stone_steve'
  | 'gingerbread'
  | 'snowman'
  | 'white_wizard'
  | 'turtle'
  | 'cauldron'
  | 'elfboy'
  | 'letter_c'
  | 'dinosaur'
  | 'letter_f'
  | 'minotaur'
  | 'hp8'
  | 'number_0'
  | 'reindeer'
  | 'robo_bird'
  | 'pug_white'
  | 'basketball'
  | 'letter_m'
  | 'scarecrow'
  | 'hypixel_h'
  | 'magic_dog'
  | 'easter_basket'
  | 'bauble'
  | 'joe_penguin'
  | 'gingerbread_man'
  | 'ghost'
  | 'santa'
  | 'comet_reindeer'
  | 'siren'
  | 'halloween_marionette'
  | 'clown2'
  | 'doge'
  | 'werewolf'
  | 'stocking'
  | 'derpy_snowman'
  | 'halloween_evil_pumpkin'
  | 'crown'
  | 'gorilla'
  | 'shibe'
  | 'eater'
  | 'devourer'
  | 'pumpkin'
  | 'iron_steve'
  | 'traffic_light'
  | 'ice_mage'
  | 'spooked_pufferfish'
  | 'gold_steve';

export type PlayerCosmeticsGadget =
  | 'explosive_bow'
  | 'snowman'
  | 'holiday_tree'
  | 'advent_proof'
  | 'christmas_cracker'
  | 'exploding_sheep'
  | 'tree_planter'
  | 'flaming_egg_launcher'
  | 'bunny_party'
  | 'magic_carpet'
  | 'parachute'
  | 'paintball_gun'
  | 'fortune_cookie'
  | 'fire_trail'
  | 'rush_pearl'
  | 'rocket'
  | 'wizardwand'
  | 'jetpack'
  | 'horror_movie'
  | 'bbq_grill'
  | 'flower_giver'
  | 'tic_tac_toe'
  | 'paint_trail'
  | 'volleyball'
  | 'secret_service'
  | 'dice'
  | 'swarm'
  | 'party_popper'
  | 'tnt_fountain'
  | 'hype_train'
  | 'teleporter'
  | 'grappling_hook'
  | 'ghosts'
  | 'tetherball'
  | 'hot_potato'
  | 'radio'
  | 'rock_paper_shears'
  | 'meteorite'
  | 'disco_ball'
  | 'latte'
  | 'sled'
  | 'new_year_countdown'
  | 'tidal_wave'
  | 'pinata'
  | 'tennis_ball'
  | 'water_balloon'
  | 'creeper_astronaut'
  | 'poop_bomb'
  | 'rainbow'
  | 'chicken_cannon'
  | 'bat_launcher'
  | 'firework_launcher'
  | 'treat_fountain'
  | 'holiday_choir'
  | 'snow_globe'
  | 'flammable_grappling_hook'
  | 'cornucopia'
  | 'trampoline'
  | 'anniversary_trampoline'
  | 'diving_board'
  | 'dreidel'
  | 'let_snow'
  | 'pong'
  | 'giant_skeleton'
  | 'levitation_gun'
  | 'new_year'
  | 'swing'
  | 'pocket_beach'
  | 'trick_or_treat'
  | 'pumpkin_cannon'
  | 'duels_banner'
  | 'sand_castle'
  | 'scare_crow'
  | 'ice_skating'
  | 'ice_cream_stand'
  | 'anniversary_knight'
  | 'corrupted'
  | 'pumpkin_rain'
  | 'graveyard'
  | 'skywars_banner'
  | 'tournament_banner'
  | 'tournament_banner_grinch_simulator_0'
  | 'frisbee'
  | 'dj_booth'
  | 'witch_cauldron'
  | 'golden_chicken_statue';

export type PlayerCosmeticsMorph =
  | 'rabbit'
  | 'spider'
  | 'pig'
  | 'sheep'
  | 'chicken'
  | 'zombie'
  | 'creeper'
  | 'cow'
  | 'guardian'
  | 'iron_golem'
  | 'enderman'
  | 'skeleton'
  | 'wither_skeleton'
  | 'blaze'
  | 'snow_morph'
  | 'grinch'
  | 'cave_spider'
  | 'witch';

export type PlayerCosmeticsCloak =
  | 'monarch_wings'
  | 'easter_egg'
  | 'sweetwings'
  | 'scanner'
  | 'firewings'
  | 'rose'
  | 'clover'
  | 'achievement_points'
  | 'mystical'
  | 'downpour'
  | 'comets'
  | 'frozen_dragon_wings'
  | 'superhero'
  | 'bone_wings'
  | 'acid_rain'
  | 'dark_angel'
  | 'shimmering_wings'
  | 'shaman'
  | 'icy_wings'
  | 'frosty_cloak'
  | 'vampire_wings'
  | 'menorah'
  | 'rainy_day'
  | 'egg_scanner'
  | 'dark_energy'
  | 'storm'
  | 'blizzard'
  | 'snowball'
  | 'candy_cane'
  | 'spooky_wings'
  | 'twisted'
  | 'colorbox'
  | 'candy_spiral'
  | 'lovely';

export type PlayerCosmeticsTaunt =
  | 'goodbye'
  | 'hype_dance'
  | 'victory'
  | 'clapping'
  | 'wave_dance'
  | 'cool_dance'
  | 'hula'
  | 'mind'
  | 'jump'
  | 'snowball_toss'
  | 'can'
  | 'zombie_dance'
  | 'possessed'
  | 'hi_5'
  | 'sun'
  | 'karaoke'
  | 'graduation'
  | 'ballet'
  | 'treasure'
  | 'crab_dance';

export type PlayerCosmeticsRankColor =
  | 'gold'
  | 'green'
  | 'yellow'
  | 'light_purple'
  | 'white'
  | 'blue'
  | 'dark_green'
  | 'dark_red'
  | 'dark_aqua'
  | 'dark_purple'
  | 'dark_gray'
  | 'black';

export type PlayerCosmeticsParticlePack =
  | 'frozen'
  | 'spring'
  | 'huge_explosion'
  | 'snow_trail'
  | 'tinsel'
  | 'spooky'
  | 'red_dust'
  | 'splash';

export type PlayerCosmeticsClickEffects = 'skull' | 'blizzard' | 'easter_egg' | 'holiday_firework' | 'hypixel';
export type ChatChannel = 'ALL' | 'PARTY' | 'GUILD' | 'OFFICER' | 'PM' | 'SKYBLOCK_COOP';
