import TurboKartRacers from './TurboKartRacers.js';
import TurboKartRacersMap from './TurboKartRacersMap.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { TurboKartRacersHorn } from '../../../Types/Player.js';

test('TurboKartRacers', () => {
  const data = new TurboKartRacers({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data).toEqualTypeOf<TurboKartRacers>();
  expect(data.coins).toBeDefined();
  expect(data.coins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.coins).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.completedLaps).toBeDefined();
  expect(data.completedLaps).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.completedLaps).toEqualTypeOf<number>();
  expect(data.bronzeTrophies).toBeDefined();
  expect(data.bronzeTrophies).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bronzeTrophies).toEqualTypeOf<number>();
  expect(data.silverTrophies).toBeDefined();
  expect(data.silverTrophies).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.silverTrophies).toEqualTypeOf<number>();
  expect(data.goldTrophies).toBeDefined();
  expect(data.goldTrophies).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.goldTrophies).toEqualTypeOf<number>();
  expect(data.boxPickups).toBeDefined();
  expect(data.boxPickups).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.boxPickups).toEqualTypeOf<number>();
  expect(data.horn).toBeDefined();
  expectTypeOf(data.horn).toEqualTypeOf<TurboKartRacersHorn>();
  expect(data.retro).toBeDefined();
  expect(data.retro).toBeInstanceOf(TurboKartRacersMap);
  expectTypeOf(data.retro).toEqualTypeOf<TurboKartRacersMap>();
  expect(data.hypixelgp).toBeDefined();
  expect(data.hypixelgp).toBeInstanceOf(TurboKartRacersMap);
  expectTypeOf(data.hypixelgp).toEqualTypeOf<TurboKartRacersMap>();
  expect(data.olympus).toBeDefined();
  expect(data.olympus).toBeInstanceOf(TurboKartRacersMap);
  expectTypeOf(data.olympus).toEqualTypeOf<TurboKartRacersMap>();
  expect(data.junglerush).toBeDefined();
  expect(data.junglerush).toBeInstanceOf(TurboKartRacersMap);
  expectTypeOf(data.junglerush).toEqualTypeOf<TurboKartRacersMap>();
  expect(data.canyon).toBeDefined();
  expect(data.canyon).toBeInstanceOf(TurboKartRacersMap);
  expectTypeOf(data.canyon).toEqualTypeOf<TurboKartRacersMap>();
  expect(data.bananaHitsReceived).toBeDefined();
  expect(data.bananaHitsReceived).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bananaHitsReceived).toEqualTypeOf<number>();
  expect(data.bananaHitsSent).toBeDefined();
  expect(data.bananaHitsSent).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bananaHitsSent).toEqualTypeOf<number>();
  expect(data.blueTorpedoHit).toBeDefined();
  expect(data.blueTorpedoHit).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.blueTorpedoHit).toEqualTypeOf<number>();
  expect(data.grandPrix).toBeDefined();
  expectTypeOf(data.grandPrix).toEqualTypeOf<boolean>();
  expect(data.grandPrixTokens).toBeDefined();
  expect(data.grandPrixTokens).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.grandPrixTokens).toEqualTypeOf<number>();
});
