import Client from '../Client.js';
import Color from '../Structures/Color.js';
import Errors from '../Errors.js';
import Game from '../Structures/Game.js';
import Guild from '../Structures/Guild/Guild.js';
import GuildMember from '../Structures/Guild/GuildMember.js';
import GuildRank from '../Structures/Guild/GuildRank.js';
import RequestData from '../Private/RequestData.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { ColorCode, ColorHex, ColorString, InGameCode } from '../Types/Color.js';
import type { ExpHistory } from '../Types/Guild.js';
import type { GameCode, GameID, GameString } from '../Types/Game.js';

test('Invalid Guild Type', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL); // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  await expect(() => client.getGuild('invalid', 'invalid')).rejects.toThrowError(Errors.INVALID_GUILD_SEARCH_PARAMETER);
  client.destroy();
});

test('Invalid Guild', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  await expect(() => client.getGuild('name', 'this guild dose not exist')).rejects.toThrowError(
    Errors.GUILD_DOES_NOT_EXIST
  );
  client.destroy();
});

test('Invalid Guild ID', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  await expect(() => client.getGuild('id', 'invalid guild id')).rejects.toThrowError(Errors.INVALID_GUILD_ID);
  client.destroy();
});

test('No Guild Query', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL); // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  await expect(() => client.getGuild('id')).rejects.toThrowError(Errors.NO_GUILD_QUERY);
  client.destroy();
});

test('User not in a guild', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getGuild('player', '37501e7512b845ab8796e2baf9e9677a');
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<RequestData<Guild | null>>();
  client.destroy();
});

test('getGuild (Name)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getGuild('name', 'Pixelic');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Guild | null>>();
  if (data.parsed === null) return;
  expect(data.parsed.id).toBeDefined();
  expectTypeOf(data.parsed.id).toEqualTypeOf<string>();
  expect(data.parsed.name).toBeDefined();
  expectTypeOf(data.parsed.name).toEqualTypeOf<string>();
  expect(data.parsed.description).toBeDefined();
  expectTypeOf(data.parsed.description).toEqualTypeOf<string>();
  expect(data.parsed.experience).toBeDefined();
  expectTypeOf(data.parsed.experience).toEqualTypeOf<number>();
  expect(data.parsed.experience).toBeGreaterThanOrEqual(0);
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<number>();
  expect(data.parsed.members).toBeDefined();
  expectTypeOf(data.parsed.members).toEqualTypeOf<GuildMember[]>();
  data.parsed.members.forEach((member: GuildMember) => {
    expect(member).toBeDefined();
    expectTypeOf(member).toEqualTypeOf<GuildMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.joinedAtTimestamp).toBeDefined();
    expectTypeOf(member.joinedAtTimestamp).toEqualTypeOf<number | null>();
    expect(member.joinedAt).toBeDefined();
    expectTypeOf(member.joinedAt).toEqualTypeOf<Date | null>();
    expect(member.questParticipation).toBeDefined();
    expectTypeOf(member.questParticipation).toEqualTypeOf<number>();
    expect(member.rank).toBeDefined();
    expectTypeOf(member.rank).toEqualTypeOf<string>();
    expect(member.mutedUntilTimestamp).toBeDefined();
    expectTypeOf(member.mutedUntilTimestamp).toEqualTypeOf<number | null>();
    expect(member.mutedUntil).toBeDefined();
    expectTypeOf(member.mutedUntil).toEqualTypeOf<Date | null>();
    expect(member.expHistory).toBeDefined();
    expectTypeOf(member.expHistory).toEqualTypeOf<ExpHistory[]>();
    expect(member.weeklyExperience).toBeDefined();
    expectTypeOf(member.weeklyExperience).toEqualTypeOf<number>();
    expect(member.weeklyExperience).toBeGreaterThanOrEqual(0);
    expect(member.toString()).toBeDefined();
    expectTypeOf(member.toString()).toEqualTypeOf<string>();
    expect(member.toString()).toEqual(member.uuid);
  });
  expect(data.parsed.me).toBeDefined();
  expectTypeOf(data.parsed.me).toEqualTypeOf<GuildMember | null>();
  if (data.parsed.me !== null) {
    expect(data.parsed.me).toBeDefined();
    expectTypeOf(data.parsed.me).toEqualTypeOf<GuildMember>();
    expect(data.parsed.me.uuid).toBeDefined();
    expectTypeOf(data.parsed.me.uuid).toEqualTypeOf<string>();
    expect(data.parsed.me.joinedAtTimestamp).toBeDefined();
    expectTypeOf(data.parsed.me.joinedAtTimestamp).toEqualTypeOf<number | null>();
    expect(data.parsed.me.joinedAt).toBeDefined();
    expectTypeOf(data.parsed.me.joinedAt).toEqualTypeOf<Date | null>();
    expect(data.parsed.me.questParticipation).toBeDefined();
    expectTypeOf(data.parsed.me.questParticipation).toEqualTypeOf<number>();
    expect(data.parsed.me.rank).toBeDefined();
    expectTypeOf(data.parsed.me.rank).toEqualTypeOf<string>();
    expect(data.parsed.me.mutedUntilTimestamp).toBeDefined();
    expectTypeOf(data.parsed.me.mutedUntilTimestamp).toEqualTypeOf<number | null>();
    expect(data.parsed.me.mutedUntil).toBeDefined();
    expectTypeOf(data.parsed.me.mutedUntil).toEqualTypeOf<Date | null>();
    expect(data.parsed.me.expHistory).toBeDefined();
    expectTypeOf(data.parsed.me.expHistory).toEqualTypeOf<ExpHistory[]>();
    expect(data.parsed.me.weeklyExperience).toBeDefined();
    expectTypeOf(data.parsed.me.weeklyExperience).toEqualTypeOf<number>();
    expect(data.parsed.me.weeklyExperience).toBeGreaterThanOrEqual(0);
    expect(data.parsed.me.toString()).toBeDefined();
    expectTypeOf(data.parsed.me.toString()).toEqualTypeOf<string>();
    expect(data.parsed.me.toString()).toEqual(data.parsed.me.uuid);
  }
  expect(data.parsed.ranks).toBeDefined();
  expectTypeOf(data.parsed.ranks).toEqualTypeOf<GuildRank[]>();
  data.parsed.ranks.forEach((rank: GuildRank) => {
    expect(rank).toBeDefined();
    expect(rank).toBeInstanceOf(GuildRank);
    expectTypeOf(rank).toEqualTypeOf<GuildRank>();
    expect(rank.name).toBeDefined();
    expectTypeOf(rank.name).toEqualTypeOf<string>();
    expect(rank.default).toBeDefined();
    expectTypeOf(rank.default).toEqualTypeOf<boolean>();
    expect(rank.tag).toBeDefined();
    expectTypeOf(rank.tag).toEqualTypeOf<string | null>();
    expect(rank.createdAtTimestamp).toBeDefined();
    expectTypeOf(rank.createdAtTimestamp).toEqualTypeOf<number | null>();
    expect(rank.createdAt).toBeDefined();
    expectTypeOf(rank.createdAt).toEqualTypeOf<Date | null>();
    expect(rank.priority).toBeDefined();
    expectTypeOf(rank.priority).toEqualTypeOf<number>();
    expect(rank.toString()).toBeDefined();
    expectTypeOf(rank.toString()).toEqualTypeOf<string>();
    expect(rank.toString()).toEqual(rank.name);
  });
  expect(data.parsed.totalWeeklyGEXP).toBeDefined();
  expectTypeOf(data.parsed.totalWeeklyGEXP).toEqualTypeOf<number>();
  expect(data.parsed.createdAtTimestamp).toBeDefined();
  expectTypeOf(data.parsed.createdAtTimestamp).toEqualTypeOf<number | null>();
  expect(data.parsed.createdAt).toBeDefined();
  expectTypeOf(data.parsed.createdAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.joinable).toBeDefined();
  expectTypeOf(data.parsed.joinable).toEqualTypeOf<boolean>();
  expect(data.parsed.publiclyListed).toBeDefined();
  expectTypeOf(data.parsed.publiclyListed).toEqualTypeOf<boolean>();
  expect(data.parsed.chatMuteUntilTimestamp).toBeDefined();
  expectTypeOf(data.parsed.chatMuteUntilTimestamp).toEqualTypeOf<number | null>();
  expect(data.parsed.chatMuteUntil).toBeDefined();
  expectTypeOf(data.parsed.chatMuteUntil).toEqualTypeOf<Date | null>();
  expect(data.parsed.banner).toBeDefined();
  expectTypeOf(data.parsed.banner).toEqualTypeOf<{ Pattern: string; Color: string }[]>();
  expect(data.parsed.tag).toBeDefined();
  expectTypeOf(data.parsed.tag).toEqualTypeOf<string>();
  expect(data.parsed.tagColor).toBeDefined();
  expectTypeOf(data.parsed.tagColor).toEqualTypeOf<Color | null>();
  if (data.parsed.tagColor) {
    expect(data.parsed.tagColor).toBeDefined();
    expectTypeOf(data.parsed.tagColor).toEqualTypeOf<Color>();
    expect(data.parsed.tagColor.color).toBeDefined();
    expectTypeOf(data.parsed.tagColor.color).toEqualTypeOf<ColorCode>();
    expect(data.parsed.tagColor.toString).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toString).toEqualTypeOf<() => ColorString>();
    expect(data.parsed.tagColor.toString()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toString()).toEqualTypeOf<ColorString>();
    expect(data.parsed.tagColor.toHex).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toHex).toEqualTypeOf<() => ColorHex>();
    expect(data.parsed.tagColor.toHex()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toHex()).toEqualTypeOf<ColorHex>();
    expect(data.parsed.tagColor.toCode).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toCode).toEqualTypeOf<() => ColorCode>();
    expect(data.parsed.tagColor.toCode()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toCode()).toEqualTypeOf<ColorCode>();
    expect(data.parsed.tagColor.toInGameCode).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toInGameCode).toEqualTypeOf<() => InGameCode>();
    expect(data.parsed.tagColor.toInGameCode()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toInGameCode()).toEqualTypeOf<InGameCode>();
  }
  expect(data.parsed.expHistory).toBeDefined();
  expectTypeOf(data.parsed.expHistory).toEqualTypeOf<ExpHistory[]>();
  expect(data.parsed.achievements).toBeDefined();
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<{
    winners: number;
    experienceKings: number;
    onlinePlayers: number;
  }>();
  expect(data.parsed.achievements.winners).toBeDefined();
  expectTypeOf(data.parsed.achievements.winners).toEqualTypeOf<number>();
  expect(data.parsed.achievements.winners).toBeGreaterThanOrEqual(0);
  expect(data.parsed.achievements.experienceKings).toBeDefined();
  expectTypeOf(data.parsed.achievements.experienceKings).toEqualTypeOf<number>();
  expect(data.parsed.achievements.experienceKings).toBeGreaterThanOrEqual(0);
  expect(data.parsed.preferredGames).toBeDefined();
  expectTypeOf(data.parsed.preferredGames).toEqualTypeOf<Game[]>();
  data.parsed.preferredGames.forEach((game: Game) => {
    expect(game).toBeDefined();
    expectTypeOf(game).toEqualTypeOf<Game>();
    expect(game.game).toBeDefined();
    expectTypeOf(game.game).toEqualTypeOf<GameID | GameCode>();
    expect(game.id).toBeDefined();
    expectTypeOf(game.id).toEqualTypeOf<GameID | null>();
    expect(game.code).toBeDefined();
    expectTypeOf(game.code).toEqualTypeOf<GameCode | null>();
    expect(game.name).toBeDefined();
    expectTypeOf(game.name).toEqualTypeOf<GameString | null>();
    expect(game.found).toBeDefined();
    expectTypeOf(game.found).toEqualTypeOf<boolean>();
    expect(game.toString()).toBeDefined();
    expect(game.toString()).toBe(game.name);
    expectTypeOf(game.toString()).toEqualTypeOf<GameString | null>();
    expect(Game.IDS).toBeDefined();
    expectTypeOf(Game.IDS).toEqualTypeOf<GameID[]>();
    expect(Game.CODES).toBeDefined();
    expectTypeOf(Game.CODES).toEqualTypeOf<GameCode[]>();
    expect(Game.NAMES).toBeDefined();
    expectTypeOf(Game.NAMES).toEqualTypeOf<GameString[]>();
  });
  expect(data.parsed.toString()).toBeDefined();
  expectTypeOf(data.parsed.toString()).toEqualTypeOf<string>();
  client.destroy();
});

test('getGuild (Id)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getGuild('id', '64b54f9d8ea8c96aaedafe84');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Guild | null>>();
  if (data.parsed === null) return;
  expect(data.parsed.id).toBeDefined();
  expectTypeOf(data.parsed.id).toEqualTypeOf<string>();
  expect(data.parsed.name).toBeDefined();
  expectTypeOf(data.parsed.name).toEqualTypeOf<string>();
  expect(data.parsed.description).toBeDefined();
  expectTypeOf(data.parsed.description).toEqualTypeOf<string>();
  expect(data.parsed.experience).toBeDefined();
  expectTypeOf(data.parsed.experience).toEqualTypeOf<number>();
  expect(data.parsed.experience).toBeGreaterThanOrEqual(0);
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<number>();
  expect(data.parsed.members).toBeDefined();
  expectTypeOf(data.parsed.members).toEqualTypeOf<GuildMember[]>();
  data.parsed.members.forEach((member: GuildMember) => {
    expect(member).toBeDefined();
    expectTypeOf(member).toEqualTypeOf<GuildMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.joinedAtTimestamp).toBeDefined();
    expectTypeOf(member.joinedAtTimestamp).toEqualTypeOf<number | null>();
    expect(member.joinedAt).toBeDefined();
    expectTypeOf(member.joinedAt).toEqualTypeOf<Date | null>();
    expect(member.questParticipation).toBeDefined();
    expectTypeOf(member.questParticipation).toEqualTypeOf<number>();
    expect(member.rank).toBeDefined();
    expectTypeOf(member.rank).toEqualTypeOf<string>();
    expect(member.mutedUntilTimestamp).toBeDefined();
    expectTypeOf(member.mutedUntilTimestamp).toEqualTypeOf<number | null>();
    expect(member.mutedUntil).toBeDefined();
    expectTypeOf(member.mutedUntil).toEqualTypeOf<Date | null>();
    expect(member.expHistory).toBeDefined();
    expectTypeOf(member.expHistory).toEqualTypeOf<ExpHistory[]>();
    expect(member.weeklyExperience).toBeDefined();
    expectTypeOf(member.weeklyExperience).toEqualTypeOf<number>();
    expect(member.weeklyExperience).toBeGreaterThanOrEqual(0);
    expect(member.toString()).toBeDefined();
    expectTypeOf(member.toString()).toEqualTypeOf<string>();
    expect(member.toString()).toEqual(member.uuid);
  });
  expect(data.parsed.me).toBeDefined();
  expectTypeOf(data.parsed.me).toEqualTypeOf<GuildMember | null>();
  if (data.parsed.me !== null) {
    expect(data.parsed.me).toBeDefined();
    expectTypeOf(data.parsed.me).toEqualTypeOf<GuildMember>();
    expect(data.parsed.me.uuid).toBeDefined();
    expectTypeOf(data.parsed.me.uuid).toEqualTypeOf<string>();
    expect(data.parsed.me.joinedAtTimestamp).toBeDefined();
    expectTypeOf(data.parsed.me.joinedAtTimestamp).toEqualTypeOf<number | null>();
    expect(data.parsed.me.joinedAt).toBeDefined();
    expectTypeOf(data.parsed.me.joinedAt).toEqualTypeOf<Date | null>();
    expect(data.parsed.me.questParticipation).toBeDefined();
    expectTypeOf(data.parsed.me.questParticipation).toEqualTypeOf<number>();
    expect(data.parsed.me.rank).toBeDefined();
    expectTypeOf(data.parsed.me.rank).toEqualTypeOf<string>();
    expect(data.parsed.me.mutedUntilTimestamp).toBeDefined();
    expectTypeOf(data.parsed.me.mutedUntilTimestamp).toEqualTypeOf<number | null>();
    expect(data.parsed.me.mutedUntil).toBeDefined();
    expectTypeOf(data.parsed.me.mutedUntil).toEqualTypeOf<Date | null>();
    expect(data.parsed.me.expHistory).toBeDefined();
    expectTypeOf(data.parsed.me.expHistory).toEqualTypeOf<ExpHistory[]>();
    expect(data.parsed.me.weeklyExperience).toBeDefined();
    expectTypeOf(data.parsed.me.weeklyExperience).toEqualTypeOf<number>();
    expect(data.parsed.me.weeklyExperience).toBeGreaterThanOrEqual(0);
    expect(data.parsed.me.toString()).toBeDefined();
    expectTypeOf(data.parsed.me.toString()).toEqualTypeOf<string>();
    expect(data.parsed.me.toString()).toEqual(data.parsed.me.uuid);
  }
  expect(data.parsed.ranks).toBeDefined();
  expectTypeOf(data.parsed.ranks).toEqualTypeOf<GuildRank[]>();
  data.parsed.ranks.forEach((rank: GuildRank) => {
    expect(rank).toBeDefined();
    expect(rank).toBeInstanceOf(GuildRank);
    expectTypeOf(rank).toEqualTypeOf<GuildRank>();
    expect(rank.name).toBeDefined();
    expectTypeOf(rank.name).toEqualTypeOf<string>();
    expect(rank.default).toBeDefined();
    expectTypeOf(rank.default).toEqualTypeOf<boolean>();
    expect(rank.tag).toBeDefined();
    expectTypeOf(rank.tag).toEqualTypeOf<string | null>();
    expect(rank.createdAtTimestamp).toBeDefined();
    expectTypeOf(rank.createdAtTimestamp).toEqualTypeOf<number | null>();
    expect(rank.createdAt).toBeDefined();
    expectTypeOf(rank.createdAt).toEqualTypeOf<Date | null>();
    expect(rank.priority).toBeDefined();
    expectTypeOf(rank.priority).toEqualTypeOf<number>();
    expect(rank.toString()).toBeDefined();
    expectTypeOf(rank.toString()).toEqualTypeOf<string>();
    expect(rank.toString()).toEqual(rank.name);
  });
  expect(data.parsed.totalWeeklyGEXP).toBeDefined();
  expectTypeOf(data.parsed.totalWeeklyGEXP).toEqualTypeOf<number>();
  expect(data.parsed.createdAtTimestamp).toBeDefined();
  expectTypeOf(data.parsed.createdAtTimestamp).toEqualTypeOf<number | null>();
  expect(data.parsed.createdAt).toBeDefined();
  expectTypeOf(data.parsed.createdAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.joinable).toBeDefined();
  expectTypeOf(data.parsed.joinable).toEqualTypeOf<boolean>();
  expect(data.parsed.publiclyListed).toBeDefined();
  expectTypeOf(data.parsed.publiclyListed).toEqualTypeOf<boolean>();
  expect(data.parsed.chatMuteUntilTimestamp).toBeDefined();
  expectTypeOf(data.parsed.chatMuteUntilTimestamp).toEqualTypeOf<number | null>();
  expect(data.parsed.chatMuteUntil).toBeDefined();
  expectTypeOf(data.parsed.chatMuteUntil).toEqualTypeOf<Date | null>();
  expect(data.parsed.banner).toBeDefined();
  expectTypeOf(data.parsed.banner).toEqualTypeOf<{ Pattern: string; Color: string }[]>();
  expect(data.parsed.tag).toBeDefined();
  expectTypeOf(data.parsed.tag).toEqualTypeOf<string>();
  expect(data.parsed.tagColor).toBeDefined();
  expectTypeOf(data.parsed.tagColor).toEqualTypeOf<Color | null>();
  if (data.parsed.tagColor) {
    expect(data.parsed.tagColor).toBeDefined();
    expectTypeOf(data.parsed.tagColor).toEqualTypeOf<Color>();
    expect(data.parsed.tagColor.color).toBeDefined();
    expectTypeOf(data.parsed.tagColor.color).toEqualTypeOf<ColorCode>();
    expect(data.parsed.tagColor.toString).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toString).toEqualTypeOf<() => ColorString>();
    expect(data.parsed.tagColor.toString()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toString()).toEqualTypeOf<ColorString>();
    expect(data.parsed.tagColor.toHex).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toHex).toEqualTypeOf<() => ColorHex>();
    expect(data.parsed.tagColor.toHex()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toHex()).toEqualTypeOf<ColorHex>();
    expect(data.parsed.tagColor.toCode).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toCode).toEqualTypeOf<() => ColorCode>();
    expect(data.parsed.tagColor.toCode()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toCode()).toEqualTypeOf<ColorCode>();
    expect(data.parsed.tagColor.toInGameCode).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toInGameCode).toEqualTypeOf<() => InGameCode>();
    expect(data.parsed.tagColor.toInGameCode()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toInGameCode()).toEqualTypeOf<InGameCode>();
  }
  expect(data.parsed.expHistory).toBeDefined();
  expectTypeOf(data.parsed.expHistory).toEqualTypeOf<ExpHistory[]>();
  expect(data.parsed.achievements).toBeDefined();
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<{
    winners: number;
    experienceKings: number;
    onlinePlayers: number;
  }>();
  expect(data.parsed.achievements.winners).toBeDefined();
  expectTypeOf(data.parsed.achievements.winners).toEqualTypeOf<number>();
  expect(data.parsed.achievements.winners).toBeGreaterThanOrEqual(0);
  expect(data.parsed.achievements.experienceKings).toBeDefined();
  expectTypeOf(data.parsed.achievements.experienceKings).toEqualTypeOf<number>();
  expect(data.parsed.achievements.experienceKings).toBeGreaterThanOrEqual(0);
  expect(data.parsed.preferredGames).toBeDefined();
  expectTypeOf(data.parsed.preferredGames).toEqualTypeOf<Game[]>();
  data.parsed.preferredGames.forEach((game: Game) => {
    expect(game).toBeDefined();
    expectTypeOf(game).toEqualTypeOf<Game>();
    expect(game.game).toBeDefined();
    expectTypeOf(game.game).toEqualTypeOf<GameID | GameCode>();
    expect(game.id).toBeDefined();
    expectTypeOf(game.id).toEqualTypeOf<GameID | null>();
    expect(game.code).toBeDefined();
    expectTypeOf(game.code).toEqualTypeOf<GameCode | null>();
    expect(game.name).toBeDefined();
    expectTypeOf(game.name).toEqualTypeOf<GameString | null>();
    expect(game.found).toBeDefined();
    expectTypeOf(game.found).toEqualTypeOf<boolean>();
    expect(game.toString()).toBeDefined();
    expect(game.toString()).toBe(game.name);
    expectTypeOf(game.toString()).toEqualTypeOf<GameString | null>();
    expect(Game.IDS).toBeDefined();
    expectTypeOf(Game.IDS).toEqualTypeOf<GameID[]>();
    expect(Game.CODES).toBeDefined();
    expectTypeOf(Game.CODES).toEqualTypeOf<GameCode[]>();
    expect(Game.NAMES).toBeDefined();
    expectTypeOf(Game.NAMES).toEqualTypeOf<GameString[]>();
  });
  expect(data.parsed.toString()).toBeDefined();
  expectTypeOf(data.parsed.toString()).toEqualTypeOf<string>();
  client.destroy();
});

test('getGuild (Player)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getGuild('player', '14727faefbdc4aff848cd2713eb9939e');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Guild | null>>();
  if (data.parsed === null) return;
  expect(data.parsed.id).toBeDefined();
  expectTypeOf(data.parsed.id).toEqualTypeOf<string>();
  expect(data.parsed.name).toBeDefined();
  expectTypeOf(data.parsed.name).toEqualTypeOf<string>();
  expect(data.parsed.description).toBeDefined();
  expectTypeOf(data.parsed.description).toEqualTypeOf<string>();
  expect(data.parsed.experience).toBeDefined();
  expectTypeOf(data.parsed.experience).toEqualTypeOf<number>();
  expect(data.parsed.experience).toBeGreaterThanOrEqual(0);
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<number>();
  expect(data.parsed.members).toBeDefined();
  expectTypeOf(data.parsed.members).toEqualTypeOf<GuildMember[]>();
  data.parsed.members.forEach((member: GuildMember) => {
    expect(member).toBeDefined();
    expectTypeOf(member).toEqualTypeOf<GuildMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.joinedAtTimestamp).toBeDefined();
    expectTypeOf(member.joinedAtTimestamp).toEqualTypeOf<number | null>();
    expect(member.joinedAt).toBeDefined();
    expectTypeOf(member.joinedAt).toEqualTypeOf<Date | null>();
    expect(member.questParticipation).toBeDefined();
    expectTypeOf(member.questParticipation).toEqualTypeOf<number>();
    expect(member.rank).toBeDefined();
    expectTypeOf(member.rank).toEqualTypeOf<string>();
    expect(member.mutedUntilTimestamp).toBeDefined();
    expectTypeOf(member.mutedUntilTimestamp).toEqualTypeOf<number | null>();
    expect(member.mutedUntil).toBeDefined();
    expectTypeOf(member.mutedUntil).toEqualTypeOf<Date | null>();
    expect(member.expHistory).toBeDefined();
    expectTypeOf(member.expHistory).toEqualTypeOf<ExpHistory[]>();
    expect(member.weeklyExperience).toBeDefined();
    expectTypeOf(member.weeklyExperience).toEqualTypeOf<number>();
    expect(member.weeklyExperience).toBeGreaterThanOrEqual(0);
    expect(member.toString()).toBeDefined();
    expectTypeOf(member.toString()).toEqualTypeOf<string>();
    expect(member.toString()).toEqual(member.uuid);
  });
  expect(data.parsed.me).toBeDefined();
  expectTypeOf(data.parsed.me).toEqualTypeOf<GuildMember | null>();
  if (data.parsed.me !== null) {
    expect(data.parsed.me).toBeDefined();
    expectTypeOf(data.parsed.me).toEqualTypeOf<GuildMember>();
    expect(data.parsed.me.uuid).toBeDefined();
    expectTypeOf(data.parsed.me.uuid).toEqualTypeOf<string>();
    expect(data.parsed.me.joinedAtTimestamp).toBeDefined();
    expectTypeOf(data.parsed.me.joinedAtTimestamp).toEqualTypeOf<number | null>();
    expect(data.parsed.me.joinedAt).toBeDefined();
    expectTypeOf(data.parsed.me.joinedAt).toEqualTypeOf<Date | null>();
    expect(data.parsed.me.questParticipation).toBeDefined();
    expectTypeOf(data.parsed.me.questParticipation).toEqualTypeOf<number>();
    expect(data.parsed.me.rank).toBeDefined();
    expectTypeOf(data.parsed.me.rank).toEqualTypeOf<string>();
    expect(data.parsed.me.mutedUntilTimestamp).toBeDefined();
    expectTypeOf(data.parsed.me.mutedUntilTimestamp).toEqualTypeOf<number | null>();
    expect(data.parsed.me.mutedUntil).toBeDefined();
    expectTypeOf(data.parsed.me.mutedUntil).toEqualTypeOf<Date | null>();
    expect(data.parsed.me.expHistory).toBeDefined();
    expectTypeOf(data.parsed.me.expHistory).toEqualTypeOf<ExpHistory[]>();
    expect(data.parsed.me.weeklyExperience).toBeDefined();
    expectTypeOf(data.parsed.me.weeklyExperience).toEqualTypeOf<number>();
    expect(data.parsed.me.weeklyExperience).toBeGreaterThanOrEqual(0);
    expect(data.parsed.me.toString()).toBeDefined();
    expectTypeOf(data.parsed.me.toString()).toEqualTypeOf<string>();
    expect(data.parsed.me.toString()).toEqual(data.parsed.me.uuid);
  }
  expect(data.parsed.ranks).toBeDefined();
  expectTypeOf(data.parsed.ranks).toEqualTypeOf<GuildRank[]>();
  data.parsed.ranks.forEach((rank: GuildRank) => {
    expect(rank).toBeDefined();
    expect(rank).toBeInstanceOf(GuildRank);
    expectTypeOf(rank).toEqualTypeOf<GuildRank>();
    expect(rank.name).toBeDefined();
    expectTypeOf(rank.name).toEqualTypeOf<string>();
    expect(rank.default).toBeDefined();
    expectTypeOf(rank.default).toEqualTypeOf<boolean>();
    expect(rank.tag).toBeDefined();
    expectTypeOf(rank.tag).toEqualTypeOf<string | null>();
    expect(rank.createdAtTimestamp).toBeDefined();
    expectTypeOf(rank.createdAtTimestamp).toEqualTypeOf<number | null>();
    expect(rank.createdAt).toBeDefined();
    expectTypeOf(rank.createdAt).toEqualTypeOf<Date | null>();
    expect(rank.priority).toBeDefined();
    expectTypeOf(rank.priority).toEqualTypeOf<number>();
    expect(rank.toString()).toBeDefined();
    expectTypeOf(rank.toString()).toEqualTypeOf<string>();
    expect(rank.toString()).toEqual(rank.name);
  });
  expect(data.parsed.totalWeeklyGEXP).toBeDefined();
  expectTypeOf(data.parsed.totalWeeklyGEXP).toEqualTypeOf<number>();
  expect(data.parsed.createdAtTimestamp).toBeDefined();
  expectTypeOf(data.parsed.createdAtTimestamp).toEqualTypeOf<number | null>();
  expect(data.parsed.createdAt).toBeDefined();
  expectTypeOf(data.parsed.createdAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.joinable).toBeDefined();
  expectTypeOf(data.parsed.joinable).toEqualTypeOf<boolean>();
  expect(data.parsed.publiclyListed).toBeDefined();
  expectTypeOf(data.parsed.publiclyListed).toEqualTypeOf<boolean>();
  expect(data.parsed.chatMuteUntilTimestamp).toBeDefined();
  expectTypeOf(data.parsed.chatMuteUntilTimestamp).toEqualTypeOf<number | null>();
  expect(data.parsed.chatMuteUntil).toBeDefined();
  expectTypeOf(data.parsed.chatMuteUntil).toEqualTypeOf<Date | null>();
  expect(data.parsed.banner).toBeDefined();
  expectTypeOf(data.parsed.banner).toEqualTypeOf<{ Pattern: string; Color: string }[]>();
  expect(data.parsed.tag).toBeDefined();
  expectTypeOf(data.parsed.tag).toEqualTypeOf<string>();
  expect(data.parsed.tagColor).toBeDefined();
  expectTypeOf(data.parsed.tagColor).toEqualTypeOf<Color | null>();
  if (data.parsed.tagColor) {
    expect(data.parsed.tagColor).toBeDefined();
    expectTypeOf(data.parsed.tagColor).toEqualTypeOf<Color>();
    expect(data.parsed.tagColor.color).toBeDefined();
    expectTypeOf(data.parsed.tagColor.color).toEqualTypeOf<ColorCode>();
    expect(data.parsed.tagColor.toString).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toString).toEqualTypeOf<() => ColorString>();
    expect(data.parsed.tagColor.toString()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toString()).toEqualTypeOf<ColorString>();
    expect(data.parsed.tagColor.toHex).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toHex).toEqualTypeOf<() => ColorHex>();
    expect(data.parsed.tagColor.toHex()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toHex()).toEqualTypeOf<ColorHex>();
    expect(data.parsed.tagColor.toCode).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toCode).toEqualTypeOf<() => ColorCode>();
    expect(data.parsed.tagColor.toCode()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toCode()).toEqualTypeOf<ColorCode>();
    expect(data.parsed.tagColor.toInGameCode).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toInGameCode).toEqualTypeOf<() => InGameCode>();
    expect(data.parsed.tagColor.toInGameCode()).toBeDefined();
    expectTypeOf(data.parsed.tagColor.toInGameCode()).toEqualTypeOf<InGameCode>();
  }
  expect(data.parsed.expHistory).toBeDefined();
  expectTypeOf(data.parsed.expHistory).toEqualTypeOf<ExpHistory[]>();
  expect(data.parsed.achievements).toBeDefined();
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<{
    winners: number;
    experienceKings: number;
    onlinePlayers: number;
  }>();
  expect(data.parsed.achievements.winners).toBeDefined();
  expectTypeOf(data.parsed.achievements.winners).toEqualTypeOf<number>();
  expect(data.parsed.achievements.winners).toBeGreaterThanOrEqual(0);
  expect(data.parsed.achievements.experienceKings).toBeDefined();
  expectTypeOf(data.parsed.achievements.experienceKings).toEqualTypeOf<number>();
  expect(data.parsed.achievements.experienceKings).toBeGreaterThanOrEqual(0);
  expect(data.parsed.preferredGames).toBeDefined();
  expectTypeOf(data.parsed.preferredGames).toEqualTypeOf<Game[]>();
  data.parsed.preferredGames.forEach((game: Game) => {
    expect(game).toBeDefined();
    expectTypeOf(game).toEqualTypeOf<Game>();
    expect(game.game).toBeDefined();
    expectTypeOf(game.game).toEqualTypeOf<GameID | GameCode>();
    expect(game.id).toBeDefined();
    expectTypeOf(game.id).toEqualTypeOf<GameID | null>();
    expect(game.code).toBeDefined();
    expectTypeOf(game.code).toEqualTypeOf<GameCode | null>();
    expect(game.name).toBeDefined();
    expectTypeOf(game.name).toEqualTypeOf<GameString | null>();
    expect(game.found).toBeDefined();
    expectTypeOf(game.found).toEqualTypeOf<boolean>();
    expect(game.toString()).toBeDefined();
    expect(game.toString()).toBe(game.name);
    expectTypeOf(game.toString()).toEqualTypeOf<GameString | null>();
    expect(Game.IDS).toBeDefined();
    expectTypeOf(Game.IDS).toEqualTypeOf<GameID[]>();
    expect(Game.CODES).toBeDefined();
    expectTypeOf(Game.CODES).toEqualTypeOf<GameCode[]>();
    expect(Game.NAMES).toBeDefined();
    expectTypeOf(Game.NAMES).toEqualTypeOf<GameString[]>();
  });
  expect(data.parsed.toString()).toBeDefined();
  expectTypeOf(data.parsed.toString()).toEqualTypeOf<string>();
  client.destroy();
});
