import Client from '../Client.js';
import Errors from '../Errors.js';
import Guild from '../Structures/Guild/Guild.js';
import House from '../Structures/House.js';
import Player from '../Structures/Player/Player.js';
import PlayerAchievements from '../Structures/Player/PlayerAchievements/PlayerAchievements.js';
import PlayerAdventRewards from '../Structures/Player/PlayerAdventRewards/PlayerAdventRewards.js';
import PlayerCosmetics from '../Structures/Player/PlayerCosmetics/PlayerCosmetics.js';
import PlayerGifting from '../Structures/Player/PlayerGifting.js';
import PlayerHousing from '../Structures/Player/PlayerHousing/PlayerHousing.js';
import PlayerParkour from '../Structures/Player/PlayerParkour.js';
import PlayerQuests from '../Structures/Player/PlayerQuests/PlayerQuests.js';
import PlayerRankPurchase from '../Structures/Player/PlayerRankPurchase.js';
import PlayerRewards from '../Structures/Player/PlayerRewards/PlayerRewards.js';
import PlayerScorpiusBribe from '../Structures/Player/PlayerScorpiusBribe.js';
import PlayerSocialMedia from '../Structures/Player/PlayerSocialMedia.js';
import PlayerStats from '../Structures/Player/PlayerStats.js';
import RecentGame from '../Structures/RecentGame.js';
import RequestData from '../Private/RequestData.js';
import { defaultRequestData } from '../../vitest.setup.js';
import { expect, expectTypeOf, test, vi } from 'vitest';
import type { ChatChannel, Language, LevelProgress, PlayerRank } from '../Types/Player.js';

test('getPlayer (never joined hypixel)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  vi.spyOn(global, 'fetch').mockResolvedValue({
    ...defaultRequestData,
    json: () => Promise.resolve({ success: true })
  } as any);

  await expect(() => client.getPlayer('14727faefbdc4aff848cd2713eb9939e')).rejects.toThrowError(
    Errors.PLAYER_HAS_NEVER_LOGGED
  );
  vi.restoreAllMocks();
  client.destroy();
});

test('getPlayer (no input)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  await expect(() => client.getPlayer()).rejects.toThrowError(Errors.NO_NICKNAME_UUID);
  client.destroy();
});

test('getPlayer (guild)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getPlayer('28667672039044989b0019b14a2c34d6', { guild: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Player>>();
  expect(data.parsed.nickname).toBeDefined();
  expectTypeOf(data.parsed.nickname).toEqualTypeOf<string>();
  expect(data.parsed.uuid).toBeDefined();
  expectTypeOf(data.parsed.uuid).toEqualTypeOf<string>();
  expect(data.parsed.rank).toBeDefined();
  expectTypeOf(data.parsed.rank).toEqualTypeOf<PlayerRank>();
  expect(data.parsed.firstLoginAt).toBeDefined();
  expectTypeOf(data.parsed.firstLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLoginAt).toBeDefined();
  expectTypeOf(data.parsed.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLogoutAt).toBeDefined();
  expectTypeOf(data.parsed.lastLogoutAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.achievements).toBeDefined();
  expect(data.parsed.achievements).toBeInstanceOf(PlayerAchievements);
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.parsed.karma).toBeDefined();
  expect(data.parsed.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.parsed.karma).toEqualTypeOf<number>();
  expect(data.parsed.stats).toBeDefined();
  expect(data.parsed.stats).toBeInstanceOf(PlayerStats);
  expectTypeOf(data.parsed.stats).toEqualTypeOf<PlayerStats>();
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<LevelProgress>();
  expect(data.parsed.claimedCenturyCakeAt).toBeDefined();
  expectTypeOf(data.parsed.claimedCenturyCakeAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.language).toBeDefined();
  expectTypeOf(data.parsed.language).toEqualTypeOf<Language>();
  expect(data.parsed.cosmetics).toBeDefined();
  expect(data.parsed.cosmetics).toBeInstanceOf(PlayerCosmetics);
  expectTypeOf(data.parsed.cosmetics).toEqualTypeOf<PlayerCosmetics>();
  expect(data.parsed.rankPurchase).toBeDefined();
  expect(data.parsed.rankPurchase).toBeInstanceOf(PlayerRankPurchase);
  expectTypeOf(data.parsed.rankPurchase).toEqualTypeOf<PlayerRankPurchase>();
  expect(data.parsed.challenges).toBeDefined();
  expectTypeOf(data.parsed.challenges).toEqualTypeOf<Record<string, Record<string, number>>>();
  expect(data.parsed.quests).toBeDefined();
  expect(data.parsed.quests).toBeInstanceOf(PlayerQuests);
  expectTypeOf(data.parsed.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.parsed.rewards).toBeDefined();
  expect(data.parsed.rewards).toBeInstanceOf(PlayerRewards);
  expectTypeOf(data.parsed.rewards).toEqualTypeOf<PlayerRewards>();
  expect(data.parsed.parkour).toBeDefined();
  expectTypeOf(data.parsed.parkour).toEqualTypeOf<PlayerParkour[]>();
  expect(data.parsed.channel).toBeDefined();
  expectTypeOf(data.parsed.channel).toEqualTypeOf<ChatChannel>();
  expect(data.parsed.skyBlockFreeCookieAt).toBeDefined();
  expectTypeOf(data.parsed.skyBlockFreeCookieAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.housing).toBeDefined();
  expect(data.parsed.housing).toBeInstanceOf(PlayerHousing);
  expectTypeOf(data.parsed.housing).toEqualTypeOf<PlayerHousing>();
  expect(data.parsed.adventRewards).toBeDefined();
  expectTypeOf(data.parsed.adventRewards).toEqualTypeOf<PlayerAdventRewards[]>();
  expect(data.parsed.gifting).toBeDefined();
  expect(data.parsed.gifting).toBeInstanceOf(PlayerGifting);
  expectTypeOf(data.parsed.gifting).toEqualTypeOf<PlayerGifting>();
  expect(data.parsed.socialMedia).toBeDefined();
  expect(data.parsed.socialMedia).toBeInstanceOf(PlayerSocialMedia);
  expectTypeOf(data.parsed.socialMedia).toEqualTypeOf<PlayerSocialMedia>();
  expect(data.parsed.scorpiusBribes).toBeDefined();
  expectTypeOf(data.parsed.scorpiusBribes).toEqualTypeOf<PlayerScorpiusBribe[]>();
  expect(data.parsed.guild).toBeDefined();
  expectTypeOf(data.parsed.guild).toEqualTypeOf<Guild | null>();
  expect(data.parsed.houses).toBeDefined();
  expectTypeOf(data.parsed.houses).toEqualTypeOf<House[] | null>();
  if (data.parsed.houses) {
    data.parsed.houses.forEach((house: House) => {
      expect(house).toBeDefined();
      expect(house).toBeInstanceOf(House);
      expectTypeOf(house).toEqualTypeOf<House>();
    });
  }
  expect(data.parsed.recentGames).toBeDefined();
  expectTypeOf(data.parsed.recentGames).toEqualTypeOf<RecentGame[] | null>();
  client.destroy();
});

test('getPlayer (houses)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getPlayer('618a96fec8b0493fa89427891049550b', { houses: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Player>>();
  expect(data.parsed.nickname).toBeDefined();
  expectTypeOf(data.parsed.nickname).toEqualTypeOf<string>();
  expect(data.parsed.uuid).toBeDefined();
  expectTypeOf(data.parsed.uuid).toEqualTypeOf<string>();
  expect(data.parsed.rank).toBeDefined();
  expectTypeOf(data.parsed.rank).toEqualTypeOf<PlayerRank>();
  expect(data.parsed.firstLoginAt).toBeDefined();
  expectTypeOf(data.parsed.firstLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLoginAt).toBeDefined();
  expectTypeOf(data.parsed.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLogoutAt).toBeDefined();
  expectTypeOf(data.parsed.lastLogoutAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.achievements).toBeDefined();
  expect(data.parsed.achievements).toBeInstanceOf(PlayerAchievements);
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.parsed.karma).toBeDefined();
  expect(data.parsed.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.parsed.karma).toEqualTypeOf<number>();
  expect(data.parsed.stats).toBeDefined();
  expect(data.parsed.stats).toBeInstanceOf(PlayerStats);
  expectTypeOf(data.parsed.stats).toEqualTypeOf<PlayerStats>();
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<LevelProgress>();
  expect(data.parsed.claimedCenturyCakeAt).toBeDefined();
  expectTypeOf(data.parsed.claimedCenturyCakeAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.language).toBeDefined();
  expectTypeOf(data.parsed.language).toEqualTypeOf<Language>();
  expect(data.parsed.cosmetics).toBeDefined();
  expect(data.parsed.cosmetics).toBeInstanceOf(PlayerCosmetics);
  expectTypeOf(data.parsed.cosmetics).toEqualTypeOf<PlayerCosmetics>();
  expect(data.parsed.rankPurchase).toBeDefined();
  expect(data.parsed.rankPurchase).toBeInstanceOf(PlayerRankPurchase);
  expectTypeOf(data.parsed.rankPurchase).toEqualTypeOf<PlayerRankPurchase>();
  expect(data.parsed.challenges).toBeDefined();
  expectTypeOf(data.parsed.challenges).toEqualTypeOf<Record<string, Record<string, number>>>();
  expect(data.parsed.quests).toBeDefined();
  expect(data.parsed.quests).toBeInstanceOf(PlayerQuests);
  expectTypeOf(data.parsed.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.parsed.rewards).toBeDefined();
  expect(data.parsed.rewards).toBeInstanceOf(PlayerRewards);
  expectTypeOf(data.parsed.rewards).toEqualTypeOf<PlayerRewards>();
  expect(data.parsed.parkour).toBeDefined();
  expectTypeOf(data.parsed.parkour).toEqualTypeOf<PlayerParkour[]>();
  expect(data.parsed.channel).toBeDefined();
  expectTypeOf(data.parsed.channel).toEqualTypeOf<ChatChannel>();
  expect(data.parsed.skyBlockFreeCookieAt).toBeDefined();
  expectTypeOf(data.parsed.skyBlockFreeCookieAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.housing).toBeDefined();
  expect(data.parsed.housing).toBeInstanceOf(PlayerHousing);
  expectTypeOf(data.parsed.housing).toEqualTypeOf<PlayerHousing>();
  expect(data.parsed.adventRewards).toBeDefined();
  expectTypeOf(data.parsed.adventRewards).toEqualTypeOf<PlayerAdventRewards[]>();
  expect(data.parsed.gifting).toBeDefined();
  expect(data.parsed.gifting).toBeInstanceOf(PlayerGifting);
  expectTypeOf(data.parsed.gifting).toEqualTypeOf<PlayerGifting>();
  expect(data.parsed.socialMedia).toBeDefined();
  expect(data.parsed.socialMedia).toBeInstanceOf(PlayerSocialMedia);
  expectTypeOf(data.parsed.socialMedia).toEqualTypeOf<PlayerSocialMedia>();
  expect(data.parsed.scorpiusBribes).toBeDefined();
  expectTypeOf(data.parsed.scorpiusBribes).toEqualTypeOf<PlayerScorpiusBribe[]>();
  expect(data.parsed.guild).toBeDefined();
  expectTypeOf(data.parsed.guild).toEqualTypeOf<Guild | null>();
  expect(data.parsed.houses).toBeDefined();
  expectTypeOf(data.parsed.houses).toEqualTypeOf<House[] | null>();
  if (data.parsed.houses) {
    data.parsed.houses.forEach((house: House) => {
      expect(house).toBeDefined();
      expect(house).toBeInstanceOf(House);
      expectTypeOf(house).toEqualTypeOf<House>();
    });
  }
  expect(data.parsed.recentGames).toBeDefined();
  expectTypeOf(data.parsed.recentGames).toEqualTypeOf<RecentGame[] | null>();
  client.destroy();
});

test('getPlayer (recent games)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getPlayer('37501e7512b845ab8796e2baf9e9677a', { recentGames: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Player>>();
  expect(data.parsed.nickname).toBeDefined();
  expectTypeOf(data.parsed.nickname).toEqualTypeOf<string>();
  expect(data.parsed.uuid).toBeDefined();
  expectTypeOf(data.parsed.uuid).toEqualTypeOf<string>();
  expect(data.parsed.rank).toBeDefined();
  expectTypeOf(data.parsed.rank).toEqualTypeOf<PlayerRank>();
  expect(data.parsed.firstLoginAt).toBeDefined();
  expectTypeOf(data.parsed.firstLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLoginAt).toBeDefined();
  expectTypeOf(data.parsed.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLogoutAt).toBeDefined();
  expectTypeOf(data.parsed.lastLogoutAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.achievements).toBeDefined();
  expect(data.parsed.achievements).toBeInstanceOf(PlayerAchievements);
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.parsed.karma).toBeDefined();
  expect(data.parsed.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.parsed.karma).toEqualTypeOf<number>();
  expect(data.parsed.stats).toBeDefined();
  expect(data.parsed.stats).toBeInstanceOf(PlayerStats);
  expectTypeOf(data.parsed.stats).toEqualTypeOf<PlayerStats>();
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<LevelProgress>();
  expect(data.parsed.claimedCenturyCakeAt).toBeDefined();
  expectTypeOf(data.parsed.claimedCenturyCakeAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.language).toBeDefined();
  expectTypeOf(data.parsed.language).toEqualTypeOf<Language>();
  expect(data.parsed.cosmetics).toBeDefined();
  expect(data.parsed.cosmetics).toBeInstanceOf(PlayerCosmetics);
  expectTypeOf(data.parsed.cosmetics).toEqualTypeOf<PlayerCosmetics>();
  expect(data.parsed.rankPurchase).toBeDefined();
  expect(data.parsed.rankPurchase).toBeInstanceOf(PlayerRankPurchase);
  expectTypeOf(data.parsed.rankPurchase).toEqualTypeOf<PlayerRankPurchase>();
  expect(data.parsed.challenges).toBeDefined();
  expectTypeOf(data.parsed.challenges).toEqualTypeOf<Record<string, Record<string, number>>>();
  expect(data.parsed.quests).toBeDefined();
  expect(data.parsed.quests).toBeInstanceOf(PlayerQuests);
  expectTypeOf(data.parsed.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.parsed.rewards).toBeDefined();
  expect(data.parsed.rewards).toBeInstanceOf(PlayerRewards);
  expectTypeOf(data.parsed.rewards).toEqualTypeOf<PlayerRewards>();
  expect(data.parsed.parkour).toBeDefined();
  expectTypeOf(data.parsed.parkour).toEqualTypeOf<PlayerParkour[]>();
  expect(data.parsed.channel).toBeDefined();
  expectTypeOf(data.parsed.channel).toEqualTypeOf<ChatChannel>();
  expect(data.parsed.skyBlockFreeCookieAt).toBeDefined();
  expectTypeOf(data.parsed.skyBlockFreeCookieAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.housing).toBeDefined();
  expect(data.parsed.housing).toBeInstanceOf(PlayerHousing);
  expectTypeOf(data.parsed.housing).toEqualTypeOf<PlayerHousing>();
  expect(data.parsed.adventRewards).toBeDefined();
  expectTypeOf(data.parsed.adventRewards).toEqualTypeOf<PlayerAdventRewards[]>();
  expect(data.parsed.gifting).toBeDefined();
  expect(data.parsed.gifting).toBeInstanceOf(PlayerGifting);
  expectTypeOf(data.parsed.gifting).toEqualTypeOf<PlayerGifting>();
  expect(data.parsed.socialMedia).toBeDefined();
  expect(data.parsed.socialMedia).toBeInstanceOf(PlayerSocialMedia);
  expectTypeOf(data.parsed.socialMedia).toEqualTypeOf<PlayerSocialMedia>();
  expect(data.parsed.scorpiusBribes).toBeDefined();
  expectTypeOf(data.parsed.scorpiusBribes).toEqualTypeOf<PlayerScorpiusBribe[]>();
  expect(data.parsed.guild).toBeDefined();
  expectTypeOf(data.parsed.guild).toEqualTypeOf<Guild | null>();
  expect(data.parsed.houses).toBeDefined();
  expectTypeOf(data.parsed.houses).toEqualTypeOf<House[] | null>();
  expect(data.parsed.recentGames).toBeDefined();
  expectTypeOf(data.parsed.recentGames).toEqualTypeOf<RecentGame[] | null>();
  if (data.parsed.recentGames) {
    data.parsed.recentGames.forEach((game: RecentGame) => {
      expect(game).toBeDefined();
      expect(game).toBeInstanceOf(RecentGame);
      expectTypeOf(game).toEqualTypeOf<RecentGame>();
    });
  }
  client.destroy();
});

test('getPlayer', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getPlayer('14727faefbdc4aff848cd2713eb9939e');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Player>>();
  expect(data.parsed.nickname).toBeDefined();
  expectTypeOf(data.parsed.nickname).toEqualTypeOf<string>();
  expect(data.parsed.uuid).toBeDefined();
  expectTypeOf(data.parsed.uuid).toEqualTypeOf<string>();
  expect(data.parsed.rank).toBeDefined();
  expectTypeOf(data.parsed.rank).toEqualTypeOf<PlayerRank>();
  expect(data.parsed.firstLoginAt).toBeDefined();
  expectTypeOf(data.parsed.firstLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLoginAt).toBeDefined();
  expectTypeOf(data.parsed.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.lastLogoutAt).toBeDefined();
  expectTypeOf(data.parsed.lastLogoutAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.achievements).toBeDefined();
  expect(data.parsed.achievements).toBeInstanceOf(PlayerAchievements);
  expectTypeOf(data.parsed.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.parsed.karma).toBeDefined();
  expect(data.parsed.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.parsed.karma).toEqualTypeOf<number>();
  expect(data.parsed.stats).toBeDefined();
  expect(data.parsed.stats).toBeInstanceOf(PlayerStats);
  expectTypeOf(data.parsed.stats).toEqualTypeOf<PlayerStats>();
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<LevelProgress>();
  expect(data.parsed.claimedCenturyCakeAt).toBeDefined();
  expectTypeOf(data.parsed.claimedCenturyCakeAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.language).toBeDefined();
  expectTypeOf(data.parsed.language).toEqualTypeOf<Language>();
  expect(data.parsed.cosmetics).toBeDefined();
  expect(data.parsed.cosmetics).toBeInstanceOf(PlayerCosmetics);
  expectTypeOf(data.parsed.cosmetics).toEqualTypeOf<PlayerCosmetics>();
  expect(data.parsed.rankPurchase).toBeDefined();
  expect(data.parsed.rankPurchase).toBeInstanceOf(PlayerRankPurchase);
  expectTypeOf(data.parsed.rankPurchase).toEqualTypeOf<PlayerRankPurchase>();
  expect(data.parsed.challenges).toBeDefined();
  expectTypeOf(data.parsed.challenges).toEqualTypeOf<Record<string, Record<string, number>>>();
  expect(data.parsed.quests).toBeDefined();
  expect(data.parsed.quests).toBeInstanceOf(PlayerQuests);
  expectTypeOf(data.parsed.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.parsed.rewards).toBeDefined();
  expect(data.parsed.rewards).toBeInstanceOf(PlayerRewards);
  expectTypeOf(data.parsed.rewards).toEqualTypeOf<PlayerRewards>();
  expect(data.parsed.parkour).toBeDefined();
  expectTypeOf(data.parsed.parkour).toEqualTypeOf<PlayerParkour[]>();
  expect(data.parsed.channel).toBeDefined();
  expectTypeOf(data.parsed.channel).toEqualTypeOf<ChatChannel>();
  expect(data.parsed.skyBlockFreeCookieAt).toBeDefined();
  expectTypeOf(data.parsed.skyBlockFreeCookieAt).toEqualTypeOf<Date | null>();
  expect(data.parsed.housing).toBeDefined();
  expect(data.parsed.housing).toBeInstanceOf(PlayerHousing);
  expectTypeOf(data.parsed.housing).toEqualTypeOf<PlayerHousing>();
  expect(data.parsed.adventRewards).toBeDefined();
  expectTypeOf(data.parsed.adventRewards).toEqualTypeOf<PlayerAdventRewards[]>();
  expect(data.parsed.gifting).toBeDefined();
  expect(data.parsed.gifting).toBeInstanceOf(PlayerGifting);
  expectTypeOf(data.parsed.gifting).toEqualTypeOf<PlayerGifting>();
  expect(data.parsed.socialMedia).toBeDefined();
  expect(data.parsed.socialMedia).toBeInstanceOf(PlayerSocialMedia);
  expectTypeOf(data.parsed.socialMedia).toEqualTypeOf<PlayerSocialMedia>();
  expect(data.parsed.scorpiusBribes).toBeDefined();
  expectTypeOf(data.parsed.scorpiusBribes).toEqualTypeOf<PlayerScorpiusBribe[]>();
  expect(data.parsed.guild).toBeDefined();
  expectTypeOf(data.parsed.guild).toEqualTypeOf<Guild | null>();
  expect(data.parsed.houses).toBeDefined();
  expectTypeOf(data.parsed.houses).toEqualTypeOf<House[] | null>();
  expect(data.parsed.recentGames).toBeDefined();
  expectTypeOf(data.parsed.recentGames).toEqualTypeOf<RecentGame[] | null>();
  client.destroy();
});
