import Arcade from '../Structures/MiniGames/Arcade/Arcade.js';
import ArenaBrawl from '../Structures/MiniGames/ArenaBrawl/ArenaBrawl.js';
import BedWars from '../Structures/MiniGames/BedWars/BedWars.js';
import BlitzSurvivalGames from '../Structures/MiniGames/BlitzSurvivalGames/BlitzSurvivalGames.js';
import BuildBattle from '../Structures/MiniGames/BuildBattle.js';
import Client from '../Client.js';
import Color from '../Structures/Color.js';
import CopsAndCrims from '../Structures/MiniGames/CopsAndCrims/CopsAndCrims.js';
import Cosmetics from '../Structures/Player/Cosmetics.js';
import Duels from '../Structures/MiniGames/Duels/Duels.js';
import Gifting from '../Structures/Player/Gifting.js';
import Guild from '../Structures/Guild/Guild.js';
import House from '../Structures/House.js';
import Housing from '../Structures/Housing.js';
import MegaWalls from '../Structures/MiniGames/MegaWalls/MegaWalls.js';
import MurderMystery from '../Structures/MiniGames/MurderMystery/MurderMystery.js';
import Paintball from '../Structures/MiniGames/Paintball.js';
import Parkour from '../Structures/Player/Parkour.js';
import Pit from '../Structures/MiniGames/Pit/Pit.js';
import Player from '../Structures/Player/Player.js';
import PlayerAchievements from '../Structures/Player/PlayerAchievements.js';
import PlayerQuests from '../Structures/Player/Quests/PlayerQuests.js';
import Quakecraft from '../Structures/MiniGames/Quakecraft/Quakecraft.js';
import RecentGame from '../Structures/RecentGame.js';
import RequestData from '../Private/RequestData.js';
import Rewards from '../Structures/Player/Rewards.js';
import Seasonal from '../Structures/Player/Seasonal/Seasonal.js';
import SkyWars from '../Structures/MiniGames/SkyWars/SkyWars.js';
import SmashHeroes from '../Structures/MiniGames/SmashHeroes/SmashHeroes.js';
import SocialMedia from '../Structures/Player/SocialMedia.js';
import SpeedUHC from '../Structures/MiniGames/SpeedUHC/SpeedUHC.js';
import TNTGames from '../Structures/MiniGames/TNTGames/TNTGames.js';
import Tourney from '../Structures/Player/Tourney/Tourney.js';
import TurboKartRacers from '../Structures/MiniGames/TurboKartRacers/TurboKartRacers.js';
import UHC from '../Structures/MiniGames/UHC/UHC.js';
import VampireZ from '../Structures/MiniGames/VampireZ/VampireZ.js';
import Walls from '../Structures/MiniGames/Walls.js';
import Warlords from '../Structures/MiniGames/Warlords/Warlords.js';
import WoolGames from '../Structures/MiniGames/WoolGames/WoolGames.js';
import { defaultRequestData } from '../../vitest.setup.js';
import { expect, expectTypeOf, test, vi } from 'vitest';
import type { ChatChannel, Language, LevelProgress, PlayerRank, PlayerStats, ScorpiusBribe } from '../Types/Player.js';

test('getPlayer (never joinned hypixel)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  vi.spyOn(global, 'fetch').mockResolvedValue({
    ...defaultRequestData,
    json: () => Promise.resolve({ success: true })
  } as any);

  await expect(() => client.getPlayer('14727faefbdc4aff848cd2713eb9939e')).rejects.toThrowError(
    client.errors.PLAYER_HAS_NEVER_LOGGED
  );
  vi.restoreAllMocks();
  client.destroy();
});

test('getPlayer (no input)', () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  expect(() => client.getPlayer()).rejects.toThrowError(client.errors.NO_NICKNAME_UUID);
  client.destroy();
});

test('getPLayer (raw)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  const data = await client.getPlayer('4855c53ee4fb4100997600a92fc50984', { raw: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<Player | RequestData>();
  client.destroy();
});

test('getPlayer (guild)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getPlayer('28667672039044989b0019b14a2c34d6', { guild: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player | RequestData>();
  data = data as Player;
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.mvpPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusColor).toEqualTypeOf<Color | null>();
  expect(data.mvpPlusPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusPlusColor).toEqualTypeOf<Color | null>();
  expect(data.gifting).toBeDefined();
  expectTypeOf(data.gifting).toEqualTypeOf<Gifting>();
  expect(data.socialMedia).toBeDefined();
  expectTypeOf(data.socialMedia).toEqualTypeOf<SocialMedia[]>();
  expect(data.firstLoginTimestamp).toBeDefined();
  expect(data.firstLoginTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.firstLoginTimestamp).toEqualTypeOf<number>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date>();
  expect(data.lastLoginTimestamp).toBeDefined();
  expectTypeOf(data.lastLoginTimestamp).toEqualTypeOf<number | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expectTypeOf(data.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.exp).toBeDefined();
  expect(data.exp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.exp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.seasonal).toBeDefined();
  expectTypeOf(data.seasonal).toEqualTypeOf<Seasonal>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.freeSkyBlockCookie).toBeDefined();
  expectTypeOf(data.freeSkyBlockCookie).toEqualTypeOf<number | null>();
  expect(data.tourney).toBeDefined();
  expectTypeOf(data.tourney).toEqualTypeOf<Tourney>();
  expect(data.rewards).toBeDefined();
  expectTypeOf(data.rewards).toEqualTypeOf<Rewards>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<object>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<Parkour[]>();
  expect(data.housing).toBeDefined();
  expectTypeOf(data.housing).toEqualTypeOf<Housing>();
  expect(data.cosmetics).toBeDefined();
  expectTypeOf(data.cosmetics).toEqualTypeOf<Cosmetics>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<ScorpiusBribe[]>();
  expect(data.quests).toBeDefined();
  expectTypeOf(data.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.guild).toBeDefined();
  expect(data.guild).toBeInstanceOf(Guild);
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expect(data.houses).toBeDefined();
  expect(data.houses).toBeNull();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  expect(data.recentGames).toBeDefined();
  expect(data.recentGames).toBeNull();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
  expect(data.stats).toBeDefined();
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.stats.arcade).toBeDefined();
  expect(data.stats.arcade).toBeInstanceOf(Arcade);
  expectTypeOf(data.stats.arcade).toEqualTypeOf<Arcade>();
  expect(data.stats.arenaBrawl).toBeDefined();
  expect(data.stats.arenaBrawl).toBeInstanceOf(ArenaBrawl);
  expectTypeOf(data.stats.arenaBrawl).toEqualTypeOf<ArenaBrawl>();
  expect(data.stats.BedWars).toBeDefined();
  expect(data.stats.BedWars).toBeInstanceOf(BedWars);
  expectTypeOf(data.stats.BedWars).toEqualTypeOf<BedWars>();
  expect(data.stats.blitzsg).toBeDefined();
  expect(data.stats.blitzsg).toBeInstanceOf(BlitzSurvivalGames);
  expectTypeOf(data.stats.blitzsg).toEqualTypeOf<BlitzSurvivalGames>();
  expect(data.stats.buildbattle).toBeDefined();
  expect(data.stats.buildbattle).toBeInstanceOf(BuildBattle);
  expectTypeOf(data.stats.buildbattle).toEqualTypeOf<BuildBattle>();
  expect(data.stats.copsandcrims).toBeDefined();
  expect(data.stats.copsandcrims).toBeInstanceOf(CopsAndCrims);
  expectTypeOf(data.stats.copsandcrims).toEqualTypeOf<CopsAndCrims>();
  expect(data.stats.duels).toBeDefined();
  expect(data.stats.duels).toBeInstanceOf(Duels);
  expectTypeOf(data.stats.duels).toEqualTypeOf<Duels>();
  expect(data.stats.megawalls).toBeDefined();
  expect(data.stats.megawalls).toBeInstanceOf(MegaWalls);
  expectTypeOf(data.stats.megawalls).toEqualTypeOf<MegaWalls>();
  expect(data.stats.murdermystery).toBeDefined();
  expect(data.stats.murdermystery).toBeInstanceOf(MurderMystery);
  expectTypeOf(data.stats.murdermystery).toEqualTypeOf<MurderMystery>();
  expect(data.stats.paintball).toBeDefined();
  expect(data.stats.paintball).toBeInstanceOf(Paintball);
  expectTypeOf(data.stats.paintball).toEqualTypeOf<Paintball>();
  expect(data.stats.pit).toBeDefined();
  expect(data.stats.pit).toBeInstanceOf(Pit);
  expectTypeOf(data.stats.pit).toEqualTypeOf<Pit>();
  expect(data.stats.quakecraft).toBeDefined();
  expect(data.stats.quakecraft).toBeInstanceOf(Quakecraft);
  expectTypeOf(data.stats.quakecraft).toEqualTypeOf<Quakecraft>();
  expect(data.stats.skywars).toBeDefined();
  expect(data.stats.skywars).toBeInstanceOf(SkyWars);
  expectTypeOf(data.stats.skywars).toEqualTypeOf<SkyWars>();
  expect(data.stats.smashheroes).toBeDefined();
  expect(data.stats.smashheroes).toBeInstanceOf(SmashHeroes);
  expectTypeOf(data.stats.smashheroes).toEqualTypeOf<SmashHeroes>();
  expect(data.stats.speeduhc).toBeDefined();
  expect(data.stats.speeduhc).toBeInstanceOf(SpeedUHC);
  expectTypeOf(data.stats.speeduhc).toEqualTypeOf<SpeedUHC>();
  expect(data.stats.tntgames).toBeDefined();
  expect(data.stats.tntgames).toBeInstanceOf(TNTGames);
  expectTypeOf(data.stats.tntgames).toEqualTypeOf<TNTGames>();
  expect(data.stats.turbokartracers).toBeDefined();
  expect(data.stats.turbokartracers).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data.stats.turbokartracers).toEqualTypeOf<TurboKartRacers>();
  expect(data.stats.uhc).toBeDefined();
  expect(data.stats.uhc).toBeInstanceOf(UHC);
  expectTypeOf(data.stats.uhc).toEqualTypeOf<UHC>();
  expect(data.stats.vampirez).toBeDefined();
  expect(data.stats.vampirez).toBeInstanceOf(VampireZ);
  expectTypeOf(data.stats.vampirez).toEqualTypeOf<VampireZ>();
  expect(data.stats.walls).toBeDefined();
  expect(data.stats.walls).toBeInstanceOf(Walls);
  expectTypeOf(data.stats.walls).toEqualTypeOf<Walls>();
  expect(data.stats.warlords).toBeDefined();
  expect(data.stats.warlords).toBeInstanceOf(Warlords);
  expectTypeOf(data.stats.warlords).toEqualTypeOf<Warlords>();
  expect(data.stats.woolgames).toBeDefined();
  expect(data.stats.woolgames).toBeInstanceOf(WoolGames);
  expectTypeOf(data.stats.woolgames).toEqualTypeOf<WoolGames>();
  client.destroy();
});

test('getPlayer (houses)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getPlayer('618a96fec8b0493fa89427891049550b', { houses: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player | RequestData>();
  data = data as Player;
  expect(data.houses).toBeDefined();
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.mvpPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusColor).toEqualTypeOf<Color | null>();
  expect(data.mvpPlusPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusPlusColor).toEqualTypeOf<Color | null>();
  expect(data.gifting).toBeDefined();
  expectTypeOf(data.gifting).toEqualTypeOf<Gifting>();
  expect(data.socialMedia).toBeDefined();
  expectTypeOf(data.socialMedia).toEqualTypeOf<SocialMedia[]>();
  expect(data.firstLoginTimestamp).toBeDefined();
  expect(data.firstLoginTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.firstLoginTimestamp).toEqualTypeOf<number>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date>();
  expect(data.lastLoginTimestamp).toBeDefined();
  expectTypeOf(data.lastLoginTimestamp).toEqualTypeOf<number | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expectTypeOf(data.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.exp).toBeDefined();
  expect(data.exp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.exp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.seasonal).toBeDefined();
  expectTypeOf(data.seasonal).toEqualTypeOf<Seasonal>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.freeSkyBlockCookie).toBeDefined();
  expectTypeOf(data.freeSkyBlockCookie).toEqualTypeOf<number | null>();
  expect(data.tourney).toBeDefined();
  expectTypeOf(data.tourney).toEqualTypeOf<Tourney>();
  expect(data.rewards).toBeDefined();
  expectTypeOf(data.rewards).toEqualTypeOf<Rewards>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<object>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<Parkour[]>();
  expect(data.housing).toBeDefined();
  expectTypeOf(data.housing).toEqualTypeOf<Housing>();
  expect(data.cosmetics).toBeDefined();
  expectTypeOf(data.cosmetics).toEqualTypeOf<Cosmetics>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<ScorpiusBribe[]>();
  expect(data.quests).toBeDefined();
  expectTypeOf(data.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.guild).toBeDefined();
  expect(data.guild).toBeNull();
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  if (data.houses) {
    data.houses.forEach((house: House) => {
      expect(house).toBeDefined();
      expect(house).toBeInstanceOf(House);
      expectTypeOf(house).toEqualTypeOf<House>();
    });
  }
  expect(data.recentGames).toBeDefined();
  expect(data.recentGames).toBeNull();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
  expect(data.stats).toBeDefined();
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.stats.arcade).toBeDefined();
  expect(data.stats.arcade).toBeInstanceOf(Arcade);
  expectTypeOf(data.stats.arcade).toEqualTypeOf<Arcade>();
  expect(data.stats.arenaBrawl).toBeDefined();
  expect(data.stats.arenaBrawl).toBeInstanceOf(ArenaBrawl);
  expectTypeOf(data.stats.arenaBrawl).toEqualTypeOf<ArenaBrawl>();
  expect(data.stats.BedWars).toBeDefined();
  expect(data.stats.BedWars).toBeInstanceOf(BedWars);
  expectTypeOf(data.stats.BedWars).toEqualTypeOf<BedWars>();
  expect(data.stats.blitzsg).toBeDefined();
  expect(data.stats.blitzsg).toBeInstanceOf(BlitzSurvivalGames);
  expectTypeOf(data.stats.blitzsg).toEqualTypeOf<BlitzSurvivalGames>();
  expect(data.stats.buildbattle).toBeDefined();
  expect(data.stats.buildbattle).toBeInstanceOf(BuildBattle);
  expectTypeOf(data.stats.buildbattle).toEqualTypeOf<BuildBattle>();
  expect(data.stats.copsandcrims).toBeDefined();
  expect(data.stats.copsandcrims).toBeInstanceOf(CopsAndCrims);
  expectTypeOf(data.stats.copsandcrims).toEqualTypeOf<CopsAndCrims>();
  expect(data.stats.duels).toBeDefined();
  expect(data.stats.duels).toBeInstanceOf(Duels);
  expectTypeOf(data.stats.duels).toEqualTypeOf<Duels>();
  expect(data.stats.megawalls).toBeDefined();
  expect(data.stats.megawalls).toBeInstanceOf(MegaWalls);
  expectTypeOf(data.stats.megawalls).toEqualTypeOf<MegaWalls>();
  expect(data.stats.murdermystery).toBeDefined();
  expect(data.stats.murdermystery).toBeInstanceOf(MurderMystery);
  expectTypeOf(data.stats.murdermystery).toEqualTypeOf<MurderMystery>();
  expect(data.stats.paintball).toBeDefined();
  expect(data.stats.paintball).toBeInstanceOf(Paintball);
  expectTypeOf(data.stats.paintball).toEqualTypeOf<Paintball>();
  expect(data.stats.pit).toBeDefined();
  expect(data.stats.pit).toBeInstanceOf(Pit);
  expectTypeOf(data.stats.pit).toEqualTypeOf<Pit>();
  expect(data.stats.quakecraft).toBeDefined();
  expect(data.stats.quakecraft).toBeInstanceOf(Quakecraft);
  expectTypeOf(data.stats.quakecraft).toEqualTypeOf<Quakecraft>();
  expect(data.stats.skywars).toBeDefined();
  expect(data.stats.skywars).toBeInstanceOf(SkyWars);
  expectTypeOf(data.stats.skywars).toEqualTypeOf<SkyWars>();
  expect(data.stats.smashheroes).toBeDefined();
  expect(data.stats.smashheroes).toBeInstanceOf(SmashHeroes);
  expectTypeOf(data.stats.smashheroes).toEqualTypeOf<SmashHeroes>();
  expect(data.stats.speeduhc).toBeDefined();
  expect(data.stats.speeduhc).toBeInstanceOf(SpeedUHC);
  expectTypeOf(data.stats.speeduhc).toEqualTypeOf<SpeedUHC>();
  expect(data.stats.tntgames).toBeDefined();
  expect(data.stats.tntgames).toBeInstanceOf(TNTGames);
  expectTypeOf(data.stats.tntgames).toEqualTypeOf<TNTGames>();
  expect(data.stats.turbokartracers).toBeDefined();
  expect(data.stats.turbokartracers).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data.stats.turbokartracers).toEqualTypeOf<TurboKartRacers>();
  expect(data.stats.uhc).toBeDefined();
  expect(data.stats.uhc).toBeInstanceOf(UHC);
  expectTypeOf(data.stats.uhc).toEqualTypeOf<UHC>();
  expect(data.stats.vampirez).toBeDefined();
  expect(data.stats.vampirez).toBeInstanceOf(VampireZ);
  expectTypeOf(data.stats.vampirez).toEqualTypeOf<VampireZ>();
  expect(data.stats.walls).toBeDefined();
  expect(data.stats.walls).toBeInstanceOf(Walls);
  expectTypeOf(data.stats.walls).toEqualTypeOf<Walls>();
  expect(data.stats.warlords).toBeDefined();
  expect(data.stats.warlords).toBeInstanceOf(Warlords);
  expectTypeOf(data.stats.warlords).toEqualTypeOf<Warlords>();
  expect(data.stats.woolgames).toBeDefined();
  expect(data.stats.woolgames).toBeInstanceOf(WoolGames);
  expectTypeOf(data.stats.woolgames).toEqualTypeOf<WoolGames>();
  client.destroy();
});

test('getPlayer (recent games)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getPlayer('37501e7512b845ab8796e2baf9e9677a', { recentGames: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player | RequestData>();
  data = data as Player;
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.mvpPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusColor).toEqualTypeOf<Color | null>();
  expect(data.mvpPlusPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusPlusColor).toEqualTypeOf<Color | null>();
  expect(data.gifting).toBeDefined();
  expectTypeOf(data.gifting).toEqualTypeOf<Gifting>();
  expect(data.socialMedia).toBeDefined();
  expectTypeOf(data.socialMedia).toEqualTypeOf<SocialMedia[]>();
  expect(data.firstLoginTimestamp).toBeDefined();
  expect(data.firstLoginTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.firstLoginTimestamp).toEqualTypeOf<number>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date>();
  expect(data.lastLoginTimestamp).toBeDefined();
  expectTypeOf(data.lastLoginTimestamp).toEqualTypeOf<number | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expectTypeOf(data.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.exp).toBeDefined();
  expect(data.exp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.exp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.seasonal).toBeDefined();
  expectTypeOf(data.seasonal).toEqualTypeOf<Seasonal>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.freeSkyBlockCookie).toBeDefined();
  expectTypeOf(data.freeSkyBlockCookie).toEqualTypeOf<number | null>();
  expect(data.tourney).toBeDefined();
  expectTypeOf(data.tourney).toEqualTypeOf<Tourney>();
  expect(data.rewards).toBeDefined();
  expectTypeOf(data.rewards).toEqualTypeOf<Rewards>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<object>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<Parkour[]>();
  expect(data.housing).toBeDefined();
  expectTypeOf(data.housing).toEqualTypeOf<Housing>();
  expect(data.cosmetics).toBeDefined();
  expectTypeOf(data.cosmetics).toEqualTypeOf<Cosmetics>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<ScorpiusBribe[]>();
  expect(data.quests).toBeDefined();
  expectTypeOf(data.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.guild).toBeDefined();
  expect(data.guild).toBeNull();
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expect(data.houses).toBeDefined();
  expect(data.houses).toBeNull();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  expect(data.recentGames).toBeDefined();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
  if (data.recentGames) {
    data.recentGames.forEach((game: RecentGame) => {
      expect(game).toBeDefined();
      expect(game).toBeInstanceOf(RecentGame);
      expectTypeOf(game).toEqualTypeOf<RecentGame>();
    });
  }
  expect(data.stats).toBeDefined();
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.stats.arcade).toBeDefined();
  expect(data.stats.arcade).toBeInstanceOf(Arcade);
  expectTypeOf(data.stats.arcade).toEqualTypeOf<Arcade>();
  expect(data.stats.arenaBrawl).toBeDefined();
  expect(data.stats.arenaBrawl).toBeInstanceOf(ArenaBrawl);
  expectTypeOf(data.stats.arenaBrawl).toEqualTypeOf<ArenaBrawl>();
  expect(data.stats.BedWars).toBeDefined();
  expect(data.stats.BedWars).toBeInstanceOf(BedWars);
  expectTypeOf(data.stats.BedWars).toEqualTypeOf<BedWars>();
  expect(data.stats.blitzsg).toBeDefined();
  expect(data.stats.blitzsg).toBeInstanceOf(BlitzSurvivalGames);
  expectTypeOf(data.stats.blitzsg).toEqualTypeOf<BlitzSurvivalGames>();
  expect(data.stats.buildbattle).toBeDefined();
  expect(data.stats.buildbattle).toBeInstanceOf(BuildBattle);
  expectTypeOf(data.stats.buildbattle).toEqualTypeOf<BuildBattle>();
  expect(data.stats.copsandcrims).toBeDefined();
  expect(data.stats.copsandcrims).toBeInstanceOf(CopsAndCrims);
  expectTypeOf(data.stats.copsandcrims).toEqualTypeOf<CopsAndCrims>();
  expect(data.stats.duels).toBeDefined();
  expect(data.stats.duels).toBeInstanceOf(Duels);
  expectTypeOf(data.stats.duels).toEqualTypeOf<Duels>();
  expect(data.stats.megawalls).toBeDefined();
  expect(data.stats.megawalls).toBeInstanceOf(MegaWalls);
  expectTypeOf(data.stats.megawalls).toEqualTypeOf<MegaWalls>();
  expect(data.stats.murdermystery).toBeDefined();
  expect(data.stats.murdermystery).toBeInstanceOf(MurderMystery);
  expectTypeOf(data.stats.murdermystery).toEqualTypeOf<MurderMystery>();
  expect(data.stats.paintball).toBeDefined();
  expect(data.stats.paintball).toBeInstanceOf(Paintball);
  expectTypeOf(data.stats.paintball).toEqualTypeOf<Paintball>();
  expect(data.stats.pit).toBeDefined();
  expect(data.stats.pit).toBeInstanceOf(Pit);
  expectTypeOf(data.stats.pit).toEqualTypeOf<Pit>();
  expect(data.stats.quakecraft).toBeDefined();
  expect(data.stats.quakecraft).toBeInstanceOf(Quakecraft);
  expectTypeOf(data.stats.quakecraft).toEqualTypeOf<Quakecraft>();
  expect(data.stats.skywars).toBeDefined();
  expect(data.stats.skywars).toBeInstanceOf(SkyWars);
  expectTypeOf(data.stats.skywars).toEqualTypeOf<SkyWars>();
  expect(data.stats.smashheroes).toBeDefined();
  expect(data.stats.smashheroes).toBeInstanceOf(SmashHeroes);
  expectTypeOf(data.stats.smashheroes).toEqualTypeOf<SmashHeroes>();
  expect(data.stats.speeduhc).toBeDefined();
  expect(data.stats.speeduhc).toBeInstanceOf(SpeedUHC);
  expectTypeOf(data.stats.speeduhc).toEqualTypeOf<SpeedUHC>();
  expect(data.stats.tntgames).toBeDefined();
  expect(data.stats.tntgames).toBeInstanceOf(TNTGames);
  expectTypeOf(data.stats.tntgames).toEqualTypeOf<TNTGames>();
  expect(data.stats.turbokartracers).toBeDefined();
  expect(data.stats.turbokartracers).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data.stats.turbokartracers).toEqualTypeOf<TurboKartRacers>();
  expect(data.stats.uhc).toBeDefined();
  expect(data.stats.uhc).toBeInstanceOf(UHC);
  expectTypeOf(data.stats.uhc).toEqualTypeOf<UHC>();
  expect(data.stats.vampirez).toBeDefined();
  expect(data.stats.vampirez).toBeInstanceOf(VampireZ);
  expectTypeOf(data.stats.vampirez).toEqualTypeOf<VampireZ>();
  expect(data.stats.walls).toBeDefined();
  expect(data.stats.walls).toBeInstanceOf(Walls);
  expectTypeOf(data.stats.walls).toEqualTypeOf<Walls>();
  expect(data.stats.warlords).toBeDefined();
  expect(data.stats.warlords).toBeInstanceOf(Warlords);
  expectTypeOf(data.stats.warlords).toEqualTypeOf<Warlords>();
  expect(data.stats.woolgames).toBeDefined();
  expect(data.stats.woolgames).toBeInstanceOf(WoolGames);
  expectTypeOf(data.stats.woolgames).toEqualTypeOf<WoolGames>();
  client.destroy();
});

test('getPlayer', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getPlayer('14727faefbdc4aff848cd2713eb9939e');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player | RequestData>();
  data = data as Player;
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.mvpPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusColor).toEqualTypeOf<Color | null>();
  expect(data.mvpPlusPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusPlusColor).toEqualTypeOf<Color | null>();
  expect(data.gifting).toBeDefined();
  expectTypeOf(data.gifting).toEqualTypeOf<Gifting>();
  expect(data.socialMedia).toBeDefined();
  expectTypeOf(data.socialMedia).toEqualTypeOf<SocialMedia[]>();
  expect(data.firstLoginTimestamp).toBeDefined();
  expect(data.firstLoginTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.firstLoginTimestamp).toEqualTypeOf<number>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date>();
  expect(data.lastLoginTimestamp).toBeDefined();
  expectTypeOf(data.lastLoginTimestamp).toEqualTypeOf<number | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expectTypeOf(data.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.exp).toBeDefined();
  expect(data.exp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.exp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.seasonal).toBeDefined();
  expectTypeOf(data.seasonal).toEqualTypeOf<Seasonal>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.freeSkyBlockCookie).toBeDefined();
  expectTypeOf(data.freeSkyBlockCookie).toEqualTypeOf<number | null>();
  expect(data.tourney).toBeDefined();
  expectTypeOf(data.tourney).toEqualTypeOf<Tourney>();
  expect(data.rewards).toBeDefined();
  expectTypeOf(data.rewards).toEqualTypeOf<Rewards>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<object>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<Parkour[]>();
  expect(data.housing).toBeDefined();
  expectTypeOf(data.housing).toEqualTypeOf<Housing>();
  expect(data.cosmetics).toBeDefined();
  expectTypeOf(data.cosmetics).toEqualTypeOf<Cosmetics>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<ScorpiusBribe[]>();
  expect(data.quests).toBeDefined();
  expectTypeOf(data.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.guild).toBeDefined();
  expect(data.guild).toBeNull();
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expect(data.houses).toBeDefined();
  expect(data.houses).toBeNull();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  expect(data.recentGames).toBeDefined();
  expect(data.recentGames).toBeNull();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
  expect(data.stats).toBeDefined();
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.stats.arcade).toBeDefined();
  expect(data.stats.arcade).toBeInstanceOf(Arcade);
  expectTypeOf(data.stats.arcade).toEqualTypeOf<Arcade>();
  expect(data.stats.arenaBrawl).toBeDefined();
  expect(data.stats.arenaBrawl).toBeInstanceOf(ArenaBrawl);
  expectTypeOf(data.stats.arenaBrawl).toEqualTypeOf<ArenaBrawl>();
  expect(data.stats.BedWars).toBeDefined();
  expect(data.stats.BedWars).toBeInstanceOf(BedWars);
  expectTypeOf(data.stats.BedWars).toEqualTypeOf<BedWars>();
  expect(data.stats.blitzsg).toBeDefined();
  expect(data.stats.blitzsg).toBeInstanceOf(BlitzSurvivalGames);
  expectTypeOf(data.stats.blitzsg).toEqualTypeOf<BlitzSurvivalGames>();
  expect(data.stats.buildbattle).toBeDefined();
  expect(data.stats.buildbattle).toBeInstanceOf(BuildBattle);
  expectTypeOf(data.stats.buildbattle).toEqualTypeOf<BuildBattle>();
  expect(data.stats.copsandcrims).toBeDefined();
  expect(data.stats.copsandcrims).toBeInstanceOf(CopsAndCrims);
  expectTypeOf(data.stats.copsandcrims).toEqualTypeOf<CopsAndCrims>();
  expect(data.stats.duels).toBeDefined();
  expect(data.stats.duels).toBeInstanceOf(Duels);
  expectTypeOf(data.stats.duels).toEqualTypeOf<Duels>();
  expect(data.stats.megawalls).toBeDefined();
  expect(data.stats.megawalls).toBeInstanceOf(MegaWalls);
  expectTypeOf(data.stats.megawalls).toEqualTypeOf<MegaWalls>();
  expect(data.stats.murdermystery).toBeDefined();
  expect(data.stats.murdermystery).toBeInstanceOf(MurderMystery);
  expectTypeOf(data.stats.murdermystery).toEqualTypeOf<MurderMystery>();
  expect(data.stats.paintball).toBeDefined();
  expect(data.stats.paintball).toBeInstanceOf(Paintball);
  expectTypeOf(data.stats.paintball).toEqualTypeOf<Paintball>();
  expect(data.stats.pit).toBeDefined();
  expect(data.stats.pit).toBeInstanceOf(Pit);
  expectTypeOf(data.stats.pit).toEqualTypeOf<Pit>();
  expect(data.stats.quakecraft).toBeDefined();
  expect(data.stats.quakecraft).toBeInstanceOf(Quakecraft);
  expectTypeOf(data.stats.quakecraft).toEqualTypeOf<Quakecraft>();
  expect(data.stats.skywars).toBeDefined();
  expect(data.stats.skywars).toBeInstanceOf(SkyWars);
  expectTypeOf(data.stats.skywars).toEqualTypeOf<SkyWars>();
  expect(data.stats.smashheroes).toBeDefined();
  expect(data.stats.smashheroes).toBeInstanceOf(SmashHeroes);
  expectTypeOf(data.stats.smashheroes).toEqualTypeOf<SmashHeroes>();
  expect(data.stats.speeduhc).toBeDefined();
  expect(data.stats.speeduhc).toBeInstanceOf(SpeedUHC);
  expectTypeOf(data.stats.speeduhc).toEqualTypeOf<SpeedUHC>();
  expect(data.stats.tntgames).toBeDefined();
  expect(data.stats.tntgames).toBeInstanceOf(TNTGames);
  expectTypeOf(data.stats.tntgames).toEqualTypeOf<TNTGames>();
  expect(data.stats.turbokartracers).toBeDefined();
  expect(data.stats.turbokartracers).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data.stats.turbokartracers).toEqualTypeOf<TurboKartRacers>();
  expect(data.stats.uhc).toBeDefined();
  expect(data.stats.uhc).toBeInstanceOf(UHC);
  expectTypeOf(data.stats.uhc).toEqualTypeOf<UHC>();
  expect(data.stats.vampirez).toBeDefined();
  expect(data.stats.vampirez).toBeInstanceOf(VampireZ);
  expectTypeOf(data.stats.vampirez).toEqualTypeOf<VampireZ>();
  expect(data.stats.walls).toBeDefined();
  expect(data.stats.walls).toBeInstanceOf(Walls);
  expectTypeOf(data.stats.walls).toEqualTypeOf<Walls>();
  expect(data.stats.warlords).toBeDefined();
  expect(data.stats.warlords).toBeInstanceOf(Warlords);
  expectTypeOf(data.stats.warlords).toEqualTypeOf<Warlords>();
  expect(data.stats.woolgames).toBeDefined();
  expect(data.stats.woolgames).toBeInstanceOf(WoolGames);
  expectTypeOf(data.stats.woolgames).toEqualTypeOf<WoolGames>();
  client.destroy();
});
