import Client from '../Client.js';
import GameQuests from '../Structures/Static/GameQuests.js';
import Quest from '../Structures/Static/Quest.js';
import QuestObjective from '../Structures/Static/QuestObjective.js';
import Quests from '../Structures/Static/Quests.js';
import RequestData from '../Private/RequestData.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { QuestReward, QuestType } from '../Types/Static.js';

test('getQuests', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getQuests();
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Quests>>();
  expect(data.parsed.lastUpdatedTimestamp).toBeDefined();
  expectTypeOf(data.parsed.lastUpdatedTimestamp).toEqualTypeOf<number>();
  expect(data.parsed.lastUpdatedTimestamp).toBeGreaterThanOrEqual(0);
  expect(data.parsed.lastUpdatedAt).toBeDefined();
  expectTypeOf(data.parsed.lastUpdatedAt).toEqualTypeOf<Date>();
  expect(data.parsed.questsPerGame).toBeDefined();
  expectTypeOf(data.parsed.questsPerGame).toEqualTypeOf<Record<string, GameQuests>>();
  Object.keys(data.parsed.questsPerGame).forEach((game) => {
    if (undefined === data.parsed.questsPerGame[game]) return;
    expect(data.parsed.questsPerGame[game]).toBeDefined();
    expect(data.parsed.questsPerGame[game]).toBeInstanceOf(GameQuests);
    expectTypeOf(data.parsed.questsPerGame[game]).toEqualTypeOf<GameQuests>();
    expect(data.parsed.questsPerGame[game].game).toBeDefined();
    expect(data.parsed.questsPerGame[game].game).toBe(game);
    expectTypeOf(data.parsed.questsPerGame[game].game).toEqualTypeOf<string>();
    expect(data.parsed.questsPerGame[game].quests).toBeDefined();
    expectTypeOf(data.parsed.questsPerGame[game].quests).toEqualTypeOf<Quest[]>();
    data.parsed.questsPerGame[game].quests.forEach((quest: Quest) => {
      expect(quest).toBeDefined();
      expect(quest).toBeInstanceOf(Quest);
      expectTypeOf(quest).toEqualTypeOf<Quest>();
      expect(quest.id).toBeDefined();
      expectTypeOf(quest.id).toEqualTypeOf<string>();
      expect(quest.name).toBeDefined();
      expectTypeOf(quest.name).toEqualTypeOf<string>();
      expect(quest.description).toBeDefined();
      expectTypeOf(quest.description).toEqualTypeOf<string>();
      expect(quest.rewards).toBeDefined();
      expectTypeOf(quest.rewards).toEqualTypeOf<QuestReward[]>();
      expect(quest.type).toBeDefined();
      expectTypeOf(quest.type).toEqualTypeOf<QuestType>();
      expect(quest.objectives).toBeDefined();
      expectTypeOf(quest.objectives).toEqualTypeOf<QuestObjective[]>();
    });
  });
  client.destroy();
});
