import Client from '../Client.js';
import RequestData from '../Private/RequestData.js';
import SkyBlockCollection from '../Structures/SkyBlock/Collections/SkyBlockCollection.js';
import SkyBlockCollections from '../Structures/SkyBlock/Collections/SkyBlockCollections.js';
import { expect, expectTypeOf, test } from 'vitest';

test('getSkyBlockCollections', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getSkyBlockCollections();
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<RequestData<SkyBlockCollections>>();
  expect(data.parsed.lastUpdated).toBeDefined();
  expectTypeOf(data.parsed.lastUpdated).toEqualTypeOf<number>();
  expect(data.parsed.lastUpdatedAt).toBeDefined();
  expectTypeOf(data.parsed.lastUpdatedAt).toEqualTypeOf<Date>();
  expect(data.parsed.version).toBeDefined();
  expectTypeOf(data.parsed.version).toEqualTypeOf<string>();
  expect(data.parsed.farming).toBeDefined();
  expectTypeOf(data.parsed.farming).toEqualTypeOf<SkyBlockCollection[]>();
  expect(data.parsed.mining).toBeDefined();
  expectTypeOf(data.parsed.mining).toEqualTypeOf<SkyBlockCollection[]>();
  expect(data.parsed.combat).toBeDefined();
  expectTypeOf(data.parsed.combat).toEqualTypeOf<SkyBlockCollection[]>();
  expect(data.parsed.foraging).toBeDefined();
  expectTypeOf(data.parsed.foraging).toEqualTypeOf<SkyBlockCollection[]>();
  expect(data.parsed.fishing).toBeDefined();
  expectTypeOf(data.parsed.fishing).toEqualTypeOf<SkyBlockCollection[]>();
  expect(data.parsed.rift).toBeDefined();
  expectTypeOf(data.parsed.rift).toEqualTypeOf<SkyBlockCollection[]>();
  client.destroy();
});
