import Client from '../Client.js';
import RequestData from '../Private/RequestData.js';
import SkyBlockSkill from '../Structures/SkyBlock/Skills/SkyBlockSkill.js';
import SkyBlockSkills from '../Structures/SkyBlock/Skills/SkyBlockSkills.js';
import { expect, expectTypeOf, test } from 'vitest';

test('getSkyBlockSkills', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getSkyBlockSkills();
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<RequestData<SkyBlockSkills>>();
  expect(data.parsed.lastUpdated).toBeDefined();
  expectTypeOf(data.parsed.lastUpdated).toEqualTypeOf<number>();
  expect(data.parsed.lastUpdatedAt).toBeDefined();
  expectTypeOf(data.parsed.lastUpdatedAt).toEqualTypeOf<Date>();
  expect(data.parsed.version).toBeDefined();
  expectTypeOf(data.parsed.version).toEqualTypeOf<string>();
  expect(data.parsed.farming).toBeDefined();
  expectTypeOf(data.parsed.farming).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.mining).toBeDefined();
  expectTypeOf(data.parsed.mining).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.combat).toBeDefined();
  expectTypeOf(data.parsed.combat).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.foraging).toBeDefined();
  expectTypeOf(data.parsed.foraging).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.fishing).toBeDefined();
  expectTypeOf(data.parsed.fishing).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.enchanting).toBeDefined();
  expectTypeOf(data.parsed.enchanting).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.alchemy).toBeDefined();
  expectTypeOf(data.parsed.alchemy).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.carpentry).toBeDefined();
  expectTypeOf(data.parsed.carpentry).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.runecrafting).toBeDefined();
  expectTypeOf(data.parsed.runecrafting).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.social).toBeDefined();
  expectTypeOf(data.parsed.social).toEqualTypeOf<SkyBlockSkill>();
  expect(data.parsed.taming).toBeDefined();
  expectTypeOf(data.parsed.taming).toEqualTypeOf<SkyBlockSkill>();
  client.destroy();
});
