import Client from '../Client.js';
import RequestData from '../Private/RequestData.js';
import SkyBlockGarden from '../Structures/SkyBlock/Garden/SkyBlockGarden.js';
import SkyBlockGardenActiveVisitor from '../Structures/SkyBlock/Garden/SkyBlockGardenActiveVisitor.js';
import SkyBlockGardenComposter from '../Structures/SkyBlock/Garden/SkyBlockGardenComposter.js';
import SkyBlockGardenCropMilestones from '../Structures/SkyBlock/Garden/SkyBlockGardenCropMilestones.js';
import SkyBlockGardenCropsUpgrades from '../Structures/SkyBlock/Garden/SkyBlockGardenCropsUpgrades.js';
import SkyBlockGardenVisitors from '../Structures/SkyBlock/Garden/SkyBlockGardenVisitors.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { BarnPlot, BarnSkin, SkillLevelData } from '../Types/SkyBlock.js';

test('getSkyBlockGarden', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getSkyBlockGarden('ed9b9d6d-d9b7-43b1-9841-5d0c20b55494');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<SkyBlockGarden>>();
  expect(data.parsed.level).toBeDefined();
  expectTypeOf(data.parsed.level).toEqualTypeOf<SkillLevelData>();
  expect(data.parsed.barnSkin).toBeDefined();
  expectTypeOf(data.parsed.barnSkin).toEqualTypeOf<BarnSkin>();
  expect(data.parsed.unlockedBarnSkins).toBeDefined();
  expectTypeOf(data.parsed.unlockedBarnSkins).toEqualTypeOf<BarnSkin[]>();
  expect(data.parsed.unlockedPlots).toBeDefined();
  expectTypeOf(data.parsed.unlockedPlots).toEqualTypeOf<BarnPlot[]>();
  expect(data.parsed.visitors).toBeDefined();
  expectTypeOf(data.parsed.visitors).toEqualTypeOf<SkyBlockGardenVisitors>();
  expect(data.parsed.currentVisitors).toBeDefined();
  expectTypeOf(data.parsed.currentVisitors).toEqualTypeOf<SkyBlockGardenActiveVisitor[]>();
  expect(data.parsed.cropMilestones).toBeDefined();
  expectTypeOf(data.parsed.cropMilestones).toEqualTypeOf<SkyBlockGardenCropMilestones>();
  expect(data.parsed.composter).toBeDefined();
  expectTypeOf(data.parsed.composter).toEqualTypeOf<SkyBlockGardenComposter>();
  expect(data.parsed.cropUpgrades).toBeDefined();
  expectTypeOf(data.parsed.cropUpgrades).toEqualTypeOf<SkyBlockGardenCropsUpgrades>();
  client.destroy();
});
