import Client from '../Client.js';
import RequestData from '../Private/RequestData.js';
import SkyBlockBingo from '../Structures/SkyBlock/Bingo/SkyBlockBingo.js';
import { expect, expectTypeOf, test } from 'vitest';
import type SkyBlockBingoGoal from '../Structures/SkyBlock/Bingo/SkyBlockBingoGoal.js';

test('getSkyBlockBingo', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getSkyBlockBingo();
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<RequestData<SkyBlockBingo>>();
  expect(data.parsed.lastUpdatedTimestamp).toBeDefined();
  expectTypeOf(data.parsed.lastUpdatedTimestamp).toEqualTypeOf<number>();
  expect(data.parsed.lastUpdatedAt).toBeDefined();
  expectTypeOf(data.parsed.lastUpdatedAt).toEqualTypeOf<Date>();
  expect(data.parsed.id).toBeDefined();
  expectTypeOf(data.parsed.id).toEqualTypeOf<number | null>();
  expect(data.parsed.name).toBeDefined();
  expectTypeOf(data.parsed.name).toEqualTypeOf<string>();
  expect(data.parsed.start).toBeDefined();
  expectTypeOf(data.parsed.start).toEqualTypeOf<number>();
  expect(data.parsed.startAt).toBeDefined();
  expectTypeOf(data.parsed.startAt).toEqualTypeOf<Date>();
  expect(data.parsed.end).toBeDefined();
  expectTypeOf(data.parsed.end).toEqualTypeOf<number>();
  expect(data.parsed.endAt).toBeDefined();
  expectTypeOf(data.parsed.endAt).toEqualTypeOf<Date>();
  expect(data.parsed.goals).toBeDefined();
  expectTypeOf(data.parsed.goals).toEqualTypeOf<SkyBlockBingoGoal[] | null>();
  client.destroy();
});
