import Client from '../Client.js';
import RequestData from '../Private/RequestData.js';
import SkyblockGarden from '../Structures/SkyBlock/SkyblockGarden.js';
import SkyblockGemstone from '../Structures/SkyBlock/SkyblockGemstone.js';
import SkyblockInventoryItem from '../Structures/SkyBlock/SkyblockInventoryItem.js';
import SkyblockMember from '../Structures/SkyBlock/SkyblockMember.js';
import SkyblockMemberStats from '../Structures/SkyBlock/SkyblockMemberStats.js';
import SkyblockMuseum from '../Structures/SkyBlock/SkyblockMuseum.js';
import SkyblockPet from '../Structures/SkyBlock/SkyblockPet.js';
import {
  Armor,
  ChocolateFactoryData,
  CrimsonIsle,
  Dungeons,
  Equipment,
  HOTM,
  JacobData,
  Rarity,
  Skills,
  Slayer
} from '../Types/Skyblock.js';
import { NetworthResult } from 'skyhelper-networth';
import { expect, expectTypeOf, test } from 'vitest';

test('getSkyblockMember (raw)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  const data = await client.getSkyblockMember('14727faefbdc4aff848cd2713eb9939e', { raw: true });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<Map<string, SkyblockMember> | RequestData>();
  client.destroy();
});

test('getSkyblockMember (no input)', () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  expect(() => client.getSkyblockMember()).rejects.toThrowError(client.errors.NO_NICKNAME_UUID);
  client.destroy();
});

test('getSkyblockMember (no profiles)', () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  expect(() => client.getSkyblockMember('b45add7b081443909fb00aa9a3e15eb0')).rejects.toThrowError(
    client.errors.NO_SKYBLOCK_PROFILES
  );
  client.destroy();
});

test('getSkyblockMember (museum)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getSkyblockMember('add71246c46e455c8345c129ea6f146c', { museum: true });
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<Map<string, SkyblockMember> | RequestData>();
  data = data as Map<string, SkyblockMember>;
  data.forEach(async (member: SkyblockMember) => {
    expect(member).toBeDefined();
    expect(member).toBeInstanceOf(SkyblockMember);
    expectTypeOf(member).toEqualTypeOf<SkyblockMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.gameMode).toBeDefined();
    expectTypeOf(member.gameMode).toEqualTypeOf<string | null>();
    expect(member.selected).toBeDefined();
    expectTypeOf(member.selected).toEqualTypeOf<boolean>();
    expect(member.garden).toBeDefined();
    expect(member.garden).toBeNull();
    expectTypeOf(member.garden).toEqualTypeOf<SkyblockGarden | null>();
    expect(member.museum).toBeDefined();
    expectTypeOf(member.museum).toEqualTypeOf<SkyblockMuseum | null>();
    expect(member.profileName).toBeDefined();
    expectTypeOf(member.profileName).toEqualTypeOf<string>();
    expect(member.profileId).toBeDefined();
    expectTypeOf(member.profileId).toEqualTypeOf<string>();
    expect(member.firstJoinTimestamp).toBeDefined();
    expectTypeOf(member.firstJoinTimestamp).toEqualTypeOf<number | null>();
    expect(member.firstJoinAt).toBeDefined();
    expectTypeOf(member.firstJoinAt).toEqualTypeOf<Date | null>();
    expect(member.experience).toBeDefined();
    expect(member.experience).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.experience).toEqualTypeOf<number>();
    expect(member.level).toBeDefined();
    expectTypeOf(member.level).toEqualTypeOf<number>();
    expect(member.hotm).toBeDefined();
    expectTypeOf(member.hotm).toEqualTypeOf<HOTM>();
    expect(member.highestMagicalPower).toBeDefined();
    expectTypeOf(member.highestMagicalPower).toEqualTypeOf<number>();
    expect(member.fairySouls).toBeDefined();
    expectTypeOf(member.fairySouls).toEqualTypeOf<number>();
    expect(member.fairyExchanges).toBeDefined();
    expectTypeOf(member.fairyExchanges).toEqualTypeOf<number>();
    expect(member.skills).toBeDefined();
    expectTypeOf(member.skills).toEqualTypeOf<Skills>();
    expect(member.bestiary).toBeDefined();
    expectTypeOf(member.bestiary).toEqualTypeOf<number>();
    expect(member.slayer).toBeDefined();
    expectTypeOf(member.slayer).toEqualTypeOf<Slayer | null>();
    expect(member.crimsonIsle).toBeDefined();
    expectTypeOf(member.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
    expect(member.dungeons).toBeDefined();
    expectTypeOf(member.dungeons).toEqualTypeOf<Dungeons>();
    expect(member.collections).toBeDefined();
    expectTypeOf(member.collections).toEqualTypeOf<Record<string, number>>();
    expect(member.purse).toBeDefined();
    expectTypeOf(member.purse).toEqualTypeOf<number>();
    expect(member.stats).toBeDefined();
    expectTypeOf(member.stats).toEqualTypeOf<SkyblockMemberStats>();
    expect(member.pets).toBeDefined();
    expectTypeOf(member.pets).toEqualTypeOf<SkyblockPet[]>();
    member.pets.forEach((pet: SkyblockPet) => {
      expect(pet).toBeDefined();
      expect(pet).toBeInstanceOf(SkyblockPet);
      expectTypeOf(pet).toEqualTypeOf<SkyblockPet>();
      expect(pet.uuid).toBeDefined();
      expectTypeOf(pet.uuid).toEqualTypeOf<string>();
      expect(pet.name).toBeDefined();
      expectTypeOf(pet.name).toEqualTypeOf<string>();
      expect(pet.xp).toBeDefined();
      expect(pet.xp).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.xp).toEqualTypeOf<number>();
      expect(pet.active).toBeDefined();
      expectTypeOf(pet.active).toEqualTypeOf<boolean>();
      expect(pet.rarity).toBeDefined();
      expectTypeOf(pet.rarity).toEqualTypeOf<Rarity>();
      expect(pet.petScore).toBeDefined();
      expect(pet.petScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.petScore).toEqualTypeOf<number>();
      expect(pet.heldItem).toBeDefined();
      expectTypeOf(pet.heldItem).toEqualTypeOf<string | null>();
      expect(pet.candyUsed).toBeDefined();
      expect(pet.candyUsed).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.candyUsed).toEqualTypeOf<number>();
      expect(pet.skin).toBeDefined();
      expectTypeOf(pet.skin).toEqualTypeOf<string | null>();
      expect(pet.toString()).toBeDefined();
      expect(pet.toString()).toBe(pet.name);
      expectTypeOf(pet.toString()).toEqualTypeOf<string>();
    });
    expect(member.jacob).toBeDefined();
    expectTypeOf(member.jacob).toEqualTypeOf<JacobData>();
    expect(member.chocolate).toBeDefined();
    expectTypeOf(member.chocolate).toEqualTypeOf<ChocolateFactoryData>();
    expect(member.getArmor()).toBeDefined();
    expectTypeOf(member.getArmor).toEqualTypeOf<() => Promise<Armor>>();
    expectTypeOf(member.getArmor()).toEqualTypeOf<Promise<Armor>>();
    expect(member.getWardrobe()).toBeDefined();
    expectTypeOf(member.getWardrobe).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getWardrobe()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getEnderChest()).toBeDefined();
    expectTypeOf(member.getEnderChest).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getEnderChest()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getInventory()).toBeDefined();
    expectTypeOf(member.getInventory).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getInventory()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    const inv = await member.getInventory();
    inv.forEach((item: SkyblockInventoryItem) => {
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<string>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
      expect(item.toString()).toBeDefined();
      expect(item.toString()).toBe(item.name);
      expectTypeOf(item.toString()).toEqualTypeOf<string>();
    });
    expect(member.getPetScore()).toBeDefined();
    expectTypeOf(member.getPetScore).toEqualTypeOf<() => number>();
    expect(member.getPetScore()).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.getPetScore()).toEqualTypeOf<number>();
    expect(member.getEquipment()).toBeDefined();
    expectTypeOf(member.getEquipment).toEqualTypeOf<() => Promise<Equipment>>();
    expectTypeOf(member.getEquipment()).toEqualTypeOf<Promise<Equipment>>();
    expect(member.getPersonalVault()).toBeDefined();
    expectTypeOf(member.getPersonalVault).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getPersonalVault()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getNetworth()).toBeDefined();
    expectTypeOf(member.getNetworth).toEqualTypeOf<() => Promise<NetworthResult | null>>();
    expectTypeOf(member.getNetworth()).toEqualTypeOf<Promise<NetworthResult | null>>();
    expect(member.getFarmingWeight()).toBeDefined();
    expectTypeOf(member.getFarmingWeight).toEqualTypeOf<() => number>();
    expect(member.getFarmingWeight()).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.getFarmingWeight()).toEqualTypeOf<number>();
    expect(member.getFarmingWeight()).toBeGreaterThanOrEqual(0);
    expect(member.toString()).toBeDefined();
    expect(member.toString()).toBe(member.uuid);
    expectTypeOf(member.toString()).toEqualTypeOf<string>();
  });
  client.destroy();
});

test('getSkyblockMember (garden)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getSkyblockMember('add71246c46e455c8345c129ea6f146c', { garden: true });
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<Map<string, SkyblockMember> | RequestData>();
  data = data as Map<string, SkyblockMember>;
  data.forEach(async (member: SkyblockMember) => {
    expect(member).toBeDefined();
    expect(member).toBeInstanceOf(SkyblockMember);
    expectTypeOf(member).toEqualTypeOf<SkyblockMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.gameMode).toBeDefined();
    expectTypeOf(member.gameMode).toEqualTypeOf<string | null>();
    expect(member.selected).toBeDefined();
    expectTypeOf(member.selected).toEqualTypeOf<boolean>();
    expect(member.garden).toBeDefined();
    expectTypeOf(member.garden).toEqualTypeOf<SkyblockGarden | null>();
    expect(member.museum).toBeDefined();
    expect(member.museum).toBeNull();
    expectTypeOf(member.museum).toEqualTypeOf<SkyblockMuseum | null>();
    expect(member.profileName).toBeDefined();
    expectTypeOf(member.profileName).toEqualTypeOf<string>();
    expect(member.profileId).toBeDefined();
    expectTypeOf(member.profileId).toEqualTypeOf<string>();
    expect(member.firstJoinTimestamp).toBeDefined();
    expectTypeOf(member.firstJoinTimestamp).toEqualTypeOf<number | null>();
    expect(member.firstJoinAt).toBeDefined();
    expectTypeOf(member.firstJoinAt).toEqualTypeOf<Date | null>();
    expect(member.experience).toBeDefined();
    expect(member.experience).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.experience).toEqualTypeOf<number>();
    expect(member.level).toBeDefined();
    expectTypeOf(member.level).toEqualTypeOf<number>();
    expect(member.hotm).toBeDefined();
    expectTypeOf(member.hotm).toEqualTypeOf<HOTM>();
    expect(member.highestMagicalPower).toBeDefined();
    expectTypeOf(member.highestMagicalPower).toEqualTypeOf<number>();
    expect(member.fairySouls).toBeDefined();
    expectTypeOf(member.fairySouls).toEqualTypeOf<number>();
    expect(member.fairyExchanges).toBeDefined();
    expectTypeOf(member.fairyExchanges).toEqualTypeOf<number>();
    expect(member.skills).toBeDefined();
    expectTypeOf(member.skills).toEqualTypeOf<Skills>();
    expect(member.bestiary).toBeDefined();
    expectTypeOf(member.bestiary).toEqualTypeOf<number>();
    expect(member.slayer).toBeDefined();
    expectTypeOf(member.slayer).toEqualTypeOf<Slayer | null>();
    expect(member.crimsonIsle).toBeDefined();
    expectTypeOf(member.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
    expect(member.dungeons).toBeDefined();
    expectTypeOf(member.dungeons).toEqualTypeOf<Dungeons>();
    expect(member.collections).toBeDefined();
    expectTypeOf(member.collections).toEqualTypeOf<Record<string, number>>();
    expect(member.purse).toBeDefined();
    expectTypeOf(member.purse).toEqualTypeOf<number>();
    expect(member.stats).toBeDefined();
    expectTypeOf(member.stats).toEqualTypeOf<SkyblockMemberStats>();
    expect(member.pets).toBeDefined();
    expectTypeOf(member.pets).toEqualTypeOf<SkyblockPet[]>();
    member.pets.forEach((pet: SkyblockPet) => {
      expect(pet).toBeDefined();
      expect(pet).toBeInstanceOf(SkyblockPet);
      expectTypeOf(pet).toEqualTypeOf<SkyblockPet>();
      expect(pet.uuid).toBeDefined();
      expectTypeOf(pet.uuid).toEqualTypeOf<string>();
      expect(pet.name).toBeDefined();
      expectTypeOf(pet.name).toEqualTypeOf<string>();
      expect(pet.xp).toBeDefined();
      expect(pet.xp).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.xp).toEqualTypeOf<number>();
      expect(pet.active).toBeDefined();
      expectTypeOf(pet.active).toEqualTypeOf<boolean>();
      expect(pet.rarity).toBeDefined();
      expectTypeOf(pet.rarity).toEqualTypeOf<Rarity>();
      expect(pet.petScore).toBeDefined();
      expect(pet.petScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.petScore).toEqualTypeOf<number>();
      expect(pet.heldItem).toBeDefined();
      expectTypeOf(pet.heldItem).toEqualTypeOf<string | null>();
      expect(pet.candyUsed).toBeDefined();
      expect(pet.candyUsed).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.candyUsed).toEqualTypeOf<number>();
      expect(pet.skin).toBeDefined();
      expectTypeOf(pet.skin).toEqualTypeOf<string | null>();
      expect(pet.toString()).toBeDefined();
      expect(pet.toString()).toBe(pet.name);
      expectTypeOf(pet.toString()).toEqualTypeOf<string>();
    });
    expect(member.jacob).toBeDefined();
    expectTypeOf(member.jacob).toEqualTypeOf<JacobData>();
    expect(member.chocolate).toBeDefined();
    expectTypeOf(member.chocolate).toEqualTypeOf<ChocolateFactoryData>();
    expect(member.getArmor()).toBeDefined();
    expectTypeOf(member.getArmor).toEqualTypeOf<() => Promise<Armor>>();
    expectTypeOf(member.getArmor()).toEqualTypeOf<Promise<Armor>>();
    expect(member.getWardrobe()).toBeDefined();
    expectTypeOf(member.getWardrobe).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getWardrobe()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getEnderChest()).toBeDefined();
    expectTypeOf(member.getEnderChest).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getEnderChest()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getInventory()).toBeDefined();
    expectTypeOf(member.getInventory).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getInventory()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    const inv = await member.getInventory();
    inv.forEach((item: SkyblockInventoryItem) => {
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<string>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
      expect(item.toString()).toBeDefined();
      expect(item.toString()).toBe(item.name);
      expectTypeOf(item.toString()).toEqualTypeOf<string>();
    });
    expect(member.getPetScore()).toBeDefined();
    expectTypeOf(member.getPetScore).toEqualTypeOf<() => number>();
    expect(member.getPetScore()).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.getPetScore()).toEqualTypeOf<number>();
    expect(member.getEquipment()).toBeDefined();
    expectTypeOf(member.getEquipment).toEqualTypeOf<() => Promise<Equipment>>();
    expectTypeOf(member.getEquipment()).toEqualTypeOf<Promise<Equipment>>();
    expect(member.getPersonalVault()).toBeDefined();
    expectTypeOf(member.getPersonalVault).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getPersonalVault()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getNetworth()).toBeDefined();
    expectTypeOf(member.getNetworth).toEqualTypeOf<() => Promise<NetworthResult | null>>();
    expectTypeOf(member.getNetworth()).toEqualTypeOf<Promise<NetworthResult | null>>();
    expect(member.getFarmingWeight()).toBeDefined();
    expectTypeOf(member.getFarmingWeight).toEqualTypeOf<() => number>();
    expect(member.getFarmingWeight()).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.getFarmingWeight()).toEqualTypeOf<number>();
    expect(member.getFarmingWeight()).toBeGreaterThanOrEqual(0);
    expect(member.toString()).toBeDefined();
    expect(member.toString()).toBe(member.uuid);
    expectTypeOf(member.toString()).toEqualTypeOf<string>();
  });
  client.destroy();
});
test('getSkyblockMember', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  let data = await client.getSkyblockMember('14727faefbdc4aff848cd2713eb9939e');
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<Map<string, SkyblockMember> | RequestData>();
  data = data as Map<string, SkyblockMember>;
  data.forEach(async (member: SkyblockMember) => {
    expect(member).toBeDefined();
    expect(member).toBeInstanceOf(SkyblockMember);
    expectTypeOf(member).toEqualTypeOf<SkyblockMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.gameMode).toBeDefined();
    expectTypeOf(member.gameMode).toEqualTypeOf<string | null>();
    expect(member.selected).toBeDefined();
    expectTypeOf(member.selected).toEqualTypeOf<boolean>();
    expect(member.garden).toBeDefined();
    expect(member.garden).toBeNull();
    expectTypeOf(member.garden).toEqualTypeOf<SkyblockGarden | null>();
    expect(member.museum).toBeDefined();
    expect(member.museum).toBeNull();
    expectTypeOf(member.museum).toEqualTypeOf<SkyblockMuseum | null>();
    expect(member.profileName).toBeDefined();
    expectTypeOf(member.profileName).toEqualTypeOf<string>();
    expect(member.profileId).toBeDefined();
    expectTypeOf(member.profileId).toEqualTypeOf<string>();
    expect(member.firstJoinTimestamp).toBeDefined();
    expectTypeOf(member.firstJoinTimestamp).toEqualTypeOf<number | null>();
    expect(member.firstJoinAt).toBeDefined();
    expectTypeOf(member.firstJoinAt).toEqualTypeOf<Date | null>();
    expect(member.experience).toBeDefined();
    expect(member.experience).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.experience).toEqualTypeOf<number>();
    expect(member.level).toBeDefined();
    expectTypeOf(member.level).toEqualTypeOf<number>();
    expect(member.hotm).toBeDefined();
    expectTypeOf(member.hotm).toEqualTypeOf<HOTM>();
    expect(member.highestMagicalPower).toBeDefined();
    expectTypeOf(member.highestMagicalPower).toEqualTypeOf<number>();
    expect(member.fairySouls).toBeDefined();
    expectTypeOf(member.fairySouls).toEqualTypeOf<number>();
    expect(member.fairyExchanges).toBeDefined();
    expectTypeOf(member.fairyExchanges).toEqualTypeOf<number>();
    expect(member.skills).toBeDefined();
    expectTypeOf(member.skills).toEqualTypeOf<Skills>();
    expect(member.bestiary).toBeDefined();
    expectTypeOf(member.bestiary).toEqualTypeOf<number>();
    expect(member.slayer).toBeDefined();
    expectTypeOf(member.slayer).toEqualTypeOf<Slayer | null>();
    expect(member.crimsonIsle).toBeDefined();
    expectTypeOf(member.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
    expect(member.dungeons).toBeDefined();
    expectTypeOf(member.dungeons).toEqualTypeOf<Dungeons>();
    expect(member.collections).toBeDefined();
    expectTypeOf(member.collections).toEqualTypeOf<Record<string, number>>();
    expect(member.purse).toBeDefined();
    expectTypeOf(member.purse).toEqualTypeOf<number>();
    expect(member.stats).toBeDefined();
    expectTypeOf(member.stats).toEqualTypeOf<SkyblockMemberStats>();
    expect(member.pets).toBeDefined();
    expectTypeOf(member.pets).toEqualTypeOf<SkyblockPet[]>();
    member.pets.forEach((pet: SkyblockPet) => {
      expect(pet).toBeDefined();
      expect(pet).toBeInstanceOf(SkyblockPet);
      expectTypeOf(pet).toEqualTypeOf<SkyblockPet>();
      expect(pet.uuid).toBeDefined();
      expectTypeOf(pet.uuid).toEqualTypeOf<string>();
      expect(pet.name).toBeDefined();
      expectTypeOf(pet.name).toEqualTypeOf<string>();
      expect(pet.xp).toBeDefined();
      expect(pet.xp).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.xp).toEqualTypeOf<number>();
      expect(pet.active).toBeDefined();
      expectTypeOf(pet.active).toEqualTypeOf<boolean>();
      expect(pet.rarity).toBeDefined();
      expectTypeOf(pet.rarity).toEqualTypeOf<Rarity>();
      expect(pet.petScore).toBeDefined();
      expect(pet.petScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.petScore).toEqualTypeOf<number>();
      expect(pet.heldItem).toBeDefined();
      expectTypeOf(pet.heldItem).toEqualTypeOf<string | null>();
      expect(pet.candyUsed).toBeDefined();
      expect(pet.candyUsed).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.candyUsed).toEqualTypeOf<number>();
      expect(pet.skin).toBeDefined();
      expectTypeOf(pet.skin).toEqualTypeOf<string | null>();
      expect(pet.toString()).toBeDefined();
      expect(pet.toString()).toBe(pet.name);
      expectTypeOf(pet.toString()).toEqualTypeOf<string>();
    });
    expect(member.jacob).toBeDefined();
    expectTypeOf(member.jacob).toEqualTypeOf<JacobData>();
    expect(member.chocolate).toBeDefined();
    expectTypeOf(member.chocolate).toEqualTypeOf<ChocolateFactoryData>();
    expect(member.getArmor()).toBeDefined();
    expectTypeOf(member.getArmor).toEqualTypeOf<() => Promise<Armor>>();
    expectTypeOf(member.getArmor()).toEqualTypeOf<Promise<Armor>>();
    expect(member.getWardrobe()).toBeDefined();
    expectTypeOf(member.getWardrobe).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getWardrobe()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getEnderChest()).toBeDefined();
    expectTypeOf(member.getEnderChest).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getEnderChest()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getInventory()).toBeDefined();
    expectTypeOf(member.getInventory).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getInventory()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    const inv = await member.getInventory();
    inv.forEach((item: SkyblockInventoryItem) => {
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<string>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
      expect(item.toString()).toBeDefined();
      expect(item.toString()).toBe(item.name);
      expectTypeOf(item.toString()).toEqualTypeOf<string>();
    });
    expect(member.getPetScore()).toBeDefined();
    expectTypeOf(member.getPetScore).toEqualTypeOf<() => number>();
    expect(member.getPetScore()).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.getPetScore()).toEqualTypeOf<number>();
    expect(member.getEquipment()).toBeDefined();
    expectTypeOf(member.getEquipment).toEqualTypeOf<() => Promise<Equipment>>();
    expectTypeOf(member.getEquipment()).toEqualTypeOf<Promise<Equipment>>();
    expect(member.getPersonalVault()).toBeDefined();
    expectTypeOf(member.getPersonalVault).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    expectTypeOf(member.getPersonalVault()).toEqualTypeOf<Promise<SkyblockInventoryItem[]>>();
    expect(member.getNetworth()).toBeDefined();
    expectTypeOf(member.getNetworth).toEqualTypeOf<() => Promise<NetworthResult | null>>();
    expectTypeOf(member.getNetworth()).toEqualTypeOf<Promise<NetworthResult | null>>();
    expect(member.getFarmingWeight()).toBeDefined();
    expectTypeOf(member.getFarmingWeight).toEqualTypeOf<() => number>();
    expect(member.getFarmingWeight()).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.getFarmingWeight()).toEqualTypeOf<number>();
    expect(member.getFarmingWeight()).toBeGreaterThanOrEqual(0);
    expect(member.toString()).toBeDefined();
    expect(member.toString()).toBe(member.uuid);
    expectTypeOf(member.toString()).toEqualTypeOf<string>();
  });
  client.destroy();
});
