import Client from '../Client.js';
import Game from '../Structures/Game.js';
import RequestData from '../Private/RequestData.js';
import Status from '../Structures/Status.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { GameCode, GameID, GameString } from '../Types/Game.js';

test('getStatus', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false });
  client.requestHandler.setBaseURL(process.env.HYPIXEL_URL);
  const data = await client.getStatus('370d6421b761456fadf28c43fe5c4bcf');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(RequestData);
  expectTypeOf(data).toEqualTypeOf<RequestData<Status>>();
  expect(data.parsed.online).toBeDefined();
  expectTypeOf(data.parsed.online).toEqualTypeOf<boolean>();
  expect(data.parsed.game).toBeDefined();
  expectTypeOf(data.parsed.game).toEqualTypeOf<Game | null>();
  if (data.parsed.game) {
    expect(data.parsed.game).toBeDefined();
    expectTypeOf(data.parsed.game).toEqualTypeOf<Game>();
    expect(data.parsed.game.game).toBeDefined();
    expectTypeOf(data.parsed.game.game).toEqualTypeOf<GameID | GameCode>();
    expect(data.parsed.game.id).toBeDefined();
    expectTypeOf(data.parsed.game.id).toEqualTypeOf<GameID | null>();
    expect(data.parsed.game.code).toBeDefined();
    expectTypeOf(data.parsed.game.code).toEqualTypeOf<GameCode | null>();
    expect(data.parsed.game.name).toBeDefined();
    expectTypeOf(data.parsed.game.name).toEqualTypeOf<GameString | null>();
    expect(data.parsed.game.found).toBeDefined();
    expectTypeOf(data.parsed.game.found).toEqualTypeOf<boolean>();
    expect(data.parsed.game.toString()).toBeDefined();
    expect(data.parsed.game.toString()).toBe(data.parsed.game.name);
    expectTypeOf(data.parsed.game.toString()).toEqualTypeOf<GameString | null>();
    expect(Game.IDS).toBeDefined();
    expectTypeOf(Game.IDS).toEqualTypeOf<GameID[]>();
    expect(Game.CODES).toBeDefined();
    expectTypeOf(Game.CODES).toEqualTypeOf<GameCode[]>();
    expect(Game.NAMES).toBeDefined();
    expectTypeOf(Game.NAMES).toEqualTypeOf<GameString[]>();
  }
  expect(data.parsed.mode).toBeDefined();
  expectTypeOf(data.parsed.mode).toEqualTypeOf<string | null>();
  expect(data.parsed.map).toBeDefined();
  expectTypeOf(data.parsed.map).toEqualTypeOf<string | null>();
  expect(data.parsed.toString()).toBeDefined();
  expectTypeOf(data.parsed.toString()).toEqualTypeOf<'Online' | 'Offline'>();
  expect(data.parsed.toString()).toBe(data.parsed.online ? 'Online' : 'Offline');
  client.destroy();
});
