module.exports = {
  getAchievements: require('./getAchievements.js'),
  getAPIStatus: require('./getAPIStatus.js'),
  getBoosters: require('./getBoosters.js'),
  getChallenges: require('./getChallenges.js'),
  getGameCounts: require('./getGameCounts.js'),
  getGuild: require('./getGuild.js'),
  getGuildAchievements: require('./getGuildAchievements.js'),
  getLeaderboards: require('./getLeaderboards.js'),
  getPlayer: require('./getPlayer.js'),
  getQuests: require('./getQuests.js'),
  getRecentGames: require('./getRecentGames.js'),
  getServerInfo: require('./getServerInfo.js'),
  getStatus: require('./getStatus.js'),
  getWatchdogStats: require('./getWatchdogStats.js'),

  getSkyblockAuction: require('./skyblock/getAuction.js'),
  getSkyblockAuctions: require('./skyblock/getAuctions.js'),
  getSkyblockAuctionsByPlayer: require('./skyblock/getAuctionsByPlayer.js'),
  getSkyblockBazaar: require('./skyblock/getBazaar.js'),
  getSkyblockBingo: require('./skyblock/getBingo.js'),
  getSkyblockBingoByPlayer: require('./skyblock/getBingoByPlayer.js'),
  getSkyblockEndedAuctions: require('./skyblock/getEndedAuctions.js'),
  getSkyblockFireSales: require('./skyblock/getFireSales.js'),
  getSkyblockGovernment: require('./skyblock/getGovernment.js'),
  getSkyblockMember: require('./skyblock/getMember.js'),
  getSkyblockMuseum: require('./skyblock/getMuseum.js'),
  getSkyblockNews: require('./skyblock/getNews.js'),
  getSkyblockProfiles: require('./skyblock/getProfiles.js')
};
