module.exports = {
  getAPIStatus: require('./getAPIStatus.js'),
  getAchievements: require('./getAchievements.js'),
  getBoosters: require('./getBoosters.js'),
  getChallenges: require('./getChallenges.js'),
  getFriends: require('./getFriends.js'),
  getGameCounts: require('./getGameCounts.js'),
  getGuild: require('./getGuild.js'),
  getGuildAchievements: require('./getGuildAchievements.js'),
  getKeyInfo: require('./getKeyInfo.js'),
  getLeaderboards: require('./getLeaderboards.js'),
  getPlayer: require('./getPlayer.js'),
  getQuests: require('./getQuests.js'),
  getRankedSkyWars: require('./getRankedSkyWars.js'),
  getRecentGames: require('./getRecentGames.js'),
  getServerInfo: require('./getServerInfo.js'),
  getStatus: require('./getStatus.js'),
  getVanityCompanions: require('./getVanityCompanions.js'),
  getVanityPets: require('./getVanityPets.js'),
  getWatchdogStats: require('./getWatchdogStats.js'),

  skyblock: {
    getEndedSkyblockAuctions: require('./skyblock/getEndedSkyblockAuctions.js'),
    getSkyblockAuction: require('./skyblock/getSkyblockAuction.js'),
    getSkyblockAuctions: require('./skyblock/getSkyblockAuctions.js'),
    getSkyblockAuctionsByPlayer: require('./skyblock/getSkyblockAuctionsByPlayer.js'),
    getSkyblockBazaar: require('./skyblock/getSkyblockBazaar.js'),
    getSkyblockBingo: require('./skyblock/getSkyblockBingo.js'),
    getSkyblockBingoByPlayer: require('./skyblock/getSkyblockBingoByPlayer.js'),
    getSkyblockGovernment: require('./skyblock/getSkyblockGovernment.js'),
    getSkyblockMember: require('./skyblock/getSkyblockMember.js'),
    getSkyblockNews: require('./skyblock/getSkyblockNews.js'),
    getSkyblockProfiles: require('./skyblock/getSkyblockProfiles.js')
  }
};
