import SkyWarsMega from './SkyWarsMega.js';
import SkyWarsMegaKits from './SkyWarsMegaKits.js';
import SkyWarsMode from '../SkyWarsMode/SkyWarsMode.ts';
import SkyWarsModePerk from '../SkyWarsMode/SkyWarsModePerk.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsMega', () => {
  const data = new SkyWarsMega({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsMega);
  expectTypeOf(data).toEqualTypeOf<SkyWarsMega>();
  expect(data.doubles).toBeDefined();
  expect(data.doubles).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.doubles).toEqualTypeOf<SkyWarsMode>();
  expect(data.doublesNormal).toBeDefined();
  expect(data.doublesNormal).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.doublesNormal).toEqualTypeOf<SkyWarsMode>();
  expect(data.normal).toBeDefined();
  expect(data.normal).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.normal).toEqualTypeOf<SkyWarsMode>();
  expect(data.kits).toBeDefined();
  expect(data.kits).toBeInstanceOf(SkyWarsMegaKits);
  expectTypeOf(data.kits).toEqualTypeOf<SkyWarsMegaKits>();
  expect(data.rusher).toBeDefined();
  expect(data.rusher).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.rusher).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.miningExpertise).toBeDefined();
  expect(data.miningExpertise).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.miningExpertise).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.enderMastery).toBeDefined();
  expect(data.enderMastery).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.enderMastery).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.blazingArrows).toBeDefined();
  expect(data.blazingArrows).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.blazingArrows).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.arrowRecovery).toBeDefined();
  expect(data.arrowRecovery).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.arrowRecovery).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.juggernaut).toBeDefined();
  expect(data.juggernaut).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.juggernaut).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.tank).toBeDefined();
  expect(data.tank).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.tank).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.nourishment).toBeDefined();
  expect(data.nourishment).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.nourishment).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.notoriety).toBeDefined();
  expect(data.notoriety).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.notoriety).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.instantSmelting).toBeDefined();
  expect(data.instantSmelting).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.instantSmelting).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.marksmanship).toBeDefined();
  expect(data.marksmanship).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.marksmanship).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.environmentalExpert).toBeDefined();
  expect(data.environmentalExpert).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.environmentalExpert).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.bridger).toBeDefined();
  expect(data.bridger).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.bridger).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.luckyCharm).toBeDefined();
  expect(data.luckyCharm).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.luckyCharm).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.blackMagic).toBeDefined();
  expect(data.blackMagic).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.blackMagic).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.necromancer).toBeDefined();
  expect(data.necromancer).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.necromancer).toEqualTypeOf<SkyWarsModePerk>();
  expect(data.telekinesis).toBeDefined();
  expect(data.telekinesis).toBeInstanceOf(SkyWarsModePerk);
  expectTypeOf(data.telekinesis).toEqualTypeOf<SkyWarsModePerk>();
});
