import BaseSkyWarsMode from '../SkyWarsMode/BaseSkyWarsMode.js';
import SkyWarsMegaKits from './SkyWarsMegaKits.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsMegaKits', () => {
  const data = new SkyWarsMegaKits({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsMegaKits);
  expectTypeOf(data).toEqualTypeOf<SkyWarsMegaKits>();
  expect(data.default).toBeDefined();
  expect(data.default).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.default).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.hunter).toBeDefined();
  expect(data.hunter).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.hunter).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.baseballPlayer).toBeDefined();
  expect(data.baseballPlayer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.baseballPlayer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.armorer).toBeDefined();
  expect(data.armorer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.armorer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.knight).toBeDefined();
  expect(data.knight).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.knight).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.cannoneer).toBeDefined();
  expect(data.cannoneer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.cannoneer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.hellhound).toBeDefined();
  expect(data.hellhound).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.hellhound).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.witch).toBeDefined();
  expect(data.witch).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.witch).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.fisherman).toBeDefined();
  expect(data.fisherman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.fisherman).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.armorsmith).toBeDefined();
  expect(data.armorsmith).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.armorsmith).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.pyromaniac).toBeDefined();
  expect(data.pyromaniac).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.pyromaniac).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.paladin).toBeDefined();
  expect(data.paladin).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.paladin).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.healer).toBeDefined();
  expect(data.healer).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.healer).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.skeletor).toBeDefined();
  expect(data.skeletor).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.skeletor).toEqualTypeOf<BaseSkyWarsMode>();
  expect(data.enderman).toBeDefined();
  expect(data.enderman).toBeInstanceOf(BaseSkyWarsMode);
  expectTypeOf(data.enderman).toEqualTypeOf<BaseSkyWarsMode>();
});
