import SkyWarsMegaKits from './SkyWarsMegaKits.js';
import SkyWarsMode from '../SkyWarsMode/SkyWarsMode.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyWarsMegaKits', () => {
  const data = new SkyWarsMegaKits({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyWarsMegaKits);
  expectTypeOf(data).toEqualTypeOf<SkyWarsMegaKits>();
  expect(data.default).toBeDefined();
  expect(data.default).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.default).toEqualTypeOf<SkyWarsMode>();
  expect(data.hunter).toBeDefined();
  expect(data.hunter).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.hunter).toEqualTypeOf<SkyWarsMode>();
  expect(data.scout).toBeDefined();
  expect(data.scout).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.scout).toEqualTypeOf<SkyWarsMode>();
  expect(data.baseballPlayer).toBeDefined();
  expect(data.baseballPlayer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.baseballPlayer).toEqualTypeOf<SkyWarsMode>();
  expect(data.armorer).toBeDefined();
  expect(data.armorer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.armorer).toEqualTypeOf<SkyWarsMode>();
  expect(data.knight).toBeDefined();
  expect(data.knight).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.knight).toEqualTypeOf<SkyWarsMode>();
  expect(data.cannoneer).toBeDefined();
  expect(data.cannoneer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.cannoneer).toEqualTypeOf<SkyWarsMode>();
  expect(data.hellhound).toBeDefined();
  expect(data.hellhound).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.hellhound).toEqualTypeOf<SkyWarsMode>();
  expect(data.witch).toBeDefined();
  expect(data.witch).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.witch).toEqualTypeOf<SkyWarsMode>();
  expect(data.fisherman).toBeDefined();
  expect(data.fisherman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.fisherman).toEqualTypeOf<SkyWarsMode>();
  expect(data.armorsmith).toBeDefined();
  expect(data.armorsmith).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.armorsmith).toEqualTypeOf<SkyWarsMode>();
  expect(data.pyromaniac).toBeDefined();
  expect(data.pyromaniac).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.pyromaniac).toEqualTypeOf<SkyWarsMode>();
  expect(data.paladin).toBeDefined();
  expect(data.paladin).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.paladin).toEqualTypeOf<SkyWarsMode>();
  expect(data.healer).toBeDefined();
  expect(data.healer).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.healer).toEqualTypeOf<SkyWarsMode>();
  expect(data.skeletor).toBeDefined();
  expect(data.skeletor).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.skeletor).toEqualTypeOf<SkyWarsMode>();
  expect(data.enderman).toBeDefined();
  expect(data.enderman).toBeInstanceOf(SkyWarsMode);
  expectTypeOf(data.enderman).toEqualTypeOf<SkyWarsMode>();
});
