import DuelsMode from './DuelsMode.js';
import DuelsModeFull from './DuelsModeFull.js';

class DuelsBedWars extends DuelsModeFull {
  normal: DuelsMode;
  rush: DuelsMode;
  bedsBroken: number;
  bedsLost: number;
  blockExplosionDeaths: number;
  blockExplosionFinalDeaths: number;
  blockExplosionFinalKills: number;
  comboDuelLongestCombo: number;
  drowningFinalDeaths: number;
  drowningFinalKills: number;
  entityAttackDeaths: number;
  entityAttackFinalDeaths: number;
  entityAttackFinalKills: number;
  entityAttackKills: number;
  entityExplosionDeaths: number;
  entityExplosionFinalDeaths: number;
  entityExplosionFinalKills: number;
  entityExplosionKills: number;
  fallDeaths: number;
  fallFinalDeaths: number;
  fallFinalKills: number;
  fallKills: number;
  finalDeaths: number;
  finalKills: number;
  fireDeaths: number;
  fireFinalDeaths: number;
  fireFinalKills: number;
  fireKills: number;
  fireTickDeaths: number;
  fireTickFinalDeaths: number;
  fireTickFinalKills: number;
  fireTickKills: number;
  gamesPlayed: number;
  itemsPurchased: number;
  magicDeaths: number;
  magicFinalDeaths: number;
  magicFinalKills: number;
  magicKills: number;
  permanentItemsPurchased: number;
  projectileDeaths: number;
  projectileFinalDeaths: number;
  projectileFinalKills: number;
  projectileKills: number;
  suffocationDeaths: number;
  suffocationFinalDeaths: number;
  voidDeaths: number;
  voidFinalDeaths: number;
  voidFinalKills: number;
  voidKills: number;
  constructor(data: Record<string, any>) {
    super(data, 'bedwars');
    this.normal = new DuelsMode(data, 'bedwars_two_one_duels');
    this.rush = new DuelsMode(data, 'bedwars_two_one_duels_rush');
    this.bedsBroken = data?.beds_broken_bedwars ?? 0;
    this.bedsLost = data?.beds_lost_bedwars ?? 0;
    this.blockExplosionDeaths = data?.block_explosion_deaths_bedwars ?? 0;
    this.blockExplosionFinalDeaths = data?.block_explosion_final_deaths_bedwars ?? 0;
    this.blockExplosionFinalKills = data?.block_explosion_final_kills_bedwars ?? 0;
    this.comboDuelLongestCombo = data?.combo_duel_longest_combo ?? 0;
    this.drowningFinalDeaths = data?.drowning_final_deaths_bedwars ?? 0;
    this.drowningFinalKills = data?.drowning_final_kills_bedwars ?? 0;
    this.entityAttackDeaths = data?.entity_attack_deaths_bedwars ?? 0;
    this.entityAttackFinalDeaths = data?.entity_attack_final_deaths_bedwars ?? 0;
    this.entityAttackFinalKills = data?.entity_attack_final_kills_bedwars ?? 0;
    this.entityAttackKills = data?.entity_attack_kills_bedwars ?? 0;
    this.entityExplosionDeaths = data?.entity_explosion_deaths_bedwars ?? 0;
    this.entityExplosionFinalDeaths = data?.entity_explosion_final_deaths_bedwars ?? 0;
    this.entityExplosionFinalKills = data?.entity_explosion_final_kills_bedwars ?? 0;
    this.entityExplosionKills = data?.entity_explosion_kills_bedwars ?? 0;
    this.fallDeaths = data?.fall_deaths_bedwars ?? 0;
    this.fallFinalDeaths = data?.fall_final_deaths_bedwars ?? 0;
    this.fallFinalKills = data?.fall_final_kills_bedwars ?? 0;
    this.fallKills = data?.fall_kills_bedwars ?? 0;
    this.finalDeaths = data?.final_deaths_bedwars ?? 0;
    this.finalKills = data?.final_kills_bedwars ?? 0;
    this.fireDeaths = data?.fire_deaths_bedwars ?? 0;
    this.fireFinalDeaths = data?.fire_final_deaths_bedwars ?? 0;
    this.fireFinalKills = data?.fire_final_kills_bedwars ?? 0;
    this.fireKills = data?.fire_kills_bedwars ?? 0;
    this.fireTickDeaths = data?.fire_tick_deaths_bedwars ?? 0;
    this.fireTickFinalDeaths = data?.fire_tick_final_deaths_bedwars ?? 0;
    this.fireTickFinalKills = data?.fire_tick_final_kills_bedwars ?? 0;
    this.fireTickKills = data?.fire_tick_kills_bedwars ?? 0;
    this.gamesPlayed = data?.games_played_bedwars ?? 0;
    this.itemsPurchased = data?.items_purchased_bedwars ?? 0;
    this.magicDeaths = data?.magic_deaths_bedwars ?? 0;
    this.magicFinalDeaths = data?.magic_final_deaths_bedwars ?? 0;
    this.magicFinalKills = data?.magic_final_kills_bedwars ?? 0;
    this.magicKills = data?.magic_kills_bedwars ?? 0;
    this.permanentItemsPurchased = data?.permanent_items_purchased_bedwars ?? 0;
    this.projectileDeaths = data?.projectile_deaths_bedwars ?? 0;
    this.projectileFinalDeaths = data?.projectile_final_deaths_bedwars ?? 0;
    this.projectileFinalKills = data?.projectile_final_kills_bedwars ?? 0;
    this.projectileKills = data?.projectile_kills_bedwars ?? 0;
    this.suffocationDeaths = data?.suffocation_deaths_bedwars ?? 0;
    this.suffocationFinalDeaths = data?.suffocation_final_deaths_bedwars ?? 0;
    this.voidDeaths = data?.void_deaths_bedwars ?? 0;
    this.voidFinalDeaths = data?.void_final_deaths_bedwars ?? 0;
    this.voidFinalKills = data?.void_final_kills_bedwars ?? 0;
    this.voidKills = data?.void_kills_bedwars ?? 0;
  }
}

export default DuelsBedWars;
