import CaptureTheWool from './CaptureTheWool.js';
import { expect, expectTypeOf, test } from 'vitest';

test('CaptureTheWool', () => {
  const data = new CaptureTheWool({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(CaptureTheWool);
  expectTypeOf(data).toEqualTypeOf<CaptureTheWool>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.assists).toBeDefined();
  expect(data.assists).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.assists).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDRatio).toBeDefined();
  expect(data.KDRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDRatio).toEqualTypeOf<number>();
  expect(data.killsWithWool).toBeDefined();
  expect(data.killsWithWool).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsWithWool).toEqualTypeOf<number>();
  expect(data.deathsWithWool).toBeDefined();
  expect(data.deathsWithWool).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsWithWool).toEqualTypeOf<number>();
  expect(data.KDRatioWithWool).toBeDefined();
  expect(data.KDRatioWithWool).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDRatioWithWool).toEqualTypeOf<number>();
  expect(data.woolCaptured).toBeDefined();
  expect(data.woolCaptured).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.woolCaptured).toEqualTypeOf<number>();
  expect(data.woolStolen).toBeDefined();
  expect(data.woolStolen).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.woolStolen).toEqualTypeOf<number>();
  expect(data.woolCaptureStolenRatio).toBeDefined();
  expect(data.woolCaptureStolenRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.woolCaptureStolenRatio).toEqualTypeOf<number>();
});
