import SheepWars from './SheepWars.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SheepWars', () => {
  const data = new SheepWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SheepWars);
  expectTypeOf(data).toEqualTypeOf<SheepWars>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.killsVoid).toBeDefined();
  expect(data.killsVoid).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsVoid).toEqualTypeOf<number>();
  expect(data.killsBow).toBeDefined();
  expect(data.killsBow).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsBow).toEqualTypeOf<number>();
  expect(data.killsExplosive).toBeDefined();
  expect(data.killsExplosive).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsExplosive).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.deathsVoid).toBeDefined();
  expect(data.deathsVoid).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsVoid).toEqualTypeOf<number>();
  expect(data.deathsMelee).toBeDefined();
  expect(data.deathsMelee).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsMelee).toEqualTypeOf<number>();
  expect(data.deathsExplosive).toBeDefined();
  expect(data.deathsExplosive).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsExplosive).toEqualTypeOf<number>();
  expect(data.KDRatio).toBeDefined();
  expect(data.KDRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDRatio).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.WLRatio).toBeDefined();
  expect(data.WLRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.WLRatio).toEqualTypeOf<number>();
  expect(data.gamesPlayed).toBeDefined();
  expect(data.gamesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gamesPlayed).toEqualTypeOf<number>();
  expect(data.damageDealt).toBeDefined();
  expect(data.damageDealt).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageDealt).toEqualTypeOf<number>();
  expect(data.sheepThrown).toBeDefined();
  expect(data.sheepThrown).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sheepThrown).toEqualTypeOf<number>();
  expect(data.magicWoolHit).toBeDefined();
  expect(data.magicWoolHit).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.magicWoolHit).toEqualTypeOf<number>();
});
