import WoolWars from './WoolWars.js';
import WoolWarsClass from './WoolWarsClass.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { WoolWarsClassNames } from '../../../Types/Player.js';

test('WoolWars', () => {
  const data = new WoolWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(WoolWars);
  expectTypeOf(data).toEqualTypeOf<WoolWars>();
  expect(data.selectedClass).toBeDefined();
  expectTypeOf(data.selectedClass).toEqualTypeOf<WoolWarsClassNames | 'None'>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.assists).toBeDefined();
  expect(data.assists).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.assists).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDRatio).toBeDefined();
  expect(data.KDRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDRatio).toEqualTypeOf<number>();
  expect(data.gamesPlayed).toBeDefined();
  expect(data.gamesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gamesPlayed).toEqualTypeOf<number>();
  expect(data.woolsPlaced).toBeDefined();
  expect(data.woolsPlaced).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.woolsPlaced).toEqualTypeOf<number>();
  expect(data.blocksBroken).toBeDefined();
  expect(data.blocksBroken).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.blocksBroken).toEqualTypeOf<number>();
  expect(data.placeBreakRatio).toBeDefined();
  expect(data.placeBreakRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.placeBreakRatio).toEqualTypeOf<number>();
  expect(data.powerUps).toBeDefined();
  expect(data.powerUps).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.powerUps).toEqualTypeOf<number>();
  expect(data.assault).toBeDefined();
  expect(data.assault).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.assault).toEqualTypeOf<WoolWarsClass>();
  expect(data.tank).toBeDefined();
  expect(data.tank).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.tank).toEqualTypeOf<WoolWarsClass>();
  expect(data.golem).toBeDefined();
  expect(data.golem).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.golem).toEqualTypeOf<WoolWarsClass>();
  expect(data.swordsman).toBeDefined();
  expect(data.swordsman).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.swordsman).toEqualTypeOf<WoolWarsClass>();
  expect(data.engineer).toBeDefined();
  expect(data.engineer).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.engineer).toEqualTypeOf<WoolWarsClass>();
  expect(data.archer).toBeDefined();
  expect(data.archer).toBeInstanceOf(WoolWarsClass);
  expectTypeOf(data.archer).toEqualTypeOf<WoolWarsClass>();
});
