import DuelsBridge from './DuelsBridge.js';
import DuelsBridgeMode from './DuelsBridgeMode.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { DuelsBridgeMap } from '../../../../../Types/Player.js';

test('DuelsBridge', () => {
  const data = new DuelsBridge({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(DuelsBridge);
  expectTypeOf(data).toEqualTypeOf<DuelsBridge>();
  expect(data.duel).toBeDefined();
  expect(data.duel).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.duel).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.doubles).toBeDefined();
  expect(data.doubles).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.doubles).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.threes).toBeDefined();
  expect(data.threes).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.threes).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.four).toBeDefined();
  expect(data.four).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.four).toEqualTypeOf<DuelsBridgeMode>();
  expect(data['2v2v2v2']).toBeDefined();
  expect(data['2v2v2v2']).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data['2v2v2v2']).toEqualTypeOf<DuelsBridgeMode>();
  expect(data['3v3v3v3']).toBeDefined();
  expect(data['3v3v3v3']).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data['3v3v3v3']).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.tournament).toBeDefined();
  expect(data.tournament).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.tournament).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.capture).toBeDefined();
  expect(data.capture).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.capture).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.captureThrees).toBeDefined();
  expect(data.captureThrees).toBeInstanceOf(DuelsBridgeMode);
  expectTypeOf(data.captureThrees).toEqualTypeOf<DuelsBridgeMode>();
  expect(data.bridgeMapWins).toBeDefined();
  expectTypeOf(data.bridgeMapWins).toEqualTypeOf<DuelsBridgeMap[]>();
});
