const i = {
  default: '⋆',
  angel_1: '★',
  angel_2: '☆',
  angel_3: '⁕',
  angel_4: '✶',
  angel_5: '✳',
  angel_6: '✴',
  angel_7: '✷',
  angel_8: '❋',
  angel_9: '✼',
  angel_10: '❂',
  angel_11: '❁',
  angel_12: '☬',
  iron_prestige: '✙',
  gold_prestige: '❤️',
  diamond_prestige: '☠',
  emerald_prestige: '✦',
  sapphire_prestige: '✌',
  ruby_prestige: '❦',
  crystal_prestige: '✵',
  opal_prestige: '❣',
  amethyst_prestige: '☯',
  rainbow_prestige: '✺',
  mythic_prestige: 'ಠ_ಠ',
  favor_of_the_angel_prestige: '⚔'
};
module.exports = i;
