import SkyBlockMemberDungeonsFloor from './SkyBlockMemberDungeonsFloor.js';
import SkyBlockMemberDungeonsFloorRun from './SkyBlockMemberDungeonsFloorRun.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberDungeonsFloor', () => {
  const data = new SkyBlockMemberDungeonsFloor({ stats: 'meow' }, '0');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberDungeonsFloor);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberDungeonsFloor>();
  expect(data.timesPlayed).toBeDefined();
  expect(data.timesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.timesPlayed).toEqualTypeOf<number>();
  expect(data.bestRuns).toBeDefined();
  expectTypeOf(data.bestRuns).toEqualTypeOf<SkyBlockMemberDungeonsFloorRun[]>();
  expect(data.bestScore).toBeDefined();
  expect(data.bestScore).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bestScore).toEqualTypeOf<number>();
  expect(data.mobsKilled).toBeDefined();
  expect(data.mobsKilled).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mobsKilled).toEqualTypeOf<number>();
  expect(data.mostMobsKilled).toBeDefined();
  expect(data.mostMobsKilled).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostMobsKilled).toEqualTypeOf<number>();
  expect(data.mostDamageBerserk).toBeDefined();
  expect(data.mostDamageBerserk).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostDamageBerserk).toEqualTypeOf<number>();
  expect(data.mostDamageMage).toBeDefined();
  expect(data.mostDamageMage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostDamageMage).toEqualTypeOf<number>();
  expect(data.mostDamageHealer).toBeDefined();
  expect(data.mostDamageHealer).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostDamageHealer).toEqualTypeOf<number>();
  expect(data.mostDamageArcher).toBeDefined();
  expect(data.mostDamageArcher).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostDamageArcher).toEqualTypeOf<number>();
  expect(data.mostDamageTank).toBeDefined();
  expect(data.mostDamageTank).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostDamageTank).toEqualTypeOf<number>();
  expect(data.mostHealing).toBeDefined();
  expect(data.mostHealing).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mostHealing).toEqualTypeOf<number>();
  expect(data.watcherKills).toBeDefined();
  expect(data.watcherKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.watcherKills).toEqualTypeOf<number>();
  expect(data.fastestTimeS).toBeDefined();
  expect(data.fastestTimeS).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fastestTimeS).toEqualTypeOf<number>();
  expect(data.fastestTimeSPlus).toBeDefined();
  expect(data.fastestTimeSPlus).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fastestTimeSPlus).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.timesPlayed);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
