import SkyblockMemberDungeonsFloor from './SkyblockMemberDungeonsFloor.js';
import SkyblockMemberDungeonsMode from './SkyblockMemberDungeonsMode.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyblockMemberDungeonsMode', () => {
  const data = new SkyblockMemberDungeonsMode({ stats: 'meow' }, 'catacombs');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyblockMemberDungeonsMode);
  expectTypeOf(data).toEqualTypeOf<SkyblockMemberDungeonsMode>();
  expect(data.highestFloorCompleted).toBeDefined();
  expectTypeOf(data.highestFloorCompleted).toEqualTypeOf<number>();
  expect(data.floor0).toBeDefined();
  expectTypeOf(data.floor0).toEqualTypeOf<SkyblockMemberDungeonsFloor | null>();
  expect(data.floor1).toBeDefined();
  expectTypeOf(data.floor1).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.floor2).toBeDefined();
  expectTypeOf(data.floor2).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.floor3).toBeDefined();
  expectTypeOf(data.floor3).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.floor4).toBeDefined();
  expectTypeOf(data.floor4).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.floor5).toBeDefined();
  expectTypeOf(data.floor5).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.floor6).toBeDefined();
  expectTypeOf(data.floor6).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.floor7).toBeDefined();
  expectTypeOf(data.floor7).toEqualTypeOf<SkyblockMemberDungeonsFloor>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toEqual(data.highestFloorCompleted);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
