import SkyBlockMemberDungeonsFloorRun from './SkyBlockMemberDungeonsFloorRun.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { DungeonClass } from '../../../../Types/SkyBlock.js';
import type { UUID } from '../../../../Types/Global.js';

test('SkyBlockMemberDungeonsFloorRun', () => {
  const data = new SkyBlockMemberDungeonsFloorRun({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberDungeonsFloorRun);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberDungeonsFloorRun>();
  expect(data.timestamp).toBeDefined();
  expect(data.timestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.timestamp).toEqualTypeOf<number>();
  expect(data.explorationScore).toBeDefined();
  expect(data.explorationScore).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.explorationScore).toEqualTypeOf<number>();
  expect(data.speedScore).toBeDefined();
  expect(data.speedScore).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.speedScore).toEqualTypeOf<number>();
  expect(data.skillScore).toBeDefined();
  expect(data.skillScore).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.skillScore).toEqualTypeOf<number>();
  expect(data.bonusScore).toBeDefined();
  expect(data.bonusScore).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bonusScore).toEqualTypeOf<number>();
  expect(data.score).toBeDefined();
  expect(data.score).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.score).toEqualTypeOf<number>();
  expect(data.selectedClass).toBeDefined();
  expectTypeOf(data.selectedClass).toEqualTypeOf<DungeonClass>();
  expect(data.teammates).toBeDefined();
  expectTypeOf(data.teammates).toEqualTypeOf<UUID[]>();
  expect(data.elapsedTime).toBeDefined();
  expect(data.elapsedTime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.elapsedTime).toEqualTypeOf<number>();
  expect(data.damageDealt).toBeDefined();
  expect(data.damageDealt).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageDealt).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.mobsKilled).toBeDefined();
  expect(data.mobsKilled).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mobsKilled).toEqualTypeOf<number>();
  expect(data.secretsFound).toBeDefined();
  expect(data.secretsFound).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.secretsFound).toEqualTypeOf<number>();
  expect(data.damageMitigated).toBeDefined();
  expect(data.damageMitigated).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageMitigated).toEqualTypeOf<number>();
  expect(data.allyHealing).toBeDefined();
  expect(data.allyHealing).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.allyHealing).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.score);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
