import BedWarsBeds from './BedWarsBeds.js';
import BedWarsKillsDeaths from './BedWarsKillsDeaths/BedWarsKillsDeaths.js';
import BedWarsMode from './BedWarsMode.js';
import BedWarsResourcesCollected from './BedWarsResourcesCollected.js';
import { expect, expectTypeOf, test } from 'vitest';

test('BedWarsMode', () => {
  const data = new BedWarsMode({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data).toEqualTypeOf<BedWarsMode>();
  expect(data.resourcesCollected).toBeDefined();
  expect(data.resourcesCollected).toBeInstanceOf(BedWarsResourcesCollected);
  expectTypeOf(data.resourcesCollected).toEqualTypeOf<BedWarsResourcesCollected>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeInstanceOf(BedWarsKillsDeaths);
  expectTypeOf(data.kills).toEqualTypeOf<BedWarsKillsDeaths>();
  expect(data.finals).toBeDefined();
  expect(data.finals).toBeInstanceOf(BedWarsKillsDeaths);
  expectTypeOf(data.finals).toEqualTypeOf<BedWarsKillsDeaths>();
  expect(data.beds).toBeDefined();
  expect(data.beds).toBeInstanceOf(BedWarsBeds);
  expectTypeOf(data.beds).toEqualTypeOf<BedWarsBeds>();
  expect(data.winstreak).toBeDefined();
  expect(data.winstreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winstreak).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.winLossRatio).toBeDefined();
  expect(data.winLossRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winLossRatio).toEqualTypeOf<number>();
  expect(data.gamesPlayed).toBeDefined();
  expect(data.gamesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gamesPlayed).toEqualTypeOf<number>();
});
