import BedWarsBoxes from './BedWarsBoxes.js';
import { expect, expectTypeOf, test } from 'vitest';

test('BedWarsBoxes', () => {
  const data = new BedWarsBoxes({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsBoxes);
  expectTypeOf(data).toEqualTypeOf<BedWarsBoxes>();
  expect(data.openedChests).toBeDefined();
  expect(data.openedChests).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.openedChests).toEqualTypeOf<number>();
  expect(data.openedCommons).toBeDefined();
  expect(data.openedCommons).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.openedCommons).toEqualTypeOf<number>();
  expect(data.openedEpics).toBeDefined();
  expect(data.openedEpics).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.openedEpics).toEqualTypeOf<number>();
  expect(data.openedLegendaries).toBeDefined();
  expect(data.openedLegendaries).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.openedLegendaries).toEqualTypeOf<number>();
  expect(data.openedRares).toBeDefined();
  expect(data.openedRares).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.openedRares).toEqualTypeOf<number>();
  expect(data.box).toBeDefined();
  expect(data.box).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.box).toEqualTypeOf<number>();
  expect(data.commons).toBeDefined();
  expect(data.commons).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.commons).toEqualTypeOf<number>();
  expect(data.epics).toBeDefined();
  expect(data.epics).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.epics).toEqualTypeOf<number>();
  expect(data.legendaries).toBeDefined();
  expect(data.legendaries).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.legendaries).toEqualTypeOf<number>();
  expect(data.rares).toBeDefined();
  expect(data.rares).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.rares).toEqualTypeOf<number>();
  expect(data.boxes).toBeDefined();
  expect(data.boxes).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.boxes).toEqualTypeOf<number>();
  expect(data.christmas).toBeDefined();
  expect(data.christmas).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.christmas).toEqualTypeOf<number>();
  expect(data.easter).toBeDefined();
  expect(data.easter).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.easter).toEqualTypeOf<number>();
  expect(data.golden).toBeDefined();
  expect(data.golden).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.golden).toEqualTypeOf<number>();
  expect(data.halloween).toBeDefined();
  expect(data.halloween).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.halloween).toEqualTypeOf<number>();
  expect(data.lunar).toBeDefined();
  expect(data.lunar).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.lunar).toEqualTypeOf<number>();
});
