import BedWarsBeds from './BedWarsBeds.js';
import BedWarsMode from './BedWarsMode.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { BedWarsGamemodeName } from '../../../Types/Player.js';

test('BedWarsMode', () => {
  const data = new BedWarsMode({ stats: 'meow' }, 'castle');
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data).toEqualTypeOf<BedWarsMode>();
  expect(data.mode).toBeDefined();
  expectTypeOf(data.mode).toEqualTypeOf<BedWarsGamemodeName>();
  expect(data.winStreak).toBeDefined();
  expect(data.winStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winStreak).toEqualTypeOf<number>();
  expect(data.playedGames).toBeDefined();
  expect(data.playedGames).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.playedGames).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.finalKills).toBeDefined();
  expect(data.finalKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.finalKills).toEqualTypeOf<number>();
  expect(data.finalDeaths).toBeDefined();
  expect(data.finalDeaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.finalDeaths).toEqualTypeOf<number>();
  expect(data.beds).toBeDefined();
  expect(data.beds).toBeInstanceOf(BedWarsBeds);
  expectTypeOf(data.beds).toEqualTypeOf<BedWarsBeds>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.WLR).toBeDefined();
  expect(data.WLR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.WLR).toEqualTypeOf<number>();
  expect(data.FKDR).toBeDefined();
  expect(data.FKDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.FKDR).toEqualTypeOf<number>();
});
