import BedWarsFavorites from './BedWarsFavorites.js';
import { expect, expectTypeOf, test } from 'vitest';

test('BedWarsFavorites', () => {
  const data = new BedWarsFavorites({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsFavorites);
  expectTypeOf(data).toEqualTypeOf<BedWarsFavorites>();
  expect(data.streakSlots).toBeDefined();
  expectTypeOf(data.streakSlots).toEqualTypeOf<string[]>();
  expect(data.hotbarSlots).toBeDefined();
  expectTypeOf(data.hotbarSlots).toEqualTypeOf<string[]>();
  expect(data.shopSlots).toBeDefined();
  expectTypeOf(data.shopSlots).toEqualTypeOf<string[]>();
  expect(data.shopSlots2).toBeDefined();
  expectTypeOf(data.shopSlots2).toEqualTypeOf<string[]>();
  expect(data.bedDestroy).toBeDefined();
  expectTypeOf(data.bedDestroy).toEqualTypeOf<string[]>();
  expect(data.deathcry).toBeDefined();
  expectTypeOf(data.deathcry).toEqualTypeOf<string[]>();
  expect(data.figurine).toBeDefined();
  expectTypeOf(data.figurine).toEqualTypeOf<string[]>();
  expect(data.glyph).toBeDefined();
  expectTypeOf(data.glyph).toEqualTypeOf<string[]>();
  expect(data.islandTopper).toBeDefined();
  expectTypeOf(data.islandTopper).toEqualTypeOf<string[]>();
  expect(data.killEffect).toBeDefined();
  expectTypeOf(data.killEffect).toEqualTypeOf<string[]>();
  expect(data.killMessages).toBeDefined();
  expectTypeOf(data.killMessages).toEqualTypeOf<string[]>();
  expect(data.npcSkin).toBeDefined();
  expectTypeOf(data.npcSkin).toEqualTypeOf<string[]>();
  expect(data.projectileTrail).toBeDefined();
  expectTypeOf(data.projectileTrail).toEqualTypeOf<string[]>();
  expect(data.sprays).toBeDefined();
  expectTypeOf(data.sprays).toEqualTypeOf<string[]>();
  expect(data.startingWeapon).toBeDefined();
  expectTypeOf(data.startingWeapon).toEqualTypeOf<string[]>();
  expect(data.victoryDance).toBeDefined();
  expectTypeOf(data.victoryDance).toEqualTypeOf<string[]>();
  expect(data.woodSkin).toBeDefined();
  expectTypeOf(data.woodSkin).toEqualTypeOf<string[]>();
});
