import BedWarsEightTwo from './BedWarsEightTwo.js';
import BedWarsMode from './BedWarsMode.js';
import { expect, expectTypeOf, test } from 'vitest';

test('BedWarsEightTwo', () => {
  const data = new BedWarsEightTwo({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsEightTwo);
  expectTypeOf(data).toEqualTypeOf<BedWarsEightTwo>();
  expect(data.tourney1).toBeDefined();
  expect(data.tourney1).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.tourney1).toEqualTypeOf<BedWarsMode>();
  expect(data.tourney0).toBeDefined();
  expect(data.tourney0).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.tourney0).toEqualTypeOf<BedWarsMode>();
  expect(data.tourney).toBeDefined();
  expect(data.tourney).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.tourney).toEqualTypeOf<BedWarsMode>();
  expect(data.armed).toBeDefined();
  expect(data.armed).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.armed).toEqualTypeOf<BedWarsMode>();
  expect(data.lucky).toBeDefined();
  expect(data.lucky).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.lucky).toEqualTypeOf<BedWarsMode>();
  expect(data.rush).toBeDefined();
  expect(data.rush).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.rush).toEqualTypeOf<BedWarsMode>();
  expect(data.swap).toBeDefined();
  expect(data.swap).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.swap).toEqualTypeOf<BedWarsMode>();
  expect(data.ultimate).toBeDefined();
  expect(data.ultimate).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.ultimate).toEqualTypeOf<BedWarsMode>();
  expect(data.underworld).toBeDefined();
  expect(data.underworld).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.underworld).toEqualTypeOf<BedWarsMode>();
  expect(data.voidless).toBeDefined();
  expect(data.voidless).toBeInstanceOf(BedWarsMode);
  expectTypeOf(data.voidless).toEqualTypeOf<BedWarsMode>();
});
