class PlayerCosmeticsPetsConsumables {
  cake: number;
  cookie: number;
  feather: number;
  goldRecord: number;
  hayBlock: number;
  lavaBucket: number;
  leash: number;
  magmaCream: number;
  melon: number;
  milkBucket: number;
  mushroomSoup: number;
  pork: number;
  pumpkinPie: number;
  rawFish: number;
  slimeBall: number;
  stick: number;
  waterBucket: number;
  woodSword: number;
  apple: number;
  bakedPotato: number;
  cookedBeef: number;
  redRose: number;
  wheat: number;
  bread: number;
  carrot: number;
  rottenFlesh: number;
  bone: number;
  constructor(data: Record<string, any>) {
    this.cake = data?.CAKE || 0;
    this.cookie = data?.COOKIE || 0;
    this.feather = data?.FEATHER || 0;
    this.goldRecord = data?.GOLD_RECORD || 0;
    this.hayBlock = data?.HAY_BLOCK || 0;
    this.lavaBucket = data?.LAVA_BUCKET || 0;
    this.leash = data?.LEASH || 0;
    this.magmaCream = data?.MAGMA_CREAM || 0;
    this.melon = data?.MELON || 0;
    this.milkBucket = data?.MILK_BUCKET || 0;
    this.mushroomSoup = data?.MUSHROOM_SOUP || 0;
    this.pork = data?.PORK || 0;
    this.pumpkinPie = data?.PUMPKIN_PIE || 0;
    this.rawFish = data?.RAW_FISH || 0;
    this.slimeBall = data?.SLIME_BALL || 0;
    this.stick = data?.STICK || 0;
    this.waterBucket = data?.WATER_BUCKET || 0;
    this.woodSword = data?.WOOD_SWORD || 0;
    this.apple = data?.APPLE || 0;
    this.bakedPotato = data?.BAKED_POTATO || 0;
    this.cookedBeef = data?.COOKED_BEEF || 0;
    this.redRose = data?.RED_ROSE || 0;
    this.wheat = data?.WHEAT || 0;
    this.bread = data?.BREAD || 0;
    this.carrot = data?.CARROT_ITEM || 0;
    this.rottenFlesh = data?.ROTTEN_FLESH || 0;
    this.bone = data?.BONE || 0;
  }
}

export default PlayerCosmeticsPetsConsumables;
