import SkyblockMemberPlayerDataMinion from './SkyblockMemberPlayerDataMinion.js';
import type { SkyblockMinion } from '../../../../Types/Skyblock.js';

class SkyblockMemberPlayerDataMinions {
  acacia: SkyblockMemberPlayerDataMinion;
  birch: SkyblockMemberPlayerDataMinion;
  blaze: SkyblockMemberPlayerDataMinion;
  cactus: SkyblockMemberPlayerDataMinion;
  carrot: SkyblockMemberPlayerDataMinion;
  cavespider: SkyblockMemberPlayerDataMinion;
  chicken: SkyblockMemberPlayerDataMinion;
  clay: SkyblockMemberPlayerDataMinion;
  coal: SkyblockMemberPlayerDataMinion;
  cobblestone: SkyblockMemberPlayerDataMinion;
  cocoa: SkyblockMemberPlayerDataMinion;
  cow: SkyblockMemberPlayerDataMinion;
  creeper: SkyblockMemberPlayerDataMinion;
  darkOak: SkyblockMemberPlayerDataMinion;
  diamond: SkyblockMemberPlayerDataMinion;
  emerald: SkyblockMemberPlayerDataMinion;
  enderman: SkyblockMemberPlayerDataMinion;
  enderStone: SkyblockMemberPlayerDataMinion;
  fishing: SkyblockMemberPlayerDataMinion;
  flower: SkyblockMemberPlayerDataMinion;
  ghast: SkyblockMemberPlayerDataMinion;
  glowstone: SkyblockMemberPlayerDataMinion;
  gold: SkyblockMemberPlayerDataMinion;
  gravel: SkyblockMemberPlayerDataMinion;
  hardStone: SkyblockMemberPlayerDataMinion;
  ice: SkyblockMemberPlayerDataMinion;
  inferno: SkyblockMemberPlayerDataMinion;
  iron: SkyblockMemberPlayerDataMinion;
  jungle: SkyblockMemberPlayerDataMinion;
  lapis: SkyblockMemberPlayerDataMinion;
  magmaCube: SkyblockMemberPlayerDataMinion;
  melon: SkyblockMemberPlayerDataMinion;
  mithril: SkyblockMemberPlayerDataMinion;
  mushroom: SkyblockMemberPlayerDataMinion;
  mycelium: SkyblockMemberPlayerDataMinion;
  netherWart: SkyblockMemberPlayerDataMinion;
  oak: SkyblockMemberPlayerDataMinion;
  obsidian: SkyblockMemberPlayerDataMinion;
  pig: SkyblockMemberPlayerDataMinion;
  potato: SkyblockMemberPlayerDataMinion;
  pumpkin: SkyblockMemberPlayerDataMinion;
  quartz: SkyblockMemberPlayerDataMinion;
  rabbit: SkyblockMemberPlayerDataMinion;
  redstone: SkyblockMemberPlayerDataMinion;
  redSand: SkyblockMemberPlayerDataMinion;
  revenant: SkyblockMemberPlayerDataMinion;
  sand: SkyblockMemberPlayerDataMinion;
  sheep: SkyblockMemberPlayerDataMinion;
  skeleton: SkyblockMemberPlayerDataMinion;
  slime: SkyblockMemberPlayerDataMinion;
  snow: SkyblockMemberPlayerDataMinion;
  spider: SkyblockMemberPlayerDataMinion;
  spruce: SkyblockMemberPlayerDataMinion;
  sugarCane: SkyblockMemberPlayerDataMinion;
  tarantula: SkyblockMemberPlayerDataMinion;
  vampire: SkyblockMemberPlayerDataMinion;
  voidling: SkyblockMemberPlayerDataMinion;
  wheat: SkyblockMemberPlayerDataMinion;
  zombie: SkyblockMemberPlayerDataMinion;
  constructor(data: SkyblockMinion[]) {
    this.acacia = new SkyblockMemberPlayerDataMinion(data || [], 'ACACIA');
    this.birch = new SkyblockMemberPlayerDataMinion(data || [], 'BIRCH');
    this.blaze = new SkyblockMemberPlayerDataMinion(data || [], 'BLAZE');
    this.cactus = new SkyblockMemberPlayerDataMinion(data || [], 'CACTUS');
    this.carrot = new SkyblockMemberPlayerDataMinion(data || [], 'CARROT');
    this.cavespider = new SkyblockMemberPlayerDataMinion(data || [], 'CAVESPIDER');
    this.chicken = new SkyblockMemberPlayerDataMinion(data || [], 'CHICKEN');
    this.clay = new SkyblockMemberPlayerDataMinion(data || [], 'CLAY');
    this.coal = new SkyblockMemberPlayerDataMinion(data || [], 'COAL');
    this.cobblestone = new SkyblockMemberPlayerDataMinion(data || [], 'COBBLESTONE');
    this.cocoa = new SkyblockMemberPlayerDataMinion(data || [], 'COCOA');
    this.cow = new SkyblockMemberPlayerDataMinion(data || [], 'COW');
    this.creeper = new SkyblockMemberPlayerDataMinion(data || [], 'CREEPER');
    this.darkOak = new SkyblockMemberPlayerDataMinion(data || [], 'DARK_OAK');
    this.diamond = new SkyblockMemberPlayerDataMinion(data || [], 'DIAMOND');
    this.emerald = new SkyblockMemberPlayerDataMinion(data || [], 'EMERALD');
    this.enderman = new SkyblockMemberPlayerDataMinion(data || [], 'ENDERMAN');
    this.enderStone = new SkyblockMemberPlayerDataMinion(data || [], 'ENDER_STONE');
    this.fishing = new SkyblockMemberPlayerDataMinion(data || [], 'FISHING');
    this.flower = new SkyblockMemberPlayerDataMinion(data || [], 'FLOWER');
    this.ghast = new SkyblockMemberPlayerDataMinion(data || [], 'GHAST');
    this.glowstone = new SkyblockMemberPlayerDataMinion(data || [], 'GLOWSTONE');
    this.gold = new SkyblockMemberPlayerDataMinion(data || [], 'GOLD');
    this.gravel = new SkyblockMemberPlayerDataMinion(data || [], 'GRAVEL');
    this.hardStone = new SkyblockMemberPlayerDataMinion(data || [], 'HARD_STONE');
    this.ice = new SkyblockMemberPlayerDataMinion(data || [], 'ICE');
    this.inferno = new SkyblockMemberPlayerDataMinion(data || [], 'INFERNO');
    this.iron = new SkyblockMemberPlayerDataMinion(data || [], 'IRON');
    this.jungle = new SkyblockMemberPlayerDataMinion(data || [], 'JUNGLE');
    this.lapis = new SkyblockMemberPlayerDataMinion(data || [], 'LAPIS');
    this.magmaCube = new SkyblockMemberPlayerDataMinion(data || [], 'MAGMA_CUBE');
    this.melon = new SkyblockMemberPlayerDataMinion(data || [], 'MELON');
    this.mithril = new SkyblockMemberPlayerDataMinion(data || [], 'MITHRIL');
    this.mushroom = new SkyblockMemberPlayerDataMinion(data || [], 'MUSHROOM');
    this.mycelium = new SkyblockMemberPlayerDataMinion(data || [], 'MYCELIUM');
    this.netherWart = new SkyblockMemberPlayerDataMinion(data || [], 'NETHER_WARTS');
    this.oak = new SkyblockMemberPlayerDataMinion(data || [], 'OAK');
    this.obsidian = new SkyblockMemberPlayerDataMinion(data || [], 'OBSIDIAN');
    this.pig = new SkyblockMemberPlayerDataMinion(data || [], 'PIG');
    this.potato = new SkyblockMemberPlayerDataMinion(data || [], 'POTATO');
    this.pumpkin = new SkyblockMemberPlayerDataMinion(data || [], 'PUMPKIN');
    this.quartz = new SkyblockMemberPlayerDataMinion(data || [], 'QUARTZ');
    this.rabbit = new SkyblockMemberPlayerDataMinion(data || [], 'RABBIT');
    this.redstone = new SkyblockMemberPlayerDataMinion(data || [], 'REDSTONE');
    this.redSand = new SkyblockMemberPlayerDataMinion(data || [], 'RED_SAND');
    this.revenant = new SkyblockMemberPlayerDataMinion(data || [], 'REVENANT');
    this.sand = new SkyblockMemberPlayerDataMinion(data || [], 'SAND');
    this.sheep = new SkyblockMemberPlayerDataMinion(data || [], 'SHEEP');
    this.skeleton = new SkyblockMemberPlayerDataMinion(data || [], 'SKELETON');
    this.slime = new SkyblockMemberPlayerDataMinion(data || [], 'SLIME');
    this.snow = new SkyblockMemberPlayerDataMinion(data || [], 'SNOW');
    this.spider = new SkyblockMemberPlayerDataMinion(data || [], 'SPIDER');
    this.spruce = new SkyblockMemberPlayerDataMinion(data || [], 'SPRUCE');
    this.sugarCane = new SkyblockMemberPlayerDataMinion(data || [], 'SUGAR_CANE');
    this.tarantula = new SkyblockMemberPlayerDataMinion(data || [], 'TARANTULA');
    this.vampire = new SkyblockMemberPlayerDataMinion(data || [], 'VAMPIRE');
    this.voidling = new SkyblockMemberPlayerDataMinion(data || [], 'VOIDLING');
    this.wheat = new SkyblockMemberPlayerDataMinion(data || [], 'WHEAT');
    this.zombie = new SkyblockMemberPlayerDataMinion(data || [], 'ZOMBIE');
  }
}

export default SkyblockMemberPlayerDataMinions;
