import SkyBlockMemberPlayerData from './SkyBlockMemberPlayerData.js';
import SkyBlockMemberPlayerDataActiveEffect from './SkyBlockMemberPlayerDataActiveEffect.js';
import SkyBlockMemberPlayerDataMinions from './SkyBlockMemberPlayerDataMinions.js';
import SkyBlockMemberPlayerDataSkills from './SkyBlockMemberPlayerDataSkills.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { SkyBlockArea, SkyBlockPotionEffectName } from '../../../../Types/SkyBlock.js';

test('SkyBlockMemberPlayerData', () => {
  const data = new SkyBlockMemberPlayerData({ stats: 'meow' }, { farmingCap: 0, tamingCap: 0 });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberPlayerData);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberPlayerData>();
  expect(data.activeEffects).toBeDefined();
  expectTypeOf(data.activeEffects).toEqualTypeOf<SkyBlockMemberPlayerDataActiveEffect[]>();
  expect(data.pausedEffects).toBeDefined();
  expectTypeOf(data.pausedEffects).toEqualTypeOf<SkyBlockPotionEffectName[]>();
  expect(data.disabledPotionEffects).toBeDefined();
  expectTypeOf(data.disabledPotionEffects).toEqualTypeOf<SkyBlockPotionEffectName[]>();
  expect(data.reaperPeppersEaten).toBeDefined();
  expect(data.reaperPeppersEaten).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.reaperPeppersEaten).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.lastDeath).toBeDefined();
  expect(data.lastDeath).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.lastDeath).toEqualTypeOf<number>();
  expect(data.visitedZones).toBeDefined();
  expectTypeOf(data.visitedZones).toEqualTypeOf<string[]>();
  expect(data.visitedModes).toBeDefined();
  expectTypeOf(data.visitedModes).toEqualTypeOf<SkyBlockArea[]>();
  expect(data.achievementSpawnedIslandTypes).toBeDefined();
  expectTypeOf(data.achievementSpawnedIslandTypes).toEqualTypeOf<string[]>();
  expect(data.unlockedCollTiers).toBeDefined();
  expectTypeOf(data.unlockedCollTiers).toEqualTypeOf<string[]>();
  expect(data.perks).toBeDefined();
  expectTypeOf(data.perks).toEqualTypeOf<Record<string, number>>();
  expect(data.minions).toBeDefined();
  expect(data.minions).toBeInstanceOf(SkyBlockMemberPlayerDataMinions);
  expectTypeOf(data.minions).toEqualTypeOf<SkyBlockMemberPlayerDataMinions>();
  expect(data.fastestTargetPractice).toBeDefined();
  expect(data.fastestTargetPractice).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fastestTargetPractice).toEqualTypeOf<number>();
  expect(data.fishingTreasureCaught).toBeDefined();
  expect(data.fishingTreasureCaught).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fishingTreasureCaught).toEqualTypeOf<number>();
  expect(data.skills).toBeDefined();
  expect(data.skills).toBeInstanceOf(SkyBlockMemberPlayerDataSkills);
  expectTypeOf(data.skills).toEqualTypeOf<SkyBlockMemberPlayerDataSkills>();
});
