import SkyBlockMemberPlayerData from './SkyBlockMemberPlayerData.js';
import { expect, expectTypeOf, test } from 'vitest';
import type SkyBlockMemberPlayerDataActiveEffect from './SkyBlockMemberPlayerDataActiveEffect.js';
import type SkyBlockMemberPlayerDataMinions from './SkyBlockMemberPlayerDataMinions.js';
import type SkyBlockMemberPlayerDataSkills from './SkyBlockMemberPlayerDataSkills.js';
import type { SkyBlockArea, SkyBlockPotionEffectName } from '../../../../Types/SkyBlock.js';

test('SkyBlockMemberPlayerData', () => {
  const data = new SkyBlockMemberPlayerData({ stats: 'meow' }, { farmingCap: 0, tamingCap: 0 });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberPlayerData);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberPlayerData>();
  expect(data.activeEffects).toBeDefined();
  expectTypeOf(data.activeEffects).toEqualTypeOf<SkyBlockMemberPlayerDataActiveEffect[]>();
  expect(data.pausedEffects).toBeDefined();
  expectTypeOf(data.pausedEffects).toEqualTypeOf<SkyBlockPotionEffectName[]>();
  expect(data.disabledPotionEffects).toBeDefined();
  expectTypeOf(data.disabledPotionEffects).toEqualTypeOf<SkyBlockPotionEffectName[]>();
  expect(data.reaperPeppersEaten).toBeDefined();
  expectTypeOf(data.reaperPeppersEaten).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.lastDeath).toBeDefined();
  expectTypeOf(data.lastDeath).toEqualTypeOf<number>();
  expect(data.visitedZones).toBeDefined();
  expectTypeOf(data.visitedZones).toEqualTypeOf<string[]>();
  expect(data.visitedModes).toBeDefined();
  expectTypeOf(data.visitedModes).toEqualTypeOf<SkyBlockArea[]>();
  expect(data.achievementSpawnedIslandTypes).toBeDefined();
  expectTypeOf(data.achievementSpawnedIslandTypes).toEqualTypeOf<string[]>();
  expect(data.unlockedCollTiers).toBeDefined();
  expectTypeOf(data.unlockedCollTiers).toEqualTypeOf<string[]>();
  expect(data.perks).toBeDefined();
  expectTypeOf(data.perks).toEqualTypeOf<Record<string, number>>();
  expect(data.minions).toBeDefined();
  expectTypeOf(data.minions).toEqualTypeOf<SkyBlockMemberPlayerDataMinions>();
  expect(data.fastestTargetPractice).toBeDefined();
  expectTypeOf(data.fastestTargetPractice).toEqualTypeOf<number>();
  expect(data.fishingTreasureCaught).toBeDefined();
  expectTypeOf(data.fishingTreasureCaught).toEqualTypeOf<number>();
  expect(data.skills).toBeDefined();
  expectTypeOf(data.skills).toEqualTypeOf<SkyBlockMemberPlayerDataSkills>();
});
