import SkyblockMemberPlayerData from './SkyblockMemberPlayerData.js';
import { expect, expectTypeOf, test } from 'vitest';
import type SkyblockMemberPlayerDataActiveEffect from './SkyblockMemberPlayerDataActiveEffect.js';
import type SkyblockMemberPlayerDataMinions from './SkyblockMemberPlayerDataMinions.js';
import type SkyblockMemberPlayerDataSkills from './SkyblockMemberPlayerDataSkills.js';
import type { SkyblockArea, SkyblockPotionEffect } from '../../../../Types/Skyblock.js';

test('SkyblockMemberPlayerData', () => {
  const data = new SkyblockMemberPlayerData({ stats: 'meow' }, { farmingCap: 0, tamingCap: 0 });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyblockMemberPlayerData);
  expectTypeOf(data).toEqualTypeOf<SkyblockMemberPlayerData>();
  expect(data.activeEffects).toBeDefined();
  expectTypeOf(data.activeEffects).toEqualTypeOf<SkyblockMemberPlayerDataActiveEffect[]>();
  expect(data.pausedEffects).toBeDefined();
  expectTypeOf(data.pausedEffects).toEqualTypeOf<SkyblockPotionEffect[]>();
  expect(data.disabledPotionEffects).toBeDefined();
  expectTypeOf(data.disabledPotionEffects).toEqualTypeOf<SkyblockPotionEffect[]>();
  expect(data.reaperPeppersEaten).toBeDefined();
  expectTypeOf(data.reaperPeppersEaten).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.lastDeath).toBeDefined();
  expectTypeOf(data.lastDeath).toEqualTypeOf<number>();
  expect(data.visitedZones).toBeDefined();
  expectTypeOf(data.visitedZones).toEqualTypeOf<string[]>();
  expect(data.visitedModes).toBeDefined();
  expectTypeOf(data.visitedModes).toEqualTypeOf<SkyblockArea[]>();
  expect(data.achievementSpawnedIslandTypes).toBeDefined();
  expectTypeOf(data.achievementSpawnedIslandTypes).toEqualTypeOf<string[]>();
  expect(data.unlockedCollTiers).toBeDefined();
  expectTypeOf(data.unlockedCollTiers).toEqualTypeOf<string[]>();
  expect(data.perks).toBeDefined();
  expectTypeOf(data.perks).toEqualTypeOf<Record<string, number>>();
  expect(data.minions).toBeDefined();
  expectTypeOf(data.minions).toEqualTypeOf<SkyblockMemberPlayerDataMinions>();
  expect(data.fastestTargetPractice).toBeDefined();
  expectTypeOf(data.fastestTargetPractice).toEqualTypeOf<number>();
  expect(data.fishingTreasureCaught).toBeDefined();
  expectTypeOf(data.fishingTreasureCaught).toEqualTypeOf<number>();
  expect(data.skills).toBeDefined();
  expectTypeOf(data.skills).toEqualTypeOf<SkyblockMemberPlayerDataSkills>();
});
