import SkyBlockMemberInventoriesWardrobe from './SkyBlockMemberInventoriesWardrobe.js';
import SkyBlockMemberInventoriesWardrobeSlot from './SkyBlockMemberInventoriesWardrobeSlot.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberInventoriesWardrobe', () => {
  const data = new SkyBlockMemberInventoriesWardrobe({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberInventoriesWardrobe);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberInventoriesWardrobe>();
  expect(data.slot1).toBeDefined();
  expectTypeOf(data.slot1).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot2).toBeDefined();
  expectTypeOf(data.slot2).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot3).toBeDefined();
  expectTypeOf(data.slot3).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot4).toBeDefined();
  expectTypeOf(data.slot4).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot5).toBeDefined();
  expectTypeOf(data.slot5).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot6).toBeDefined();
  expectTypeOf(data.slot6).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot7).toBeDefined();
  expectTypeOf(data.slot7).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot8).toBeDefined();
  expectTypeOf(data.slot8).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot9).toBeDefined();
  expectTypeOf(data.slot9).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot10).toBeDefined();
  expectTypeOf(data.slot10).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot11).toBeDefined();
  expectTypeOf(data.slot11).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot12).toBeDefined();
  expectTypeOf(data.slot12).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot13).toBeDefined();
  expectTypeOf(data.slot13).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot14).toBeDefined();
  expectTypeOf(data.slot14).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot15).toBeDefined();
  expectTypeOf(data.slot15).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot16).toBeDefined();
  expectTypeOf(data.slot16).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot17).toBeDefined();
  expectTypeOf(data.slot17).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot18).toBeDefined();
  expectTypeOf(data.slot18).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot19).toBeDefined();
  expectTypeOf(data.slot19).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot20).toBeDefined();
  expectTypeOf(data.slot20).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot21).toBeDefined();
  expectTypeOf(data.slot21).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot22).toBeDefined();
  expectTypeOf(data.slot22).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot23).toBeDefined();
  expectTypeOf(data.slot23).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot24).toBeDefined();
  expectTypeOf(data.slot24).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot25).toBeDefined();
  expectTypeOf(data.slot25).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot26).toBeDefined();
  expectTypeOf(data.slot26).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
  expect(data.slot27).toBeDefined();
  expectTypeOf(data.slot27).toEqualTypeOf<SkyBlockMemberInventoriesWardrobeSlot | null>();
});
