import BowSpleef from './BowSpleef.ts';
import PVPRun from './PVPRun.ts';
import TNTGames from './TNTGames.ts';
import TNTRun from './TNTRun.ts';
import TNTTag from './TNTTag.ts';
import TNTWizards from './TNTWizards.ts';
import { expect, expectTypeOf, test } from 'vitest';

test('TNTGames', () => {
  const data = new TNTGames({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(TNTGames);
  expectTypeOf(data).toEqualTypeOf<TNTGames>();
  expect(data.coins).toBeDefined();
  expect(data.coins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.coins).toEqualTypeOf<number>();
  expect(data.winStreak).toBeDefined();
  expect(data.winStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winStreak).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.tntrun).toBeDefined();
  expect(data.tntrun).toBeInstanceOf(TNTRun);
  expectTypeOf(data.tntrun).toEqualTypeOf<TNTRun>();
  expect(data.pvpRun).toBeDefined();
  expect(data.pvpRun).toBeInstanceOf(PVPRun);
  expectTypeOf(data.pvpRun).toEqualTypeOf<PVPRun>();
  expect(data.bowSpleef).toBeDefined();
  expect(data.bowSpleef).toBeInstanceOf(BowSpleef);
  expectTypeOf(data.bowSpleef).toEqualTypeOf<BowSpleef>();
  expect(data.tnttag).toBeDefined();
  expect(data.tnttag).toBeInstanceOf(TNTTag);
  expectTypeOf(data.tnttag).toEqualTypeOf<TNTTag>();
  expect(data.wizards).toBeDefined();
  expect(data.wizards).toBeInstanceOf(TNTWizards);
  expectTypeOf(data.wizards).toEqualTypeOf<TNTWizards>();
});
