import BowSpleef from './BowSpleef.js';
import PVPRun from './PVPRun.js';
import TNTGames from './TNTGames.js';
import TNTRun from './TNTRun.js';
import TNTTag from './TNTTag.js';
import TNTWizards from './TNTWizards.js';
import { expect, expectTypeOf, test } from 'vitest';

test('TNTGames', () => {
  const data = new TNTGames({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(TNTGames);
  expectTypeOf(data).toEqualTypeOf<TNTGames>();
  expect(data.coins).toBeDefined();
  expect(data.coins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.coins).toEqualTypeOf<number>();
  expect(data.winStreak).toBeDefined();
  expect(data.winStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winStreak).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.tntrun).toBeDefined();
  expectTypeOf(data.tntrun).toEqualTypeOf<TNTRun>();
  expect(data.pvpRun).toBeDefined();
  expectTypeOf(data.pvpRun).toEqualTypeOf<PVPRun>();
  expect(data.bowSpleef).toBeDefined();
  expectTypeOf(data.bowSpleef).toEqualTypeOf<BowSpleef>();
  expect(data.tnttag).toBeDefined();
  expectTypeOf(data.tnttag).toEqualTypeOf<TNTTag>();
  expect(data.wizards).toBeDefined();
  expectTypeOf(data.wizards).toEqualTypeOf<TNTWizards>();
});
