import TNTRun from './TNTRun.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { ColorString } from '../../../Types/Color.js';

test('TNTRun', () => {
  const data = new TNTRun({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(TNTRun);
  expectTypeOf(data).toEqualTypeOf<TNTRun>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.bestTime).toBeDefined();
  expect(data.bestTime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bestTime).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.slownessPotions).toBeDefined();
  expect(data.slownessPotions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.slownessPotions).toEqualTypeOf<number>();
  expect(data.speedPotions).toBeDefined();
  expect(data.speedPotions).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.speedPotions).toEqualTypeOf<number>();
  expect(data.doubleJumps).toBeDefined();
  expect(data.doubleJumps).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.doubleJumps).toEqualTypeOf<number>();
  expect(data.prefix).toBeDefined();
  expectTypeOf(data.prefix).toEqualTypeOf<ColorString | 'Rainbow'>();
});
