import SkyBlockMemberRift from './SkyBlockMemberRift.js';
import { expect, expectTypeOf, test } from 'vitest';
import type SkyBlockMemberRiftAccess from './SkyBlockMemberRiftAccess.js';
import type SkyBlockMemberRiftBlackLagoon from './SkyBlockMemberRiftBlackLagoon.js';
import type SkyBlockMemberRiftCastle from './SkyBlockMemberRiftCastle.js';
import type SkyBlockMemberRiftDeadCats from './SkyBlockMemberRiftDeadCats.js';
import type SkyBlockMemberRiftDreamFarm from './SkyBlockMemberRiftDreamFarm.js';
import type SkyBlockMemberRiftEnigma from './SkyBlockMemberRiftEnigma.js';
import type SkyBlockMemberRiftGallery from './SkyBlockMemberRiftGallery.js';
import type SkyBlockMemberRiftInventory from './SkyBlockMemberRiftInventory.js';
import type SkyBlockMemberRiftVillagePlaza from './VillagePlaza/SkyBlockMemberRiftVillagePlaza.js';
import type SkyBlockMemberRiftWestVillage from './WestVillage/SkyBlockMemberRiftWestVillage.js';
import type SkyBlockMemberRiftWitherCage from './SkyBlockMemberRiftWitherCage.js';
import type SkyBlockMemberRiftWizardTower from './SkyBlockMemberRiftWizardTower.js';

test('SkyBlockMemberRift', () => {
  const data = new SkyBlockMemberRift({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberRift);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberRift>();
  expect(data.villagePlaza).toBeDefined();
  expectTypeOf(data.villagePlaza).toEqualTypeOf<SkyBlockMemberRiftVillagePlaza>();
  expect(data.witherCage).toBeDefined();
  expectTypeOf(data.witherCage).toEqualTypeOf<SkyBlockMemberRiftWitherCage>();
  expect(data.blackLagoon).toBeDefined();
  expectTypeOf(data.blackLagoon).toEqualTypeOf<SkyBlockMemberRiftBlackLagoon>();
  expect(data.deadCats).toBeDefined();
  expectTypeOf(data.deadCats).toEqualTypeOf<SkyBlockMemberRiftDeadCats>();
  expect(data.wizardTower).toBeDefined();
  expectTypeOf(data.wizardTower).toEqualTypeOf<SkyBlockMemberRiftWizardTower>();
  expect(data.enigma).toBeDefined();
  expectTypeOf(data.enigma).toEqualTypeOf<SkyBlockMemberRiftEnigma>();
  expect(data.gallery).toBeDefined();
  expectTypeOf(data.gallery).toEqualTypeOf<SkyBlockMemberRiftGallery>();
  expect(data.lifetimePurchasedBoundaries).toBeDefined();
  expectTypeOf(data.lifetimePurchasedBoundaries).toEqualTypeOf<string[]>();
  expect(data.westVillage).toBeDefined();
  expectTypeOf(data.westVillage).toEqualTypeOf<SkyBlockMemberRiftWestVillage>();
  expect(data.castle).toBeDefined();
  expectTypeOf(data.castle).toEqualTypeOf<SkyBlockMemberRiftCastle>();
  expect(data.access).toBeDefined();
  expectTypeOf(data.access).toEqualTypeOf<SkyBlockMemberRiftAccess>();
  expect(data.dreamFarm).toBeDefined();
  expectTypeOf(data.dreamFarm).toEqualTypeOf<SkyBlockMemberRiftDreamFarm>();
  expect(data.inventory).toBeDefined();
  expectTypeOf(data.inventory).toEqualTypeOf<SkyBlockMemberRiftInventory>();
});
