import SkyblockMemberRift from './SkyblockMemberRift.js';
import { expect, expectTypeOf, test } from 'vitest';
import type SkyblockMemberRiftAccess from './SkyblockMemberRiftAccess.js';
import type SkyblockMemberRiftBlackLagoon from './SkyblockMemberRiftBlackLagoon.js';
import type SkyblockMemberRiftCastle from './SkyblockMemberRiftCastle.js';
import type SkyblockMemberRiftDeadCats from './SkyblockMemberRiftDeadCats.js';
import type SkyblockMemberRiftDreamFarm from './SkyblockMemberRiftDreamFarm.js';
import type SkyblockMemberRiftEnigma from './SkyblockMemberRiftEnigma.js';
import type SkyblockMemberRiftGallery from './SkyblockMemberRiftGallery.js';
import type SkyblockMemberRiftInventory from './SkyblockMemberRiftInventory.js';
import type SkyblockMemberRiftVillagePlaza from './VillagePlaza/SkyblockMemberRiftVillagePlaza.js';
import type SkyblockMemberRiftWestVillage from './WestVillage/SkyblockMemberRiftWestVillage.js';
import type SkyblockMemberRiftWitherCage from './SkyblockMemberRiftWitherCage.js';
import type SkyblockMemberRiftWizardTower from './SkyblockMemberRiftWizardTower.js';

test('SkyblockMemberRift', () => {
  const data = new SkyblockMemberRift({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyblockMemberRift);
  expectTypeOf(data).toEqualTypeOf<SkyblockMemberRift>();
  expect(data.villagePlaza).toBeDefined();
  expectTypeOf(data.villagePlaza).toEqualTypeOf<SkyblockMemberRiftVillagePlaza>();
  expect(data.witherCage).toBeDefined();
  expectTypeOf(data.witherCage).toEqualTypeOf<SkyblockMemberRiftWitherCage>();
  expect(data.blackLagoon).toBeDefined();
  expectTypeOf(data.blackLagoon).toEqualTypeOf<SkyblockMemberRiftBlackLagoon>();
  expect(data.deadCats).toBeDefined();
  expectTypeOf(data.deadCats).toEqualTypeOf<SkyblockMemberRiftDeadCats>();
  expect(data.wizardTower).toBeDefined();
  expectTypeOf(data.wizardTower).toEqualTypeOf<SkyblockMemberRiftWizardTower>();
  expect(data.enigma).toBeDefined();
  expectTypeOf(data.enigma).toEqualTypeOf<SkyblockMemberRiftEnigma>();
  expect(data.gallery).toBeDefined();
  expectTypeOf(data.gallery).toEqualTypeOf<SkyblockMemberRiftGallery>();
  expect(data.lifetimePurchasedBoundaries).toBeDefined();
  expectTypeOf(data.lifetimePurchasedBoundaries).toEqualTypeOf<string[]>();
  expect(data.westVillage).toBeDefined();
  expectTypeOf(data.westVillage).toEqualTypeOf<SkyblockMemberRiftWestVillage>();
  expect(data.castle).toBeDefined();
  expectTypeOf(data.castle).toEqualTypeOf<SkyblockMemberRiftCastle>();
  expect(data.access).toBeDefined();
  expectTypeOf(data.access).toEqualTypeOf<SkyblockMemberRiftAccess>();
  expect(data.dreamFarm).toBeDefined();
  expectTypeOf(data.dreamFarm).toEqualTypeOf<SkyblockMemberRiftDreamFarm>();
  expect(data.inventory).toBeDefined();
  expectTypeOf(data.inventory).toEqualTypeOf<SkyblockMemberRiftInventory>();
});
