import SkyBlockMemberRift from './SkyBlockMemberRift.js';
import SkyBlockMemberRiftAccess from './SkyBlockMemberRiftAccess.js';
import SkyBlockMemberRiftBlackLagoon from './SkyBlockMemberRiftBlackLagoon.js';
import SkyBlockMemberRiftCastle from './SkyBlockMemberRiftCastle.js';
import SkyBlockMemberRiftDeadCats from './SkyBlockMemberRiftDeadCats.js';
import SkyBlockMemberRiftDreamFarm from './SkyBlockMemberRiftDreamFarm.js';
import SkyBlockMemberRiftEnigma from './SkyBlockMemberRiftEnigma.js';
import SkyBlockMemberRiftGallery from './SkyBlockMemberRiftGallery.js';
import SkyBlockMemberRiftInventory from './SkyBlockMemberRiftInventory.js';
import SkyBlockMemberRiftVillagePlaza from './VillagePlaza/SkyBlockMemberRiftVillagePlaza.js';
import SkyBlockMemberRiftWestVillage from './WestVillage/SkyBlockMemberRiftWestVillage.js';
import SkyBlockMemberRiftWitherCage from './SkyBlockMemberRiftWitherCage.js';
import SkyBlockMemberRiftWizardTower from './SkyBlockMemberRiftWizardTower.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockMemberRift', () => {
  const data = new SkyBlockMemberRift({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockMemberRift);
  expectTypeOf(data).toEqualTypeOf<SkyBlockMemberRift>();
  expect(data.villagePlaza).toBeDefined();
  expect(data.villagePlaza).toBeInstanceOf(SkyBlockMemberRiftVillagePlaza);
  expectTypeOf(data.villagePlaza).toEqualTypeOf<SkyBlockMemberRiftVillagePlaza>();
  expect(data.witherCage).toBeDefined();
  expect(data.witherCage).toBeInstanceOf(SkyBlockMemberRiftWitherCage);
  expectTypeOf(data.witherCage).toEqualTypeOf<SkyBlockMemberRiftWitherCage>();
  expect(data.blackLagoon).toBeDefined();
  expect(data.blackLagoon).toBeInstanceOf(SkyBlockMemberRiftBlackLagoon);
  expectTypeOf(data.blackLagoon).toEqualTypeOf<SkyBlockMemberRiftBlackLagoon>();
  expect(data.deadCats).toBeDefined();
  expect(data.deadCats).toBeInstanceOf(SkyBlockMemberRiftDeadCats);
  expectTypeOf(data.deadCats).toEqualTypeOf<SkyBlockMemberRiftDeadCats>();
  expect(data.wizardTower).toBeDefined();
  expect(data.wizardTower).toBeInstanceOf(SkyBlockMemberRiftWizardTower);
  expectTypeOf(data.wizardTower).toEqualTypeOf<SkyBlockMemberRiftWizardTower>();
  expect(data.enigma).toBeDefined();
  expect(data.enigma).toBeInstanceOf(SkyBlockMemberRiftEnigma);
  expectTypeOf(data.enigma).toEqualTypeOf<SkyBlockMemberRiftEnigma>();
  expect(data.gallery).toBeDefined();
  expect(data.gallery).toBeInstanceOf(SkyBlockMemberRiftGallery);
  expectTypeOf(data.gallery).toEqualTypeOf<SkyBlockMemberRiftGallery>();
  expect(data.lifetimePurchasedBoundaries).toBeDefined();
  expectTypeOf(data.lifetimePurchasedBoundaries).toEqualTypeOf<string[]>();
  expect(data.westVillage).toBeDefined();
  expect(data.westVillage).toBeInstanceOf(SkyBlockMemberRiftWestVillage);
  expectTypeOf(data.westVillage).toEqualTypeOf<SkyBlockMemberRiftWestVillage>();
  expect(data.castle).toBeDefined();
  expect(data.castle).toBeInstanceOf(SkyBlockMemberRiftCastle);
  expectTypeOf(data.castle).toEqualTypeOf<SkyBlockMemberRiftCastle>();
  expect(data.access).toBeDefined();
  expect(data.access).toBeInstanceOf(SkyBlockMemberRiftAccess);
  expectTypeOf(data.access).toEqualTypeOf<SkyBlockMemberRiftAccess>();
  expect(data.dreamFarm).toBeDefined();
  expect(data.dreamFarm).toBeInstanceOf(SkyBlockMemberRiftDreamFarm);
  expectTypeOf(data.dreamFarm).toEqualTypeOf<SkyBlockMemberRiftDreamFarm>();
  expect(data.inventory).toBeDefined();
  expect(data.inventory).toBeInstanceOf(SkyBlockMemberRiftInventory);
  expectTypeOf(data.inventory).toEqualTypeOf<SkyBlockMemberRiftInventory>();
});
