import Pit from './Pit.js';
import PitInventoryItem from './PitInventoryItem.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { PitArmor } from '../../../Types/Player.js';

test('Pit', () => {
  const data = new Pit({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Pit);
  expectTypeOf(data).toEqualTypeOf<Pit>();
  expect(data.prestige).toBeDefined();
  expect(data.prestige).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.prestige).toEqualTypeOf<number>();
  expect(data.xp).toBeDefined();
  expect(data.xp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.xp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expect(data.level).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.level).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.assists).toBeDefined();
  expect(data.assists).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.assists).toEqualTypeOf<number>();
  expect(data.maxKillStreak).toBeDefined();
  expect(data.maxKillStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.maxKillStreak).toEqualTypeOf<number>();
  expect(data.playtime).toBeDefined();
  expect(data.playtime).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.playtime).toEqualTypeOf<number>();
  expect(data.joins).toBeDefined();
  expect(data.joins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.joins).toEqualTypeOf<number>();
  expect(data.damageReceived).toBeDefined();
  expect(data.damageReceived).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageReceived).toEqualTypeOf<number>();
  expect(data.damageDealt).toBeDefined();
  expect(data.damageDealt).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageDealt).toEqualTypeOf<number>();
  expect(data.damageRatio).toBeDefined();
  expect(data.damageRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.damageRatio).toEqualTypeOf<number>();
  expect(data.meleeDamageReceived).toBeDefined();
  expect(data.meleeDamageReceived).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.meleeDamageReceived).toEqualTypeOf<number>();
  expect(data.meleeDamageDealt).toBeDefined();
  expect(data.meleeDamageDealt).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.meleeDamageDealt).toEqualTypeOf<number>();
  expect(data.swordHits).toBeDefined();
  expect(data.swordHits).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.swordHits).toEqualTypeOf<number>();
  expect(data.leftClicks).toBeDefined();
  expect(data.leftClicks).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.leftClicks).toEqualTypeOf<number>();
  expect(data.meleeAccuracy).toBeDefined();
  expect(data.meleeAccuracy).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.meleeAccuracy).toEqualTypeOf<number>();
  expect(data.meleeDamageRatio).toBeDefined();
  expect(data.meleeDamageRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.meleeDamageRatio).toEqualTypeOf<number>();
  expect(data.bowDamageReceived).toBeDefined();
  expect(data.bowDamageReceived).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowDamageReceived).toEqualTypeOf<number>();
  expect(data.bowDamageDealt).toBeDefined();
  expect(data.bowDamageDealt).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowDamageDealt).toEqualTypeOf<number>();
  expect(data.arrowsHit).toBeDefined();
  expect(data.arrowsHit).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsHit).toEqualTypeOf<number>();
  expect(data.arrowsFired).toBeDefined();
  expect(data.arrowsFired).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsFired).toEqualTypeOf<number>();
  expect(data.bowAccuracy).toBeDefined();
  expect(data.bowAccuracy).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowAccuracy).toEqualTypeOf<number>();
  expect(data.bowDamageRatio).toBeDefined();
  expect(data.bowDamageRatio).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowDamageRatio).toEqualTypeOf<number>();
  expect(data.goldenHeadsEaten).toBeDefined();
  expect(data.goldenHeadsEaten).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.goldenHeadsEaten).toEqualTypeOf<number>();
  expect(data.getInventory).toBeDefined();
  expectTypeOf(data.getInventory).toEqualTypeOf<() => Promise<PitInventoryItem[]>>();
  expect(data.getEnterChest).toBeDefined();
  expectTypeOf(data.getEnterChest).toEqualTypeOf<() => Promise<PitInventoryItem[]>>();
  expect(data.getArmor).toBeDefined();
  expectTypeOf(data.getArmor).toEqualTypeOf<() => Promise<PitArmor>>();
});
