import SkyBlockGardenComposter from './SkyBlockGardenComposter.js';
import SkyBlockGardenComposterUpgrades from './SkyBlockGardenComposterUpgrades.js';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyBlockGardenComposter', () => {
  const data = new SkyBlockGardenComposter({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockGardenComposter);
  expectTypeOf(data).toEqualTypeOf<SkyBlockGardenComposter>();
  expect(data.organicMatter).toBeDefined();
  expect(data.organicMatter).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.organicMatter).toEqualTypeOf<number>();
  expect(data.fuelUnits).toBeDefined();
  expect(data.fuelUnits).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fuelUnits).toEqualTypeOf<number>();
  expect(data.compostUnits).toBeDefined();
  expect(data.compostUnits).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.compostUnits).toEqualTypeOf<number>();
  expect(data.compostItems).toBeDefined();
  expect(data.compostItems).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.compostItems).toEqualTypeOf<number>();
  expect(data.conversionTicks).toBeDefined();
  expect(data.conversionTicks).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.conversionTicks).toEqualTypeOf<number>();
  expect(data.upgrades).toBeDefined();
  expect(data.upgrades).toBeInstanceOf(SkyBlockGardenComposterUpgrades);
  expectTypeOf(data.upgrades).toEqualTypeOf<SkyBlockGardenComposterUpgrades>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => number>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.organicMatter);
  expectTypeOf(data.toString()).toEqualTypeOf<number>();
});
