class InventoryLayout {
  slot0: string | undefined;
  slot1: string | undefined;
  slot2: string | undefined;
  slot3: string | undefined;
  slot4: string | undefined;
  slot5: string | undefined;
  slot6: string | undefined;
  slot7: string | undefined;
  slot8: string | undefined;
  slot9: string | undefined;
  slot10: string | undefined;
  slot11: string | undefined;
  slot12: string | undefined;
  slot13: string | undefined;
  slot14: string | undefined;
  slot15: string | undefined;
  slot16: string | undefined;
  slot17: string | undefined;
  slot18: string | undefined;
  slot19: string | undefined;
  slot20: string | undefined;
  slot21: string | undefined;
  slot22: string | undefined;
  slot23: string | undefined;
  slot24: string | undefined;
  slot25: string | undefined;
  slot26: string | undefined;
  slot27: string | undefined;
  slot28: string | undefined;
  slot29: string | undefined;
  slot30: string | undefined;
  slot31: string | undefined;
  slot32: string | undefined;
  slot33: string | undefined;
  slot34: string | undefined;
  slot35: string | undefined;
  constructor(data: Record<string, any>) {
    this.slot0 = data?.['0'] || undefined;
    this.slot1 = data?.['1'] || undefined;
    this.slot2 = data?.['2'] || undefined;
    this.slot3 = data?.['3'] || undefined;
    this.slot4 = data?.['4'] || undefined;
    this.slot5 = data?.['5'] || undefined;
    this.slot6 = data?.['6'] || undefined;
    this.slot7 = data?.['7'] || undefined;
    this.slot8 = data?.['8'] || undefined;
    this.slot9 = data?.['9'] || undefined;
    this.slot10 = data?.['10'] || undefined;
    this.slot11 = data?.['11'] || undefined;
    this.slot12 = data?.['12'] || undefined;
    this.slot13 = data?.['13'] || undefined;
    this.slot14 = data?.['14'] || undefined;
    this.slot15 = data?.['15'] || undefined;
    this.slot16 = data?.['16'] || undefined;
    this.slot17 = data?.['17'] || undefined;
    this.slot18 = data?.['18'] || undefined;
    this.slot19 = data?.['19'] || undefined;
    this.slot20 = data?.['20'] || undefined;
    this.slot21 = data?.['21'] || undefined;
    this.slot22 = data?.['22'] || undefined;
    this.slot23 = data?.['23'] || undefined;
    this.slot24 = data?.['24'] || undefined;
    this.slot25 = data?.['25'] || undefined;
    this.slot26 = data?.['26'] || undefined;
    this.slot27 = data?.['27'] || undefined;
    this.slot28 = data?.['28'] || undefined;
    this.slot29 = data?.['29'] || undefined;
    this.slot30 = data?.['30'] || undefined;
    this.slot31 = data?.['31'] || undefined;
    this.slot32 = data?.['32'] || undefined;
    this.slot33 = data?.['33'] || undefined;
    this.slot34 = data?.['34'] || undefined;
    this.slot35 = data?.['35'] || undefined;
  }
}

export default InventoryLayout;
