import DropperMap from './DropperMap.js';

class Dropper {
  fails: number;
  fastestGame: number;
  flawlessGames: number;
  gamesFinished: number;
  gamesPlayed: number;
  mapsCompleted: number;
  wins: number;
  atlantis: DropperMap;
  balloons: DropperMap;
  bbq: DropperMap;
  beanstalk: DropperMap;
  birdcage: DropperMap;
  boardgames: DropperMap;
  bridges: DropperMap;
  butterflies: DropperMap;
  cabin: DropperMap;
  castle: DropperMap;
  city: DropperMap;
  distance: DropperMap;
  distortion: DropperMap;
  drainage: DropperMap;
  emoji: DropperMap;
  factory: DropperMap;
  floatingIslands: DropperMap;
  flytrap: DropperMap;
  frogspawn: DropperMap;
  gears: DropperMap;
  geometry: DropperMap;
  glacier: DropperMap;
  hellgate: DropperMap;
  illusion: DropperMap;
  iris: DropperMap;
  kingDommines: DropperMap;
  kingsPass: DropperMap;
  kraken: DropperMap;
  launchZone: DropperMap;
  lavaFall: DropperMap;
  lily: DropperMap;
  maelstrom: DropperMap;
  mainframe: DropperMap;
  microscope: DropperMap;
  mineshaft: DropperMap;
  mushroom: DropperMap;
  nightlife: DropperMap;
  ocean: DropperMap;
  overgrown: DropperMap;
  painted: DropperMap;
  paradigm: DropperMap;
  plughole: DropperMap;
  raindrops: DropperMap;
  ravine: DropperMap;
  retro: DropperMap;
  revolve: DropperMap;
  sandWorm: DropperMap;
  sewer: DropperMap;
  space: DropperMap;
  stratocumulus: DropperMap;
  sweets: DropperMap;
  tangle: DropperMap;
  time: DropperMap;
  toilet: DropperMap;
  ufo: DropperMap;
  upsideDown: DropperMap;
  vintage: DropperMap;
  vortex: DropperMap;
  warp: DropperMap;
  warPortal: DropperMap;
  well: DropperMap;
  western: DropperMap;
  constructor(data: Record<string, any>) {
    this.fails = data?.fails || 0;
    this.fastestGame = data?.fastest_game || 0;
    this.flawlessGames = data?.flawless_games || 0;
    this.gamesFinished = data?.games_finished || 0;
    this.gamesPlayed = data?.games_played || 0;
    this.mapsCompleted = data?.maps_completed || 0;
    this.wins = data?.wins || 0;
    this.atlantis = new DropperMap(data?.atlantis || {});
    this.balloons = new DropperMap(data?.balloons || {});
    this.bbq = new DropperMap(data?.bbq || {});
    this.beanstalk = new DropperMap(data?.beanstalk || {});
    this.birdcage = new DropperMap(data?.birdcage || {});
    this.boardgames = new DropperMap(data?.boardgames || {});
    this.bridges = new DropperMap(data?.bridges || {});
    this.butterflies = new DropperMap(data?.butterflies || {});
    this.cabin = new DropperMap(data?.cabin || {});
    this.castle = new DropperMap(data?.castle || {});
    this.city = new DropperMap(data?.city || {});
    this.distance = new DropperMap(data?.distance || {});
    this.distortion = new DropperMap(data?.distortion || {});
    this.drainage = new DropperMap(data?.drainage || {});
    this.emoji = new DropperMap(data?.emoji || {});
    this.factory = new DropperMap(data?.factory || {});
    this.floatingIslands = new DropperMap(data?.floatingislands || {});
    this.flytrap = new DropperMap(data?.flytrap || {});
    this.frogspawn = new DropperMap(data?.frogspawn || {});
    this.gears = new DropperMap(data?.gears || {});
    this.geometry = new DropperMap(data?.geometry || {});
    this.glacier = new DropperMap(data?.glacier || {});
    this.hellgate = new DropperMap(data?.hellgate || {});
    this.illusion = new DropperMap(data?.illusion || {});
    this.iris = new DropperMap(data?.iris || {});
    this.kingDommines = new DropperMap(data?.kingdommines || {});
    this.kingsPass = new DropperMap(data?.kingspass || {});
    this.kraken = new DropperMap(data?.kraken || {});
    this.launchZone = new DropperMap(data?.launchzone || {});
    this.lavaFall = new DropperMap(data?.lavafall || {});
    this.lily = new DropperMap(data?.lily || {});
    this.maelstrom = new DropperMap(data?.maelstrom || {});
    this.mainframe = new DropperMap(data?.mainframe || {});
    this.microscope = new DropperMap(data?.microscope || {});
    this.mineshaft = new DropperMap(data?.mineshaft || {});
    this.mushroom = new DropperMap(data?.mushroom || {});
    this.nightlife = new DropperMap(data?.nightlife || {});
    this.ocean = new DropperMap(data?.ocean || {});
    this.overgrown = new DropperMap(data?.overgrown || {});
    this.painted = new DropperMap(data?.painted || {});
    this.paradigm = new DropperMap(data?.paradigm || {});
    this.plughole = new DropperMap(data?.plughole || {});
    this.raindrops = new DropperMap(data?.raindrops || {});
    this.ravine = new DropperMap(data?.ravine || {});
    this.retro = new DropperMap(data?.retro || {});
    this.revolve = new DropperMap(data?.revolve || {});
    this.sandWorm = new DropperMap(data?.sandworm || {});
    this.sewer = new DropperMap(data?.sewer || {});
    this.space = new DropperMap(data?.space || {});
    this.stratocumulus = new DropperMap(data?.stratocumulus || {});
    this.sweets = new DropperMap(data?.sweets || {});
    this.tangle = new DropperMap(data?.tangle || {});
    this.time = new DropperMap(data?.time || {});
    this.toilet = new DropperMap(data?.toilet || {});
    this.ufo = new DropperMap(data?.ufo || {});
    this.upsideDown = new DropperMap(data?.upsidedown || {});
    this.vintage = new DropperMap(data?.vintage || {});
    this.vortex = new DropperMap(data?.vortex || {});
    this.warp = new DropperMap(data?.warp || {});
    this.warPortal = new DropperMap(data?.warportal || {});
    this.well = new DropperMap(data?.well || {});
    this.western = new DropperMap(data?.western || {});
  }
}

export default Dropper;
