import Arcade from './Arcade.js';
import ArcadeOptions from './ArcadeOptions.js';
import BlockingDead from './BlockingDead.js';
import DragonWars from './DragonWars.js';
import DrawTheirThing from './DrawTheirThing.js';
import Dropper from './Dropper/Dropper.js';
import Dtt from './Dtt.js';
import EasterSimulator from './EasterSimulator.js';
import EnderSpleef from './EnderSpleef.js';
import FarmHunt from './FarmHunt.js';
import FootBall from './FootBall.js';
import GalaxyWars from './GalaxyWars.js';
import GrinchSimulator from './GrinchSimulator.js';
import HalloweenSimulator from './HalloweenSimulator.js';
import HideAndSeek from './HideAndSeek.js';
import HoleInTheWall from './HoleInTheWall.js';
import HypixelSports from './HypixelSports.js';
import MiniWalls from './MiniWalls.js';
import OneInTheQuiver from './OneInTheQuiver.js';
import PartyGames from './PartyGames/PartyGames.js';
import SantaSays from './SantaSays.js';
import SantaSimulator from './SantaSimulator.js';
import ScubaSimulator from './ScubaSimulator.js';
import SimonSays from './SimonSays.js';
import Soccer from './Soccer.js';
import ThrowOut from './ThrowOut.js';
import WoolHunt from './WoolHunt.js';
import Zombies from './Zombies/Zombies.js';
import { expect, expectTypeOf, test } from 'vitest';
import type {
  ArcadeBountyHead,
  ArcadeMeleeWeapon,
  ArcadeMovementTrail,
  ArcadePackage,
  ArcadeProjectileTrail,
  ArcadeVictoryDance,
  Language,
  PlayerGeneralSelectedCosmetic,
  ShopSort
} from '../../../Types/Player.js';

test('Arcade', () => {
  const data = new Arcade({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Arcade);
  expectTypeOf(data).toEqualTypeOf<Arcade>();
  expect(data.activeMovementTrail).toBeDefined();
  expectTypeOf(data.activeMovementTrail).toEqualTypeOf<
    ArcadeMovementTrail | PlayerGeneralSelectedCosmetic | 'UNKNOWN'
  >();
  expect(data.activeProjectileTrail).toBeDefined();
  expectTypeOf(data.activeProjectileTrail).toEqualTypeOf<
    ArcadeProjectileTrail | PlayerGeneralSelectedCosmetic | 'UNKNOWN'
  >();
  expect(data.activeVictoryDance).toBeDefined();
  expectTypeOf(data.activeVictoryDance).toEqualTypeOf<ArcadeVictoryDance | PlayerGeneralSelectedCosmetic | 'UNKNOWN'>();
  expect(data.blood).toBeDefined();
  expectTypeOf(data.blood).toEqualTypeOf<boolean>();
  expect(data.bountyHead).toBeDefined();
  expectTypeOf(data.bountyHead).toEqualTypeOf<ArcadeBountyHead>();
  expect(data.tokens).toBeDefined();
  expect(data.tokens).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.tokens).toEqualTypeOf<number>();
  expect(data.dec2016Achievements).toBeDefined();
  expectTypeOf(data.dec2016Achievements).toEqualTypeOf<boolean>();
  expect(data.dec2016Achievements2).toBeDefined();
  expectTypeOf(data.dec2016Achievements2).toEqualTypeOf<boolean>();
  expect(data.flash).toBeDefined();
  expectTypeOf(data.flash).toEqualTypeOf<boolean>();
  expect(data.hideAndSeekShowQueueBook).toBeDefined();
  expectTypeOf(data.hideAndSeekShowQueueBook).toEqualTypeOf<boolean>();
  expect(data.hints).toBeDefined();
  expectTypeOf(data.hints).toEqualTypeOf<boolean>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language | 'UNKNOWN'>();
  expect(data.maxWave).toBeDefined();
  expect(data.maxWave).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.maxWave).toEqualTypeOf<number>();
  expect(data.meleeWeapon).toBeDefined();
  expectTypeOf(data.meleeWeapon).toEqualTypeOf<ArcadeMeleeWeapon | 'UNKNOWN'>();
  expect(data.monthlyTokens).toBeDefined();
  expect(data.monthlyTokens).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyTokens).toEqualTypeOf<number>();
  expect(data.monthlyTokensA).toBeDefined();
  expect(data.monthlyTokensA).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyTokensA).toEqualTypeOf<number>();
  expect(data.monthlyTokensB).toBeDefined();
  expect(data.monthlyTokensB).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyTokensB).toEqualTypeOf<number>();
  expect(data.music).toBeDefined();
  expectTypeOf(data.music).toEqualTypeOf<boolean>();
  expect(data.mysteryGiftsObtained).toBeDefined();
  expect(data.mysteryGiftsObtained).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.mysteryGiftsObtained).toEqualTypeOf<number>();
  expect(data.options).toBeDefined();
  expect(data.options).toBeInstanceOf(ArcadeOptions);
  expectTypeOf(data.options).toEqualTypeOf<ArcadeOptions>();
  expect(data.poopCollected).toBeDefined();
  expect(data.poopCollected).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.poopCollected).toEqualTypeOf<number>();
  expect(data.ppLanguage).toBeDefined();
  expectTypeOf(data.ppLanguage).toEqualTypeOf<Language | 'UNKNOWN'>();
  expect(data.privategames).toBeDefined();
  expectTypeOf(data.privategames).toEqualTypeOf<Record<string, any>>();
  expect(data.shopSort).toBeDefined();
  expectTypeOf(data.shopSort).toEqualTypeOf<ShopSort | 'UNKNOWN'>();
  expect(data.shopSortEnableOwnedFirst).toBeDefined();
  expectTypeOf(data.shopSortEnableOwnedFirst).toEqualTypeOf<boolean>();
  expect(data.showInfoBook).toBeDefined();
  expectTypeOf(data.showInfoBook).toEqualTypeOf<boolean>();
  expect(data.simonSong).toBeDefined();
  expectTypeOf(data.simonSong).toEqualTypeOf<boolean>();
  expect(data.stampLevel).toBeDefined();
  expect(data.stampLevel).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.stampLevel).toEqualTypeOf<number>();
  expect(data.timestamp).toBeDefined();
  expect(data.timestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.timestamp).toEqualTypeOf<number>();
  expect(data.weeklyTokens).toBeDefined();
  expect(data.weeklyTokens).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyTokens).toEqualTypeOf<number>();
  expect(data.weeklyTokensA).toBeDefined();
  expect(data.weeklyTokensA).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyTokensA).toEqualTypeOf<number>();
  expect(data.weeklyTokensB).toBeDefined();
  expect(data.weeklyTokensB).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyTokensB).toEqualTypeOf<number>();
  expect(data.xmasMusic).toBeDefined();
  expectTypeOf(data.xmasMusic).toEqualTypeOf<boolean>();
  expect(data.packages).toBeDefined();
  expectTypeOf(data.packages).toEqualTypeOf<ArcadePackage[]>();
  expect(data.blockingDead).toBeDefined();
  expect(data.blockingDead).toBeInstanceOf(BlockingDead);
  expectTypeOf(data.blockingDead).toEqualTypeOf<BlockingDead>();
  expect(data.dragonWars).toBeDefined();
  expect(data.dragonWars).toBeInstanceOf(DragonWars);
  expectTypeOf(data.dragonWars).toEqualTypeOf<DragonWars>();
  expect(data.dropper).toBeDefined();
  expect(data.dropper).toBeInstanceOf(Dropper);
  expectTypeOf(data.dropper).toEqualTypeOf<Dropper>();
  expect(data.drawTheirThing).toBeDefined();
  expect(data.drawTheirThing).toBeInstanceOf(DrawTheirThing);
  expectTypeOf(data.drawTheirThing).toEqualTypeOf<DrawTheirThing>();
  expect(data.dtt).toBeDefined();
  expect(data.dtt).toBeInstanceOf(Dtt);
  expectTypeOf(data.dtt).toEqualTypeOf<Dtt>();
  expect(data.easterSimulator).toBeDefined();
  expect(data.easterSimulator).toBeInstanceOf(EasterSimulator);
  expectTypeOf(data.easterSimulator).toEqualTypeOf<EasterSimulator>();
  expect(data.enderSpleef).toBeDefined();
  expect(data.enderSpleef).toBeInstanceOf(EnderSpleef);
  expectTypeOf(data.enderSpleef).toEqualTypeOf<EnderSpleef>();
  expect(data.farmHunt).toBeDefined();
  expect(data.farmHunt).toBeInstanceOf(FarmHunt);
  expectTypeOf(data.farmHunt).toEqualTypeOf<FarmHunt>();
  expect(data.footBall).toBeDefined();
  expect(data.footBall).toBeInstanceOf(FootBall);
  expectTypeOf(data.footBall).toEqualTypeOf<FootBall>();
  expect(data.galaxyWars).toBeDefined();
  expect(data.galaxyWars).toBeInstanceOf(GalaxyWars);
  expectTypeOf(data.galaxyWars).toEqualTypeOf<GalaxyWars>();
  expect(data.grinchSimulator).toBeDefined();
  expect(data.grinchSimulator).toBeInstanceOf(GrinchSimulator);
  expectTypeOf(data.grinchSimulator).toEqualTypeOf<GrinchSimulator>();
  expect(data.halloweenSimulator).toBeDefined();
  expect(data.halloweenSimulator).toBeInstanceOf(HalloweenSimulator);
  expectTypeOf(data.halloweenSimulator).toEqualTypeOf<HalloweenSimulator>();
  expect(data.hideAndSeek).toBeDefined();
  expect(data.hideAndSeek).toBeInstanceOf(HideAndSeek);
  expectTypeOf(data.hideAndSeek).toEqualTypeOf<HideAndSeek>();
  expect(data.holeInTheWall).toBeDefined();
  expect(data.holeInTheWall).toBeInstanceOf(HoleInTheWall);
  expectTypeOf(data.holeInTheWall).toEqualTypeOf<HoleInTheWall>();
  expect(data.hypixelSports).toBeDefined();
  expect(data.hypixelSports).toBeInstanceOf(HypixelSports);
  expectTypeOf(data.hypixelSports).toEqualTypeOf<HypixelSports>();
  expect(data.MiniWalls).toBeDefined();
  expect(data.MiniWalls).toBeInstanceOf(MiniWalls);
  expectTypeOf(data.MiniWalls).toEqualTypeOf<MiniWalls>();
  expect(data.oneInTheQuiver).toBeDefined();
  expect(data.oneInTheQuiver).toBeInstanceOf(OneInTheQuiver);
  expectTypeOf(data.oneInTheQuiver).toEqualTypeOf<OneInTheQuiver>();
  expect(data.partyGames).toBeDefined();
  expect(data.partyGames).toBeInstanceOf(PartyGames);
  expectTypeOf(data.partyGames).toEqualTypeOf<PartyGames>();
  expect(data.santaSays).toBeDefined();
  expect(data.santaSays).toBeInstanceOf(SantaSays);
  expectTypeOf(data.santaSays).toEqualTypeOf<SantaSays>();
  expect(data.santaSimulator).toBeDefined();
  expect(data.santaSimulator).toBeInstanceOf(SantaSimulator);
  expectTypeOf(data.santaSimulator).toEqualTypeOf<SantaSimulator>();
  expect(data.scubaSimulator).toBeDefined();
  expect(data.scubaSimulator).toBeInstanceOf(ScubaSimulator);
  expectTypeOf(data.scubaSimulator).toEqualTypeOf<ScubaSimulator>();
  expect(data.simonSays).toBeDefined();
  expect(data.simonSays).toBeInstanceOf(SimonSays);
  expectTypeOf(data.simonSays).toEqualTypeOf<SimonSays>();
  expect(data.soccer).toBeDefined();
  expect(data.soccer).toBeInstanceOf(Soccer);
  expectTypeOf(data.soccer).toEqualTypeOf<Soccer>();
  expect(data.throwOut).toBeDefined();
  expect(data.throwOut).toBeInstanceOf(ThrowOut);
  expectTypeOf(data.throwOut).toEqualTypeOf<ThrowOut>();
  expect(data.woolHunt).toBeDefined();
  expect(data.woolHunt).toBeInstanceOf(WoolHunt);
  expectTypeOf(data.woolHunt).toEqualTypeOf<WoolHunt>();
  expect(data.zombies).toBeDefined();
  expect(data.zombies).toBeInstanceOf(Zombies);
  expectTypeOf(data.zombies).toEqualTypeOf<Zombies>();
});
