import GalaxyWars from './GalaxyWars.js';
import { expect, expectTypeOf, test } from 'vitest';

test('GalaxyWars', () => {
  const data = new GalaxyWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(GalaxyWars);
  expectTypeOf(data).toEqualTypeOf<GalaxyWars>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.empireKills).toBeDefined();
  expect(data.empireKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.empireKills).toEqualTypeOf<number>();
  expect(data.gameWins).toBeDefined();
  expect(data.gameWins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gameWins).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.monthlyKills).toBeDefined();
  expect(data.monthlyKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKills).toEqualTypeOf<number>();
  expect(data.monthlyKillsA).toBeDefined();
  expect(data.monthlyKillsA).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKillsA).toEqualTypeOf<number>();
  expect(data.monthlyKillsB).toBeDefined();
  expect(data.monthlyKillsB).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKillsB).toEqualTypeOf<number>();
  expect(data.rebelKills).toBeDefined();
  expect(data.rebelKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.rebelKills).toEqualTypeOf<number>();
  expect(data.shotsFired).toBeDefined();
  expect(data.shotsFired).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.shotsFired).toEqualTypeOf<number>();
  expect(data.weeklyKills).toBeDefined();
  expect(data.weeklyKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKills).toEqualTypeOf<number>();
  expect(data.weeklyKillsA).toBeDefined();
  expect(data.weeklyKillsA).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKillsA).toEqualTypeOf<number>();
  expect(data.weeklyKillsB).toBeDefined();
  expect(data.weeklyKillsB).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKillsB).toEqualTypeOf<number>();
});
