import GalaxyWars from './GalaxyWars.js';
import { expect, expectTypeOf, test } from 'vitest';

test('GalaxyWars', () => {
  const data = new GalaxyWars({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(GalaxyWars);
  expectTypeOf(data).toEqualTypeOf<GalaxyWars>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.shotsFired).toBeDefined();
  expect(data.shotsFired).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.shotsFired).toEqualTypeOf<number>();
  expect(data.weeklyKills).toBeDefined();
  expect(data.weeklyKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.weeklyKills).toEqualTypeOf<number>();
  expect(data.monthlyKills).toBeDefined();
  expect(data.monthlyKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.monthlyKills).toEqualTypeOf<number>();
  expect(data.attackerKills).toBeDefined();
  expect(data.attackerKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.attackerKills).toEqualTypeOf<number>();
  expect(data.defenderKills).toBeDefined();
  expect(data.defenderKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.defenderKills).toEqualTypeOf<number>();
});
