import MiniWalls from './MiniWalls.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { MiniWallsKits } from '../../../Types/Player.js';

test('MiniWalls', () => {
  const data = new MiniWalls({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(MiniWalls);
  expectTypeOf(data).toEqualTypeOf<MiniWalls>();
  expect(data.kit).toBeDefined();
  expectTypeOf(data.kit).toEqualTypeOf<MiniWallsKits | 'None'>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.finalKills).toBeDefined();
  expect(data.finalKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.finalKills).toEqualTypeOf<number>();
  expect(data.witherKills).toBeDefined();
  expect(data.witherKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherKills).toEqualTypeOf<number>();
  expect(data.witherDamage).toBeDefined();
  expect(data.witherDamage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherDamage).toEqualTypeOf<number>();
  expect(data.arrowsShot).toBeDefined();
  expect(data.arrowsShot).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsShot).toEqualTypeOf<number>();
  expect(data.arrowsHit).toBeDefined();
  expect(data.arrowsHit).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsHit).toEqualTypeOf<number>();
  expect(data.bowAccuracy).toBeDefined();
  expect(data.bowAccuracy).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bowAccuracy).toEqualTypeOf<number>();
});
