import MiniWalls from './MiniWalls.js';
import { expect, expectTypeOf, test } from 'vitest';

test('MiniWalls', () => {
  const data = new MiniWalls({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(MiniWalls);
  expectTypeOf(data).toEqualTypeOf<MiniWalls>();
  expect(data.arrowsHit).toBeDefined();
  expect(data.arrowsHit).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsHit).toEqualTypeOf<number>();
  expect(data.arrowsHitTourney0).toBeDefined();
  expect(data.arrowsHitTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsHitTourney0).toEqualTypeOf<number>();
  expect(data.arrowsShot).toBeDefined();
  expect(data.arrowsShot).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsShot).toEqualTypeOf<number>();
  expect(data.arrowsShotTourney0).toBeDefined();
  expect(data.arrowsShotTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.arrowsShotTourney0).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.deathsTourney0).toBeDefined();
  expect(data.deathsTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deathsTourney0).toEqualTypeOf<number>();
  expect(data.finalKills).toBeDefined();
  expect(data.finalKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.finalKills).toEqualTypeOf<number>();
  expect(data.finalKillsTourney0).toBeDefined();
  expect(data.finalKillsTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.finalKillsTourney0).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.killsTourney0).toBeDefined();
  expect(data.killsTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsTourney0).toEqualTypeOf<number>();
  expect(data.inventoryLayout).toBeDefined();
  expectTypeOf(data.inventoryLayout).toEqualTypeOf<Record<string, number>>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.winsTourney0).toBeDefined();
  expect(data.winsTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winsTourney0).toEqualTypeOf<number>();
  expect(data.witherDamage).toBeDefined();
  expect(data.witherDamage).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherDamage).toEqualTypeOf<number>();
  expect(data.witherDamageTourney0).toBeDefined();
  expect(data.witherDamageTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherDamageTourney0).toEqualTypeOf<number>();
  expect(data.witherKills).toBeDefined();
  expect(data.witherKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherKills).toEqualTypeOf<number>();
  expect(data.witherKillsTourney0).toBeDefined();
  expect(data.witherKillsTourney0).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.witherKillsTourney0).toEqualTypeOf<number>();
});
