packages:
  - ./TypeScript/SettingUpClient/Code
  - ./TypeScript/SkyHelperNetworth/Code
  - ./JavaScript/SettingUpClient/Code
  - ./JavaScript/SkyHelperNetworth/Code
catalog:
  tsx: ^4.20.6
  typescript: ^5.9.3
  prettier: ^3.6.2
  hypixel-api-reborn: 12.0.0-15
  yaml: ^2.8.1
  skyhelper-networth: ^2.5.1
