module.exports = {
  INVALID_API_KEY: '[hypixel-api-reborn] Invalid API Key! For help join our Discord Server https://discord.gg/NSEBNMM',
  NO_API_KEY: '[hypixel-api-reborn] No API Key specified! For help join our Discord Server https://discord.gg/NSEBNMM',
  ERROR_CODE_CAUSE: '[hypixel-api-reborn] Code: {code} - {cause}! For help join our Discord Server https://discord.gg/NSEBNMM',
  ERROR_STATUSTEXT: '[hypixel-api-reborn] {statustext}! For help join our Discord Server https://discord.gg/NSEBNMM',
  KEY_MUST_BE_A_STRING: '[hypixel-api-reborn] Specified API Key must be a string! For help join our Discord Server https://discord.gg/NSEBNMM',
  OPTIONS_MUST_BE_AN_OBJECT: '[hypixel-api-reborn] Options must be an object! For help join our Discord Server https://discord.gg/NSEBNMM',
  CACHE_TIME_MUST_BE_A_NUMBER: '[hypixel-api-reborn] Cache Time must be a number! For help join our Discord Server https://discord.gg/NSEBNMM',
  CACHE_LIMIT_MUST_BE_A_NUMBER: '[hypixel-api-reborn] Cache Limit must be a number! For help join our Discord Server https://discord.gg/NSEBNMM',
  NO_NICKNAME_UUID: '[hypixel-api-reborn] No nickname or uuid specified.',
  NO_UUID: '[hypixel-api-reborn] No uuid specified.',
  UUID_NICKNAME_MUST_BE_A_STRING: '[hypixel-api-reborn] Nickname or uuid must be a string.',
  MALFORMED_UUID: '[hypixel-api-reborn] Malformed UUID!',
  PLAYER_DOES_NOT_EXIST: '[hypixel-api-reborn] Player does not exist.',
  NO_GUILD_QUERY: '[hypixel-api-reborn] No guild search query specified.',
  INVALID_GUILD_ID: '[hypixel-api-reborn] Specified Guild ID is invalid.',
  INVALID_GUILD_SEARCH_PARAMETER: '[hypixel-api-reborn] getGuild() searchParameter must be \'id\', \'guild\' or \'player\'.',
  SOMETHING_WENT_WRONG: '[hypixel-api-reborn] Something went wrong. {cause}',
  GUILD_DOES_NOT_EXIST: '[hypixel-api-reborn] Guild does not exist.',
  INVALID_RESPONSE_BODY: '[hypixel-api-reborn] An error occurred while converting to JSON. Perhaps this is due to an update or maintenance. For help join our Discord Server https://discord.gg/NSEBNMM'
};
