import Warlords from './Warlords.js';
import WarlordsClass from './WarlordsClass.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { WarlordsClasses } from '../../../Types/Player.js';

test('Warlords', () => {
  const data = new Warlords({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Warlords);
  expectTypeOf(data).toEqualTypeOf<Warlords>();
  expect(data.coins).toBeDefined();
  expect(data.coins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.coins).toEqualTypeOf<number>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.WLR).toBeDefined();
  expect(data.WLR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.WLR).toEqualTypeOf<number>();
  expect(data.winStreak).toBeDefined();
  expect(data.winStreak).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.winStreak).toEqualTypeOf<number>();
  expect(data.assists).toBeDefined();
  expect(data.assists).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.assists).toEqualTypeOf<number>();
  expect(data.class).toBeDefined();
  expectTypeOf(data.class).toEqualTypeOf<WarlordsClasses | 'None'>();
  expect(data.pyromancer).toBeDefined();
  expect(data.pyromancer).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.pyromancer).toEqualTypeOf<WarlordsClass>();
  expect(data.mage).toBeDefined();
  expect(data.mage).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.mage).toEqualTypeOf<WarlordsClass>();
  expect(data.thunderlord).toBeDefined();
  expect(data.thunderlord).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.thunderlord).toEqualTypeOf<WarlordsClass>();
  expect(data.shaman).toBeDefined();
  expect(data.shaman).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.shaman).toEqualTypeOf<WarlordsClass>();
  expect(data.earthwarden).toBeDefined();
  expect(data.earthwarden).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.earthwarden).toEqualTypeOf<WarlordsClass>();
  expect(data.aquamancer).toBeDefined();
  expect(data.aquamancer).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.aquamancer).toEqualTypeOf<WarlordsClass>();
  expect(data.paladin).toBeDefined();
  expect(data.paladin).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.paladin).toEqualTypeOf<WarlordsClass>();
  expect(data.avenger).toBeDefined();
  expect(data.avenger).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.avenger).toEqualTypeOf<WarlordsClass>();
  expect(data.warrior).toBeDefined();
  expect(data.warrior).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.warrior).toEqualTypeOf<WarlordsClass>();
  expect(data.defender).toBeDefined();
  expect(data.defender).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.defender).toEqualTypeOf<WarlordsClass>();
  expect(data.cryomancer).toBeDefined();
  expect(data.cryomancer).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.cryomancer).toEqualTypeOf<WarlordsClass>();
  expect(data.crusader).toBeDefined();
  expect(data.crusader).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.crusader).toEqualTypeOf<WarlordsClass>();
  expect(data.berserker).toBeDefined();
  expect(data.berserker).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.berserker).toEqualTypeOf<WarlordsClass>();
  expect(data.protector).toBeDefined();
  expect(data.protector).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.protector).toEqualTypeOf<WarlordsClass>();
  expect(data.revenant).toBeDefined();
  expect(data.revenant).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.revenant).toEqualTypeOf<WarlordsClass>();
  expect(data.spiritguard).toBeDefined();
  expect(data.spiritguard).toBeInstanceOf(WarlordsClass);
  expectTypeOf(data.spiritguard).toEqualTypeOf<WarlordsClass>();
});
