import GaemCountsDuels from './Duels/GameCountsDuels.js';
import GameCountsArcade from './Arcade/GameCountsArcade.js';
import GameCountsBattleGround from './BattleGround/GameCountsBattleGround.js';
import GameCountsBedWars from './BedWars/GameCountsBedWars.js';
import GameCountsBuildBattle from './BuildBattle/GameCountsBuildBattle.js';
import GameCountsGeneric from './GameCountsGeneric.ts';
import GameCountsLegacy from './Legacy/GameCountsLegacy.js';
import GameCountsMCGO from './MCGO/GameCountsMCGO.js';
import GameCountsMurderMystery from './MurderMystery/GameCountsMurderMystery.js';
import GameCountsPit from './Pit/GameCountsPit.js';
import GameCountsReplay from './Replay/GameCountsReplay.js';
import GameCountsSkyBlock from './SkyBlock/GameCountsSkyBlock.js';
import GameCountsSkyWars from './SkyWars/GameCountsSkyWars.js';
import GameCountsSpeedUHC from './SpeedUHC/GameCountsSpeedUHC.js';
import GameCountsSuperSmash from './SuperSmash/GameCountsSuperSmash.js';
import GameCountsSurvivalGames from './SurvivalGames/GameCountsSurvivalGames.js';
import GameCountsTNTGames from './TNTGames/GameCountsTNTGames.js';
import GameCountsWoolGames from './WoolGames/GameCountsWoolGames.js';
import UHC from './UHC/GameCountsUHC.js';
import Walls3 from './Walls3/GameCountsWalls3.js';

class GameCountGames {
  mainLobby: GameCountsGeneric;
  tournamentLobby: GameCountsGeneric;
  smp: GameCountsGeneric;
  legacy: GameCountsLegacy;
  SkyBlock: GameCountsSkyBlock;
  UHC: UHC;
  skywars: GameCountsSkyWars;
  replay: GameCountsReplay;
  speedUHC: GameCountsSpeedUHC;
  arcade: GameCountsArcade;
  housing: GameCountsGeneric;
  battleGround: GameCountsBattleGround;
  superSmash: GameCountsSuperSmash;
  bedwars: GameCountsBedWars;
  duels: GaemCountsDuels;
  walls3: Walls3;
  murderMystery: GameCountsMurderMystery;
  survivalGames: GameCountsSurvivalGames;
  buildBattle: GameCountsBuildBattle;
  pit: GameCountsPit;
  woolGames: GameCountsWoolGames;
  tntGames: GameCountsTNTGames;
  MCGO: GameCountsMCGO;
  prototype: GameCountsGeneric;
  limbo: GameCountsGeneric;
  idle: GameCountsGeneric;
  queue: GameCountsGeneric;
  constructor(data: Record<string, any>) {
    this.mainLobby = new GameCountsGeneric(data?.MAIN_LOBBY);
    this.tournamentLobby = new GameCountsGeneric(data?.TOURNAMENT_LOBBY);
    this.smp = new GameCountsGeneric(data?.SMP);
    this.legacy = new GameCountsLegacy(data?.LEGACY);
    this.SkyBlock = new GameCountsSkyBlock(data?.SKYBLOCK);
    this.UHC = new UHC(data?.UHC);
    this.skywars = new GameCountsSkyWars(data?.SKYWARS);
    this.replay = new GameCountsReplay(data?.REPLAY);
    this.speedUHC = new GameCountsSpeedUHC(data?.SPEED_UHC);
    this.arcade = new GameCountsArcade(data?.ARCADE);
    this.housing = new GameCountsGeneric(data?.HOUSING);
    this.battleGround = new GameCountsBattleGround(data?.BATTLEGROUND);
    this.superSmash = new GameCountsSuperSmash(data?.SUPER_SMASH);
    this.bedwars = new GameCountsBedWars(data?.BEDWARS);
    this.duels = new GaemCountsDuels(data?.DUELS);
    this.walls3 = new Walls3(data?.WALLS3);
    this.murderMystery = new GameCountsMurderMystery(data?.MURDER_MYSTERY);
    this.survivalGames = new GameCountsSurvivalGames(data?.SURVIVAL_GAMES);
    this.buildBattle = new GameCountsBuildBattle(data?.BUILD_BATTLE);
    this.pit = new GameCountsPit(data?.PIT);
    this.woolGames = new GameCountsWoolGames(data?.WOOL_GAMES);
    this.tntGames = new GameCountsTNTGames(data?.TNTGAMES);
    this.MCGO = new GameCountsMCGO(data?.MCGO);
    this.prototype = new GameCountsGeneric(data?.PROTOTYPE);
    this.limbo = new GameCountsGeneric(data?.LIMBO);
    this.idle = new GameCountsGeneric(data?.IDLE);
    this.queue = new GameCountsGeneric(data?.QUEUE);
  }
}

export default GameCountGames;
