import GaemCountsDuels from './Duels/GameCountsDuels.js';
import GameCountGames from './GameCountsGames.ts';
import GameCountsArcade from './Arcade/GameCountsArcade.js';
import GameCountsBattleGround from './BattleGround/GameCountsBattleGround.js';
import GameCountsBedWars from './BedWars/GameCountsBedWars.js';
import GameCountsBuildBattle from './BuildBattle/GameCountsBuildBattle.js';
import GameCountsGeneric from './GameCountsGeneric.js';
import GameCountsLegacy from './Legacy/GameCountsLegacy.js';
import GameCountsMCGO from './MCGO/GameCountsMCGO.js';
import GameCountsMurderMystery from './MurderMystery/GameCountsMurderMystery.js';
import GameCountsPit from './Pit/GameCountsPit.js';
import GameCountsReplay from './Replay/GameCountsReplay.js';
import GameCountsSkyBlock from './SkyBlock/GameCountsSkyBlock.js';
import GameCountsSkyWars from './SkyWars/GameCountsSkyWars.js';
import GameCountsSpeedUHC from './SpeedUHC/GameCountsSpeedUHC.js';
import GameCountsSuperSmash from './SuperSmash/GameCountsSuperSmash.js';
import GameCountsSurvivalGames from './SurvivalGames/GameCountsSurvivalGames.js';
import GameCountsTNTGames from './TNTGames/GameCountsTNTGames.js';
import GameCountsWoolGames from './WoolGames/GameCountsWoolGames.js';
import UHC from './UHC/GameCountsUHC.js';
import Walls3 from './Walls3/GameCountsWalls3.js';
import { expect, expectTypeOf, test } from 'vitest';

test('GameCountGames', () => {
  const data = new GameCountGames({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(GameCountGames);
  expectTypeOf(data).toEqualTypeOf<GameCountGames>();
  expect(data.mainLobby).toBeDefined();
  expect(data.mainLobby).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.mainLobby).toEqualTypeOf<GameCountsGeneric>();
  expect(data.tournamentLobby).toBeDefined();
  expect(data.tournamentLobby).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.tournamentLobby).toEqualTypeOf<GameCountsGeneric>();
  expect(data.smp).toBeDefined();
  expect(data.smp).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.smp).toEqualTypeOf<GameCountsGeneric>();
  expect(data.legacy).toBeDefined();
  expect(data.legacy).toBeInstanceOf(GameCountsLegacy);
  expectTypeOf(data.legacy).toEqualTypeOf<GameCountsLegacy>();
  expect(data.SkyBlock).toBeDefined();
  expect(data.SkyBlock).toBeInstanceOf(GameCountsSkyBlock);
  expectTypeOf(data.SkyBlock).toEqualTypeOf<GameCountsSkyBlock>();
  expect(data.UHC).toBeDefined();
  expect(data.UHC).toBeInstanceOf(UHC);
  expectTypeOf(data.UHC).toEqualTypeOf<UHC>();
  expect(data.skywars).toBeDefined();
  expect(data.skywars).toBeInstanceOf(GameCountsSkyWars);
  expectTypeOf(data.skywars).toEqualTypeOf<GameCountsSkyWars>();
  expect(data.replay).toBeDefined();
  expect(data.replay).toBeInstanceOf(GameCountsReplay);
  expectTypeOf(data.replay).toEqualTypeOf<GameCountsReplay>();
  expect(data.speedUHC).toBeDefined();
  expect(data.speedUHC).toBeInstanceOf(GameCountsSpeedUHC);
  expectTypeOf(data.speedUHC).toEqualTypeOf<GameCountsSpeedUHC>();
  expect(data.arcade).toBeDefined();
  expect(data.arcade).toBeInstanceOf(GameCountsArcade);
  expectTypeOf(data.arcade).toEqualTypeOf<GameCountsArcade>();
  expect(data.housing).toBeDefined();
  expect(data.housing).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.housing).toEqualTypeOf<GameCountsGeneric>();
  expect(data.battleGround).toBeDefined();
  expect(data.battleGround).toBeInstanceOf(GameCountsBattleGround);
  expectTypeOf(data.battleGround).toEqualTypeOf<GameCountsBattleGround>();
  expect(data.superSmash).toBeDefined();
  expect(data.superSmash).toBeInstanceOf(GameCountsSuperSmash);
  expectTypeOf(data.superSmash).toEqualTypeOf<GameCountsSuperSmash>();
  expect(data.bedwars).toBeDefined();
  expect(data.bedwars).toBeInstanceOf(GameCountsBedWars);
  expectTypeOf(data.bedwars).toEqualTypeOf<GameCountsBedWars>();
  expect(data.duels).toBeDefined();
  expect(data.duels).toBeInstanceOf(GaemCountsDuels);
  expectTypeOf(data.duels).toEqualTypeOf<GaemCountsDuels>();
  expect(data.walls3).toBeDefined();
  expect(data.walls3).toBeInstanceOf(Walls3);
  expectTypeOf(data.walls3).toEqualTypeOf<Walls3>();
  expect(data.murderMystery).toBeDefined();
  expect(data.murderMystery).toBeInstanceOf(GameCountsMurderMystery);
  expectTypeOf(data.murderMystery).toEqualTypeOf<GameCountsMurderMystery>();
  expect(data.survivalGames).toBeDefined();
  expect(data.survivalGames).toBeInstanceOf(GameCountsSurvivalGames);
  expectTypeOf(data.survivalGames).toEqualTypeOf<GameCountsSurvivalGames>();
  expect(data.buildBattle).toBeDefined();
  expect(data.buildBattle).toBeInstanceOf(GameCountsBuildBattle);
  expectTypeOf(data.buildBattle).toEqualTypeOf<GameCountsBuildBattle>();
  expect(data.pit).toBeDefined();
  expect(data.pit).toBeInstanceOf(GameCountsPit);
  expectTypeOf(data.pit).toEqualTypeOf<GameCountsPit>();
  expect(data.woolGames).toBeDefined();
  expect(data.woolGames).toBeInstanceOf(GameCountsWoolGames);
  expectTypeOf(data.woolGames).toEqualTypeOf<GameCountsWoolGames>();
  expect(data.tntGames).toBeDefined();
  expect(data.tntGames).toBeInstanceOf(GameCountsTNTGames);
  expectTypeOf(data.tntGames).toEqualTypeOf<GameCountsTNTGames>();
  expect(data.MCGO).toBeDefined();
  expect(data.MCGO).toBeInstanceOf(GameCountsMCGO);
  expectTypeOf(data.MCGO).toEqualTypeOf<GameCountsMCGO>();
  expect(data.prototype).toBeDefined();
  expect(data.prototype).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.prototype).toEqualTypeOf<GameCountsGeneric>();
  expect(data.limbo).toBeDefined();
  expect(data.limbo).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.limbo).toEqualTypeOf<GameCountsGeneric>();
  expect(data.idle).toBeDefined();
  expect(data.idle).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.idle).toEqualTypeOf<GameCountsGeneric>();
  expect(data.queue).toBeDefined();
  expect(data.queue).toBeInstanceOf(GameCountsGeneric);
  expectTypeOf(data.queue).toEqualTypeOf<GameCountsGeneric>();
});
