import BedWarsKillsDeaths from './BedWarsKillsDeaths.js';
import BedWarsKillsDeathsType from './BedWarsKillsDeathsType.js';
import { expect, expectTypeOf, test } from 'vitest';

test('BedWarsKillsDeaths', () => {
  const data = new BedWarsKillsDeaths({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(BedWarsKillsDeaths);
  expectTypeOf(data).toEqualTypeOf<BedWarsKillsDeaths>();
  expect(data.total).toBeDefined();
  expect(data.total).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.total).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.custom).toBeDefined();
  expect(data.custom).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.custom).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.drowning).toBeDefined();
  expect(data.drowning).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.drowning).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.entityAttack).toBeDefined();
  expect(data.entityAttack).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.entityAttack).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.entityExplosion).toBeDefined();
  expect(data.entityExplosion).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.entityExplosion).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.fall).toBeDefined();
  expect(data.fall).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.fall).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.fire).toBeDefined();
  expect(data.fire).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.fire).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.fireTick).toBeDefined();
  expect(data.fireTick).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.fireTick).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.magic).toBeDefined();
  expect(data.magic).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.magic).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.projectile).toBeDefined();
  expect(data.projectile).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.projectile).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.suffocation).toBeDefined();
  expect(data.suffocation).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.suffocation).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.void).toBeDefined();
  expect(data.void).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.void).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.fallingBlock).toBeDefined();
  expect(data.fallingBlock).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.fallingBlock).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.lava).toBeDefined();
  expect(data.lava).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.lava).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.contact).toBeDefined();
  expect(data.contact).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.contact).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.thorns).toBeDefined();
  expect(data.thorns).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.thorns).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.wither).toBeDefined();
  expect(data.wither).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.wither).toEqualTypeOf<BedWarsKillsDeathsType>();
  expect(data.blockExplosion).toBeDefined();
  expect(data.blockExplosion).toBeInstanceOf(BedWarsKillsDeathsType);
  expectTypeOf(data.blockExplosion).toEqualTypeOf<BedWarsKillsDeathsType>();
});
