import SkyBlockBazaarQuickStatus from './SkyBlockBazaarQuickStatus.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { BazaarProduct } from '../../../Types/SkyBlock.js';

test('SkyBlockBazaarQuickStatus', () => {
  const data = new SkyBlockBazaarQuickStatus({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyBlockBazaarQuickStatus);
  expectTypeOf(data).toEqualTypeOf<SkyBlockBazaarQuickStatus>();
  expect(data.productId).toBeDefined();
  expectTypeOf(data.productId).toEqualTypeOf<BazaarProduct | 'UNKNOWN'>();
  expect(data.sellPrice).toBeDefined();
  expect(data.sellPrice).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sellPrice).toEqualTypeOf<number>();
  expect(data.sellVolume).toBeDefined();
  expect(data.sellVolume).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sellVolume).toEqualTypeOf<number>();
  expect(data.sellMovingWeek).toBeDefined();
  expect(data.sellMovingWeek).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sellMovingWeek).toEqualTypeOf<number>();
  expect(data.sellOrders).toBeDefined();
  expect(data.sellOrders).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.sellOrders).toEqualTypeOf<number>();
  expect(data.buyPrice).toBeDefined();
  expect(data.buyPrice).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.buyPrice).toEqualTypeOf<number>();
  expect(data.buyVolume).toBeDefined();
  expect(data.buyVolume).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.buyVolume).toEqualTypeOf<number>();
  expect(data.buyMovingWeek).toBeDefined();
  expect(data.buyMovingWeek).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.buyMovingWeek).toEqualTypeOf<number>();
  expect(data.buyOrders).toBeDefined();
  expect(data.buyOrders).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.buyOrders).toEqualTypeOf<number>();
  expect(data.toString).toBeDefined();
  expectTypeOf(data.toString).toEqualTypeOf<() => BazaarProduct | 'UNKNOWN'>();
  expect(data.toString()).toBeDefined();
  expect(data.toString()).toBe(data.productId);
  expectTypeOf(data.toString()).toEqualTypeOf<BazaarProduct | 'UNKNOWN'>();
});
