import Guild from '../Guild/Guild.js';
import House from '../House.js';
import Player from './Player.js';
import PlayerAchievements from './PlayerAchievements/PlayerAchievements.js';
import PlayerAdventRewards from './PlayerAdventRewards/PlayerAdventRewards.js';
import PlayerCosmetics from './PlayerCosmetics/PlayerCosmetics.js';
import PlayerGifting from './PlayerGifting.js';
import PlayerHousing from './PlayerHousing/PlayerHousing.js';
import PlayerParkour from './PlayerParkour.js';
import PlayerQuests from './PlayerQuests/PlayerQuests.js';
import PlayerRankPurchase from './PlayerRankPurchase.js';
import PlayerRewards from './PlayerRewards/PlayerRewards.js';
import PlayerScorpiusBribe from './PlayerScorpiusBribe.js';
import PlayerSocialMedia from './PlayerSocialMedia.js';
import PlayerStats from './PlayerStats.js';
import RecentGame from '../RecentGame.js';
import { expect, expectTypeOf, test } from 'vitest';
import type { ChatChannel, Language, LevelProgress, PlayerRank } from '../../Types/Player.js';

test('Player', () => {
  const data = new Player({ stats: 'meow' }, {});
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.lastLogoutAt).toBeDefined();
  expectTypeOf(data.lastLogoutAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expect(data.achievements).toBeInstanceOf(PlayerAchievements);
  expectTypeOf(data.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.stats).toBeDefined();
  expect(data.stats).toBeInstanceOf(PlayerStats);
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.claimedCenturyCakeAt).toBeDefined();
  expectTypeOf(data.claimedCenturyCakeAt).toEqualTypeOf<Date | null>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.cosmetics).toBeDefined();
  expect(data.cosmetics).toBeInstanceOf(PlayerCosmetics);
  expectTypeOf(data.cosmetics).toEqualTypeOf<PlayerCosmetics>();
  expect(data.rankPurchase).toBeDefined();
  expect(data.rankPurchase).toBeInstanceOf(PlayerRankPurchase);
  expectTypeOf(data.rankPurchase).toEqualTypeOf<PlayerRankPurchase>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<Record<string, Record<string, number>>>();
  expect(data.quests).toBeDefined();
  expect(data.quests).toBeInstanceOf(PlayerQuests);
  expectTypeOf(data.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.rewards).toBeDefined();
  expect(data.rewards).toBeInstanceOf(PlayerRewards);
  expectTypeOf(data.rewards).toEqualTypeOf<PlayerRewards>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<PlayerParkour[]>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.skyBlockFreeCookieAt).toBeDefined();
  expectTypeOf(data.skyBlockFreeCookieAt).toEqualTypeOf<Date | null>();
  expect(data.housing).toBeDefined();
  expect(data.housing).toBeInstanceOf(PlayerHousing);
  expectTypeOf(data.housing).toEqualTypeOf<PlayerHousing>();
  expect(data.adventRewards).toBeDefined();
  expectTypeOf(data.adventRewards).toEqualTypeOf<PlayerAdventRewards[]>();
  expect(data.gifting).toBeDefined();
  expect(data.gifting).toBeInstanceOf(PlayerGifting);
  expectTypeOf(data.gifting).toEqualTypeOf<PlayerGifting>();
  expect(data.socialMedia).toBeDefined();
  expect(data.socialMedia).toBeInstanceOf(PlayerSocialMedia);
  expectTypeOf(data.socialMedia).toEqualTypeOf<PlayerSocialMedia>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<PlayerScorpiusBribe[]>();
  expect(data.guild).toBeDefined();
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expect(data.houses).toBeDefined();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  expect(data.recentGames).toBeDefined();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
});
