import Arcade from '../MiniGames/Arcade/Arcade.ts';
import ArenaBrawl from '../MiniGames/ArenaBrawl/ArenaBrawl.ts';
import BedWars from '../MiniGames/BedWars/BedWars.ts';
import BlitzSurvivalGames from '../MiniGames/BlitzSurvivalGames/BlitzSurvivalGames.ts';
import BuildBattle from '../MiniGames/BuildBattle/BuildBattle.ts';
import CopsAndCrims from '../MiniGames/CopsAndCrims/CopsAndCrims.ts';
import Duels from '../MiniGames/Duels/Duels.ts';
import MegaWalls from '../MiniGames/MegaWalls/MegaWalls.ts';
import MurderMystery from '../MiniGames/MurderMystery/MurderMystery.ts';
import Paintball from '../MiniGames/Paintball.ts';
import Pit from '../MiniGames/Pit/Pit.ts';
import Quakecraft from '../MiniGames/Quakecraft/Quakecraft.ts';
import SkyWars from '../MiniGames/SkyWars/SkyWars.ts';
import SmashHeroes from '../MiniGames/SmashHeroes/SmashHeroes.ts';
import SpeedUHC from '../MiniGames/SpeedUHC/SpeedUHC.ts';
import TNTGames from '../MiniGames/TNTGames/TNTGames.ts';
import TurboKartRacers from '../MiniGames/TurboKartRacers/TurboKartRacers.ts';
import UHC from '../MiniGames/UHC/UHC.ts';
import VampireZ from '../MiniGames/VampireZ/VampireZ.ts';
import Walls from '../MiniGames/Walls.ts';
import Warlords from '../MiniGames/Warlords/Warlords.ts';
import WoolGames from '../MiniGames/WoolGames/WoolGames.ts';

class PlayerStats {
  Arcade: Arcade;
  ArenaBrawl: ArenaBrawl;
  BedWars: BedWars;
  BlitzSurvivalGames: BlitzSurvivalGames;
  BuildBattle: BuildBattle;
  CopsAndCrims: CopsAndCrims;
  Duels: Duels;
  MegaWalls: MegaWalls;
  MurderMystery: MurderMystery;
  Paintball: Paintball;
  Pit: Pit;
  QuakeCraft: Quakecraft;
  SkyWars: SkyWars;
  SmashHeroes: SmashHeroes;
  SpeedUHC: SpeedUHC;
  TNTGames: TNTGames;
  TurboKartRacers: TurboKartRacers;
  UHC: UHC;
  VampireZ: VampireZ;
  Walls: Walls;
  Warlords: Warlords;
  WoolGames: WoolGames;
  constructor(data: Record<string, any>) {
    this.Arcade = new Arcade(data?.Arcade);
    this.ArenaBrawl = new ArenaBrawl(data?.Arena);
    this.BedWars = new BedWars(data?.Bedwars);
    this.BlitzSurvivalGames = new BlitzSurvivalGames(data?.HungerGames);
    this.BuildBattle = new BuildBattle(data?.BuildBattle);
    this.CopsAndCrims = new CopsAndCrims(data?.MCGO);
    this.Duels = new Duels(data?.Duels);
    this.MegaWalls = new MegaWalls(data?.Walls3);
    this.MurderMystery = new MurderMystery(data?.MurderMystery);
    this.Paintball = new Paintball(data?.Paintball);
    this.Pit = new Pit(data?.Pit);
    this.QuakeCraft = new Quakecraft(data?.Quake);
    this.SkyWars = new SkyWars(data?.SkyWars);
    this.SmashHeroes = new SmashHeroes(data?.SuperSmash);
    this.SpeedUHC = new SpeedUHC(data?.SpeedUHC);
    this.TNTGames = new TNTGames(data?.TNTGames);
    this.TurboKartRacers = new TurboKartRacers(data?.GingerBread);
    this.UHC = new UHC(data?.UHC);
    this.VampireZ = new VampireZ(data?.VampireZ);
    this.Walls = new Walls(data?.Walls);
    this.Warlords = new Warlords(data?.Battleground);
    this.WoolGames = new WoolGames(data?.WoolGames);
  }
}

export default PlayerStats;
