import Arcade from '../MiniGames/Arcade/Arcade.js';
import ArenaBrawl from '../MiniGames/ArenaBrawl/ArenaBrawl.js';
import BedWars from '../MiniGames/BedWars/BedWars.js';
import BlitzSurvivalGames from '../MiniGames/BlitzSurvivalGames/BlitzSurvivalGames.js';
import BuildBattle from '../MiniGames/BuildBattle.js';
import Color from '../Color.js';
import CopsAndCrims from '../MiniGames/CopsAndCrims/CopsAndCrims.js';
import Cosmetics from './Cosmetics.js';
import Duels from '../MiniGames/Duels/Duels.js';
import Gifting from './Gifting.js';
import Guild from '../Guild/Guild.js';
import House from '../House.js';
import Housing from '../Housing.js';
import MegaWalls from '../MiniGames/MegaWalls/MegaWalls.js';
import MurderMystery from '../MiniGames/MurderMystery/MurderMystery.js';
import Paintball from '../MiniGames/Paintball.js';
import Parkour from './Parkour.js';
import Pit from '../MiniGames/Pit/Pit.js';
import Player from './Player.js';
import PlayerAchievements from './PlayerAchievements.js';
import PlayerQuests from './Quests/PlayerQuests.js';
import Quakecraft from '../MiniGames/Quakecraft/Quakecraft.js';
import RecentGame from '../RecentGame.js';
import Rewards from './Rewards.js';
import Seasonal from './Seasonal/Seasonal.js';
import SkyWars from '../MiniGames/SkyWars/SkyWars.js';
import SmashHeroes from '../MiniGames/SmashHeroes/SmashHeroes.js';
import SocialMedia from './SocialMedia.js';
import SpeedUHC from '../MiniGames/SpeedUHC/SpeedUHC.js';
import TNTGames from '../MiniGames/TNTGames/TNTGames.js';
import Tourney from './Tourney/Tourney.js';
import TurboKartRacers from '../MiniGames/TurboKartRacers/TurboKartRacers.js';
import UHC from '../MiniGames/UHC/UHC.js';
import VampireZ from '../MiniGames/VampireZ/VampireZ.js';
import Walls from '../MiniGames/Walls.js';
import Warlords from '../MiniGames/Warlords/Warlords.js';
import WoolGames from '../MiniGames/WoolGames/WoolGames.js';
import { expect, expectTypeOf, test } from 'vitest';
import type {
  ChatChannel,
  Language,
  LevelProgress,
  PlayerRank,
  PlayerStats,
  ScorpiusBribe
} from '../../Types/Player.js';

test('Player', () => {
  const data = new Player({ stats: 'meow' }, { guild: null, houses: null, recentGames: null });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.mvpPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusColor).toEqualTypeOf<Color | null>();
  expect(data.mvpPlusPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusPlusColor).toEqualTypeOf<Color | null>();
  expect(data.gifting).toBeDefined();
  expectTypeOf(data.gifting).toEqualTypeOf<Gifting>();
  expect(data.socialMedia).toBeDefined();
  expectTypeOf(data.socialMedia).toEqualTypeOf<SocialMedia[]>();
  expect(data.firstLoginTimestamp).toBeDefined();
  expect(data.firstLoginTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.firstLoginTimestamp).toEqualTypeOf<number>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date>();
  expect(data.lastLoginTimestamp).toBeDefined();
  expectTypeOf(data.lastLoginTimestamp).toEqualTypeOf<number | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expectTypeOf(data.achievements).toEqualTypeOf<PlayerAchievements>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.exp).toBeDefined();
  expect(data.exp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.exp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.seasonal).toBeDefined();
  expectTypeOf(data.seasonal).toEqualTypeOf<Seasonal>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.freeSkyblockCookie).toBeDefined();
  expectTypeOf(data.freeSkyblockCookie).toEqualTypeOf<number | null>();
  expect(data.tourney).toBeDefined();
  expectTypeOf(data.tourney).toEqualTypeOf<Tourney>();
  expect(data.rewards).toBeDefined();
  expectTypeOf(data.rewards).toEqualTypeOf<Rewards>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<object>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<Parkour[]>();
  expect(data.housing).toBeDefined();
  expectTypeOf(data.housing).toEqualTypeOf<Housing>();
  expect(data.cosmetics).toBeDefined();
  expectTypeOf(data.cosmetics).toEqualTypeOf<Cosmetics>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<ScorpiusBribe[]>();
  expect(data.quests).toBeDefined();
  expectTypeOf(data.quests).toEqualTypeOf<PlayerQuests>();
  expect(data.guild).toBeDefined();
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expect(data.houses).toBeDefined();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  expect(data.recentGames).toBeDefined();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
  expect(data.stats).toBeDefined();
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.stats.arcade).toBeDefined();
  expect(data.stats.arcade).toBeInstanceOf(Arcade);
  expectTypeOf(data.stats.arcade).toEqualTypeOf<Arcade>();
  expect(data.stats.arenaBrawl).toBeDefined();
  expect(data.stats.arenaBrawl).toBeInstanceOf(ArenaBrawl);
  expectTypeOf(data.stats.arenaBrawl).toEqualTypeOf<ArenaBrawl>();
  expect(data.stats.bedwars).toBeDefined();
  expect(data.stats.bedwars).toBeInstanceOf(BedWars);
  expectTypeOf(data.stats.bedwars).toEqualTypeOf<BedWars>();
  expect(data.stats.blitzsg).toBeDefined();
  expect(data.stats.blitzsg).toBeInstanceOf(BlitzSurvivalGames);
  expectTypeOf(data.stats.blitzsg).toEqualTypeOf<BlitzSurvivalGames>();
  expect(data.stats.buildbattle).toBeDefined();
  expect(data.stats.buildbattle).toBeInstanceOf(BuildBattle);
  expectTypeOf(data.stats.buildbattle).toEqualTypeOf<BuildBattle>();
  expect(data.stats.copsandcrims).toBeDefined();
  expect(data.stats.copsandcrims).toBeInstanceOf(CopsAndCrims);
  expectTypeOf(data.stats.copsandcrims).toEqualTypeOf<CopsAndCrims>();
  expect(data.stats.duels).toBeDefined();
  expect(data.stats.duels).toBeInstanceOf(Duels);
  expectTypeOf(data.stats.duels).toEqualTypeOf<Duels>();
  expect(data.stats.megawalls).toBeDefined();
  expect(data.stats.megawalls).toBeInstanceOf(MegaWalls);
  expectTypeOf(data.stats.megawalls).toEqualTypeOf<MegaWalls>();
  expect(data.stats.murdermystery).toBeDefined();
  expect(data.stats.murdermystery).toBeInstanceOf(MurderMystery);
  expectTypeOf(data.stats.murdermystery).toEqualTypeOf<MurderMystery>();
  expect(data.stats.paintball).toBeDefined();
  expect(data.stats.paintball).toBeInstanceOf(Paintball);
  expectTypeOf(data.stats.paintball).toEqualTypeOf<Paintball>();
  expect(data.stats.pit).toBeDefined();
  expect(data.stats.pit).toBeInstanceOf(Pit);
  expectTypeOf(data.stats.pit).toEqualTypeOf<Pit>();
  expect(data.stats.quakecraft).toBeDefined();
  expect(data.stats.quakecraft).toBeInstanceOf(Quakecraft);
  expectTypeOf(data.stats.quakecraft).toEqualTypeOf<Quakecraft>();
  expect(data.stats.skywars).toBeDefined();
  expect(data.stats.skywars).toBeInstanceOf(SkyWars);
  expectTypeOf(data.stats.skywars).toEqualTypeOf<SkyWars>();
  expect(data.stats.smashheroes).toBeDefined();
  expect(data.stats.smashheroes).toBeInstanceOf(SmashHeroes);
  expectTypeOf(data.stats.smashheroes).toEqualTypeOf<SmashHeroes>();
  expect(data.stats.speeduhc).toBeDefined();
  expect(data.stats.speeduhc).toBeInstanceOf(SpeedUHC);
  expectTypeOf(data.stats.speeduhc).toEqualTypeOf<SpeedUHC>();
  expect(data.stats.tntgames).toBeDefined();
  expect(data.stats.tntgames).toBeInstanceOf(TNTGames);
  expectTypeOf(data.stats.tntgames).toEqualTypeOf<TNTGames>();
  expect(data.stats.turbokartracers).toBeDefined();
  expect(data.stats.turbokartracers).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data.stats.turbokartracers).toEqualTypeOf<TurboKartRacers>();
  expect(data.stats.uhc).toBeDefined();
  expect(data.stats.uhc).toBeInstanceOf(UHC);
  expectTypeOf(data.stats.uhc).toEqualTypeOf<UHC>();
  expect(data.stats.vampirez).toBeDefined();
  expect(data.stats.vampirez).toBeInstanceOf(VampireZ);
  expectTypeOf(data.stats.vampirez).toEqualTypeOf<VampireZ>();
  expect(data.stats.walls).toBeDefined();
  expect(data.stats.walls).toBeInstanceOf(Walls);
  expectTypeOf(data.stats.walls).toEqualTypeOf<Walls>();
  expect(data.stats.warlords).toBeDefined();
  expect(data.stats.warlords).toBeInstanceOf(Warlords);
  expectTypeOf(data.stats.warlords).toEqualTypeOf<Warlords>();
  expect(data.stats.woolgames).toBeDefined();
  expect(data.stats.woolgames).toBeInstanceOf(WoolGames);
  expectTypeOf(data.stats.woolgames).toEqualTypeOf<WoolGames>();
});
