name: Update Docs

on:
  push:
    paths:
      - src/**
    branches:
      - master
  workflow_dispatch:

jobs:
  UpdateDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate docs
        run: |
          mkdir tmp
          npm run docgen
          mv ./master.json tmp/master.json

      - name: Switch to docs branch
        run: |
          git fetch --all
          git checkout docs --

      - name: Replace master.json in docs branch
        run: |
          rm master.json
          mv tmp/master.json master.json

      - name: Commit and push changes
        run: |
          git config --global user.name "Docs Updater[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update Docs"
          git push origin docs
