name: 'Update Docs'
on:
  push:
    paths:
      - src/**
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  pnpm:
    name: Install dependencies (pnpm)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install node dependencies
        run: pnpm install

  UpdateDocs:
    name: Update Documentation
    needs: [pnpm]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install node dependencies
        run: pnpm install

      - name: Generate Documentation
        run: pnpm docgen

      - name: Move new documentation to temp directory
        run: mv documentation/ tmp/

      - name: Switch to documentation branch
        run: |
          git fetch --all
          git checkout documentation

      - name: Clear Old Documentation files
        run:
          rm -rf assets/ classes/ functions/ interfaces/ modules/ types/ variables/ 404.html hierarchy.html index.html
          modules.html sitemap.xml .nojekyll

      - name: Move new Documentation files into place
        run: |
          mv tmp/.nojekyll ./
          mv tmp/* ./
          rm -r tmp/

      - name: Commit and push changes
        run: |
          git config --global user.name "Docs Updater[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Documentation" || echo "No changes to commit"
          git push origin documentation
